<%
	Response.CodePage = 1252 
	Response.CharSet = "windows-1252" 
%>
<!--#INCLUDE FILE="local/local.phtml"-->
<!--#INCLUDE FILE="core/i_adoopen.phtml"-->
<!--#INCLUDE FILE="util/xt_func_session.phtml"-->
<!--#INCLUDE File="util/xt_func_util.phtml" -->
<!--#INCLUDE FILE="util/xt_func_string.phtml"-->
<%
	sessionID = Request("sessionID")
	sessionID = FilterSessionString(sessionID)

	if Len(sessionID) > 0 then
		Session("SESSIONKEY") = sessionID
	else
		if Len(Session("SESSIONKEY")) > 0 then
			'session key exist
		else
			'no key information...
			Response.Redirect Session("StoreURL") & "/index.phtml"
		end if
	end if
%>
<!-- #INCLUDE File="util/xt_func_shoppingcart.phtml" -->
<%	
	pf_id = Trim(Request("pf_id"))
	pf_id = FilterSKUString(pf_id)
	product_mode = Trim(Request("product_mode"))
	qty = Trim(Request("qty"))
	
	SELECT CASE product_mode
	CASE "0"
		if AddItemToShoppingCart(pf_id, product_mode, 0, 0, 0, "", qty) then
			bRedirect = true
		else
			iCount = iCount - 1
		end if
	END SELECT
%>