<SCRIPT LANGUAGE=VBScript RUNAT=Server>
Const MaxShoppingCartItems = 21

Const cartProductID		= 1
Const cartProductName		= 2
Const cartOptions		= 3
Const cartOrderQuantity		= 4
Const cartProductUnitPrice	= 5
Const cartProductUnitWeight	= 6
Const cartTaxable		= 7
Const cartShip			= 8
Const cartProductMode		= 9
Const cartProductUnitCost	= 10
Const cartProductMfgNumber	= 11
Const cartProductWarranty	= 12
Const cartProductWarrantySelection	= 13
Const cartProductSHRate	= 14
Const cartTDNumber	= 15
Const cartIMNumber	= 16
Const cartECNumber	= 17
Const cartError	= 18
Const cartMfg = 19
Const cartSNNumber	= 20
Const cartDHNumber = 21

</SCRIPT>