<%@  language="VBScript" %>
<%
	Response.CodePage = 65001
	Response.CharSet = "UTF-8"
%>
<!--#INCLUDE FILE="local/local.phtml"-->
<!--#INCLUDE FILE="core/i_adoopen.phtml"-->
<!--#INCLUDE FILE="util/xt_func_session.phtml"-->
<!--#INCLUDE FILE="util/xt_func_string.phtml"-->
<!--#INCLUDE FILE="util/xt_func_util.phtml"-->

<%
	pf_id = Trim(Request("pf_id"))
	action = Trim(Request("action"))

	edit_mode = trim(Request("edit_mode"))
	ratingID = trim(Request("ratingID"))

	if (Session("shopper_id") = "") then
		response.Redirect(g_secure_url & "login.phtml?sessionID=" & Session("SESSIONKEY"))
	end if

	if (Session("shopper_id") = "GUEST") then
		response.Redirect(g_secure_url & "login.phtml?sessionID=" & Session("SESSIONKEY"))
	end if

	pf_id = FilterSKUString(pf_id)

	customer_id = Session("shopper_id")
	Rating = Request("Rating")
	ReviewTitle = Request("title")
	Comments = Request("review")

	'szSql = "INSERT INTO " & g_storeid & "_Rating (productID, customerID, Rating, ReviewTitle, Comments) VALUES ('" 
	'szSql = szSql & pf_id & "', '" & customer_id & "', '" & Rating & "', '" & CheckString(ReviewTitle) & "', '" & CheckString(Comments) & "')"

	'dbconn.Execute szSql
	
	Set rsUpdate = Server.CreateObject("ADODB.Recordset")
	with rsUpdate
		.ActiveConnection = dbconn
		.CursorLocation = 3
		.CursorType = 1
		.LockType = 3
		.Source = g_storeid & "_Rating WHERE RatingID=0"
		.Open
		.AddNew
	end with
	
	rsUpdate("productID") = pf_id
	rsUpdate("customerID") = customer_id
	rsUpdate("Rating") = Rating
	rsUpdate("ReviewTitle") = ReviewTitle
	rsUpdate("Comments") = Comments
	
	If dbconn.Errors.Count > 0 Then
		dbconn.Errors.Clear
		rsUpdate.CancelUpdate
	else
		rsUpdate.Update
	End If
	
	rsUpdate.Close
	set rsUpdate = nothing

	prod_url_key = ""
	sql = "SELECT url_key FROM " & g_storeid & "_product WHERE pf_id = '" & pf_id & "'"
			
	Set rsProd = dbconn.Execute(sql)
				
	if not rsProd.EOF then	
		prod_url_key = rsProd("url_key")
	end if
			
	rsProd.Close
	set rsProd = nothing
	
	'===================================================
	'SEO URLs
	if Len(prod_url_key) > 0 then
		g_product_link = g_store_url & prod_url_key & ".html"
	else
		g_product_link = g_store_url & "product.phtml?pf_id=" & pf_id
	end if
	'===================================================
	Response.Redirect(g_product_link)
%>
