<%
	Response.CodePage = 65001
	Response.CharSet = "UTF-8"
	
	storeviewid = Trim(Request("storeviewid"))
	if Len(storeviewid) > 0 then
		Session("CURRENT_ADMIN_VIEW_ID")  = storeviewid
	end if
%>
<!-- #INCLUDE File="local/local.phtml" -->
<!-- #INCLUDE File="util/xt_func_util.phtml" -->
<!-- #INCLUDE File="util/xt_func_string.phtml" -->
<!-- #INCLUDE File="include/i_login.phtml" -->

<!--#INCLUDE FILE="include/doctype.phtml"-->
<head>
<!--#INCLUDE FILE="include/head.phtml"-->
<!-- start: CSS REQUIRED FOR THIS PAGE ONLY -->
<!-- end: CSS REQUIRED FOR THIS PAGE ONLY -->
<link rel="stylesheet" href="assets/css/custom.css">
</head>	
<body>
	<div id="app">
		<!--#INCLUDE FILE="include/sidebar.phtml"-->
		<div class="app-content">
			<!--#INCLUDE FILE="include/header.phtml"-->
			<div class="main-content" >
				<div class="wrap-content container" id="container">
					<!-- start: TITLE -->
					<section id="page-title" class="padding-top-15 padding-bottom-15">
						<div class="row">
							<div class="col-sm-8">
								<h1 class="mainTitle">Filter Attibutes</h1>
								<span class="mainDescription">overview &amp; list </span>
							</div>
							<ol class="breadcrumb">
								<% if Session("CURRENT_ADMIN_VIEW_ID") = "1" then %>
								<a href="catalog_attribute_detail.phtml?id=0" class="btn btn-green btn-sm" role="button" style="float:right"><i class="ti-plus"></i> Add New Filter</a>
								<% end if %>
							</ol>
						</div>
					</section>
					<!-- end: TITLE -->
					<div class="container-fluid container-fullw bg-white">
						<div class="row">
							<div class="col-md-12">
								<table class="table table-hover" id="sample-table-1">
									<thead>
										<tr>
											<th class="center">#</th>
											<th>Filter Name</th>
											<th></th>
										</tr>
									</thead>
									<tbody>
										<%
											sql = "SELECT * FROM " & g_storeid & "_eav_attribute"
											set rs = dbconn.Execute(sql)
											do while not rs.EOF
												attribute_id = rs("attribute_id")
												frontend_label = rs("frontend_label")
												if Session("CURRENT_ADMIN_VIEW_ID") <> "1" then
													frontend_label = TranslateX(frontend_label, 20, attribute_id, 1)
												end if
										%>
										<tr>
											<td class="center"><%=attribute_id%></td>
											<td><%=frontend_label%></td>
											<td class="center">
											<div class="visible-md visible-lg hidden-sm hidden-xs">
												<a href="catalog_attribute_detail.phtml?id=<%=attribute_id%>" class="btn btn-transparent btn-xs" tooltip-placement="top" tooltip="Edit"><i class="fa fa-pencil"></i></a>
												<a href="#" class="btn btn-transparent btn-xs tooltips" tooltip-placement="top" tooltip="Remove"><i class="fa fa-times fa fa-white"></i></a>
											</div>
											<div class="visible-xs visible-sm hidden-md hidden-lg">
												<div class="btn-group" dropdown is-open="status.isopen">
													<button type="button" class="btn btn-primary btn-o btn-sm dropdown-toggle" dropdown-toggle>
														<i class="fa fa-cog"></i>&nbsp;<span class="caret"></span>
													</button>
													<ul class="dropdown-menu pull-right dropdown-light" role="menu">
														<li>
															<a href="catalog_attribute_detail.phtml?id=<%=attribute_id%>">
																Edit
															</a>
														</li>
														<li>
															<a href="#">
																Remove
															</a>
														</li>
													</ul>
												</div>
											</div></td>
										</tr>
										<%
												rs.MoveNext
											loop
											rs.Close
											set rs = nothing
										%>
									</tbody>
								</table>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!--#INCLUDE FILE="include/footer.phtml"-->
	</div>
	<!--#INCLUDE FILE="include/js.phtml"-->
	<!-- start: JAVASCRIPTS REQUIRED FOR THIS PAGE ONLY -->
	<!-- end: JAVASCRIPTS REQUIRED FOR THIS PAGE ONLY -->
	<script src="assets/js/main.js"></script>
	<!-- start: JavaScript Event Handlers for this page -->
	
	<script>
		jQuery(document).ready(function() {
			Main.init();
		});
	</script>
	<!-- end: JavaScript Event Handlers for this page -->
</body>
</html>
