<!-- #INCLUDE File="local/local.phtml" -->
<!-- #INCLUDE File="util/xt_func_util.phtml" -->
<!-- #INCLUDE File="util/xt_func_string.phtml" -->
<!-- #INCLUDE File="include/i_login.phtml" -->
<%
	g_access_key = "02-b"
%>
<!-- #INCLUDE File="include/i_access.phtml" -->
<!--#INCLUDE FILE="include/doctype.phtml"-->
<head>
<!--#INCLUDE FILE="include/head.phtml"-->
<!-- start: CSS REQUIRED FOR THIS PAGE ONLY -->
<link href="vendor/select2/select2.min.css" rel="stylesheet" media="screen">
<link href="vendor/DataTables/css/jquery.dataTables.css" rel="stylesheet" media="screen">
<link href="vendor/DataTables/css/DT_bootstrap.css" rel="stylesheet" media="screen">
<!-- end: CSS REQUIRED FOR THIS PAGE ONLY -->
<link rel="stylesheet" href="assets/css/custom.css">
</head>	
<body>
	<div id="app" class="app-sidebar-closed">
		<!--#INCLUDE FILE="include/sidebar.phtml"-->
		<div class="app-content">
			<!--#INCLUDE FILE="include/header.phtml"-->
			<div class="main-content" >
				<div class="wrap-content container" id="container">
					<!-- start: TITLE -->
					<section id="page-title" class="padding-top-15 padding-bottom-15">
						<div class="row">
							<div class="col-sm-8">
								<h1 class="mainTitle">Products</h1>
								<span class="mainDescription">overview &amp; list </span>
							</div>
							<ol class="breadcrumb">
								<a href="catalog_product_detail.phtml?pf_id=0" class="btn btn-green btn-sm" role="button" style="float:right"><i class="ti-plus"></i> Add New Product</a>
							</ol>
						</div>
					</section>
					<!-- end: TITLE -->
					<div class="container-fluid container-fullw bg-white">
						<div class="content-header-floating" style="display: block;">
							<div class="content-header">
								<h3 class="mainTitle">Products</h3>
								<p class="content-buttons form-buttons">
									<a href="catalog_product_detail.phtml?pf_id=0" class="btn btn-green btn-sm" role="button" style="float:right"><i class="ti-plus"></i> Add New Product</a>
								</p>	
							</div>
						</div>
						<div class="row">
							<div class="col-md-12">
								<table class="table table-striped table-bordered table-hover table-full-width" id="sample_1">
									<thead>
									<tr>
										<th>Product ID</th>
										<th>Thumbnail</th>
										<th>Name</th>
										<th>SKU</th>
										<th>Price</th>
										<th>Qty</th>
										<th>Category</th>
										<th>Status</th>
										<!--<th>Action</th>-->
									</tr>
									</thead>
									<tbody>
										<tr>
											<td colspan="9" class="dataTables_empty">Loading data from server</td>
										</tr>
									</tbody>
								</table>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!--#INCLUDE FILE="include/footer.phtml"-->
	</div>
	<!--#INCLUDE FILE="include/js.phtml"-->
	<!-- start: JAVASCRIPTS REQUIRED FOR THIS PAGE ONLY -->
	<script src="vendor/select2/select2.min.js"></script>
	<script src="vendor/DataTables/jquery.dataTables.min.js"></script>
	<!-- end: JAVASCRIPTS REQUIRED FOR THIS PAGE ONLY -->
	<!-- start: CLIP-TWO JAVASCRIPTS -->
	<script src="assets/js/main.js"></script>
	<!-- start: JavaScript Event Handlers for this page -->
	<%
		order_display = "3"
		order_filter = "All"
	%>
	<script type="text/javascript">
	var oTable;
	var v1 = "All";
	var v2 = "All";
	var v3 = "All";
	
	var TableData = function () {
		//function to initiate DataTable
		//DataTable is a highly flexible tool, based upon the foundations of progressive enhancement, 
		//which will add advanced interaction controls to any HTML table
		//For more information, please visit https://datatables.net/
		var runDataTable = function () {
			oTable = $('#sample_1').dataTable({
				"bProcessing": true,
				"bStateSave": false,
				"bJQueryUI": false,
				"iDisplayLength": 20,
				"bServerSide": true,
				"bAutoWidth": false,
				"sAjaxSource": "api/sp_product_list.phtml?v1=" + v1 + "&v2=" + v2 + "&v3=" + v3 + "&z1=",
				"aoColumns": [ 
					/* Product ID */  { "sClass": "left" },
					/* Thumbnail */  { "sClass": "center","bSortable": false },
					/* Name */  { "sClass": "left" },
					/* sku */  { "sClass": "center" },
					/* Price */  { "sClass": "text-right"},
					/* Qty */ { "sClass": "text-right"},
					/* Category */ { "sClass": "center","bSortable": false },
					/* Status*/  { "sClass": "center" ,"bSortable": false}
				  ],
				  
				"aaSorting": [[0, 'desc']],
				
				"aLengthMenu": [
					[10, 20, 30, 40, 50],
					[10, 20, 30, 40, 50] // change per page values here
				],
				
				"oLanguage": {
					"sLengthMenu": "Show _MENU_ Rows",
					"sSearch": "",
					"sProcessing": '<img src="assets/images/ajax-loader-primary.gif"/>',
					"oPaginate": {
						"sPrevious": "",
						"sNext": ""
					}
				},
				
				'fnServerData' : function ( sSource, aoData, fnCallback ) {
					aoData.push( { 'name' : 'min', 'value' : $("#min").val() } );
					aoData.push( { 'name' : 'max', 'value' : $("#max").val() } );
					$.ajax({
						'dataType' : 'json',
						'data' : aoData,
						'type' : 'GET',
						'url' : sSource,
						'success' : fnCallback
					});
				} 
			});
			
			$('#sample_1_wrapper .dataTables_filter input').addClass("form-control input-sm").attr("placeholder", "Search");
			// modify table search input
			$('#sample_1_wrapper .dataTables_length select').addClass("m-wrap small");
			// modify table per page dropdown
			$('#sample_1_wrapper .dataTables_length select').select2();
			// initialzie select2 dropdown
		};
		
		return {
			//main function to initiate template pages
			init: function () {
				runDataTable();
			},
			
			reload: function(theURL) {
				if ( theURL ) {
					oTable.fnReloadAjax(theURL);
				}
				else {
					oTable.fnReloadAjax("sp_product_list.phtml?v1=All&v2=All&v3=All&z1=");
				}
			}
		};
	}();
	
	function StatusFilter (theObj)
	{
		v3 = theObj.value;
		oTable.fnReloadAjax("sp_product_list.phtml?v1=" + v1 + "&v2=" + v2 + "&v3=" + theObj.value + "&z1=");
	}
	
	function VisibilityFilter (theObj)
	{
		v2 = theObj.value;
		oTable.fnReloadAjax("sp_product_list.phtml?v1=" + v1 + "&v2=" + theObj.value + "&v3=" + v3 + "&z1=");
	}
	
	function TypeFilter (theObj)
	{
		v1 = theObj.value;
		oTable.fnReloadAjax("sp_product_list.phtml?v1=" + theObj.value + "&v2=" + v2 + "&v3=" + v3 + "&z1=");
	}
	
	
	
	</script>
	<script>
		jQuery(document).ready(function() {
			Main.init();
			TableData.init();
		});
	</script>
	<!-- end: JavaScript Event Handlers for this page -->
	<!-- end: CLIP-TWO JAVASCRIPTS -->
</body>
</html>
