<!-- #INCLUDE File="local/local.phtml" -->
<!-- #INCLUDE File="util/xt_func_util.phtml" -->
<!-- #INCLUDE File="util/xt_func_string.phtml" -->
<!-- #INCLUDE File="include/i_login.phtml" -->
<!--#INCLUDE FILE="include/doctype.phtml"-->
<head>
<!--#INCLUDE FILE="include/head.phtml"-->
<!-- start: CSS REQUIRED FOR THIS PAGE ONLY -->
<!-- end: CSS REQUIRED FOR THIS PAGE ONLY -->
<link rel="stylesheet" href="assets/css/custom.css">
</head>	
	<body>
		<div id="app">
			<!-- sidebar -->
			<!--#INCLUDE FILE="include/sidebar.phtml"-->
			<!-- / sidebar -->
			<div class="app-content">
				<!-- start: TOP NAVBAR -->
				<!--#INCLUDE FILE="include/header.phtml"-->
				<!-- end: TOP NAVBAR -->
				<div class="main-content" >
					<div class="wrap-content container" id="container">
						<!-- start: DASHBOARD TITLE -->
						<section id="page-title" class="padding-top-15 padding-bottom-15">
							<div class="row">
								<div class="col-sm-8">
									<h1 class="mainTitle">Dashboard</h1>
									<span class="mainDescription">overview &amp; stats </span>
								</div>
							</div>
						</section>
						<!-- end: DASHBOARD TITLE -->
						<!-- start: FEATURED BOX LINKS -->
						<div class="container-fluid container-fullw bg-white">
							<div class="content-header-floating" style="display: block;">
								<div class="content-header">
									<h3 class="mainTitle">Dashboard</h3>
									<p class="content-buttons form-buttons">
										
									</p>	
								</div>
							</div>
							<div class="row">
								<div class="col-sm-4">
									<div class="panel panel-white no-radius text-center">
										<div class="panel-body">
											<span class="fa-stack fa-2x"> <i class="fa fa-square fa-stack-2x text-primary"></i> <i class="fa fa-smile-o fa-stack-1x fa-inverse"></i> </span>
											<h2 class="StepTitle">Manage Customers</h2>
											<p class="text-small">
												To add users, you need to be signed in as the super user.
											</p>
											<p class="links cl-effect-1">
												<a href="customer_manage_customer.phtml">
													view more
												</a>
											</p>
										</div>
									</div>
								</div>
								<div class="col-sm-4">
									<div class="panel panel-white no-radius text-center">
										<div class="panel-body">
											<span class="fa-stack fa-2x"> <i class="fa fa-square fa-stack-2x text-primary"></i> <i class="fa fa-shopping-cart fa-stack-1x fa-inverse"></i> </span>
											<h2 class="StepTitle">Manage Orders</h2>
											<p class="text-small">
												The Manage Orders tool provides a view of all your orders.
											</p>
											<p class="cl-effect-1">
												<a href="sales_order.phtml">
													view more
												</a>
											</p>
										</div>
									</div>
								</div>
								<div class="col-sm-4">
									<div class="panel panel-white no-radius text-center">
										<div class="panel-body">
											<span class="fa-stack fa-2x"> <i class="fa fa-square fa-stack-2x text-primary"></i> <i class="fa fa-terminal fa-stack-1x fa-inverse"></i> </span>
											<h2 class="StepTitle">Manage Quotation</h2>
											<p class="text-small">
												The Manage Quotation tool provides a view of all your quotations.
											</p>
											<p class="links cl-effect-1">
												<a href="sales_quotation.phtml">
													view more
												</a>
											</p>
										</div>
									</div>
								</div>
							</div>
						</div>
						<div class="wrap-content container" id="container">
							<div class="row">
								<div class="col-sm-5">
									<%
										order_lifetime_total = 0
										sql = "SELECT SUM(total) FROM " & g_storeid & "_order"
										set rs = dbconn.Execute(sql)
										if not rs.EOF then
											order_lifetime_total = rs(0)
										end if
										rs.Close
										set rs = nothing
										
										if IsNumeric(order_lifetime_total) then
										else
											order_lifetime_total = 0
										end if
									%>
									<div class="row">
										<div class="col-sm-12">
											<div class="panel panel-dark-primary">
												<div class="panel-heading">
													<h4 class="panel-title">Lifetime Sales</h4>
													<div class="panel-tools" >
														<a data-original-title="Collapse" data-toggle="tooltip" data-placement="top" class="btn btn-transparent btn-sm panel-collapse" href="#"><i class="ti-minus collapse-off"></i><i class="ti-plus collapse-on"></i></a>
													</div>
												</div>
												<div class="panel-body partition-white">
													<b style="font-size:20px;">$<%=FormatNumber(order_lifetime_total,2) %></b>
												</div>
											</div>
										</div>
									</div>
									<%
										order_lifetime_count = 0
										sql = "SELECT COUNT(order_id) FROM " & g_storeid & "_order"
										set rs = dbconn.Execute(sql)
										if not rs.EOF then
											order_lifetime_count = rs(0)
										end if
										rs.Close
										set rs = nothing
										
										if order_lifetime_count > 0 then
											order_lifetime_avg = order_lifetime_total / order_lifetime_count
										else
											order_lifetime_avg = 0
										end if
									%>
									<div class="row">
										<div class="col-sm-12">
											<div class="panel panel-dark-primary">
												<div class="panel-heading">
													<h4 class="panel-title">Average Orders</h4>
													<div class="panel-tools" >
														<a data-original-title="Collapse" data-toggle="tooltip" data-placement="top" class="btn btn-transparent btn-sm panel-collapse" href="#"><i class="ti-minus collapse-off"></i><i class="ti-plus collapse-on"></i></a>
													</div>
												</div>
												<div class="panel-body partition-white">
													<b style="font-size:20px;">$<%=FormatNumber(order_lifetime_avg,2) %></b>
												</div>
											</div>
										</div>
									</div>
									<div class="row">
										<div class="col-sm-12">
											<div class="panel panel-dark-primary">
												<div class="panel-heading">
													<h4 class="panel-title">Last 5 Orders</h4>
													<div class="panel-tools" >
														<a data-original-title="Collapse" data-toggle="tooltip" data-placement="top" class="btn btn-transparent btn-sm panel-collapse" href="#"><i class="ti-minus collapse-off"></i><i class="ti-plus collapse-on"></i></a>
													</div>
												</div>
												<div class="panel-body partition-white">
													<table class="table table-bordered table-striped">
														<thead>
															<tr>
																<th class="hidden-xs">Customer</th>
																<th>Items</th>
																<th>Total</th>
															</tr>
														</thead>
														<tbody>
															<%
																sql = "SELECT TOP 5 * FROM " & g_storeid & "_order ORDER BY date_entered DESC"
																set rs = dbconn.Execute(sql)
																do while not rs.EOF
																	x_order_id = rs("order_id")
																	x_order_item = 0
																	sqlx = "SELECT SUM(quantity) FROM " & g_storeid & "_order_item WHERE order_id='" & x_order_id & "'"
																	set rsx = dbconn.Execute(sqlx)
																	if not rsx.EOF then
																		x_order_item = rsx(0)
																	end if
																	rsx.Close
																	set rsx = nothing
															%>
															<tr>
																<td class="hidden-xs"><%=rs("bill_contact")%></td>
																<td style="text-align:center"><span class="badge"><%=x_order_item%></span></td>
																<td style="text-align:right"><%=FormatNumber(rs("total"),2)%></td>
															</tr>
															<%
																	rs.MoveNext
																Loop
																rs.Close
																set rs = nothing
															%>
															
														</tbody>
													</table>
												</div>
											</div>
										</div>
									</div>
									<div class="row">
										<div class="col-sm-12">
											<div class="panel panel-dark-primary">
												<div class="panel-heading">
													<h4 class="panel-title">Last 5 New Customers</h4>
													<div class="panel-tools" >
														<a data-original-title="Collapse" data-toggle="tooltip" data-placement="top" class="btn btn-transparent btn-sm panel-collapse" href="#"><i class="ti-minus collapse-off"></i><i class="ti-plus collapse-on"></i></a>
													</div>
												</div>
												<div class="panel-body partition-white">
													<table class="table table-bordered table-striped">
														<thead>
															<tr>
																<th class="hidden-xs">Name</th>
																<th># of Orders</th>
																<th>Order Amount</th>
															</tr>
														</thead>
														<tbody>
															<%
																sql = "SELECT TOP 5 * FROM " & g_storeid & "_shopper ORDER BY DateEntered DESC"
																set rs = dbconn.Execute(sql)
																do while not rs.EOF
																	x_shopper_id = rs("shopper_id")
																	x_order_number = 0
																	sqlx = "SELECT COUNT(order_id) FROM " & g_storeid & "_order WHERE shopper_id='" & x_shopper_id & "'"
																	set rsx = dbconn.Execute(sqlx)
																	if not rsx.EOF then
																		x_order_number = rsx(0)
																	end if
																	rsx.Close
																	set rsx = nothing
																	
																	x_order_total = 0
																	sqlx = "SELECT SUM(total) FROM " & g_storeid & "_order WHERE shopper_id='" & x_shopper_id & "'"
																	set rsx = dbconn.Execute(sqlx)
																	if not rsx.EOF then
																		x_order_total = rsx(0)
																	end if
																	rsx.Close
																	set rsx = nothing
																	
																	if IsNumeric(x_order_number) then
																	else
																		x_order_number = 0
																	end if
																	
																	if IsNumeric(x_order_total) then
																	else
																		x_order_total = 0
																	end if
																
															%>
															<tr>
																<td class="hidden-xs"><%=rs("firstname") & " "  & rs("lastname") %></td>
																<td style="text-align:center"><span class="badge"><%=x_order_number%></span></td>
																<td style="text-align:right"><%=FormatNumber(x_order_total,2)%></td>
															</tr>
															<%
																	rs.MoveNext
																Loop
																rs.Close
																set rs = nothing
															%>
															
														</tbody>
													</table>
												</div>
											</div>
										</div>
									</div>
								</div>
								<div class="col-sm-7">
									<div class="row">
										<div class="col-sm-12">
											<div class="panel panel-dark-primary">
												<div class="panel-heading">
													<h4 class="panel-title">Order Amounts</h4>
													<div class="panel-tools" >
														<a data-original-title="Collapse" data-toggle="tooltip" data-placement="top" class="btn btn-transparent btn-sm panel-collapse" href="#"><i class="ti-minus collapse-off"></i><i class="ti-plus collapse-on"></i></a>
													</div>
												</div>
												<div class="panel-body partition-white">
													<div class="flot-container">
														<div id="placeholder3" class="flot-placeholder"></div>
													</div>
												</div>
											</div>
										</div>
									</div>
									<div class="row">
										<div class="col-sm-12">
											<div class="panel panel-dark-primary">
												<div class="panel-heading">
													<h4 class="panel-title"># of Orders</h4>
													<div class="panel-tools" >
														<a data-original-title="Collapse" data-toggle="tooltip" data-placement="top" class="btn btn-transparent btn-sm panel-collapse" href="#"><i class="ti-minus collapse-off"></i><i class="ti-plus collapse-on"></i></a>
													</div>
												</div>
												<div class="panel-body partition-white">
													<div class="flot-container">
														<div id="placeholder4" class="flot-placeholder"></div>
													</div>
												</div>
											</div>
										</div>
									</div>
								</div>

							</div>
						</div>
					</div>
				</div>
			</div>
			<!--#INCLUDE FILE="include/footer.phtml"-->
			
		</div>
		<!--#INCLUDE FILE="include/js.phtml"-->
		<!-- start: JAVASCRIPTS REQUIRED FOR THIS PAGE ONLY -->
		<script src="vendor/jquery.sparkline/jquery.sparkline.min.js"></script>
		<!-- end: JAVASCRIPTS REQUIRED FOR THIS PAGE ONLY -->
		<script src="assets/plugins/flot/jquery.flot.js"></script>
		<script src="assets/plugins/flot/jquery.flot.resize.min.js"></script>
		<script src="assets/plugins/flot/jquery.flot.time.min.js"></script>
		<!-- start: CLIP-TWO JAVASCRIPTS -->
		<script src="assets/js/main.js"></script>
		<!-- start: JavaScript Event Handlers for this page -->
		
		<%
			dim chart_order_count(30)
			for iii = 0 to 30
				chart_order_count(iii) = "0"
			next
			sql = "SELECT TOP 30 30 - DATEDIFF ( d , date_entered , GETDATE ( )) as a, COUNT(order_id) FROM " & g_storeid & "_order "
			sql = sql & " WHERE (30 - DATEDIFF ( d , date_entered , GETDATE ( )))  > 0 "
			sql = sql & " GROUP BY 30 - DATEDIFF ( d , date_entered , GETDATE ( )) ORDER BY a"
			set rsChart = dbconn.execute(sql)
			do while not rsChart.EOF
				if (rsChart(0) > -1) then
					chart_order_count(rsChart(0)) = FormatNumber(rsChart(1),0)
				end if
				rsChart.MoveNext
			loop
			rsChart.Close
			set rsChart = nothing
			
			'Response.Write(sql)
			
			'--------------------------------------------
			dim chart_order_amount(30)
			for iii = 0 to 30
				chart_order_amount(iii) = "0.00"
			next
			sql = "SELECT TOP 30 30 - DATEDIFF ( d , date_entered , GETDATE ( )) as a, SUM(total) FROM " & g_storeid & "_order "
			sql = sql & " WHERE (30 - DATEDIFF ( d , date_entered , GETDATE ( )))  > 0 "
			sql = sql & " GROUP BY 30 - DATEDIFF ( d , date_entered , GETDATE ( )) ORDER BY a"
			set rsChart = dbconn.execute(sql)
			do while not rsChart.EOF
				if (rsChart(0) > -1) then
				chart_order_amount(rsChart(0)) = FormatNumber(rsChart(1),2,,,0)
				end if
				rsChart.MoveNext
			loop
			rsChart.Close
			set rsChart = nothing
		%>
		<script>
			var Charts = function () {
			var runCharts = function () {
				
				var pageviews = [
					[<%=date2epoch(DateAdd("D", -29, date))%>000, <%=chart_order_amount(1)%>],
					[<%=date2epoch(DateAdd("D", -28, date))%>000, <%=chart_order_amount(2)%>],
					[<%=date2epoch(DateAdd("D", -27, date))%>000, <%=chart_order_amount(3)%>],
					[<%=date2epoch(DateAdd("D", -26, date))%>000, <%=chart_order_amount(4)%>],
					[<%=date2epoch(DateAdd("D", -25, date))%>000, <%=chart_order_amount(5)%>],
					[<%=date2epoch(DateAdd("D", -24, date))%>000, <%=chart_order_amount(6)%>],
					[<%=date2epoch(DateAdd("D", -23, date))%>000, <%=chart_order_amount(7)%>],
					[<%=date2epoch(DateAdd("D", -22, date))%>000, <%=chart_order_amount(8)%>],
					[<%=date2epoch(DateAdd("D", -21, date))%>000, <%=chart_order_amount(9)%>],
					[<%=date2epoch(DateAdd("D", -20, date))%>000, <%=chart_order_amount(10)%>],
					[<%=date2epoch(DateAdd("D", -19, date))%>000, <%=chart_order_amount(11)%>],
					[<%=date2epoch(DateAdd("D", -18, date))%>000, <%=chart_order_amount(12)%>],
					[<%=date2epoch(DateAdd("D", -17, date))%>000, <%=chart_order_amount(13)%>],
					[<%=date2epoch(DateAdd("D", -16, date))%>000, <%=chart_order_amount(14)%>],
					[<%=date2epoch(DateAdd("D", -15, date))%>000, <%=chart_order_amount(15)%>],
					[<%=date2epoch(DateAdd("D", -14, date))%>000, <%=chart_order_amount(16)%>],
					[<%=date2epoch(DateAdd("D", -13, date))%>000, <%=chart_order_amount(17)%>],
					[<%=date2epoch(DateAdd("D", -12, date))%>000, <%=chart_order_amount(18)%>],
					[<%=date2epoch(DateAdd("D", -11, date))%>000, <%=chart_order_amount(19)%>],
					[<%=date2epoch(DateAdd("D", -10, date))%>000, <%=chart_order_amount(20)%>],
					[<%=date2epoch(DateAdd("D", -9, date))%>000, <%=chart_order_amount(21)%>],
					[<%=date2epoch(DateAdd("D", -8, date))%>000, <%=chart_order_amount(22)%>],
					[<%=date2epoch(DateAdd("D", -7, date))%>000, <%=chart_order_amount(23)%>],
					[<%=date2epoch(DateAdd("D", -6, date))%>000, <%=chart_order_amount(24)%>],
					[<%=date2epoch(DateAdd("D", -5, date))%>000, <%=chart_order_amount(25)%>],
					[<%=date2epoch(DateAdd("D", -4, date))%>000, <%=chart_order_amount(26)%>],
					[<%=date2epoch(DateAdd("D", -3, date))%>000, <%=chart_order_amount(27)%>],
					[<%=date2epoch(DateAdd("D", -2, date))%>000, <%=chart_order_amount(28)%>],
					[<%=date2epoch(DateAdd("D", -1, date))%>000, <%=chart_order_amount(29)%>],
					[<%=date2epoch(DateAdd("D", 0, date))%>000, <%=chart_order_amount(30)%>]
				];
				var visitors = [
					[<%=date2epoch(DateAdd("D", -29, date))%>000, <%=chart_order_count(1)%>],
					[<%=date2epoch(DateAdd("D", -28, date))%>000, <%=chart_order_count(2)%>],
					[<%=date2epoch(DateAdd("D", -27, date))%>000, <%=chart_order_count(3)%>],
					[<%=date2epoch(DateAdd("D", -26, date))%>000, <%=chart_order_count(4)%>],
					[<%=date2epoch(DateAdd("D", -25, date))%>000, <%=chart_order_count(5)%>],
					[<%=date2epoch(DateAdd("D", -24, date))%>000, <%=chart_order_count(6)%>],
					[<%=date2epoch(DateAdd("D", -23, date))%>000, <%=chart_order_count(7)%>],
					[<%=date2epoch(DateAdd("D", -22, date))%>000, <%=chart_order_count(8)%>],
					[<%=date2epoch(DateAdd("D", -21, date))%>000, <%=chart_order_count(9)%>],
					[<%=date2epoch(DateAdd("D", -20, date))%>000, <%=chart_order_count(10)%>],
					[<%=date2epoch(DateAdd("D", -19, date))%>000, <%=chart_order_count(11)%>],
					[<%=date2epoch(DateAdd("D", -18, date))%>000, <%=chart_order_count(12)%>],
					[<%=date2epoch(DateAdd("D", -17, date))%>000, <%=chart_order_count(13)%>],
					[<%=date2epoch(DateAdd("D", -16, date))%>000, <%=chart_order_count(14)%>],
					[<%=date2epoch(DateAdd("D", -15, date))%>000, <%=chart_order_count(15)%>],
					[<%=date2epoch(DateAdd("D", -14, date))%>000, <%=chart_order_count(16)%>],
					[<%=date2epoch(DateAdd("D", -13, date))%>000, <%=chart_order_count(17)%>],
					[<%=date2epoch(DateAdd("D", -12, date))%>000, <%=chart_order_count(18)%>],
					[<%=date2epoch(DateAdd("D", -11, date))%>000, <%=chart_order_count(19)%>],
					[<%=date2epoch(DateAdd("D", -10, date))%>000, <%=chart_order_count(20)%>],
					[<%=date2epoch(DateAdd("D", -9, date))%>000, <%=chart_order_count(21)%>],
					[<%=date2epoch(DateAdd("D", -8, date))%>000, <%=chart_order_count(22)%>],
					[<%=date2epoch(DateAdd("D", -7, date))%>000, <%=chart_order_count(23)%>],
					[<%=date2epoch(DateAdd("D", -6, date))%>000, <%=chart_order_count(24)%>],
					[<%=date2epoch(DateAdd("D", -5, date))%>000, <%=chart_order_count(25)%>],
					[<%=date2epoch(DateAdd("D", -4, date))%>000, <%=chart_order_count(26)%>],
					[<%=date2epoch(DateAdd("D", -3, date))%>000, <%=chart_order_count(27)%>],
					[<%=date2epoch(DateAdd("D", -2, date))%>000, <%=chart_order_count(28)%>],
					[<%=date2epoch(DateAdd("D", -1, date))%>000, <%=chart_order_count(29)%>],
					[<%=date2epoch(DateAdd("D", 0, date))%>000, <%=chart_order_count(30)%>]
				];
				var plot = $.plot($("#placeholder3"), [{
					data: pageviews,
					label: "Amount"
				}], {
					series: {
						lines: {
							show: true,
							lineWidth: 2,
							fill: true,
							fillColor: {
								colors: [{
									opacity: 0.05
								}, {
									opacity: 0.01
								}]
							}
						},
						points: {
							show: true
						},
						shadowSize: 2
					},
					grid: {
						hoverable: true,
						clickable: true,
						tickColor: "#eee",
						borderWidth: 0
					},
					colors: ["#d12610", "#37b7f3", "#52e136"],
					xaxis: {
						mode: "time",  timeformat: "%m/%d",   minTickSize: [1, "day"]
					},
					yaxis: {
						ticks: 11,
						tickDecimals: 0
					}
				});
				
				var plot2 = $.plot($("#placeholder4"), [{
					data: visitors,
					label: "# of Orders"
				}], {
					series: {
						lines: {
							show: true,
							lineWidth: 2,
							fill: true,
							fillColor: {
								colors: [{
									opacity: 0.05
								}, {
									opacity: 0.01
								}]
							}
						},
						points: {
							show: true
						},
						shadowSize: 2
					},
					grid: {
						hoverable: true,
						clickable: true,
						tickColor: "#eee",
						borderWidth: 0
					},
					colors: ["#37b7f3", "#d12610", "#52e136"],
					xaxis: {
						mode: "time",  timeformat: "%m/%d",   minTickSize: [1, "day"]
					},
					yaxis: {
						ticks: 11,
						tickDecimals: 0
					}
				});

				function showTooltip(x, y, contents) {
					$('<div id="tooltip">' + contents + '</div>').css({
						position: 'absolute',
						display: 'none',
						top: y + 5,
						left: x + 15,
						border: '1px solid #333',
						padding: '4px',
						color: '#fff',
						'border-radius': '3px',
						'background-color': '#333',
						opacity: 0.80
					}).appendTo("body").fadeIn(200);
				}
				var previousPoint = null;
				$("#placeholder3").bind("plothover", function (event, pos, item) {
					$("#x").text(pos.x.toFixed(2));
					$("#y").text(pos.y.toFixed(2));
					if (item) {
						if (previousPoint != item.dataIndex) {
							previousPoint = item.dataIndex;
							$("#tooltip").remove();
							var x = item.datapoint[0].toFixed(2),
								y = item.datapoint[1].toFixed(2);
							showTooltip(item.pageX, item.pageY,y);
						}
					} else {
						$("#tooltip").remove();
						previousPoint = null;
					}
				});
				
				$("#placeholder4").bind("plothover", function (event, pos, item) {
					$("#x").text(pos.x.toFixed(2));
					$("#y").text(pos.y.toFixed(2));
					if (item) {
						if (previousPoint != item.dataIndex) {
							previousPoint = item.dataIndex;
							$("#tooltip").remove();
							var x = item.datapoint[0].toFixed(2),
								y = item.datapoint[1].toFixed(0);
							showTooltip(item.pageX, item.pageY, y);
						}
					} else {
						$("#tooltip").remove();
						previousPoint = null;
					}
				});
				
			};
			return {
				//main function to initiate template pages
				init: function () {
					runCharts();
				}
			};
		}();
		</script>
		
		<script>
			jQuery(document).ready(function() {
				Main.init();
				//Index.init();
				Charts.init();
			});
		</script>
		<!-- end: JavaScript Event Handlers for this page -->
		<!-- end: CLIP-TWO JAVASCRIPTS -->
	</body>
</html>
