<%
	Response.CodePage = 65001
	Response.CharSet = "UTF-8"
%>
<!-- #INCLUDE File="local/local.phtml" -->
<!-- #INCLUDE File="../util/xt_func_util.phtml" -->
<!-- #INCLUDE File="../util/xt_func_string.phtml" -->
<!-- #INCLUDE File="../util/xt_func_user_access.phtml" -->
<!-- #INCLUDE File="include/i_login.phtml" -->
<!-- #INCLUDE FILE="include/doctype.phtml"-->
<head>
<!--#INCLUDE FILE="include/head.phtml"-->
<!-- start: CSS REQUIRED FOR THIS PAGE ONLY -->
<link href="vendor/bootstrap-touchspin/jquery.bootstrap-touchspin.min.css" rel="stylesheet" media="screen">
<link href="vendor/select2/select2.min.css" rel="stylesheet" media="screen">
<link href="vendor/bootstrap-datepicker/bootstrap-datepicker3.standalone.min.css" rel="stylesheet" media="screen">
<link href="vendor/bootstrap-timepicker/bootstrap-timepicker.min.css" rel="stylesheet" media="screen">
<link href="vendor/DataTables/css/DT_bootstrap.css" rel="stylesheet" media="screen">
<!-- end: CSS REQUIRED FOR THIS PAGE ONLY -->
<link rel="stylesheet" href="assets/css/custom.css">
</head>	
<body>
	<div id="app">
		<!--#INCLUDE FILE="include/sidebar.phtml"-->
		<div class="app-content">
			<!--#INCLUDE FILE="include/header.phtml"-->
			<div class="main-content" >
				<div class="wrap-content container" id="container">
					<!-- start: TITLE -->
					<section id="page-title" class="padding-top-15 padding-bottom-15">
						<div class="row">
							<div class="col-sm-8">
								<h1 class="mainTitle">CMS Pages</h1>
								<span class="mainDescription">overview &amp; list </span>
							</div>
							<ol class="breadcrumb">
								<a class="btn btn-green btn-sm" style="float:right" href="design_cms_page_edit.phtml?pid=0">
								<i class="ti-plus"></i> Add New Page
								</a>
							</ol>
						</div>
					</section>
					<!-- end: TITLE -->
					<div class="container-fluid container-fullw bg-white">
						<div class="content-header-floating" style="display: block;">
							<div class="content-header">
								<h3 class="mainTitle">CMS Pages</h3>
								<p class="content-buttons form-buttons">
									<a href="design_cms_page_edit.phtml?pid=0" class="btn btn-green btn-sm" role="button" style="float:right"><i class="ti-plus"></i> Add New Page</a>
								</p>	
							</div>
						</div>
						<div class="row">
							<div class="col-md-12">
								<table class="table table-striped table-bordered table-hover table-full-width" id="sample_1">
									<thead>
									<tr>
										<th>Page ID</th>
										<th>Title</th>
										<th>Date Created</th>
										<th>
										Last Modified
										<%
											  SELECT CASE Session("STORETIMEZONE")
											  CASE "0"
												  Response.Write("(PST)")
											  CASE "1"
												  Response.Write("(MST)")
											  CASE "2"
												  Response.Write("(CST)")
											  CASE "3"
												  Response.Write("(EST)")
											  CASE ELSE
												  Response.Write("(PST)")
											  END SELECT
										  %>
										</th>
										<th width="2%" nowrap>Page Size</th>
										<th width="2%">Preview</th>
									</tr>
									
									</thead>
									<tbody>
										<tr>
											<td colspan="11" class="dataTables_empty">Loading data from server</td>
										</tr>
									</tbody>
								</table>
							</div>
						</div>

					</div>
				</div>
			</div>
		</div>
		<!--#INCLUDE FILE="include/footer.phtml"-->
	</div>
	<!-- #INCLUDE FILE="include/js.phtml"-->
	<!-- start: JAVASCRIPTS REQUIRED FOR THIS PAGE ONLY -->
	<script src="vendor/maskedinput/jquery.maskedinput.min.js"></script>
	<script src="vendor/bootstrap-touchspin/jquery.bootstrap-touchspin.min.js"></script>
	<script src="vendor/autosize/autosize.min.js"></script>
	<script src="vendor/selectFx/classie.js"></script>
	<script src="vendor/selectFx/selectFx.js"></script>
	<script src="vendor/select2/select2.min.js"></script>
	<script src="vendor/bootstrap-datepicker/bootstrap-datepicker.min.js"></script>
	<script src="vendor/bootstrap-timepicker/bootstrap-timepicker.min.js"></script>
	<script src="vendor/DataTables/jquery.dataTables.min.js"></script>
	<!-- end: JAVASCRIPTS REQUIRED FOR THIS PAGE ONLY -->
	<script src="assets/js/main.js"></script>
	<script src="assets/js/form-elements.js"></script>
	<!-- start: JavaScript Event Handlers for this page -->
	


	<script type="text/javascript">
		
	var oTable;
	var v1 = "All";
	var v2 = "All";
	var v3 = "All";
	
	var TableData = function () {
		//function to initiate DataTable
		//DataTable is a highly flexible tool, based upon the foundations of progressive enhancement, 
		//which will add advanced interaction controls to any HTML table
		//For more information, please visit https://datatables.net/
		var runDataTable = function () {
			oTable = $('#sample_1').dataTable({
				"bProcessing": true,
				"bStateSave": false,
				"bJQueryUI": false,
				"iDisplayLength": 20,
				"bServerSide": true,
				"bAutoWidth": false,
				"sAjaxSource": "api/sp_cms.phtml",
				"aoColumns": [ 
					/* Page ID */  { "sClass": "center" },
					/* Page Title */  { "sClass": "left" },
					/* Created Date */  { "sClass": "center" },
					/* Last Updated */ { "sClass": "center" },
					/* Page Size */ { "sClass": "center" },
					/* Preview */ { "sClass": "center","bSortable": false }
				  ],
				  
				"aaSorting": [[0, 'desc']],
				"aLengthMenu": [
					[10, 20, 30, 40, 50, 100],
					[10, 20, 30, 40, 50, 100] // change per page values here
				],
				
				"oLanguage": {
					"sLengthMenu": "Show _MENU_ Rows",
					"sSearch": "",
					"sProcessing": '<img src="assets/images/ajax-loader-primary.gif"/>',
					"oPaginate": {
						"sPrevious": "",
						"sNext": ""
					}
				},
				
				'fnServerData' : function ( sSource, aoData, fnCallback ) {
					aoData.push( { 'name' : 'min', 'value' : $("#min").val() } );
					aoData.push( { 'name' : 'max', 'value' : $("#max").val() } );
					$.ajax({
						'dataType' : 'json',
						'data' : aoData,
						'type' : 'GET',
						'url' : sSource,
						'success' : fnCallback
					});
				} 
			});
			
			$('#sample_1').on( 'draw.dt', function () {
				//UIModals.init();
				var $modal = $('#ajax-modal');
				$('.ajax .demo').on('click', function () {
					// create the backdrop and wait for next modal to be triggered
					$('body').modalmanager('loading');
					modal_po_id = $(this).data('id');
					setTimeout(function () {
						$modal.load('modal_ajax_po_email.phtml?po_id=' + modal_po_id, '', function () {
							$modal.modal();
						});
					}, 1000);
				});
			} );
			
			$('#sample_1_wrapper .dataTables_filter input').addClass("form-control input-sm").attr("placeholder", "Search");
			// modify table search input
			$('#sample_1_wrapper .dataTables_length select').addClass("m-wrap small");
			// modify table per page dropdown
			$('#sample_1_wrapper .dataTables_length select').select2();
			// initialzie select2 dropdown
		};

		return {
			//main function to initiate template pages
			init: function () {
				runDataTable();
			},
			
			reload: function(theURL) {
				if ( theURL ) {
					oTable.fnReloadAjax(theURL);
				}
				else {
					oTable.fnReloadAjax('sp_cms.phtml?v1=&v2=&z1=');
				}
			}
		};
	}();

	function StatusFilter (theObj)
	{
		oTable.fnReloadAjax('api/sp_cms.phtml?v1=&v2=' + theObj.value + '&z1=');
	}
	function DateFilter()
	{
		oTable.fnReloadAjax('api/sp_cms.phtml?v1=&v2=<%=cms_filter%>&DF=' + document.getElementById('DateRange').value + '&z1=');
	}
	
	$('#daterange').on('apply.daterangepicker', function(ev, picker) { 
		oTable.fnReloadAjax('api/sp_cms.phtml?v1=&v2=<%=cms_filter%>&DF=' + document.getElementById('DateRange').value + '&z1=');
		//do something, like clearing an input
	 $('#daterange').val(''); 
	}); 
	function DeletePages()
	{
		if(confirm("You are about to delete these pages.  Do you want to continue?"))
			document.pageDelete.submit();
		else
			return false;
	}

	</script>
	
	<script>
		jQuery(document).ready(function() {
			Main.init();
			FormElements.init();
			TableData.init();
		});
	</script>
	<!-- end: JavaScript Event Handlers for this page -->
</body>
</html>
