<%
	Response.CodePage = 65001
	Response.CharSet = "UTF-8"
%>
<!-- #INCLUDE File="local/local.phtml" -->
<!-- #INCLUDE File="util/xt_func_util.phtml" -->
<!-- #INCLUDE File="util/xt_func_string.phtml" -->
<!-- #INCLUDE File="include/i_login.phtml" -->
<%
	page_id = Trim(Request("pid"))
	
	sql = "SELECT * FROM " & g_storeid & "_pages WHERE page_id='" & page_id & "'"
	set rsPages = dbconn.Execute(sql)
	if not rsPages.EOF Then
	
		page_title = rsPages("page_title")
		page_row = rsPages("page_row")
		page_topmenu = rsPages("page_topmenu")
		page_bottommenu = rsPages("page_bottommenu")
		page_showleft = rsPages("page_showleft")
		page_showright = rsPages("page_showright")
		page_date_created = rsPages("page_date_created")
		page_date_modified = rsPages("page_date_modified")
		page_size = rsPages("page_size")
		page_text = rsPages("page_text")
		page_flag = rsPages("page_flag")
		custom_page_title = rsPages("custom_page_title")
		page_url_key = rsPages("page_url_key")
		page_status = rsPages("page_status")

	end If
	
	rsPages.Close
	set rsPages = nothing
	
%>
<!--#INCLUDE FILE="include/doctype.phtml"-->
<head>
<!--#INCLUDE FILE="include/head.phtml"-->
<!-- start: CSS REQUIRED FOR THIS PAGE ONLY -->
<link href="assets/plugins/jquery-ui/jquery-ui-1.10.1.custom.css" rel="stylesheet" type="text/css"/>
<!-- end: CSS REQUIRED FOR THIS PAGE ONLY -->
<link rel="stylesheet" href="assets/css/custom.css">
</head>	
<body>
	<div id="app">
	<!--#INCLUDE FILE="include/sidebar.phtml"-->
	<div class="app-content">
		<!--#INCLUDE FILE="include/header.phtml"-->
		<div class="main-content" >
			<div class="wrap-content container" id="container">
				<!-- start: TITLE -->
				<form role="form" class="form-horizontal" id="form">
				<section id="page-title" class="padding-top-15 padding-bottom-15">
					<div class="row">
						<div class="col-sm-8">
							<h1 class="mainTitle">Custom Page</h1>
							<span class="mainDescription">Overview &amp; Edit</span>
						</div>
						<ol class="breadcrumb">
							<a href="design_cms.phtml" class="btn btn-default btn-sm" role="button">
						<i class="fa fa-arrow-circle-left"></i> Back
						</a>
						<button class="btn btn-blue btn-sm" type="submit">
						<i class="fa fa-check-square"></i>
						Save
						</button>
						<%
							if page_id = "0" then
							else
						%>
						<button class="btn btn-danger btn-sm" type="button" id="DeleteEntry">
						<i class="fa fa-times-circle"></i>
						Delete
						</button>
						<%
							end if
						%>
						</ol>
					</div>
				</section>
				<!-- end: TITLE -->
				<div class="container-fluid container-fullw bg-white">
					<div class="content-header-floating" style="display: block;">
						<div class="content-header">
							<h3 class="mainTitle">
							<%
							if Len(block_title) > 0 then
								Response.Write(block_title)
							else
								Response.Write("New Static Block")
							end if
							%>
							</h3>
							<p class="content-buttons form-buttons">
								<a href="design_cms.phtml" class="btn btn-default btn-sm" role="button">
								<i class="fa fa-arrow-circle-left"></i> Back
								</a>
								<button class="btn btn-blue btn-sm" type="submit">
								<i class="fa fa-check-square"></i>
								Save
								</button>
								<%
								if page_id = "0" then
								else
								%>
								<button class="btn btn-danger btn-sm" type="button" id="DeleteEntry">
								<i class="fa fa-times-circle"></i>
								Delete
								</button>
								<%
									end if
								%>
							</p>	
						</div>
					</div>
					<div class="row">
						<div class="col-md-12">
							<div id="errorHandler1" class="errorHandler alert alert-danger" style="display:none;">
								<button type="button" class="close" aria-label="Close">
									<span aria-hidden="true">&times;</span>
								</button>
								<i class="fa fa-times-sign"></i> You have some form errors. Please check below.
							</div>
							<div id="errorHandler2" class="errorHandler alert alert-danger" style="display:none;">
								<button type="button" class="close" aria-label="Close">
									<span aria-hidden="true">&times;</span>
								</button>
								<i class="fa fa-times-sign"></i> The information has not been saved properly. Please contact system administrator.
							</div>
							<div class="successHandler alert alert-success" style="display:none;">
								<button type="button" class="close" aria-label="Close">
									<span aria-hidden="true">&times;</span>
								</button>
								<i class="fa fa-check-square-o"></i> The page information has been saved.
								<a href="design_cms.phtml"class="btn btn-green btn-xs" role="button">
								<i class="fa  fa-chevron-left"></i> Back to list 
								</a>
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-sm-12">
							<!-- start: INLINE TABS PANEL -->
							<div class="panel panel-blue">
								<div class="panel-heading">
									<h4 class="panel-title">Information</h4>
									<div class="panel-tools" >
										<a data-original-title="Collapse" data-toggle="tooltip" data-placement="top" class="btn btn-transparent btn-sm panel-collapse" href="#"><i class="ti-minus collapse-off"></i><i class="ti-plus collapse-on"></i></a>
									</div>
								</div>
								<div class="panel-body partition-white">
									<div class="row">
										<div class="col-sm-12">
											<input type="hidden" id="page_id" name="page_id" value="<%=page_id%>" />
											<div class="row">
												<div class="col-md-12">
													<div class="form-group">
														<label class="col-sm-2 control-label" for="page_title">
															Page Title<span class="symbol required"></span>
														</label>
														<div class="col-sm-9">
															<input type="text" class="form-control input-sm" id="page_title" name="page_title" value="<%=page_title%>">
														</div>
													</div>
													<div class="form-group">
														<label class="col-sm-2 control-label" for="url_key">
															URL Key
														</label>
														<div class="col-sm-9">
															<input type="text" class="form-control input-sm" id="url_key" name="url_key" value="<%=page_url_key%>">
														</div>
													</div>
													<div class="form-group">
														<label class="col-sm-2 control-label" for="page_status">
															Status <span class="symbol required"></span>
														</label>
														<div class="col-sm-5">
															<select id="page_status"  name="page_status" class="form-control input-sm">
																<option value="1" <%if page_status = 1 then%>selected<%end if%>>Enabled</option>
																<option value="2" <%if page_status = 2 then%>selected<%end if%>>Disabled</option>
															</select>
														</div>
													</div>
													<div class="form-group">
														<label class="col-sm-2 control-label" for="page_text">
															Content <span class="symbol required"></span>
														</label>
														<div class="col-sm-9">
															<textarea id="page_text" name="page_text" class="form-control input-sm" style="height:200px;"><%=page_text%></textarea>
															<button class="btn btn-primary btn-xs" type="button" id="wysiwyg_description">
															<i class="fa fa-file-code-o"></i>
															WYSIWYG Editor
															</button>
														</div>
													</div>
												</div>
											</div>

										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				</form>
			</div>
		</div>
	</div>
	<!--#INCLUDE FILE="include/footer.phtml"-->
	</div>
	<div id="ajax-modal" class="modal container fade" tabindex="-1" style="display: none;"></div>
	<div id="dialog-confirm" title="Delete Confirmation" style="display: none;">
	<p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>You are about to permanently delete this page. Are you sure?</p>
	</div>
	<!--#INCLUDE FILE="include/js.phtml"-->
	<!-- start: JAVASCRIPTS REQUIRED FOR THIS PAGE ONLY -->
	<script src="assets/plugins/jquery-ui/jquery-ui-1.10.1.custom.min.js" type="text/javascript"></script>
	<script src="vendor/jquery-validation/jquery.validate.min.js"></script>
	<script src="assets/plugins/bootstrap-modal/js/bootstrap-modal.js"></script>
	<script src="assets/plugins/bootstrap-modal/js/bootstrap-modalmanager.js"></script>
	<!-- end: JAVASCRIPTS REQUIRED FOR THIS PAGE ONLY -->
	<script src="assets/js/main.js"></script>
	<!-- start: JavaScript Event Handlers for this page -->
	<script>
	//CKEDITOR.config.contentsCss = ['/theme/porto/js/smartwave/bootstrap/css/bootstrap.min.css', '/theme/porto/skin/frontend/smartwave/porto/css/local.css', '/theme/porto/skin/frontend/smartwave/porto/css/responsive.css'];
	//var editor = CKEDITOR.replace( 'page_text' );
	//CKFinder.setupCKEditor( editor, 'ckfinder/' );
	</script>
	<script>
	//MODAL
	var UIModals = function () {
		//function to initiate bootstrap extended modals
		var initModals = function () {
			$.fn.modalmanager.defaults.resize = true;
			$.fn.modal.defaults.spinner = $.fn.modalmanager.defaults.spinner =
				'<div class="loading-spinner" style="width: 200px; margin-left: -100px;">' +
				'<div class="progress progress-striped active">' +
				'<div class="progress-bar" style="width: 100%;"></div>' +
				'</div>' +
				'</div>';
				
			var $modal = $('#ajax-modal');
			$('#wysiwyg_description').on('click', function () {
				$('body').modalmanager('loading');
				setTimeout(function () {
					$modal.load('api/modal_ajax_wysiwyg_editor.phtml?id=page_text', '', function () {
						$modal.modal();
					});
				}, 100);
			});
			$modal.on('click', '.update_1', function () {
				editor_1.updateElement();
				$('#page_text').val($('#wysiwig_text_1').val());
				$modal.modal('hide');
			});
			
		};
		return {
			init: function () {
				initModals();
			}
		};
	}();
	</script>	
	<script language="javascript">
		var FormValidator = function () {
		// function to initiate Validation Sample 1
			var runValidator1 = function () {
				var form1 = $('#form');
				var errorHandler1 = $('#errorHandler1', form1);
				var errorHandler2 = $('#errorHandler2', form1);
				var successHandler1 = $('.successHandler', form1);

				$('#form').validate({
					errorElement: "span", // contain the error msg in a span tag
					errorClass: 'help-block',
					errorPlacement: function (error, element) { // render error placement for each input type
						if (element.attr("type") == "radio" || element.attr("type") == "checkbox") { // for chosen elements, need to insert the error after the chosen container
							error.insertAfter($(element).closest('.form-group').children('div').children().last());
						} else if (element.attr("name") == "dd" || element.attr("name") == "mm" || element.attr("name") == "yyyy") {
							error.insertAfter($(element).closest('.form-group').children('div'));
						} else {
							error.insertAfter(element);
							// for other inputs, just perform default behavior
						}
					},
					ignore: "",
					
					//RULES
					rules: {
						page_title: {
							minlength: 3,
							required: true
						},
						page_status: {
							required: true
						},
						page_text: {
							required: true
						},
						url_key: {
							minlength: 5,
							"remote":
							{
							  url: 'api/sp_product_check_url_key.phtml?pf_id=<%=page_id%>',
							  type: "post"
							}
						}
					},
					//END OF RULES
					
					messages: {
					
					url_key:
					{
						minlength: "The URL Key must be greater than 5 chracter length.",
						remote: "The specified URL Key is not unique."
					}
				},
					
					invalidHandler: function (event, validator) { //display error alert on form submit
						successHandler1.hide();
						errorHandler1.show();
					},
					highlight: function (element) {
						$(element).closest('.help-block').removeClass('valid');
						$(element).closest('.form-group').removeClass('has-success').addClass('has-error').find('.symbol').removeClass('ok').addClass('required');
					},
					unhighlight: function (element) { 
						$(element).closest('.form-group').removeClass('has-error');
					},
					success: function (label, element) {
						label.addClass('help-block valid');
						$(element).closest('.form-group').removeClass('has-error').addClass('has-success').find('.symbol').removeClass('required').addClass('ok');
					},
					submitHandler: function (form) {
						//editor.updateElement();
						successHandler1.hide();
						errorHandler1.hide();
						errorHandler2.hide();
						//page_text.value = CKEDITOR.instances.page_text.getData();
						$.ajax({
							type: "POST",
							url: "api/sp_design_cms_update.phtml",
							data: $("#form").serialize(),
							success: function() {
								successHandler1.show();
								setTimeout(function () {
									window.location.replace("design_cms.phtml");
								}, 500);
							},
							error: function() {
								errorHandler2.show();
							}
						});
					}
				});
			};
			return {
				//main function to initiate template pages
				init: function () {
					runValidator1();
				}
			};
		}();
		</script>
		<script>
			jQuery(document).ready(function() {
				Main.init();
				FormValidator.init();
				UIModals.init();
				
				$('#DeleteEntry').on('click', function () {
				$("#dialog-confirm").dialog({
					resizable: false,
					height:170,
					modal: true,
					buttons: {
						"Confirm Delete": function() {
							$( this ).dialog( "close" );
							location.replace('api/tp_design_cms_delete.phtml?page_id=<%=page_id%>')
						},
						Cancel: function() {
							$( this ).dialog( "close" );
						}
					}
				});
			});	
			});
		</script>
		
	<!-- end: JavaScript Event Handlers for this page -->
</body>
</html>
