<%
	Response.CodePage = 65001
	Response.CharSet = "UTF-8"
	
	storeviewid = Trim(Request("storeviewid"))
	if Len(storeviewid) > 0 then
		Session("CURRENT_ADMIN_VIEW_ID")  = storeviewid
	end if
%>
<!-- #INCLUDE File="local/local.phtml" -->
<!-- #INCLUDE File="../util/xt_func_util.phtml" -->
<!-- #INCLUDE File="../util/xt_func_string.phtml" -->
<!-- #INCLUDE File="../util/xt_func_user_access.phtml" -->
<!-- #INCLUDE File="include/i_login.phtml" -->
<%
	'ACCESS ROUTINE (TODO)==========================================
	'if GetAccessFlagEx(flagPurchaseOrder) = 0 then
		'Response.Redirect("dashboard.asp?err_msg=You don't have access to purchase order.")
	'end if
	'bPageAccess = GetAccessFlagEx(flagPurchaseOrder)
	'=========================================================

	view_all_po_flag = GetUserAccessVariables("VIEW_ALL_PO")
	v1 = Trim(Request("v1"))

	if Len(Request("po_display")) > 0 then
		po_display = Request("po_display")
	else
		if view_all_pos_flag = "1" then
			po_display = "3"
		else
			po_display = "1"
		end if
	end if

	index_date = DateAdd("d", -30, Date())
	Select case po_display
	case "0"
		str_filter = " WHERE date_created > '" & index_date & "'"
	case "1"

	case "2"
		str_filter = " WHERE date_created > '" & index_date & "'"
	case "3"
		str_filter = ""
	end select

	sql = "SELECT Count(*), SUM(po_amount) FROM :9_po" & str_filter
	sql = Replace(sql, ":9", g_storeid)

	set rs = dbconn.Execute(sql)

	if not rs.EOF then
		pos_count = rs(0)
		if not isNumeric(rs(1)) then
			pos_amount = 0
		else
			pos_amount = rs(1)
		end if
	end if
	rs.Close

	op = Trim(Request("op"))
	delete_po = Trim(Request("delete_po"))

	if op = "-" then
		if Len(delete_po) > 0 then
			sql = "DELETE FROM :9_po WHERE po_id IN(" & delete_po & ")"
			sql = Replace(sql, ":9", g_storeid)
			dbconn.Execute sql
			
			sql = "DELETE FROM :9_po_item WHERE po_id IN(" & delete_po & ")"
			sql = Replace(sql, ":9", g_storeid)
			dbconn.Execute sql
			
		end if
	end if
%>
<!--#INCLUDE FILE="include/doctype.phtml"-->
<head>
<!--#INCLUDE FILE="include/head.phtml"-->
<!-- start: CSS REQUIRED FOR THIS PAGE ONLY -->
<link href="vendor/bootstrap-touchspin/jquery.bootstrap-touchspin.min.css" rel="stylesheet" media="screen">
<link href="vendor/select2/select2.min.css" rel="stylesheet" media="screen">
<link href="vendor/bootstrap-datepicker/bootstrap-datepicker3.standalone.min.css" rel="stylesheet" media="screen">
<link href="vendor/bootstrap-timepicker/bootstrap-timepicker.min.css" rel="stylesheet" media="screen">
<link href="vendor/DataTables/css/DT_bootstrap.css" rel="stylesheet" media="screen">
<!-- end: CSS REQUIRED FOR THIS PAGE ONLY -->
<link rel="stylesheet" href="assets/css/custom.css">
</head>	
<body>
	<div id="app">
		<!--#INCLUDE FILE="include/sidebar.phtml"-->
		<div class="app-content">
			<!--#INCLUDE FILE="include/header.phtml"-->
			<div class="main-content" >
				<div class="wrap-content container" id="container">
					<!-- start: TITLE -->
					<section id="page-title" class="padding-top-15 padding-bottom-15">
						<div class="row">
							<div class="col-sm-8">
								<h1 class="mainTitle">Purchase Orders</h1>
								<span class="mainDescription">overview &amp; list </span>
							</div>
							<ol class="breadcrumb">
								<a class="btn btn-green btn-sm" data-toggle="modal" style="float:right" href="#stack2"><i class="ti-plus"></i> Add New Purchase Order</a>
							</ol>
						</div>
					</section>
					<!-- end: TITLE -->
					<div class="container-fluid container-fullw bg-white">

						<div class="content-header-floating" style="display: block;">
							<div class="content-header">
								<h3 class="mainTitle">Purchase Orders</h3>
								<p class="content-buttons form-buttons">
									<a class="btn btn-green btn-sm" data-toggle="modal" style="float:right" href="#stack2"><i class="ti-plus"></i> Add New Purchase Order</a>
								</p>	
							</div>
						</div>

						<div class="row">
							<div class="col-md-1">
							</div>
							<div class="col-md-7">
								<div class="row">
									<div class="col-md-9">		
										<div class="input-group input-daterange datepicker">
											<span class="input-group-addon bg-primary">Date Range <i class="fa fa-calendar"></i> </span>
											<input type="text" class="form-control"/>
											<span class="input-group-addon bg-primary">to</span>
											<input type="text" class="form-control" />
										</div>
									</div>
									<div class="col-md-3 margin-top-5"><input type="button" value="Submit" class="btn btn-blue btn-block btn-sm" onclick="DateFilter()"></span>
									</div>
								</div>
							</div>
							<div class="col-md-2">
							</div>
							<div class="col-md-2"></div>
						</div>
						<br>

						<div class="row">
							<div class="col-md-12">
								<table class="table table-striped table-bordered table-hover table-full-width" id="sample_1">
									<thead>
									<tr>
										<th colspan="8">
											<select onchange="StatusFilter(this);" class="form-control" style="width:160px;">
												<option value="Created" <%if po_filter="Created" or po_filter="" then%>Selected<%end if%>>Created</option>
												<option value="Closed" <%if po_filter="Closed" then%>Selected<%end if%>>Closed</option>
												<option value="Approved" <%if po_filter="Approved" then%>Selected<%end if%>>Approved</option>
												<option value="Fulfilled" <%if po_filter="Fulfilled" then%>Selected<%end if%>>Fulfilled</option>
												<option value="All" <%if po_filter="All" then%>Selected<%end if%>>All PO</option>
											</select>
										</th>
									</tr>
									<tr>
										<th>PO ID</th>
										<th>Company</th>
										<th>Contact</th>
										<th>Amount</th>
										<th>Status</th>
										<th>
										Last Updated
										<%
											  SELECT CASE Session("STORETIMEZONE")
											  CASE "0"
												  Response.Write("(PST)")
											  CASE "1"
												  Response.Write("(MST)")
											  CASE "2"
												  Response.Write("(CST)")
											  CASE "3"
												  Response.Write("(EST)")
											  CASE ELSE
												  Response.Write("(PST)")
											  END SELECT
										  %>
										</th>
										<th width="2%">Print</th>
										<th width="2%">Delete</th>
									</tr>
									
									</thead>
									<tbody>
										<tr>
											<td colspan="11" class="dataTables_empty">Loading data from server</td>
										</tr>
									</tbody>
								</table>	
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!--#INCLUDE FILE="include/footer.phtml"-->
	</div>
	<!--#INCLUDE FILE="include/js.phtml"-->
	<!-- start: JAVASCRIPTS REQUIRED FOR THIS PAGE ONLY -->
	<script src="vendor/maskedinput/jquery.maskedinput.min.js"></script>
	<script src="vendor/bootstrap-touchspin/jquery.bootstrap-touchspin.min.js"></script>
	<script src="vendor/autosize/autosize.min.js"></script>
	<script src="vendor/selectFx/classie.js"></script>
	<script src="vendor/selectFx/selectFx.js"></script>
	<script src="vendor/select2/select2.min.js"></script>
	<script src="vendor/bootstrap-datepicker/bootstrap-datepicker.min.js"></script>
	<script src="vendor/bootstrap-timepicker/bootstrap-timepicker.min.js"></script>
	<script src="vendor/DataTables/jquery.dataTables.min.js"></script>
	<!-- end: JAVASCRIPTS REQUIRED FOR THIS PAGE ONLY -->
	<script src="assets/js/main.js"></script>
	<script src="assets/js/form-elements.js"></script>
	<!-- start: JavaScript Event Handlers for this page -->

	<%
		po_display = "3"
		po_filter = "All"
	%>

	<script type="text/javascript">
		
	var oTable;
	var v1 = "All";
	var v2 = "All";
	var v3 = "All";
	
	var TableData = function () {
		//function to initiate DataTable
		//DataTable is a highly flexible tool, based upon the foundations of progressive enhancement, 
		//which will add advanced interaction controls to any HTML table
		//For more information, please visit https://datatables.net/
		var runDataTable = function () {
			oTable = $('#sample_1').dataTable({
				"bProcessing": true,
				"bStateSave": false,
				"bJQueryUI": false,
				"iDisplayLength": 20,
				"bServerSide": true,
				"bAutoWidth": false,
				"sAjaxSource": "api/sp_po_list.phtml?v1=<%=po_display%>&z1=",
				"aoColumns": [ 
					/* PO ID */  { "sClass": "center" },
					/* Distributor */  { "sClass": "center" },
					/* Contact */  { "sClass": "center" },
					/* po Amount */  { "sClass": "text-right" },
					/* Status */  { "sClass": "center" },
					/* Last Updated */ { "sClass": "center" },
					/* Print */ { "sClass": "center","bSortable": false },
					/* Delete */ { "sClass": "center","bSortable": false }
				  ],
				  
				"aaSorting": [[0, 'desc']],
				"aLengthMenu": [
					[10, 20, 30, 40, 50, 100],
					[10, 20, 30, 40, 50, 100] // change per page values here
				],
				
				"oLanguage": {
					"sLengthMenu": "Show _MENU_ Rows",
					"sSearch": "",
					"oPaginate": {
						"sPrevious": "",
						"sNext": ""
					}
				},
				
				'fnServerData' : function ( sSource, aoData, fnCallback ) {
					aoData.push( { 'name' : 'min', 'value' : $("#min").val() } );
					aoData.push( { 'name' : 'max', 'value' : $("#max").val() } );
					$.ajax({
						'dataType' : 'json',
						'data' : aoData,
						'type' : 'GET',
						'url' : sSource,
						'success' : fnCallback
					});
				} 
			});
			
			
			$('#sample_1').on( 'draw.dt', function () {
				//UIModals.init();
				var $modal = $('#ajax-modal');
				$('.ajax .demo').on('click', function () {
					// create the backdrop and wait for next modal to be triggered
					$('body').modalmanager('loading');
					modal_po_id = $(this).data('id');
					setTimeout(function () {
						$modal.load('modal_ajax_po_email.phtml?po_id=' + modal_po_id, '', function () {
							$modal.modal();
						});
					}, 1000);
				});
			} );
			
			$('#sample_1_wrapper .dataTables_filter input').addClass("form-control input-sm").attr("placeholder", "Search");
			// modify table search input
			$('#sample_1_wrapper .dataTables_length select').addClass("m-wrap small");
			// modify table per page dropdown
			$('#sample_1_wrapper .dataTables_length select').select2();
			// initialzie select2 dropdown
		};
		
		var runDataTable2 = function () {
			oTable = $('#sample_2').dataTable({
				"bProcessing": true,
				"bStateSave": false,
				"bJQueryUI": false,
				"iDisplayLength": 20,
				"bServerSide": true,
				"bAutoWidth": false,
				"responsive": true,
				"sAjaxSource": "api/sp_customer_list_2.phtml?v1=" + v1 + "&v2=" + v2 + "&v3=" + v3 + "&z1=",
				"aoColumns": [ 
					/* ID */  { "sClass": "left" },
					/* First Name */  { "sClass": "left"},
					/* Last Name */  { "sClass": "left" },
					/* Email */  { "sClass": "left"},
					/* Customer Since */  { "sClass": "left"},
					/* Status */ { "sClass": "center" ,"bSortable": false},
					/* Action */  { "sClass": "left"}
				  ],
				  
				"aaSorting": [[0, 'desc']],
				
				"aLengthMenu": [
					[10, 20, 30, 40, 50],
					[10, 20, 30, 40, 50] // change per page values here
				],
				
				"oLanguage": {
					"sLengthMenu": "Show _MENU_ Rows",
					"sSearch": "",
					"oPaginate": {
						"sPrevious": "",
						"sNext": ""
					}
				},
				
				'fnServerData' : function ( sSource, aoData, fnCallback ) {
					aoData.push( { 'name' : 'min', 'value' : $("#min").val() } );
					aoData.push( { 'name' : 'max', 'value' : $("#max").val() } );
					$.ajax({
						'dataType' : 'json',
						'data' : aoData,
						'type' : 'GET',
						'url' : sSource,
						'success' : fnCallback
					});
				} 
			});
			
			$('#sample_1_wrapper .dataTables_filter input').addClass("form-control input-sm").attr("placeholder", "Search");
			// modify table search input
			$('#sample_1_wrapper .dataTables_length select').addClass("m-wrap small");
			// modify table per page dropdown
			$('#sample_1_wrapper .dataTables_length select').select2();
			// initialzie select2 dropdown
		};
		
		return {
			//main function to initiate template pages
			init: function () {
				runDataTable();
				runDataTable2();
			},
			
			reload: function(theURL) {
				if ( theURL ) {
					oTable.fnReloadAjax(theURL);
				}
				else {
					oTable.fnReloadAjax('sp_po_list.phtml?v1=<%=po_display%>&v2=<%=po_filter%>&z1=');
				}
			}
		};
	}();
	
	function StatusFilter (theObj)
	{
		oTable.fnReloadAjax('sp_po_list.phtml?v1=<%=po_display%>&v2=' + theObj.value + '&z1=');
	}
	function DateFilter()
	{
		oTable.fnReloadAjax('sp_po_list.phtml?v1=<%=po_display%>&v2=<%=po_filter%>&DF=' + document.getElementById('DateRange').value + '&z1=');
	}
	
	$('#daterange').on('apply.daterangepicker', function(ev, picker) { 
		oTable.fnReloadAjax('sp_po_list.phtml?v1=<%=po_display%>&v2=<%=po_filter%>&DF=' + document.getElementById('DateRange').value + '&z1=');
		//do something, like clearing an input
	 $('#daterange').val(''); 
	}); 

	</script>	
	<script>
		jQuery(document).ready(function() {
			Main.init();
			FormElements.init();
			TableData.init();
		});
	</script>
	<!-- end: JavaScript Event Handlers for this page -->
</body>
</html>
