<%
	Response.CodePage = 65001
	Response.CharSet = "UTF-8"
%>
<!-- #INCLUDE File="local/local.phtml" -->
<!-- #INCLUDE File="util/xt_func_util.phtml" -->
<!-- #INCLUDE File="util/xt_func_string.phtml" -->
<!-- #INCLUDE File="../util/xt_func_misc_option.phtml" -->
<!-- #INCLUDE File="include/i_login.phtml" -->
<%
	g_access_key = "08-a"
%>
<!-- #INCLUDE File="include/i_access.phtml" -->
<%
	sql = "SELECT * FROM " & g_storeid & "_profile"
	set rs = dbconn.Execute(sql)
	if not rs.EOF then
	
		company = rs("Company")
		address = rs("Address")
		city = rs("City")
		state = rs("State")
		zip = rs("Zip")
		szCountry = rs("Country")
		phone = rs("Phone")
		email = rs("Email")
		
		profile_visa = rs("visa")
		profile_mastercard = rs("MasterCard")
		profile_americanexpress = rs("AmericanExpress")
		profile_discover = rs("Discover")
		profile_cod = rs("cod")
		profile_billme = rs("billme")
		'profile_check = rs("HasCheckPayment")
		
		SH_display_flag = rs("SH_display_flag")
		
		
		'Warehouse Information...
		warehouse_city = Trim(rs("warehouse_city"))
		warehouse_state = Trim(rs("warehouse_state"))
		warehouse_zip = Trim(rs("warehouse_zip"))
		warehouse_country = Trim(rs("warehouse_country"))
		
		'UPS
		sh_handling = rs("sh_handling")
		sh_handling = CStr(FormatNumber(sh_handling,2))
		sh_markup = rs("sh_markup")
		sh_markup = CStr(FormatNumber(sh_markup,2))
		ups_xml_userid = Trim(rs("ups_xml_userid"))
		ups_xml_password = Trim(rs("ups_xml_password"))
		ups_xml_key = Trim(rs("ups_xml_key"))
		ups_xml_flag = Trim(rs("ups_xml_flag"))
		sh_ups_flags = rs("sh_ups_flags")
		
		'UPS tables...(2)
		GND="0"
		DM1="0"
		DA1="0"
		DP1="0"
		DM2="0"
		DA2="0"
		DS3="0"
			
		if mid(sh_ups_flags,1,1) = "1" then
			GND = "1"
		end if
		if mid(sh_ups_flags,2,1) = "1" then
			DM1 = "1"
		end if
		if mid(sh_ups_flags,3,1) = "1" then
			DA1 = "1"
		end if
		if mid(sh_ups_flags,4,1) = "1" then
			DP1 = "1"
		end if
		if mid(sh_ups_flags,5,1) = "1" then
			DM2 = "1"
		end if
		if mid(sh_ups_flags,6,1) = "1" then
			DA2 = "1"
		end if
		if mid(sh_ups_flags,7,1) = "1" then
			DS3 = "1"
		end if
	
		'FedEx Settings
		fedex_markup = rs("fedex_markup")
		fedex_markup = CStr(FormatNumber(fedex_markup,2))
		fedex_handling = rs("fedex_handling")
		fedex_handling = CStr(FormatNumber(fedex_handling,2))
		show_fedex_tracking = rs("show_fedex_tracking")
		fedex_service_flag = Trim(rs("fedex_service_flag"))
		
		fedex_account = Trim(rs("fedex_account"))
		fedex_meter = Trim(rs("fedex_meter")) 
		
		'USPS Settings
		usps_userid = Trim(rs("usps_userid"))
		usps_password = Trim(rs("usps_password"))
		usps_markup = rs("usps_markup")
		usps_markup = CStr(FormatNumber(usps_markup,2))
		usps_handling = rs("usps_handling")
		usps_handling = CStr(FormatNumber(usps_handling,2))
		show_usps_tracking = rs("show_usps_tracking")
		usps_service_flag = Trim(rs("usps_service_flag"))
		
	end if
	rs.Close
	set rs = nothing
	
	goodgree_payment_enable = GetSettingValue("goodgree_payment_enable", "0")
	goodgree_payment_mode = GetSettingValue("goodgree_payment_mode", "sandbox")
	goodgree_payment_sandbox_sk = GetSettingValue("goodgree_payment_sandbox_sk", "")
	goodgree_payment_live_sk = GetSettingValue("goodgree_payment_live_sk", "")
	goodgree_payment_payment_action = GetSettingValue("goodgree_payment_payment_action", "authorize_capture")
	goodgree_payment_descriptor = GetSettingValue("goodgree_payment_descriptor", "")
	goodgree_payment_account_id = GetSettingValue("goodgree_payment_account_id", "")
	goodgree_payment_access_token = GetSettingValue("goodgree_payment_access_token", "")
	goodgree_payment_access_token_sandbox = GetSettingValue("goodgree_payment_access_token_sandbox", "")
	
	store_payment_gateway_enabled = GetSettingValue("store_payment_gateway_enabled", "0")
	store_payment_cc_type = GetSettingValue("store_payment_cc_type", "")
	store_payment_cc_use_card_id = GetSettingValue("store_payment_cc_use_card_id", "0")
	
	store_payment_authorizenet_api_login_id = GetSettingValue("store_payment_authorizenet_api_login_id", "")
	store_payment_authorizenet_payment_action = GetSettingValue("store_payment_authorizenet_payment_action", "authorize")
	store_payment_authorizenet_transaction_key = GetSettingValue("store_payment_authorizenet_transaction_key", "")
	
	store_payment_paypal_payflowpro_payment_action = GetSettingValue("store_payment_paypal_payflowpro_payment_action", "Authorization")
	store_payment_paypal_payflowpro_partner = GetSettingValue("store_payment_paypal_payflowpro_partner", "")
	store_payment_paypal_payflowpro_user = GetSettingValue("store_payment_paypal_payflowpro_user", "")
	store_payment_paypal_payflowpro_vendor = GetSettingValue("store_payment_paypal_payflowpro_vendor", "")
	store_payment_paypal_payflowpro_password = GetSettingValue("store_payment_paypal_payflowpro_password", "")
	
	store_payment_paypal_payflowlink_partner = GetSettingValue("store_payment_paypal_payflowlink_partner", "")
	store_payment_paypal_payflowlink_user = GetSettingValue("store_payment_paypal_payflowlink_user", "")
	store_payment_paypal_payflowlink_vendor = GetSettingValue("store_payment_paypal_payflowlink_vendor", "")
	store_payment_paypal_payflowlink_password = GetSettingValue("store_payment_paypal_payflowlink_password", "")
	
	store_payment_paypal_paymentpro_payment_action = GetSettingValue("store_payment_paypal_paymentpro_payment_action", "Authorization")
	store_payment_paypal_paymentpro_paypal_email_address = GetSettingValue("store_payment_paypal_paymentpro_paypal_email_address", "")
	store_payment_paypal_paymentpro_api_username = GetSettingValue("store_payment_paypal_paymentpro_api_username", "")
	store_payment_paypal_paymentpro_api_password = GetSettingValue("store_payment_paypal_paymentpro_api_password", "")
	store_payment_paypal_paymentpro_api_signature = GetSettingValue("store_payment_paypal_paymentpro_api_signature", "")
	store_payment_paypal_paymentpro_sandbox_mode = GetSettingValue("store_payment_paypal_paymentpro_sandbox_mode", "0")
	
	store_payment_paypal_expresscheckout_payment_action = GetSettingValue("store_payment_paypal_expresscheckout_payment_action", "0")
	store_payment_paypal_expresscheckout_paypal_email_address = GetSettingValue("store_payment_paypal_expresscheckout_paypal_email_address", "")
	store_payment_paypal_expresscheckout_api_username = GetSettingValue("store_payment_paypal_expresscheckout_api_username", "")
	store_payment_paypal_expresscheckout_api_password = GetSettingValue("store_payment_paypal_expresscheckout_api_password", "")
	store_payment_paypal_expresscheckout_api_signature = GetSettingValue("store_payment_paypal_expresscheckout_api_signature", "")
	store_payment_paypal_expresscheckout_sandbox_mode = GetSettingValue("store_payment_paypal_expresscheckout_sandbox_mode", "0")
	
	store_payment_check_enabled = GetSettingValue("store_payment_check_enabled", "0")
	store_payment_check_title = GetSettingValue("store_payment_check_title", "Check/Money Order")
	
	store_payment_purchase_order_enabled = GetSettingValue("store_payment_purchase_order_enabled", "0")
	store_payment_purchase_order_title = GetSettingValue("store_payment_purchase_order_title", "Purchase Order")
	


%>
<!--#INCLUDE FILE="include/doctype.phtml"-->
<head>
<!--#INCLUDE FILE="include/head.phtml"-->
<!-- start: CSS REQUIRED FOR THIS PAGE ONLY -->
<!-- end: CSS REQUIRED FOR THIS PAGE ONLY -->
<link rel="stylesheet" href="assets/css/custom.css">
</head>	
<body>
	<div id="app">
		<!--#INCLUDE FILE="include/sidebar.phtml"-->
		<div class="app-content">
			<!--#INCLUDE FILE="include/header.phtml"-->
			<div class="main-content" >
				<div class="wrap-content container" id="container">
					<!-- start: TITLE -->
					<section id="page-title" class="padding-top-15 padding-bottom-15">
						<div class="row">
							<div class="col-sm-8">
								<h1 class="mainTitle">Store Information</h1>
								<span class="mainDescription">overview </span>
							</div>
							<ol class="breadcrumb">
								
							</ol>
						</div>
					</section>
					<!-- end: TITLE -->
					<div class="container-fluid container-fullw bg-white">
						<div class="content-header-floating" style="display: block;">
							<div class="content-header">
								<h3 class="mainTitle">Store Information</h3>
								<p class="content-buttons form-buttons">
									
								</p>	
							</div>
						</div>
						<div class="row">
							<div class="col-sm-12">
								<!-- start: INLINE TABS PANEL -->
								<div class="panel panel-dark-primary collapses">
									<div class="panel-heading">
										<h4 class="panel-title">General Information</h4>
										<div class="panel-tools" >
											<a data-original-title="Collapse" data-toggle="tooltip" data-placement="top" class="btn btn-transparent btn-sm panel-collapse" href="#"><i class="ti-minus collapse-off"></i><i class="ti-plus collapse-on"></i></a>
										</div>
									</div>
									<div class="panel-body partition-white">
										<div class="row">
											<div class="col-sm-12">
												<form role="form" class="form-horizontal" id="form1">
													<input type="hidden" id="formid" name="formid" value="pan1" />
													<div class="row">
														<div class="col-md-12">
															<div id="errorHandler1_1" class="errorHandler alert alert-danger" style="display:none;">
																<button type="button" class="close" aria-label="Close">
																	<span aria-hidden="true">&times;</span>
																</button>
																<i class="fa fa-times-sign"></i> You have some form errors. Please check below.
															</div>
															<div id="errorHandler2_1" class="errorHandler alert alert-danger" style="display:none;">
																<button type="button" class="close" aria-label="Close">
																	<span aria-hidden="true">&times;</span>
																</button>
																<i class="fa fa-times-sign"></i> The information has not been saved properly. Please contact system administrator.
															</div>
															<div id="successHandler_1" class="successHandler alert alert-success" style="display:none;">
																<button type="button" class="close" aria-label="Close">
																	<span aria-hidden="true">&times;</span>
																</button>
																<i class="fa fa-check-square-o"></i> The information has been saved.
															</div>
														</div>
														<div class="col-md-12">
															<div class="form-group">
																<label class="col-sm-2 control-label" for="company">
																	Company <span class="symbol required"></span>
																</label>
																<div class="col-sm-9">
																	<input type="text" placeholder="" class="form-control input-sm" id="company" name="company" value="<%=company%>">
																</div>
															</div>
															<div class="form-group">
																<label class="col-sm-2 control-label" for="address">
																	Street Address <span class="symbol required"></span>
																</label>
																<div class="col-sm-9">
																	<input type="text" placeholder="" id="address" name="address" class="form-control input-sm" value="<%=address%>">
																</div>
															</div>
															<div class="form-group">
																<label class="col-sm-2 control-label" for="city">
																	City <span class="symbol required"></span>
																</label>
																<div class="col-sm-9">
																	<input type="text"  id="city" name="city" class="form-control input-sm" value="<%=city%>">
																</div>
															</div>
															<div class="form-group">
																<label class="col-sm-2 control-label" for="state">
																	State / Province <span class="symbol required"></span>
																</label>
																<div class="col-sm-9">
																	<select class="form-control input-sm" id="state" name="state">
																		<%=GetStatesOptionTags(state)%>
																	</select>
																</div>
															</div>
															<div class="form-group">
																<label class="col-sm-2 control-label" for="zip">
																	Zip / Postal Code <span class="symbol required"></span>
																</label>
																<div class="col-sm-9">
																	<input type="text"  id="zip" name="zip" class="form-control input-sm" value="<%=zip%>">
																</div>
															</div>
															<div class="form-group">
																<label class="col-sm-2 control-label" for="phone">
																	Phone Number <span class="symbol required"></span>
																</label>
																<div class="col-sm-9">
																	<input type="text"  id="phone" name="phone" class="form-control input-sm" value="<%=phone%>">
																</div>
															</div>
															<div class="form-group">
																<label class="col-sm-2 control-label" for="email">
																	Email Address <span class="symbol required"></span>
																</label>
																<div class="col-sm-9">
																	<input type="text"  id="email" name="email" class="form-control input-sm" value="<%=email%>">
																</div>
															</div>
															<!--
															<div class="form-group">
																<label class="col-sm-2 control-label" for="form-field-1">
																	Show this on Contact Block <span class="symbol required"></span>
																</label>
																<div class="col-sm-9">
																	<label class="radio-inline">
																		<input type="radio" value="" name="optionsRadios" class="grey">
																		Yes
																	</label>
																	<label class="radio-inline">
																		<input type="radio" value="" name="optionsRadios" class="grey">
																		No
																	</label>
																</div>
															</div>
															-->
															
														</div>
													</div>
													<div class="row">
														<div class="col-sm-1">
														</div>
														<div class="col-sm-8">
															<button class="btn btn-blue btn-sm" type="submit">
															<i class="fa fa-check-square"></i>
															Save
															</button>
														</div>
													</div>
												</form>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
						
						<div class="row">
							<div class="col-sm-12">
								<!-- start: INLINE TABS PANEL -->
								<div class="panel panel-dark-primary collapses">
									<div class="panel-heading">
										<h4 class="panel-title">Payments</h4>
										<div class="panel-tools" >
											<a data-original-title="Collapse" data-toggle="tooltip" data-placement="top" class="btn btn-transparent btn-sm panel-collapse" href="#"><i class="ti-minus collapse-off"></i><i class="ti-plus collapse-on"></i></a>
										</div>
									</div>
									<div class="panel-body partition-white">
										<div class="row">
											<div class="col-sm-12">
												<form role="form"  action="tp_store_information_payment_update.phtml" class="form-horizontal" id="form2" method="post">
												<input type="hidden" id="formid" name="formid" value="pan2" />
												<div class="row">
													<div class="col-md-12">
														<div id="errorHandler1_2" class="errorHandler alert alert-danger" style="display:none;">
															<button type="button" class="close" aria-label="Close">
																<span aria-hidden="true">&times;</span>
															</button>
															<i class="fa fa-times-sign"></i> You have some form errors. Please check below.
														</div>
														<div id="errorHandler2_2" class="errorHandler alert alert-danger" style="display:none;">
															<button type="button" class="close" aria-label="Close">
																<span aria-hidden="true">&times;</span>
															</button>
															<i class="fa fa-times-sign"></i> The information has not been saved properly. Please contact system administrator.
														</div>
														<div id="successHandler_2" class="successHandler alert alert-success" style="display:none;">
															<button type="button" class="close" aria-label="Close">
																<span aria-hidden="true">&times;</span>
															</button>
															<i class="fa fa-check-square-o"></i> The information has been saved.
														</div>
													</div>
												</div>
												<div class="tabbable">
													<ul id="myTab4" class="nav nav-tabs tab-green">
														<li class="active">
															<a href="#panel_tab2_example0" data-toggle="tab">
																Settings
															</a>
														</li>
														<li>
															<a href="#panel_tab2_example2" data-toggle="tab">
																Authorize.net
															</a>
														</li>
														<li>
															<a href="#panel_tab2_example3" data-toggle="tab">
																Paypal
															</a>
														</li>
														<li>
															<a href="#panel_tab2_example4" data-toggle="tab">
																Check / Money Order
															</a>
														</li>
														<li>
															<a href="#panel_tab2_example5" data-toggle="tab">
																Purchase Order
															</a>
														</li>
														<li>
															<a href="#panel_tab2_example1" data-toggle="tab">
																Stripe Payment
															</a>
														</li>
													</ul>
													
													<div class="tab-content">
														<div class="tab-pane active" id="panel_tab2_example0">
															<div class="form-group">
																<label class="col-sm-2 control-label" for="store_payment_gateway_enabled">
																	Gateway Enable <span class="symbol required"></span>
																</label>
																<div class="col-sm-4">
																	<select id="store_payment_gateway_enabled" name="store_payment_gateway_enabled" class="form-control select input-sm">
																		<option value="0" <% if store_payment_gateway_enabled = "0" then%>selected<% end if %>>No</option>
																		<option value="6" <% if store_payment_gateway_enabled = "6" then%>selected<% end if %>>Authorize.net</option>
																		<option value="2" <% if store_payment_gateway_enabled = "2" then%>selected<% end if %>>Paypal Payflow Pro</option>
																		<option value="5" <% if store_payment_gateway_enabled = "5" then%>selected<% end if %>>Paypal Payflow Link</option>
																		<option value="91" <% if store_payment_gateway_enabled = "91" then%>selected<% end if %>>Paypal Payment Pro</option>
																		<option value="18" <% if store_payment_gateway_enabled = "18" then%>selected<% end if %>>Stripe</option>
																	</select>
																</div>
																<div class="col-sm-4">
																</div>
															</div>
															<div class="form-group">
																<label class="col-sm-2 control-label" for="store_payment_cc_type">
																	Credit Card Types <span class="symbol required"></span>
																</label>
																<div class="col-sm-4">
																	<select id="store_payment_cc_type" name="store_payment_cc_type" class="form-control select input-sm" size="5" multiple="multiple">
																	<option value="AE">American Express</option>
																	<option value="VI" selected="selected">Visa</option>
																	<option value="MC" selected="selected">MasterCard</option>
																	<option value="DI" selected="selected">Discover</option>
																	<option value="OT" selected="selected">JCB Card</option>
																	</select>
																</div>
															</div>
															<div class="form-group">
																<label class="col-sm-2 control-label" for="store_payment_cc_use_card_id">
																	Credit Card Verification <span class="symbol required"></span>
																</label>
																<div class="col-sm-4">
																	<select id="store_payment_cc_use_card_id" name="store_payment_cc_use_card_id" class="form-control select input-sm">
																	<option value="1" <% if store_payment_cc_use_card_id = "1" then%>selected<% end if %>>Yes</option>
																	<option value="0" <% if store_payment_cc_use_card_id = "0" then%>selected<% end if %>>No</option>
																	</select>
																</div>
															</div>
														</div>
														<div class="tab-pane" id="panel_tab2_example1">
															<div class="form-group">
																<label class="col-sm-2 control-label" for="goodgree_payment_mode">
																	Mode <span class="symbol required"></span>
																</label>
																<div class="col-sm-9">
																	<select id="goodgree_payment_mode" name="goodgree_payment_mode" class="form-control select input-sm">
																		<option value="sandbox"  <% if goodgree_payment_mode = "sandbox" then%>selected<% end if %>>Sandbox</option>
																		<option value="live"  <% if goodgree_payment_mode = "live" then%>selected<% end if %>>Live</option>
																	</select>
																</div>
															</div>
															<!--
															<div class="form-group">
																<label class="col-sm-2 control-label" for="goodgree_payment_sandbox_sk">
																	Test Secret Key <span class="symbol required"></span>
																</label>
																<div class="col-sm-9">
																	<input type="text"  id="goodgree_payment_sandbox_sk" name="goodgree_payment_sandbox_sk" class="form-control" value="<%=goodgree_payment_sandbox_sk%>">
																</div>
															</div>
															<div class="form-group">
																<label class="col-sm-2 control-label" for="goodgree_payment_live_sk">
																	Live Secret Key <span class="symbol required"></span>
																</label>
																<div class="col-sm-9">
																	<input type="text"  id="goodgree_payment_live_sk" name="goodgree_payment_live_sk" class="form-control" value="<%=goodgree_payment_live_sk%>">
																</div>
															</div>
															-->
															<div class="form-group">
																<label class="col-sm-2 control-label" for="goodgree_payment_payment_action">
																	Payment Action <span class="symbol required"></span>
																</label>
																<div class="col-sm-9">
																	<select id="goodgree_payment_payment_action" name="goodgree_payment_payment_action" class="form-control select input-sm">
																		<option value="authorize" <% if goodgree_payment_payment_action = "authorize" then%>selected<% end if %>>Authorize Only</option>
																		<option value="authorize_capture" <% if goodgree_payment_payment_action = "authorize_capture" then%>selected<% end if %>>Authorize and Capture</option>
																	</select>
																</div>
															</div>
															
															<div class="form-group">
																<label class="col-sm-2 control-label" for="goodgree_payment_descriptor">
																	Store Descriptor (OC:xxxxxx)<span class="symbol required"></span>
																</label>
																<div class="col-sm-9">
																	<input type="text"  id="goodgree_payment_descriptor" name="goodgree_payment_descriptor" class="form-control input-sm" value="<%=goodgree_payment_descriptor%>">
																</div>
															</div>
															
															<div class="form-group">
																<label class="col-sm-2 control-label" for="goodgree_payment_account_id">
																	Account ID
																</label>
																<div class="col-sm-9">
																	<input type="text"  id="goodgree_payment_account_id" name="goodgree_payment_account_id" class="form-control input-sm" value="<%=goodgree_payment_account_id%>" disabled>
																</div>
															</div>
															
															<div class="form-group">
																<label class="col-sm-2 control-label" for="goodgree_payment_access_token_sandbox">
																	Access Key (sandbox)
																</label>
																<div class="col-sm-9">
																	<input type="text"  id="goodgree_payment_access_token_sandbox" name="goodgree_payment_access_token_sandbox" class="form-control input-sm" value="<%=goodgree_payment_access_token_sandbox%>" disabled>
																</div>
															</div>
															
															<div class="form-group">
																<label class="col-sm-2 control-label" for="goodgree_payment_access_token">
																	Access Key (production)
																</label>
																<div class="col-sm-9">
																	<input type="text"  id="goodgree_payment_access_token" name="goodgree_payment_access_token" class="form-control input-sm" value="<%=goodgree_payment_access_token%>" disabled>
																</div>
															</div>
															
															<div class="form-group">
																<label class="col-sm-2 control-label" for="goodgree_payment_account_id">
																	&nbsp;
																</label>
																<div class="col-sm-9">
																	<a class="stripe-connect" href="http://app.olivecommerce.com/stripe_auth.php?storeid=<%=g_storeid%>" target="_blank"><span>Connect with Stripe (sandbox)</span></a>
																	<a class="stripe-connect" href="http://app.olivecommerce.com/stripe_auth_production.php?storeid=<%=g_storeid%>" target="_blank"><span>Connect with Stripe (live)</span></a>
																</div>
															</div>
														</div>
														<div class="tab-pane" id="panel_tab2_example2">
															<div class="form-group">
																<label class="col-sm-2 control-label" for="store_payment_authorizenet_payment_action">
																	Payment Action <span class="symbol required"></span>
																</label>
																<div class="col-sm-4">
																	<select id="store_payment_authorizenet_payment_action" name="store_payment_authorizenet_payment_action" class="form-control select input-sm">
																		<option value="authorize" <% if store_payment_authorizenet_payment_action = "authorize" then%>selected<% end if %>>Authorize Only</option>
																		<option value="authorize_capture" <% if store_payment_authorizenet_payment_action = "authorize_capture" then%>selected<% end if %>>Authorize and Capture</option>
																	</select>
																</div>
															</div>
															<div class="form-group">
																<label class="col-sm-2 control-label" for="store_payment_authorizenet_api_login_id">
																	API Login ID <span class="symbol required"></span>
																</label>
																<div class="col-sm-9">
																	<input type="text" placeholder="" class="form-control input-sm" id="store_payment_authorizenet_api_login_id" name="store_payment_authorizenet_api_login_id" value="<%=store_payment_authorizenet_api_login_id%>">
																</div>
															</div>
															<div class="form-group">
																<label class="col-sm-2 control-label" for="store_payment_authorizenet_transaction_key">
																	Transaction Key <span class="symbol required"></span>
																</label>
																<div class="col-sm-9">
																	<input type="text" placeholder="" class="form-control input-sm" id="store_payment_authorizenet_transaction_key" name="store_payment_authorizenet_transaction_key" value="<%=store_payment_authorizenet_transaction_key%>">
																</div>
															</div>
														</div>
														<div class="tab-pane" id="panel_tab2_example3">
															<div class="row">
																<div class="col-lg-12">
																	<!--
																	<h5 class="over-title margin-bottom-15"><span class="text-bold">Bootsrap Accordions</span></h5>
																	<p>
																		Extend the default collapse behavior to create an accordion with the panel component.
																	</p>
																	-->
																	<div class="panel-group accordion" id="accordion">
																		<div class="panel panel-white">
																			<div class="panel-heading">
																				<h5 class="panel-title">
																				<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
																					<i class="icon-arrow"></i> Paypal Payflow Pro
																				</a></h5>
																			</div>
																			<div id="collapseOne" class="panel-collapse collapse">
																				<div class="panel-body">
																					<div class="form-group">
																						<label class="col-sm-2 control-label" for="store_payment_paypal_payflowpro_payment_action">
																							Payment Action <span class="symbol required"></span>
																						</label>
																						<div class="col-sm-4">
																							<select id="store_payment_paypal_payflowpro_payment_action" name="store_payment_paypal_payflowpro_payment_action" class="form-control select input-sm">
																							<option value="Authorization" <% if store_payment_paypal_payflowpro_payment_action = "Authorization" then%>selected<% end if %>>Authorization</option>
																							<option value="Sale" <% if store_payment_paypal_payflowpro_payment_action = "Sale" then%>selected<% end if %>>Sale</option>
																							</select>
																						</div>
																					</div>
																					<div class="form-group">
																						<label class="col-sm-2 control-label" for="store_payment_paypal_payflowpro_partner">
																							Partner <span class="symbol required"></span>
																						</label>
																						<div class="col-sm-9">
																							<input type="text" placeholder="" class="form-control input-sm" id="store_payment_paypal_payflowpro_partner" name="store_payment_paypal_payflowpro_partner" value="<%=store_payment_paypal_payflowpro_partner%>">
																						</div>
																					</div>
																					<div class="form-group">
																						<label class="col-sm-2 control-label" for="store_payment_paypal_payflowpro_user">
																							User <span class="symbol required"></span>
																						</label>
																						<div class="col-sm-9">
																							<input type="text" placeholder="" class="form-control input-sm" id="store_payment_paypal_payflowpro_user" name="store_payment_paypal_payflowpro_user" value="<%=store_payment_paypal_payflowpro_user%>">
																						</div>
																					</div>
																					<div class="form-group">
																						<label class="col-sm-2 control-label" for="store_payment_paypal_payflowpro_vendor">
																							Vendor <span class="symbol required"></span>
																						</label>
																						<div class="col-sm-9">
																							<input type="text" placeholder="" class="form-control input-sm" id="store_payment_paypal_payflowpro_vendor" name="store_payment_paypal_payflowpro_vendor" value="<%=store_payment_paypal_payflowpro_vendor%>">
																						</div>
																					</div>
																					<div class="form-group">
																						<label class="col-sm-2 control-label" for="store_payment_paypal_payflowpro_password">
																							Password <span class="symbol required"></span>
																						</label>
																						<div class="col-sm-9">
																							<input type="text" placeholder="" class="form-control input-sm" id="store_payment_paypal_payflowpro_password" name="store_payment_paypal_payflowpro_password" value="<%=store_payment_paypal_payflowpro_password%>">
																						</div>
																					</div>
																				</div>
																			</div>
																		</div>
																		<div class="panel panel-white">
																			<div class="panel-heading">
																				<h5 class="panel-title">
																				<a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">
																					<i class="icon-arrow"></i> Paypal Payflow Link
																				</a></h5>
																			</div>
																			<div id="collapseTwo" class="panel-collapse collapse">
																				<div class="panel-body">
																					<div class="form-group">
																						<label class="col-sm-2 control-label" for="store_payment_paypal_payflowlink_partner">
																							Partner <span class="symbol required"></span>
																						</label>
																						<div class="col-sm-9">
																							<input type="text" placeholder="" class="form-control input-sm" id="store_payment_paypal_payflowlink_partner" name="store_payment_paypal_payflowlink_partner" value="<%=store_payment_paypal_payflowlink_partner%>">
																						</div>
																					</div>
																					<div class="form-group">
																						<label class="col-sm-2 control-label" for="store_payment_paypal_payflowlink_user">
																							User <span class="symbol required"></span>
																						</label>
																						<div class="col-sm-9">
																							<input type="text" placeholder="" class="form-control input-sm" id="store_payment_paypal_payflowlink_user" name="store_payment_paypal_payflowlink_user" value="<%=store_payment_paypal_payflowlink_user%>">
																						</div>
																					</div>
																					<div class="form-group">
																						<label class="col-sm-2 control-label" for="store_payment_paypal_payflowlink_vendor">
																							Vendor <span class="symbol required"></span>
																						</label>
																						<div class="col-sm-9">
																							<input type="text" placeholder="" class="form-control input-sm" id="store_payment_paypal_payflowlink_vendor" name="store_payment_paypal_payflowlink_vendor" value="<%=store_payment_paypal_payflowlink_vendor%>">
																						</div>
																					</div>
																					<div class="form-group">
																						<label class="col-sm-2 control-label" for="store_payment_paypal_payflowlink_password ">
																							Password <span class="symbol required"></span>
																						</label>
																						<div class="col-sm-9">
																							<input type="text" placeholder="" class="form-control input-sm" id="store_payment_paypal_payflowlink_password " name="store_payment_paypal_payflowlink_password " value="<%=store_payment_paypal_payflowlink_password %>">
																						</div>
																					</div>
																				</div>
																			</div>
																		</div>
																		<div class="panel panel-white">
																			<div class="panel-heading">
																				<h5 class="panel-title">
																				<a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
																					<i class="icon-arrow"></i> Payflow Payments Pro
																				</a></h5>
																			</div>
																			<div id="collapseThree" class="panel-collapse collapse">
																				<div class="panel-body">
																					<div class="form-group">
																						<label class="col-sm-2 control-label" for="store_payment_paypal_paymentpro_payment_action">
																							Payment Action <span class="symbol required"></span>
																						</label>
																						<div class="col-sm-4">
																							<select id="store_payment_paypal_paymentpro_payment_action" name="store_payment_paypal_paymentpro_payment_action" class="form-control select input-sm">
																							<option value="Authorization" <% if store_payment_paypal_paymentpro_payment_action = "Authorization" then%>selected<% end if %>>Authorization</option>
																							<option value="Sale" <% if store_payment_paypal_paymentpro_payment_action = "Sale" then%>selected<% end if %>>Sale</option>
																							</select>
																						</div>
																					</div>
																					<div class="form-group">
																						<label class="col-sm-2 control-label" for="store_payment_paypal_paymentpro_paypal_email_address">
																							Paypal Email Address <span class="symbol required"></span>
																						</label>
																						<div class="col-sm-9">
																							<input type="text" placeholder="" class="form-control input-sm" id="store_payment_paypal_paymentpro_paypal_email_address" name="store_payment_paypal_paymentpro_paypal_email_address" value="<%=store_payment_paypal_paymentpro_paypal_email_address%>">
																						</div>
																					</div>
																					<div class="form-group">
																						<label class="col-sm-2 control-label" for="store_payment_paypal_paymentpro_api_username">
																							API Username <span class="symbol required"></span>
																						</label>
																						<div class="col-sm-9">
																							<input type="text" placeholder="" class="form-control input-sm" id="store_payment_paypal_paymentpro_api_username" name="store_payment_paypal_paymentpro_api_username" value="<%=store_payment_paypal_paymentpro_api_username%>">
																						</div>
																					</div>
																					<div class="form-group">
																						<label class="col-sm-2 control-label" for="store_payment_paypal_paymentpro_api_password">
																							API Password <span class="symbol required"></span>
																						</label>
																						<div class="col-sm-9">
																							<input type="text" placeholder="" class="form-control input-sm" id="store_payment_paypal_paymentpro_api_password" name="store_payment_paypal_paymentpro_api_password" value="<%=store_payment_paypal_paymentpro_api_password%>">
																						</div>
																					</div>
																					<div class="form-group">
																						<label class="col-sm-2 control-label" for="store_payment_paypal_paymentpro_api_signature">
																							API Signature <span class="symbol required"></span>
																						</label>
																						<div class="col-sm-9">
																							<input type="text" placeholder="" class="form-control input-sm" id="store_payment_paypal_paymentpro_api_signature" name="store_payment_paypal_paymentpro_api_signature" value="<%=store_payment_paypal_paymentpro_api_signature%>">
																						</div>
																					</div>
																					<div class="form-group">
																						<label class="col-sm-2 control-label" for="store_payment_paypal_paymentpro_sandbox_mode">
																							Mode <span class="symbol required"></span>
																						</label>
																						<div class="col-sm-4">
																							<select id="store_payment_paypal_paymentpro_sandbox_mode" name="store_payment_paypal_paymentpro_sandbox_mode" class="form-control select input-sm">
																							<option value="1" <% if store_payment_paypal_paymentpro_sandbox_mode = "1" then%>selected<% end if %>>Yes</option>
																							<option value="0" <% if store_payment_paypal_paymentpro_sandbox_mode = "0" then%>selected<% end if %>>No</option>
																							</select>
																						</div>
																					</div>
																				</div>
																			</div>
																		</div>
																		<div class="panel panel-white">
																			<div class="panel-heading">
																				<h5 class="panel-title">
																				<a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseFour">
																					<i class="icon-arrow"></i> Payflow Express Checkout
																				</a></h5>
																			</div>
																			<div id="collapseFour" class="panel-collapse collapse">
																				<div class="panel-body">
																					<div class="form-group">
																						<label class="col-sm-2 control-label" for="store_payment_paypal_expresscheckout_payment_action">
																							Payment Action <span class="symbol required"></span>
																						</label>
																						<div class="col-sm-4">
																							<select id="store_payment_paypal_expresscheckout_payment_action " name="store_payment_paypal_expresscheckout_payment_action " class="form-control select input-sm">
																							<option value="0" <% if store_payment_paypal_expresscheckout_payment_action = "0" then%>selected<% end if %>>Disable</option>
																							<option value="Authorization" <% if store_payment_paypal_expresscheckout_payment_action = "Authorization" then%>selected<% end if %>>Authorization</option>
																							<option value="Sale" <% if store_payment_paypal_expresscheckout_payment_action = "Sale" then%>selected<% end if %>>Sale</option>
																							</select>
																						</div>
																					</div>
																					<div class="form-group">
																						<label class="col-sm-2 control-label" for="store_payment_paypal_expresscheckout_paypal_email_address">
																							Paypal Email Address <span class="symbol required"></span>
																						</label>
																						<div class="col-sm-9">
																							<input type="text" placeholder="" class="form-control input-sm" id="store_payment_paypal_expresscheckout_paypal_email_address" name="store_payment_paypal_expresscheckout_paypal_email_address" value="<%=store_payment_paypal_expresscheckout_paypal_email_address%>">
																						</div>
																					</div>
																					<div class="form-group">
																						<label class="col-sm-2 control-label" for="store_payment_paypal_expresscheckout_api_username">
																							API Username <span class="symbol required"></span>
																						</label>
																						<div class="col-sm-9">
																							<input type="text" placeholder="" class="form-control input-sm" id="store_payment_paypal_expresscheckout_api_username" name="store_payment_paypal_expresscheckout_api_username" value="<%=store_payment_paypal_expresscheckout_api_username%>">
																						</div>
																					</div>
																					<div class="form-group">
																						<label class="col-sm-2 control-label" for="store_payment_paypal_expresscheckout_api_password">
																							API Password <span class="symbol required"></span>
																						</label>
																						<div class="col-sm-9">
																							<input type="text" placeholder="" class="form-control input-sm" id="store_payment_paypal_expresscheckout_api_password" name="store_payment_paypal_expresscheckout_api_password" value="<%=store_payment_paypal_expresscheckout_api_password%>">
																						</div>
																					</div>
																					<div class="form-group">
																						<label class="col-sm-2 control-label" for="store_payment_paypal_expresscheckout_api_signature">
																							API Signature <span class="symbol required"></span>
																						</label>
																						<div class="col-sm-9">
																							<input type="text" placeholder="" class="form-control input-sm" id="store_payment_paypal_expresscheckout_api_signature" name="store_payment_paypal_expresscheckout_api_signature" value="<%=store_payment_paypal_expresscheckout_api_signature%>">
																						</div>
																					</div>
																					<div class="form-group">
																						<label class="col-sm-2 control-label" for="store_payment_paypal_expresscheckout_sandbox_mode">
																							Mode <span class="symbol required"></span>
																						</label>
																						<div class="col-sm-4">
																							<select id="store_payment_paypal_expresscheckout_sandbox_mode" name="store_payment_paypal_expresscheckout_sandbox_mode" class="form-control select input-sm">
																							<option value="1" <% if store_payment_paypal_expresscheckout_sandbox_mode = "1" then%>selected<% end if %>>Yes</option>
																							<option value="0" <% if store_payment_paypal_expresscheckout_sandbox_mode = "0" then%>selected<% end if %>>No</option>
																							</select>
																						</div>
																					</div>
																				</div>
																			</div>
																		</div>
																	</div>
																</div>
															</div>
														</div>
														<div class="tab-pane" id="panel_tab2_example4">
															<div class="form-group">
																<label class="col-sm-2 control-label" for="store_payment_check_enabled">
																	Enabled <span class="symbol required"></span>
																</label>
																<div class="col-sm-4">
																	<select id="store_payment_check_enabled" name="store_payment_check_enabled" class="form-control select input-sm">
																		<option value="1" <% if store_payment_check_enabled = "1" then%>selected<% end if %>>Yes</option>
																		<option value="0" <% if store_payment_check_enabled = "0" then%>selected<% end if %>>No</option>
																	</select>
																</div>
															</div>
															<div class="form-group">
																<label class="col-sm-2 control-label" for="store_payment_check_title">
																	Title <span class="symbol required"></span>
																</label>
																<div class="col-sm-9">
																	<input type="text" placeholder="" class="form-control input-sm" id="store_payment_check_title" name="store_payment_check_title" value="<%=store_payment_check_title%>">
																</div>
															</div>
														</div>
														<div class="tab-pane" id="panel_tab2_example5">
															<div class="form-group">
																<label class="col-sm-2 control-label" for="store_payment_purchase_order_enabled">
																	Enabled <span class="symbol required"></span>
																</label>
																<div class="col-sm-4">
																	<select id="store_payment_purchase_order_enabled" name="store_payment_purchase_order_enabled" class="form-control select input-sm">
																		<option value="1" <% if store_payment_purchase_order_enabled = "1" then%>selected<% end if %>>Yes</option>
																		<option value="0" <% if store_payment_purchase_order_enabled = "0" then%>selected<% end if %>>No</option>
																	</select>
																</div>
															</div>
															<div class="form-group">
																<label class="col-sm-2 control-label" for="store_payment_purchase_order_title">
																	Title <span class="symbol required"></span>
																</label>
																<div class="col-sm-9">
																	<input type="text" placeholder="" class="form-control input-sm" id="store_payment_purchase_order_title" name="store_payment_purchase_order_title" value="<%=store_payment_purchase_order_title%>">
																</div>
															</div>
														</div>
													</div>
												</div>
												<div class="row">
													<div class="col-sm-1">
													</div>
													<div class="col-sm-8">
														<button class="btn btn-blue btn-sm" type="submit">
														<i class="fa fa-check-square"></i>
														Save
														</button>
													</div>
												</div>
												</form>
											</div>
										</div>
									</div>
								</div>
								<!-- end: INLINE TABS PANEL -->
							</div>
						</div>
						<div class="row">
							<div class="col-sm-12">
								<!-- start: INLINE TABS PANEL -->
								<div class="panel panel-dark-primary collapses">
									<div class="panel-heading">
										<h4 class="panel-title">Shipping</h4>
										<div class="panel-tools" >
											<a data-original-title="Collapse" data-toggle="tooltip" data-placement="top" class="btn btn-transparent btn-sm panel-collapse" href="#"><i class="ti-minus collapse-off"></i><i class="ti-plus collapse-on"></i></a>
										</div>
									</div>
									<div class="panel-body partition-white">
										<div class="row">
											<div class="col-sm-12">
												<div class="tabbable">
													<ul id="myTab4" class="nav nav-tabs tab-padding tab-space-3 tab-blue">
														<li class="active">
															<a href="#panel_tab3_example1" data-toggle="tab">
																Preference
															</a>
														</li>
														<li>
															<a href="#panel_tab3_example2" data-toggle="tab">
																UPS
															</a>
														</li>
														<li>
															<a href="#panel_tab3_example3" data-toggle="tab">
																FedEx
															</a>
														</li>
														<li>
															<a href="#panel_tab3_example4" data-toggle="tab">
																USPS
															</a>
														</li>
														<!--
														<li>
															<a href="#panel_tab3_example5" data-toggle="tab">
																Flat Table
															</a>
														</li>
														<li>
															<a href="#panel_tab3_example6" data-toggle="tab">
																Custom Table
															</a>
														</li>
														-->
													</ul>
													<form role="form"  action="tp_store_information_shipping_update.phtml" class="form-horizontal" id="form3">
													<div class="tab-content">
														<div class="tab-pane in active" id="panel_tab3_example1">
															<h4><i class="fa fa-pencil-square teal"></i> Warehouse</h4>
															<div class="form-group">
																<label class="col-sm-3 control-label" for="warehouse_city">
																	City <span class="symbol required"></span>
																</label>
																<div class="col-sm-9">
																	<input type="text"  id="warehouse_city" name="warehouse_city" class="form-control" value="<%=warehouse_city%>">
																</div>
															</div>
															<div class="form-group">
																<label class="col-sm-3 control-label" for="warehouse_country">
																	Country <span class="symbol required"></span>
																</label>
																<div class="col-sm-9">
																	<select id="warehouse_country" name="warehouse_country"  class="form-control">
																		<option value="US" <%if warehouse_country = "US" then %>selected<%end if%>>United States</option>
																		<option value="CA" <%if warehouse_country = "CA" then %>selected<%end if%>>CANADA</option>
																	</select></div>
															</div>
															<div class="form-group">
																<label class="col-sm-3 control-label" for="warehouse_state">
																	State <span class="symbol required"></span>
																</label>
																<div class="col-sm-9">
																	<select id="warehouse_state" name="warehouse_state" class="form-control" size=1>
																	<%
																		SELECT CASE Session("ENABLEINT")
																		CASE "0"
																			Response.Write(GetStatesOptionTags(warehouse_state))
																		CASE "1"
																			Response.Write(GetStatesOptionTagsInt(warehouse_state, "0"))
																		CASE "2"
																			Response.Write(GetStatesOptionTagsInt(warehouse_state, "1"))
																		CASE "3"
																			Response.Write(GetStatesOptionTagsInt(warehouse_state, "0"))
																		CASE ELSE
																			Response.Write(GetStatesOptionTags(warehouse_state))
																		END SELECT
																	%>
																	</select>
																</div>
															</div>
															<div class="form-group">
																<label class="col-sm-3 control-label" for="warehouse_zip">
																	Zip / Postal Code <span class="symbol required"></span>
																</label>
																<div class="col-sm-9">
																	<input type="text"  id="warehouse_zip" name="warehouse_zip" class="form-control" value="<%=warehouse_zip%>">
																</div>
															</div>
															<h4><i class="fa fa-pencil-square teal"></i> Shipping & Handling Setting</h4>
															<!--
															<div class="form-group">
																<label class="col-sm-3 control-label" for="form-field-1">
																	Tax on Shipping<span class="symbol required"></span>
																</label>
																<div class="col-sm-9">
																	<input type="text"  id="form-field-1" class="form-control">
																</div>
															</div>
															-->
															<div class="form-group">
																<label class="col-sm-3 control-label" for="form-field-1">
																	Default Destination Type <span class="symbol required"></span>
																</label>
																<div class="col-sm-9">
																	<label class="radio-inline">
																		<input type="radio" value="1" name="assume_res" class="grey" <% if assume_res = "1" then%>checked<%end if%>>
																		Residential
																	</label>
																	<label class="radio-inline">
																		<input type="radio" value="0" name="assume_res" class="grey" <% if assume_res = "0" then%>checked<%end if%>>
																		Commercial
																	</label>
																</div>
															</div>
															
														</div>
														<div class="tab-pane" id="panel_tab3_example2">
															<div class="form-group">
																<label class="col-sm-3 control-label" for="form-field-1">
																	Enable <span class="symbol required"></span>
																</label>
																<div class="col-sm-9">
																	<div class="make-switch" data-on="primary" data-off="default">
																		<input type="checkbox" id="SH_display_flag" name="SH_display_flag" value="UPS" <% if InStr(SH_display_flag, "UPS")>0 then%> checked <% end if%>>
																	</div>
																</div>
															</div>
															<div class="form-group">
																<label class="col-sm-3 control-label" for="ups_xml_password">
																	Password <span class="symbol required"></span>
																</label>
																<div class="col-sm-9">
																	<input type="text"  id="ups_xml_password" name="ups_xml_password" class="form-control" value="<%=ups_xml_password%>">
																</div>
															</div>
															<div class="form-group">
																<label class="col-sm-3 control-label" for="ups_xml_key">
																	Access License Number <span class="symbol required"></span>
																</label>
																<div class="col-sm-9">
																	<input type="text"  id="ups_xml_key" name="ups_xml_key" class="form-control" value="<%=ups_xml_key%>">
																</div>
															</div>
															<div class="form-group">
																<label class="col-sm-3 control-label" for="ups_xml_userid">
																	User ID <span class="symbol required"></span>
																</label>
																<div class="col-sm-9">
																	<input type="text"  id="ups_xml_userid" name="ups_xml_userid" class="form-control" value="<%=ups_xml_userid%>">
																</div>
															</div>
															<div class="form-group">
																<label class="col-sm-3 control-label" for="form-field-1">
																	Allowed Methods <span class="symbol required"></span>
																</label>
																<div class="col-sm-9">
																	<div class="checkbox">
																		<label>
																			<input type="checkbox" name="DA1" value="1" <%if DA1="1" then%>checked<%end if%> class="grey">
																			Next Day Air
																		</label>
																	</div>
																	<div class="checkbox">
																		<label>
																			<input type="checkbox" name="DA2" value="1" <%if DA2="1" then%>checked<%end if%> class="grey">
																			2nd Day Air
																		</label>
																	</div>
																	<div class="checkbox">
																		<label>
																			<input type="checkbox" name="GND" value="1" <%if GND="1" then%>checked<%end if%> class="grey">
																			Ground 
																		</label>
																	</div>
																	<div class="checkbox">
																		<label>
																			<input type="checkbox" name="DS3" value="1" <%if DS3="1" then%>checked<%end if%> class="grey">
																			3Day Select
																		</label>
																	</div>
																	<div class="checkbox">
																		<label>
																			<input type="checkbox" name="DP1" value="1" <%if DP1="1" then%>checked<%end if%> class="grey">
																			Next Day Air Saver
																		</label>
																	</div>
																	<div class="checkbox">
																		<label>
																			<input type="checkbox" name="DM1" value="1" <%if DM1="1" then%>checked<%end if%> class="grey">
																			Next Day Air Early AM
																		</label>
																	</div>
																	<div class="checkbox">
																		<label>
																			<input type="checkbox" name="DM2" value="1" <%if DM2="1" then%>checked<%end if%> class="grey">
																			2nd Day Early AM
																		</label>
																	</div>
																	<div class="checkbox">
																		<label>
																			<input type="checkbox" name="X07" value="1" <%if X07="1" then%>checked<%end if%> class="grey">
																			Worldwide Express
																		</label>
																	</div>
																	<div class="checkbox">
																		<label>
																			<input type="checkbox" name="X08" value="1" <%if X08="1" then%>checked<%end if%> class="grey">
																			Worldwide Expedited
																		</label>
																	</div>
																	<div class="checkbox">
																		<label>
																			<input type="checkbox" name="X11" value="1" <%if X11="1" then%>checked<%end if%> class="grey">
																			Standard
																		</label>
																	</div>
																	<div class="checkbox">
																		<label>
																			<input type="checkbox" name="X54" value="1" <%if X54="1" then%>checked<%end if%> class="grey">
																			Worldwide Express Plus
																		</label>
																	</div>
																	<div class="checkbox">
																		<label>
																			<input type="checkbox" name="X65" value="1" <%if X65="1" then%>checked<%end if%> class="grey">
																			Express Saver
																		</label>
																	</div>
																	
																</div>
															</div>
															<div class="form-group">
																<label class="col-sm-3 control-label" for="sh_markup">
																	Markup Multiplier <span class="symbol required"></span>
																</label>
																<div class="col-sm-9">
																	<input type="text"  id="sh_markup" name="sh_markup" class="form-control" value="<%=sh_markup%>">
																</div>
															</div>
															<div class="form-group">
																<label class="col-sm-3 control-label" for="sh_handling">
																	Handling Fee<span class="symbol required"></span>
																</label>
																<div class="col-sm-9">
																	<input type="text"  id="sh_handling" name="sh_handling" class="form-control" value="<%=sh_handling%>">
																</div>
															</div>
														</div>
														<div class="tab-pane" id="panel_tab3_example3">
															<div class="form-group">
																<label class="col-sm-3 control-label" for="form-field-1">
																	Enable <span class="symbol required"></span>
																</label>
																<div class="col-sm-9">
																	<div class="make-switch" data-on="primary" data-off="default">
																		<input type="checkbox" id="SH_display_flag" name="SH_display_flag" value="FedEx" <% if InStr(SH_display_flag, "FedEx")>0 then%> checked <% end if%>>
																	</div>
																</div>
															</div>
															<div class="form-group">
																<label class="col-sm-3 control-label" for="fedex_account">
																	Account ID <span class="symbol required"></span>
																</label>
																<div class="col-sm-9">
																	<input type="text"  id="fedex_account" name="fedex_account" class="form-control" value="<%=fedex_account%>">
																</div>
															</div>
															<div class="form-group">
																<label class="col-sm-3 control-label" for="fedex_meter">
																	Meter Number <span class="symbol required"></span>
																</label>
																<div class="col-sm-9">
																	<input type="text"  id="fedex_meter" name="fedex_meter" class="form-control" value="<%=fedex_meter%>">
																</div>
															</div>
															<div class="form-group">
																<label class="col-sm-3 control-label" for="form-field-1">
																	Allowed Methods <span class="symbol required"></span>
																</label>
																<div class="col-sm-9">
																	<div class="checkbox">
																		<label>
																			<input type="checkbox" name="fedex_service_flag" value="01"  <%if InStr(fedex_service_flag, "01")>0 then%>checked<%end if%> class="grey">
																			Priority (International Priority)
																		</label>
																	</div>
																	<div class="checkbox">
																		<label>
																			<input type="checkbox" name="fedex_service_flag" value="03"  <%if InStr(fedex_service_flag, "03")>0 then%>checked<%end if%> class="grey">
																			2Day (International Economy)
																		</label>
																	</div>
																	<div class="checkbox">
																		<label>
																			<input type="checkbox" name="fedex_service_flag" value="05"  <%if InStr(fedex_service_flag, "05")>0 then%>checked<%end if%> class="grey">
																			Standard Overnight
																		</label>
																	</div>
																	<div class="checkbox">
																		<label>
																			<input type="checkbox" name="fedex_service_flag" value="06"  <%if InStr(fedex_service_flag, "06")>0 then%>checked<%end if%> class="grey">
																			First Overnight  (International First)
																		</label>
																	</div>
																	<div class="checkbox">
																		<label>
																			<input type="checkbox" name="fedex_service_flag" value="20"  <%if InStr(fedex_service_flag, "20")>0 then%>checked<%end if%> class="grey">
																			Express Saver
																		</label>
																	</div>
																	<div class="checkbox">
																		<label>
																			<input type="checkbox" name="fedex_service_flag" value="90"  <%if InStr(fedex_service_flag, "90")>0 then%>checked<%end if%> class="grey">
																			FedEx Home Delivery (Residential)
																		</label>
																	</div>
																	<div class="checkbox">
																		<label>
																			<input type="checkbox" name="fedex_service_flag" value="92"  <%if InStr(fedex_service_flag, "92")>0 then%>checked<%end if%> class="grey">
																			FedEx Ground (Commercial)
																		</label>
																	</div>
																</div>
															</div>
															<div class="form-group">
																<label class="col-sm-3 control-label" for="fedex_markup">
																	Markup Multiplier <span class="symbol required"></span>
																</label>
																<div class="col-sm-9">
																	<input type="text"  id="fedex_markup" name="fedex_markup" class="form-control" value="<%=fedex_markup%>">
																</div>
															</div>
															<div class="form-group">
																<label class="col-sm-3 control-label" for="fedex_handling">
																	Handling Fee<span class="symbol required"></span>
																</label>
																<div class="col-sm-9">
																	<input type="text"  id="fedex_handling" name="fedex_handling" class="form-control" value="<%=fedex_handling%>">
																</div>
															</div>
														</div>
														<div class="tab-pane" id="panel_tab3_example4">
															<div class="form-group">
																<label class="col-sm-3 control-label" for="form-field-1">
																	Enable <span class="symbol required"></span>
																</label>
																<div class="col-sm-9">
																	<div class="make-switch" data-on="primary" data-off="default">
																		<input type="checkbox" id="SH_display_flag" name="SH_display_flag" value="USPS" <% if InStr(SH_display_flag, "USPS")>0 then%> checked <% end if%>>
																	</div>
																</div>
															</div>
															<div class="form-group">
																<label class="col-sm-3 control-label" for="usps_userid">
																	User ID <span class="symbol required"></span>
																</label>
																<div class="col-sm-9">
																	<input type="text"  id="usps_userid" name="usps_userid" class="form-control" value="<%=usps_userid%>">
																</div>
															</div>
															<div class="form-group">
																<label class="col-sm-3 control-label" for="usps_password">
																	Password <span class="symbol required"></span>
																</label>
																<div class="col-sm-9">
																	<input type="text"  id="usps_password" name="usps_password" class="form-control" value="<%=usps_password%>">
																</div>
															</div>
															<div class="form-group">
																<label class="col-sm-3 control-label" for="form-field-1">
																	Allowed Methods <span class="symbol required"></span>
																</label>
																<div class="col-sm-9">
																	<div class="checkbox">
																		<label>
																			<input type="checkbox" name="usps_service_flag" value="92"  <%if InStr(usps_service_flag, "92")>0 then%>checked<%end if%> class="grey">
																			Parcel
																		</label>
																	</div>
																	<div class="checkbox">
																		<label>
																			<input type="checkbox" name="usps_service_flag" value="01"  <%if InStr(usps_service_flag, "01")>0 then%>checked<%end if%> class="grey">
																			Priority
																		</label>
																	</div>
																	<div class="checkbox">
																		<label>
																			<input type="checkbox" name="usps_service_flag" value="02"  <%if InStr(usps_service_flag, "02")>0 then%>checked<%end if%> class="grey">
																			Express
																		</label>
																	</div>
																	<div class="checkbox">
																		<label>
																			<input type="checkbox" name="usps_service_flag" value="04"  <%if InStr(usps_service_flag, "04")>0 then%>checked<%end if%> class="grey">
																			Global Express Mail (EMS)
																		</label>
																	</div>
																	<div class="checkbox">
																		<label>
																			<input type="checkbox" name="usps_service_flag" value="05"  <%if InStr(usps_service_flag, "05")>0 then%>checked<%end if%> class="grey">
																			Airmail Parcel Post
																		</label>
																	</div>
																	<div class="checkbox">
																		<label>
																			<input type="checkbox" name="usps_service_flag" value="06"  <%if InStr(usps_service_flag, "06")>0 then%>checked<%end if%> class="grey">
																			Economy (surface) Parcel Post
																		</label>
																	</div>
																</div>
															</div>
															<div class="form-group">
																<label class="col-sm-3 control-label" for="usps_markup">
																	Markup Multiplier <span class="symbol required"></span>
																</label>
																<div class="col-sm-9">
																	<input type="text"  id="usps_markup" name="usps_markup" class="form-control" value="<%=usps_markup%>">
																</div>
															</div>
															<div class="form-group">
																<label class="col-sm-3 control-label" for="usps_handling">
																	Handling Fee<span class="symbol required"></span>
																</label>
																<div class="col-sm-9">
																	<input type="text"  id="usps_handling" name="usps_handling" class="form-control" value="<%=usps_handling%>">
																</div>
															</div>
														</div>
														
														<div class="tab-pane" id="panel_tab3_example5">
															<p>
																Trust fund seitan letterpress, keytar raw denim keffiyeh etsy art party before they sold out master cleanse gluten-free squid scenester freegan cosby sweater. Fanny pack portland seitan DIY, art party locavore wolf cliche high life echo park Austin.
															</p>
															<p>
																<a href="#panel_tab3_example1" class="btn btn-purple show-tab">
																	Return to tab 1
																</a>
															</p>
														</div>
														
														<div class="tab-pane" id="panel_tab3_example6">
															<p>
																Trust fund seitan letterpress, keytar raw denim keffiyeh etsy art party before they sold out master cleanse gluten-free squid scenester freegan cosby sweater. Fanny pack portland seitan DIY, art party locavore wolf cliche high life echo park Austin.
															</p>
															<p>
																<a href="#panel_tab3_example1" class="btn btn-purple show-tab">
																	Return to tab 1
																</a>
															</p>
														</div>
													</div>
													<br>
													<div class="row">
														<div class="col-sm-1">
														</div>
														<div class="col-sm-8">
															<button class="btn btn-blue btn-sm" type="submit">
															<i class="fa fa-check-square"></i>
															Save
															</button>
														</div>
													</div>
													</form>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
						
						<div class="row">
							<div class="col-sm-12">
								<!-- start: INLINE TABS PANEL -->
								<div class="panel panel-dark-primary collapses">
									<div class="panel-heading">
										<h4 class="panel-title">Tax</h4>
										<div class="panel-tools" >
											<a data-original-title="Collapse" data-toggle="tooltip" data-placement="top" class="btn btn-transparent btn-sm panel-collapse" href="#"><i class="ti-minus collapse-off"></i><i class="ti-plus collapse-on"></i></a>
										</div>
									</div>
									<div class="panel-body partition-white">
										<form method="post" action="tp_store_information_tax_update.phtml" id="CompanyInfoForm" id="CompanyInfoForm">
										<div class="row">
											<div class="col-sm-12">
											
											
											<table class="table table-condensed table-hover" id="sample-table-3">
												<thead>
												<tr class="header_section">
													<td>&nbsp;</td>
													<th align="left" width=20%>State</th>
													<th align="left" width=40%>Tax Collection Method</th>
													<th align="left" width=10%>Freight</th>
													<th align="left" width=15%>Nexus City</th>
													<th align="left" width=15%>Nexus Zip</th>
												</tr>
												</thead>
												<tbody>
												<%
													sql = "SELECT * FROM A_STATE_LIST_US ORDER BY state_name"
													set rsState = dbconn.Execute(sql)
													
													do while not rsState.EOF
													
														'get values...
														nsql = "SELECT * FROM " & g_storeid & "_nexus_tax WHERE StateID='" & rsState("state") & "'"
														set rsNexus = dbconn.Execute(nsql)
														if not rsNexus.EOF then
															n_tax_method = rsNexus("CollectionMethod")
															n_freight_tax = rsNexus("TaxOnFreight")
															n_nexus_city = rsNexus("NexusCity")
															n_nexus_zip = rsNexus("NexusZip")
														else
															n_tax_method = "0"
															n_freight_tax = "0"
															n_nexus_city = ""
															n_nexus_zip = ""
														end if
														rsNexus.Close
												%>
												<tr class=alt>
													<td>&nbsp;</td>
													<td><%=rsState("state_name")%></td>
													<td>
														<select name="tax_method_<%=rsState("state")%>">
														<option value="0">Do not collect tax from customers in this state</option>
														<option value="1" style="color:red" <%if n_tax_method = "1" then%>selected<%end if%>>Use the sales tax rate of ship-to location</option>
														<option value="2" style="color:red" <%if n_tax_method = "2" then%>selected<%end if%>>Use the sales tax rate of billing location</option>
														<option value="3" style="color:red" <%if n_tax_method = "3" then%>selected<%end if%>>Use the sales tax rate of our nexus location</option>
														<option value="4" style="color:red" <%if n_tax_method = "4" then%>selected<%end if%>>Use the sales tax rate of our headquater location</option>
														<option value="6" style="color:red" <%if n_tax_method = "6" then%>selected<%end if%>>Use the use tax rate of ship-to location</option>
														<option value="7" style="color:red" <%if n_tax_method = "7" then%>selected<%end if%>>Use the use tax rate of billing location</option>
														</select>
													</td>
													<td><input type="checkbox" name="freight_tax_<%=rsState("state")%>" value="1" <%if n_freight_tax = "1" then%>checked<%end if%>></td>
													<td><input type="text" name="nexus_city_<%=rsState("state")%>" value="<%=n_nexus_city%>"></td>
													<td><input type="text" name="nexus_zip_<%=rsState("state")%>" value="<%=n_nexus_zip%>"></td>
												</tr>
												
												<%
														rsState.MoveNext
													loop
													rsState.Close
												%>
												</tbody>		
											</table>
											
											
											
											
											
											</div>
										</div>
										<div class="row">
											<div class="col-sm-1">
											</div>
											<div class="col-sm-8">
												<button class="btn btn-blue btn-sm" type="submit">
												<i class="fa fa-check-square"></i>
												Save
												</button>
											</div>
										</div>
										</form>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!--#INCLUDE FILE="include/footer.phtml"-->
	</div>
	<!--#INCLUDE FILE="include/js.phtml"-->
	<!-- start: JAVASCRIPTS REQUIRED FOR THIS PAGE ONLY -->
	<script src="vendor/bootstrap-datepicker/bootstrap-datepicker.min.js"></script>
	<script src="vendor/bootstrap-timepicker/bootstrap-timepicker.min.js"></script>
	<script src="vendor/jquery-validation/jquery.validate.min.js"></script>
	<!-- end: JAVASCRIPTS REQUIRED FOR THIS PAGE ONLY -->
	<script src="assets/js/main.js"></script>
	<!-- start: JavaScript Event Handlers for this page -->
	<script language="javascript">
	var FormValidator = function () {
	// function to initiate Validation Sample 1
		var runValidator1 = function () {
			var form1 = $('#form1');
			var errorHandler1 = $('#errorHandler1_1', form1);
			var errorHandler2 = $('#errorHandler2_1', form1);
			var successHandler1 = $('#successHandler_1', form1);
			
			$('#form1').validate({
				errorElement: "span", // contain the error msg in a span tag
				errorClass: 'help-block',
				errorPlacement: function (error, element) { // render error placement for each input type
					if (element.attr("type") == "radio" || element.attr("type") == "checkbox") { // for chosen elements, need to insert the error after the chosen container
						error.insertAfter($(element).closest('.form-group').children('div').children().last());
					} else if (element.attr("name") == "dd" || element.attr("name") == "mm" || element.attr("name") == "yyyy") {
						error.insertAfter($(element).closest('.form-group').children('div'));
					} else {
						error.insertAfter(element);
						// for other inputs, just perform default behavior
					}
				},
				ignore: "",
				
				//RULES
				rules: {
					company: {
						required: true
					},
					address: {
						required: true
					},
					city: {
						required: true
					},
					state: {
						required: true
					},
					zip: {
						required: true
					},
					phone: {
						required: true
					},
					email: {
						required: true,
						email: true
					}
					
				},
				
				//END OF RULES
				
				invalidHandler: function (event, validator) { //display error alert on form submit
					successHandler1.hide();
					errorHandler1.show();
				},
				highlight: function (element) {
					$(element).closest('.help-block').removeClass('valid');
					$(element).closest('.form-group').removeClass('has-success').addClass('has-error').find('.symbol').removeClass('ok').addClass('required');
				},
				unhighlight: function (element) { 
					$(element).closest('.form-group').removeClass('has-error');
				},
				success: function (label, element) {
					label.addClass('help-block valid');
					$(element).closest('.form-group').removeClass('has-error').addClass('has-success').find('.symbol').removeClass('required').addClass('ok');
				},
				submitHandler: function (form) {
					successHandler1.hide();
					errorHandler1.hide();
					errorHandler2.hide();
					$.ajax({
						type: "POST",
						url: "api/sp_store_information_update.phtml",
						data: $("#form1").serialize(),
						success: function() {
							successHandler1.show();
						},
						error: function() {
							errorHandler2.show();
						}
					});
					
				}
			});
		};
		
		var runValidator2 = function () {
			var form1 = $('#form2');
			var errorHandler1 = $('#errorHandler1_2', form2);
			var errorHandler2 = $('#errorHandler2_2', form2);
			var successHandler1 = $('#successHandler_2', form2);
			
			$('#form2').validate({
				errorElement: "span", // contain the error msg in a span tag
				errorClass: 'help-block',
				errorPlacement: function (error, element) { // render error placement for each input type
					if (element.attr("type") == "radio" || element.attr("type") == "checkbox") { // for chosen elements, need to insert the error after the chosen container
						error.insertAfter($(element).closest('.form-group').children('div').children().last());
					} else if (element.attr("name") == "dd" || element.attr("name") == "mm" || element.attr("name") == "yyyy") {
						error.insertAfter($(element).closest('.form-group').children('div'));
					} else {
						error.insertAfter(element);
						// for other inputs, just perform default behavior
					}
				},
				ignore: "",
				
				//RULES
				rules: {
					company: {
						required: true
					},
					address: {
						required: true
					},
					city: {
						required: true
					},
					state: {
						required: true
					},
					zip: {
						required: true
					},
					phone: {
						required: true
					},
					email: {
						required: true,
						email: true
					}
					
				},
				
				//END OF RULES
				
				invalidHandler: function (event, validator) { //display error alert on form submit
					successHandler1.hide();
					errorHandler1.show();
				},
				highlight: function (element) {
					$(element).closest('.help-block').removeClass('valid');
					$(element).closest('.form-group').removeClass('has-success').addClass('has-error').find('.symbol').removeClass('ok').addClass('required');
				},
				unhighlight: function (element) { 
					$(element).closest('.form-group').removeClass('has-error');
				},
				success: function (label, element) {
					label.addClass('help-block valid');
					$(element).closest('.form-group').removeClass('has-error').addClass('has-success').find('.symbol').removeClass('required').addClass('ok');
				},
				submitHandler: function (form) {
					successHandler1.hide();
					errorHandler1.hide();
					errorHandler2.hide();
					$.ajax({
						type: "POST",
						url: "api/sp_store_information_update.phtml",
						data: $("#form2").serialize(),
						success: function() {
							successHandler1.show();
						},
						error: function() {
							errorHandler2.show();
						}
					});
					
				}
			});
		};
		
		return {
			//main function to initiate template pages
			init: function () {
				runValidator1();
				runValidator2();
			}
		};
	}();
	
	</script>
	<script>
		jQuery(document).ready(function() {
			Main.init();
			FormValidator.init();
		});
	</script>
	<!-- end: JavaScript Event Handlers for this page -->
	
</body>
</html>
