<div class="container">
<div class="row">
	<!--Middle Part Start-->
	<div id="content" class="col-sm-12">
		<h1 class="title">Checkout</h1>
		<div class="row">
			<div class="col-sm-4">
				<div class="panel panel-default">
					<div class="panel-heading">
						<h4 class="panel-title"><i class="fa fa-book"></i> Billing Information</h4>
					</div>
					<div class="panel-body">
						<div class="form-group required">
							<select class="form-control" id="billing_address_id" name="billing_address_id">
							<%
								sql = "SELECT * FROM " & g_storeid & "_shopper WHERE shopper_id = '" & Session("shopper_id") & "'"
								set rsShopper = dbconn.Execute(sql)
								if not rsShopper.EOF then
									shopper_billing_firstname = rsShopper("billing_firstname")
									shopper_billing_lastname = rsShopper("billing_lastname")
									shopper_billing_address = rsShopper("Address")
									shopper_billing_city = rsShopper("City")
									shopper_billing_state = rsShopper("State")
									shopper_billing_zip = rsShopper("ZipCode")
									shopper_billing_country = rsShopper("Country")
									shopper_billing_phone = rsShopper("Phone")
							%>
							<option value="0"><%=shopper_billing_firstname%>&nbsp;<%=shopper_billing_lastname%>&nbsp;<%=shopper_billing_address%>&nbsp;<%=shopper_billing_city%>,&nbsp;<%=shopper_billing_state%>&nbsp;<%=shopper_billing_zip%>&nbsp;<%=shopper_billing_country%></option>
							<%
								end if
							%>
							<%
								sql = "SELECT * FROM " & g_storeid & "_shopper_billing_address WHERE billing_shopper_id = '" & Session("shopper_id") & "'"
								set rs = dbconn.Execute(sql)
								do while not rs.EOF
									alt_address_id = rs("billing_address_id")
									alt_shopper_id = rs("billing_shopper_id")
									alt_address_name = rs("billing_address_name")
									alt_firstname = rs("billing_firstname")
									alt_lastname = rs("billing_lastname")
									alt_address = rs("billing_address")
									alt_city = rs("billing_city")
									alt_state = rs("billing_state")
									alt_zip = rs("billing_zip")
									alt_country= rs("billing_country")
									alt_phone = rs("billing_phone")
									alt_set_default = rs("billing_set_default")
							%>
							<option value="<%=alt_address_id%>" <% if alt_set_default = 1 then %>selected<%end if%>><%=alt_firstname%>&nbsp;<%=alt_lastname%>&nbsp;<%=alt_lastname%>&nbsp;<%=alt_address%>&nbsp;<%=alt_city%>,&nbsp;<%=alt_state%>&nbsp;<%=alt_zip%>&nbsp;<%=alt_country%></option>
							<%
									rs.MoveNext
								loop
								rs.Close
								set rs = nothing
							%>
							<option value="new">New Address</option>
							</select>
						</div>
						<fieldset id="billing_address" class="required display-hide">
							<div class="form-group">
							<label for="input-payment-company" class="control-label">Company</label>
							<input type="text" class="form-control" id="input-payment-company" placeholder="Company" value="" name="company">
							</div>
							<div class="form-group required">
							<label for="input-payment-address-1" class="control-label">Address 1</label>
							<input type="text" class="form-control" id="input-payment-address-1" placeholder="Address 1" value="" name="address_1">
							</div>
							<div class="form-group">
							<label for="input-payment-address-2" class="control-label">Address 2</label>
							<input type="text" class="form-control" id="input-payment-address-2" placeholder="Address 2" value="" name="address_2">
							</div>
							<div class="form-group required">
							<label for="input-payment-city" class="control-label">City</label>
							<input type="text" class="form-control" id="input-payment-city" placeholder="City" value="" name="city">
							</div>
							<div class="form-group required">
							<label for="input-payment-postcode" class="control-label">Post Code</label>
							<input type="text" class="form-control" id="input-payment-postcode" placeholder="Post Code" value="" name="postcode">
							</div>
							<div class="form-group required">
                            <label for="input-payment-country" class="control-label">Country</label>
                            <select class="form-control" id="input-payment-country" name="country_id">
							</select>
							</div>
							<div class="form-group required">
                            <label for="input-payment-zone" class="control-label">Region / State</label>
                            <select class="form-control" id="input-payment-zone" name="zone_id">
							</select>
							</div>
							
							<div class="checkbox">
								<label>
								<input type="checkbox" checked="checked" value="1" name="shipping_address">
								My delivery and billing addresses are the same.</label>
							</div>
						</fieldset>
					</div>
				</div>
				<div class="panel panel-default">
					<div class="panel-heading">
						<h4 class="panel-title"><i class="fa fa-book"></i> Shipping Information</h4>
					</div>
					<div class="panel-body">
						<div class="form-group required">
							<select class="form-control" id="shipping_address_id" name="shipping_address_id">
							<%
								sql = "SELECT * FROM " & g_storeid & "_shopper WHERE shopper_id = '" & Session("shopper_id") & "'"
								set rsShopper = dbconn.Execute(sql)
								if not rsShopper.EOF then
									
									shopper_shipping_firstname = rsShopper("shipping_FirstName")
									shopper_shipping_lastname = rsShopper("shipping_LastName")
									shopper_shipping_address = rsShopper("shipping_Address")
									shopper_shipping_city = rsShopper("shipping_City")
									shopper_shipping_state = rsShopper("shipping_State")
									shopper_shipping_zip = rsShopper("shipping_ZipCode")
									shopper_shipping_country = rsShopper("shipping_Country")
									shopper_shipping_phone = rsShopper("shipping_Phone")
									shopper_shipping_company = rsShopper("shipping_company")
		
							%>
							<option value="0"><%=shopper_shipping_firstname%>&nbsp;<%=shopper_shipping_lastname%>&nbsp;<%=shopper_shipping_address%>&nbsp;<%=shopper_shipping_city%>,&nbsp;<%=shopper_shippingstate%>&nbsp;<%=shopper_shipping_zip%>&nbsp;<%=shopper_shipping_country%></option>
							<%
								end if
							%>
							<%
								sql = "SELECT * FROM " & g_storeid & "_shopper_shipping_address WHERE shopper_id = '" & Session("shopper_id") & "'"
								set rs = dbconn.Execute(sql)
								do while not rs.EOF
									alt_address_id = rs("address_id")
									alt_shopper_id = rs("shopper_id")
									alt_address_name = rs("address_name")
									alt_firstname = rs("firstname")
									alt_lastname = rs("lastname")
									alt_address = rs("address")
									alt_city = rs("city")
									alt_state = rs("state")
									alt_zip = rs("zip")
									alt_country= rs("country")
									alt_phone = rs("phone")
									alt_set_default = rs("set_default")
									alt_company = rs("company")
									alt_address_type = rs("address_type")
				
							%>
							<option value="<%=alt_address_id%>" <% if alt_set_default = 1 then %>selected<%end if%>><%=alt_firstname%>&nbsp;<%=alt_lastname%>&nbsp;<%=alt_lastname%>&nbsp;<%=alt_address%>&nbsp;<%=alt_city%>,&nbsp;<%=alt_state%>&nbsp;<%=alt_zip%>&nbsp;<%=alt_country%></option>
							<%
									rs.MoveNext
								loop
								rs.Close
								set rs = nothing
							%>
							<option value="new">New Address</option>
							</select>
						</div>
						<fieldset id="shipping_address" class="required display-hide">
							<div class="form-group">
							<label for="input-payment-company" class="control-label">Company</label>
							<input type="text" class="form-control" id="input-payment-company" placeholder="Company" value="" name="company">
							</div>
							<div class="form-group required">
							<label for="input-payment-address-1" class="control-label">Address 1</label>
							<input type="text" class="form-control" id="input-payment-address-1" placeholder="Address 1" value="" name="address_1">
							</div>
							<div class="form-group">
							<label for="input-payment-address-2" class="control-label">Address 2</label>
							<input type="text" class="form-control" id="input-payment-address-2" placeholder="Address 2" value="" name="address_2">
							</div>
							<div class="form-group required">
							<label for="input-payment-city" class="control-label">City</label>
							<input type="text" class="form-control" id="input-payment-city" placeholder="City" value="" name="city">
							</div>
							<div class="form-group required">
							<label for="input-payment-postcode" class="control-label">Post Code</label>
							<input type="text" class="form-control" id="input-payment-postcode" placeholder="Post Code" value="" name="postcode">
							</div>
							<div class="form-group required">
                            <label for="input-payment-country" class="control-label">Country</label>
                            <select class="form-control" id="input-payment-country" name="country_id">
							</select>
							</div>
							<div class="form-group required">
                            <label for="input-payment-zone" class="control-label">Region / State</label>
                            <select class="form-control" id="input-payment-zone" name="zone_id">
							</select>
							</div>
							
						</fieldset>
					</div>
				</div>
			</div>
			<div class="col-sm-8">
				<div class="row">
					<div class="col-sm-6">
						<div class="panel panel-default">
							<div class="panel-heading">
								<h4 class="panel-title"><i class="fa fa-truck"></i> Shipping Method</h4>
							</div>
							<div class="panel-body">
								<p>
									Please select the preferred shipping method to use on this order.
								</p>
								<div class="radio">
									<label>
									<input type="radio" checked="checked" name="Free Shipping">
									Free Shipping - $0.00</label>
								</div>
								<div class="radio">
									<label>
									<input type="radio" name="Flat Shipping Rate">
									Flat Shipping Rate - $8.00</label>
								</div>
								<div class="radio">
									<label>
									<input type="radio" name="Per Item Shipping Rate">
									Per Item Shipping Rate - $150.00</label>
								</div>
							</div>
						</div>
					</div>
					<div class="col-sm-6">
						<div class="panel panel-default">
							<div class="panel-heading">
								<h4 class="panel-title"><i class="fa fa-credit-card"></i> Payment Method</h4>
							</div>
							<div class="panel-body">
								<p>
									Please select the preferred payment method to use on this order.
								</p>
								<div class="radio">
									<label>
									<input type="radio" checked="checked" name="Cash On Delivery">
									Cash On Delivery</label>
								</div>
								<div class="radio">
									<label>
									<input type="radio" name="Bank Transfer">
									Bank Transfer</label>
								</div>
								<div class="radio">
									<label>
									<input type="radio" name="Paypal">
									Paypal</label>
								</div>
							</div>
						</div>
					</div>
					<div class="col-sm-12">
						<div class="panel panel-default">
							<div class="panel-heading">
								<h4 class="panel-title"><i class="fa fa-shopping-cart"></i> Shopping cart</h4>
							</div>
							<div class="panel-body">
								<div class="table-responsive">
									<table class="table table-bordered">
									<thead>
									<tr>
										<td class="text-center">
											Image
										</td>
										<td class="text-left">
											Product Name
										</td>
										<td class="text-left">
											Quantity
										</td>
										<td class="text-right">
											Unit Price
										</td>
										<td class="text-right">
											Total
										</td>
									</tr>
									</thead>
									<tbody>
									<!--#INCLUDE FILE="../../../core/checkout/include_cart_loop_start.phtml"-->
									<tr>
										<td class="text-center">
											<a href="product.html"><img class="img-thumbnail" src="image/product/sony_vaio_1-50x50.jpg"></a>
										</td>
										<td class="text-left">
											<%=g_cartProductName%>
										</td>
										<td class="text-right">
											<%=g_cartOrderQuantity%>
										</td>
										<td class="text-right">
											$<%=g_cartProductUnitPrice%>
										</td>
										<td class="text-right">
											$<%=g_cartProductUnitTotal%>
										</td>
									</tr>
									<!--#INCLUDE FILE="../../../core/checkout/include_cart_loop_end.phtml"-->
									</tbody>
									<tfoot>
									<tr>
										<td class="text-right" colspan="4">
											<strong>Sub-Total:</strong>
										</td>
										<td class="text-right">
											$750.00
										</td>
									</tr>
									<tr>
										<td class="text-right" colspan="4">
											<strong>Flat Shipping Rate:</strong>
										</td>
										<td class="text-right">
											$5.00
										</td>
									</tr>
									<tr>
										<td class="text-right" colspan="4">
											<strong>Eco Tax (-2.00):</strong>
										</td>
										<td class="text-right">
											$4.00
										</td>
									</tr>
									<tr>
										<td class="text-right" colspan="4">
											<strong>VAT (20%):</strong>
										</td>
										<td class="text-right">
											$151.00
										</td>
									</tr>
									<tr>
										<td class="text-right" colspan="4">
											<strong>Total:</strong>
										</td>
										<td class="text-right">
											$910.00
										</td>
									</tr>
									</tfoot>
									</table>
								</div>
							</div>
						</div>
					</div>
					<div class="col-sm-12">
						<div class="panel panel-default">
							<div class="panel-heading">
								<h4 class="panel-title"><i class="fa fa-pencil"></i> Add Comments About Your Order</h4>
							</div>
							<div class="panel-body">
								<textarea rows="4" class="form-control" id="confirm_comment" name="comments"></textarea>
								<br>
								<!--
								<label class="control-label" for="confirm_agree">
								<input type="checkbox" checked="checked" value="1" required="" class="validate required" id="confirm_agree" name="confirm agree">
								<span>I have read and agree to the <a class="agree" href="#"><b>Terms &amp; Conditions</b></a></span></label>
								-->
								<div class="buttons">
									<div class="pull-right">
										<input type="button" class="btn btn-primary" id="button-confirm" value="Place Order">
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!--Middle Part End -->
</div>
</div>