<!--Footer Start-->
<footer id="footer">
	<div class="fpart-first">
	<%
		g_static_block_code = "TPL_MARKETSHOP1_FOOTER_FIRST"
	%>
	<!--#INCLUDE FILE="../../../core/cms/include_show_static_block.phtml"-->
	</div>
	<div class="fpart-second">
	<%
		g_static_block_code = "TPL_MARKETSHOP1_FOOTER_SECOND"
	%>
	<!--#INCLUDE FILE="../../../core/cms/include_show_static_block.phtml"--> 
	</div>
	<div id="back-top"><a data-toggle="tooltip" title="Back to Top" href="javascript:void(0)" class="backtotop"><i class="fa fa-chevron-up"></i></a></div>
</footer>
<!--Footer End-->
  