<%
	config_general_default_meta_tags = GetSettingValue("config_general_default_meta_tags", "")
%>
<title><%=g_page_title%></title>
<%=config_general_default_meta_tags%>
<!-- CSS Part Start-->
<link rel="stylesheet" type="text/css" href="<%=skin_base_url%>theme/<%=THEME_TEMPLATE%>/js/bootstrap/css/bootstrap.min.css" />
<link rel="stylesheet" type="text/css" href="<%=skin_base_url%>theme/<%=THEME_TEMPLATE%>/css/font-awesome/css/font-awesome.min.css" />
<link rel="stylesheet" type="text/css" href="<%=skin_base_url%>theme/<%=THEME_TEMPLATE%>/css/stylesheet.css" />
<link rel="stylesheet" type="text/css" href="<%=skin_base_url%>theme/<%=THEME_TEMPLATE%>/css/owl.carousel.css" />
<link rel="stylesheet" type="text/css" href="<%=skin_base_url%>theme/<%=THEME_TEMPLATE%>/css/owl.transitions.css" />
<% if g_route_page_id = "product" then %>
<link rel="stylesheet" type="text/css" href="<%=skin_base_url%>theme/<%=THEME_TEMPLATE%>/js/swipebox/src/css/swipebox.min.css">
<% end if %>
<link rel="stylesheet" type="text/css" href="<%=skin_base_url%>theme/<%=THEME_TEMPLATE%>/css/responsive.css" />
<link rel="stylesheet" type="text/css" href="<%=skin_base_url%>theme/<%=THEME_TEMPLATE%>/css/custom.css" />
<link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Open+Sans' type='text/css'>
<style>
label.error {
    color: red;
    font-style: italic;
}
</style>
<!-- CSS Part End-->