<%
	header_logo_image = GetSettingValue("header_logo_image", "logo.png")
	global_email_address = GetSettingValue("global_email_address", "support@mydomain.com")
%>
<div id="header">
	<!-- Top Bar Start-->
	<nav id="top" class="htop">
	<div class="container">
		<div class="row">
			<span class="drop-icon visible-sm visible-xs"><i class="fa fa-align-justify"></i></span>
			<div class="pull-left flip left-top">
				<div class="links">
					<ul>
						<li class="email"><a href="mailto:<%=global_email_address%>"><i class="fa fa-envelope"></i><%=global_email_address%></a></li>
						<!--
						<li class="wrap_custom_block hidden-sm hidden-xs"><a><%=a("Become Prime Member")%><b></b></a>
						<div class="dropdown-menu custom_block">
							<ul>
								<li>
								<table>
								<tbody>
								<tr>
									<td>
										<img alt="" src="image/banner/cms-block.jpg">
									</td>
									<td>
										<img alt="" src="image/banner/responsive.jpg">
									</td>
								</tr>
								<tr>
									<td>
										<h4>Membership Only</h4>
									</td>
									<td>
										<h4>Membership + Product</h4>
									</td>
								</tr>
								<tr>
									<td>
										1 year Prime Membership
									</td>
									<td>
										1 year Prime Membership and Product up to 50% discount
									</td>
								</tr>
								<tr>
									<td>
										<strong><a class="btn btn-default btn-sm" href="#">Read More</a></strong>
									</td>
									<td>
										<strong><a class="btn btn-default btn-sm" href="#">Read More</a></strong>
									</td>
								</tr>
								</tbody>
								</table>
								</li>
							</ul>
						</div>
						-->
						</li>
						<li><a href="<%=g_secure_url%>checkout.phtml"><%=a("Checkout")%></a></li>
					</ul>
				</div>
				<%
					sql = "SELECT COUNT(view_id) FROM " & g_storeid & "_store_view"
					set rs = dbconn.Execute(sql)
					if not rs.EOF then
						view_count = rs(0)
					end if
					rs.Close
					set rs = nothing
				%>
				<%
					if view_count > 1 then 
				%>
				<div id="language" class="btn-group">
					<%
						sql = "SELECT * FROM " & g_storeid & "_store_view WHERE view_id = " & Session("CURRENT_VIEW_ID") 
						set rs = dbconn.Execute(sql)
						if not rs.EOF then
							view_id = rs("view_id")
							view_code = rs("view_code")
							view_name = rs("view_name")
							view_status = rs("view_status")
					%>
					<button class="btn-link dropdown-toggle" data-toggle="dropdown"><span><img src="/image/flags/<%=view_code%>.png" alt="<%=view_name%>" title="<%=view_name%>"><%=view_name%> <i class="fa fa-caret-down"></i></span></button>
					<%
						end if
						rs.close
						set rs = nothing
					%>
					<ul class="dropdown-menu">
						<%
							sql = "SELECT * FROM " & g_storeid & "_store_view WHERE view_id <> " & Session("CURRENT_VIEW_ID") & " ORDER BY view_sort_order"
							set rs = dbconn.Execute(sql)
							do while not rs.EOF
								view_id = rs("view_id")
								view_code = rs("view_code")
								view_name = rs("view_name")
								view_status = rs("view_status")
						%>
						<li>
						<button class="btn btn-link btn-block language-select" type="button" name="<%=view_code%>" onclick="window.location.href='?storeviewid=<%=view_id%>';"><img src="image/flags/<%=view_code%>.png" alt="<%=view_name%>" title="<%=view_name%>" /> <%=view_name%></button>
						</li>
						<%
								rs.MoveNext
							loop
							rs.close
							set rs = nothing
						%>
					</ul>
				</div>
				<%
					end if
				%>
			</div>
			<div id="top-links" class="nav pull-right flip">
				<ul>
					<% if Session("shopper_id") = "" OR Session("shopper_id") = "GUEST" then %>
					<li><a href="<%=g_secure_url%>login.phtml?sessionID=<%=Session("SESSIONKEY")%>"><%=a("Login")%></a></li>
					<li><a href="<%=g_secure_url%>register.phtml"><%=a("Register")%></a></li>
					<% else %>
					<li><a href="<%=g_secure_url%>tp_login.phtml?sessionID=<%=Session("SESSIONKEY")%>&op=logout"><%=a("Log Out")%></a></li>
					<li><a href="<%=g_secure_url%>account_profile.phtml?sessionID=<%=Session("SESSIONKEY")%>"><%=a("My Account")%></a></li>
					<% end if %>
					
				</ul>
			</div>
		</div>
	</div>
	</nav>
	<!-- Top Bar End-->
	<!-- Header Start-->
	<header class="header-row">
	<div class="container">
		<div class="table-container">
			<!-- Logo Start -->
			<div class="col-table-cell col-lg-6 col-md-6 col-sm-12 col-xs-12 inner">
				<div id="logo">
					<a href="<%=g_store_url%>"><img class="img-responsive" src="/media/logo/<%=header_logo_image%>" title="MarketShop" alt="MarketShop"/></a>
				</div>
			</div>
			<!-- Logo End -->
			<!-- Mini Cart Start-->
			<div class="col-table-cell col-lg-3 col-md-3 col-sm-6 col-xs-12">
				<div id="cart">
					<button type="button" data-toggle="dropdown" data-loading-text="Loading..." class="heading dropdown-toggle">
					<span class="cart-icon pull-left flip"></span>
					<span id="cart-total"><%=GetTotalItemsInCart()%>&nbsp;<%=a("item(s)")%> - $<%=FormatNumber(GetTotalAmountInCart(),2)%></span></button>
					<% if GetTotalItemsInCart() > 0 then %>
					<ul class="dropdown-menu">
						<li>
						<table class="table">
						<tbody>
						<!--#INCLUDE FILE="../../../core/checkout/include_cart_loop_start.phtml"-->
						<tr>
							<td class="text-center">
								<a href="product.html"><img class="img-thumbnail" title="Xitefun Causal Wear Fancy Shoes" alt="Xitefun Causal Wear Fancy Shoes" src="image/product/sony_vaio_1-50x50.jpg"></a>
							</td>
							<td class="text-left">
								<%=g_cartProductName%>
							</td>
							<td class="text-right" nowrap>
								x <%=g_cartOrderQuantity%>
							</td>
							<td class="text-right">
								$<%=g_cartProductUnitPrice%>
							</td>
							<td class="text-center">
								<button class="btn btn-danger btn-xs remove" title="Remove" onclick="setLocation('<%=g_basket_item_delete_link%>');" type="button"><i class="fa fa-times"></i></button>
							</td>
						</tr>
						<!--#INCLUDE FILE="../../../core/checkout/include_cart_loop_end.phtml"-->
						</tbody>
						</table>
						</li>
						<li>
						<div>
							<p class="checkout">
								<a href="cart.phtml" class="btn btn-primary"><i class="fa fa-shopping-cart"></i> View Cart</a>&nbsp;&nbsp;&nbsp;<a href="checkout.phtml" class="btn btn-primary"><i class="fa fa-share"></i> Checkout</a>
							</p>
						</div>
						</li>
					</ul>
					<% end if %>
				</div>
			</div>
			<!-- Mini Cart End-->
			<!-- Search Start-->
			<div class="col-table-cell col-lg-3 col-md-3 col-sm-6 col-xs-12 inner">
				<div id="search" class="input-group">
					<form id="search_mini_form" action="<%=g_store_url%>search.phtml" method="get">
					<input id="filter_name" type="text" name="sp" value="" placeholder="<%=a("Search")%>" class="form-control input-lg"/>
					<button type="button" class="button-search"><i class="fa fa-search"></i></button>
					</form>
				</div>
			</div>
			<!-- Search End-->
		</div>
	</div>
	</header>
	<!-- Header End-->
	<!-- Main Menu Start-->
	<%
		mm = "<!--0-->"
		'sql = "SELECT dept_id, LEN(dept_id) as a, dept_name, parent_dept, dept_row, url_key FROM hubutu_dept WHERE include_topnav = 1 AND is_hidden = 0 ORDER BY a, dept_row"
		sql = "SELECT dept_id, LEN(dept_id) as a, dept_name, parent_dept, dept_row, url_Key, ISNULL(CONVERT(nvarchar(100),b.field_value),'') as dept_name_2"
		sql = sql & " FROM " & g_storeid & "_dept as a "
		sql = sql & " LEFT OUTER JOIN " & g_storeid & "_store_type_data_varchar b"
		sql = sql & " ON a.dept_id = b.entity_id"
		sql = sql & " AND b.type_id =1 AND b.field_id = 1 AND view_id = " &  Session("CURRENT_VIEW_ID")
		sql = sql & " WHERE a.include_topnav = 1 AND a.is_hidden = 0 "
		sql = sql & " ORDER BY a, dept_row"
		
		jjj = 1
		Set rsM = dbconn.Execute(sql)
		do while not rsM.EOF
			m_dept_id = rsM("dept_id")
			m_dept_name  = rsM("dept_name")
			dept_name_2  = rsM("dept_name_2")
			m_url_key  = rsM("url_key")
			if Len(m_url_key) > 0 then
				m_dept_link = g_store_url & m_url_key & ".html"
			else
				m_dept_link = g_store_url & "dept.phtml?dept_id=" & m_dept_id
			end if
			
			if Len(dept_name_2)> 0 then
				'm_dept_name = TranslateX(m_dept_name, 1, m_dept_id, 1)
				m_dept_name = dept_name_2
			end if
			
			SELECT CASE rsM("a") 
			CASE 2
			m = "<li class=""dropdown information-link""><a href=""" & m_dept_link & """>" & m_dept_name & "</a><div class=""dropdown-menu""><ul><!--" & rsM("dept_id") & "--></ul></div></li><!--" & jjj & "-->"
			mm = mm & m
			jjj = jjj + 1
			CASE 6
			m = "<li><a href=""" & m_dept_link & """>" &  m_dept_name & "</a><div class=""dropdown-menu""><ul><!--" & rsM("dept_id") & "--></ul></div></li>"
			mm = Replace(mm, "<!--" & rsM("parent_dept") & "-->", m & "<!--" & rsM("parent_dept") & "-->")
			CASE 10
			m = "<li><a href=""" & m_dept_link & """>" & m_dept_name & "</a></li>"
			mm = Replace(mm, "<!--" & rsM("parent_dept") & "-->", m & "<!--" & rsM("parent_dept") & "-->")
			END SELECT
			rsM.MoveNext
		loop
		rsM.Close
		set rsM = nothing
		
		sql = "SELECT dept_id FROM " & g_storeid & "_dept WHERE include_topnav = 1 AND is_hidden = 0 ORDER BY dept_row"
		Set rsM = dbconn.Execute(sql)
		do while not rsM.EOF
			mm = Replace(mm, "<div class=""dropdown-menu""><ul><!--" & rsM("dept_id") & "--></ul></div>", "")
			mm = Replace(mm, "<!--" & rsM("dept_id") & "-->", "")
			rsM.MoveNext
		loop
		rsM.Close
		set rsM = nothing
		
		'------STATIC BLOCK -----
		TPL_MARKETSHOP1_MENU_BLOCK_1_ID = GetSettingValue("TPL_MARKETSHOP1_MENU_BLOCK_1_ID", "")
		TPL_MARKETSHOP1_MENU_BLOCK_1_TITLE = GetSettingValue("TPL_MARKETSHOP1_MENU_BLOCK_1_TITLE", "")
		TPL_MARKETSHOP1_MENU_BLOCK_1_PLACEMENT = GetSettingValue("TPL_MARKETSHOP1_MENU_BLOCK_1_PLACEMENT", "0")
		TPL_MARKETSHOP1_MENU_BLOCK_1_CLASS = GetSettingValue("TPL_MARKETSHOP1_MENU_BLOCK_1_CLASS", "")
		
		TPL_MARKETSHOP1_MENU_BLOCK_2_ID = GetSettingValue("TPL_MARKETSHOP1_MENU_BLOCK_2_ID", "")
		TPL_MARKETSHOP1_MENU_BLOCK_2_TITLE = GetSettingValue("TPL_MARKETSHOP1_MENU_BLOCK_2_TITLE", "")
		TPL_MARKETSHOP1_MENU_BLOCK_2_PLACEMENT = GetSettingValue("TPL_MARKETSHOP1_MENU_BLOCK_2_PLACEMENT", "0")
		TPL_MARKETSHOP1_MENU_BLOCK_2_CLASS = GetSettingValue("TPL_MARKETSHOP1_MENU_BLOCK_2_CLASS", "")
		
		TPL_MARKETSHOP1_MENU_BLOCK_3_ID = GetSettingValue("TPL_MARKETSHOP1_MENU_BLOCK_3_ID", "")
		TPL_MARKETSHOP1_MENU_BLOCK_3_TITLE = GetSettingValue("TPL_MARKETSHOP1_MENU_BLOCK_3_TITLE", "")
		TPL_MARKETSHOP1_MENU_BLOCK_3_PLACEMENT = GetSettingValue("TPL_MARKETSHOP1_MENU_BLOCK_3_PLACEMENT", "0")
		TPL_MARKETSHOP1_MENU_BLOCK_3_CLASS = GetSettingValue("TPL_MARKETSHOP1_MENU_BLOCK_3_CLASS", "")
		
		
		if Len(TPL_MARKETSHOP1_MENU_BLOCK_1_ID) > 0 AND Len(TPL_MARKETSHOP1_MENU_BLOCK_1_TITLE) > 0 then
			block1 = ""
			sql = "SELECT block_content FROM " & g_storeid & "_static_block WHERE block_identifier='" & TPL_MARKETSHOP1_MENU_BLOCK_1_ID & "' AND block_status=1"
			set rsStaticBlock = dbconn.Execute(sql)
			if not rsStaticBlock.EOF then
				block1 = "<li class=""" & TPL_MARKETSHOP1_MENU_BLOCK_1_CLASS & " dropdown"" class=""position:static;""><a href=""#"">" & TPL_MARKETSHOP1_MENU_BLOCK_1_TITLE & "</a>"
				block1 = block1 & rsStaticBlock("block_content")
				block1 = block1 & "</li>"
			end if
			rsStaticBlock.close
			set rsStaticBlock = nothing
			mm = Replace(mm, "<!--" & TPL_MARKETSHOP1_MENU_BLOCK_1_PLACEMENT & "-->" , block1 & "<!--" & TPL_MARKETSHOP1_MENU_BLOCK_1_PLACEMENT & "-->")
		end if
		
		if Len(TPL_MARKETSHOP1_MENU_BLOCK_2_ID) > 0 AND Len(TPL_MARKETSHOP1_MENU_BLOCK_2_TITLE) > 0 then
			block1 = ""
			sql = "SELECT block_content FROM " & g_storeid & "_static_block WHERE block_identifier='" & TPL_MARKETSHOP1_MENU_BLOCK_2_ID & "' AND block_status=1"
			set rsStaticBlock = dbconn.Execute(sql)
			if not rsStaticBlock.EOF then
				block1 = "<li class=""" & TPL_MARKETSHOP1_MENU_BLOCK_2_CLASS & " dropdown"" class=""position:static;""><a href=""#"">" & TPL_MARKETSHOP1_MENU_BLOCK_2_TITLE & "</a>"
				block1 = block1 & rsStaticBlock("block_content")
				block1 = block1 & "</li>"
			end if
			rsStaticBlock.close
			set rsStaticBlock = nothing
			mm = Replace(mm, "<!--" & TPL_MARKETSHOP1_MENU_BLOCK_2_PLACEMENT & "-->" , block1 & "<!--" & TPL_MARKETSHOP1_MENU_BLOCK_2_PLACEMENT & "-->")
		end if
		
		if Len(TPL_MARKETSHOP1_MENU_BLOCK_3_ID) > 0 AND Len(TPL_MARKETSHOP1_MENU_BLOCK_3_TITLE) > 0 then
			block1 = ""
			sql = "SELECT block_content FROM " & g_storeid & "_static_block WHERE block_identifier='" & TPL_MARKETSHOP1_MENU_BLOCK_3_ID & "' AND block_status=1"
			set rsStaticBlock = dbconn.Execute(sql)
			if not rsStaticBlock.EOF then
				block1 = "<li class=""" & TPL_MARKETSHOP1_MENU_BLOCK_3_CLASS & " dropdown"" class=""position:static;""><a href=""#"">" & TPL_MARKETSHOP1_MENU_BLOCK_3_TITLE & "</a>"
				block1 = block1 & rsStaticBlock("block_content")
				block1 = block1 & "</li>"
			end if
			rsStaticBlock.close
			set rsStaticBlock = nothing
			mm = Replace(mm, "<!--" & TPL_MARKETSHOP1_MENU_BLOCK_3_PLACEMENT & "-->" , block1 & "<!--" & TPL_MARKETSHOP1_MENU_BLOCK_3_PLACEMENT & "-->")
		end if
		
	%>
	
	<div class="container">
		<nav id="menu" class="navbar">
		<div class="navbar-header">
			<span class="visible-xs visible-sm"> Menu <b></b></span>
		</div>
		<div class="collapse navbar-collapse navbar-ex1-collapse">
			<ul class="nav navbar-nav">
				<li><a class="home_link" title="Home" href="<%=g_store_url%>index.phtml"><span>Home</span></a></li>
				<%=mm%>
			</ul>
		</div>
		</nav>
	</div>
	<!-- Main Menu End-->
</div>