<%
	g_static_block_code = "TPL_MARKETSHOP1_INDEX_SLIDER"
%>
<!--#INCLUDE FILE="../../../core/cms/include_show_static_block.phtml"-->
<!-- Slideshow End-->
<!-- Featured Product Start-->
<%
	custom_category_index = 0
%>
<!--#INCLUDE FILE="../custom/include_custom_productlist.phtml"-->
<!-- Featured Product End-->
<!-- Categories Product Slider Start-->
<%
	'custom_category_id = "01-001"
	custom_category_index = 1
%>
<!--#INCLUDE FILE="../custom/include_custom_productlist.phtml"-->
<!-- Categories Product Slider End-->
<!-- Banner Start -->
<%
	g_static_block_code = "TPL_MARKETSHOP1_INDEX_BANNER"
%>
<!--#INCLUDE FILE="../../../core/cms/include_show_static_block.phtml"-->
<!-- Banner End -->
<!-- Categories Product Slider Start -->
<%
	'custom_category_id = "01-001-001"
	custom_category_index = 2
%>
<!--#INCLUDE FILE="../custom/include_custom_productlist.phtml"-->
<!-- Categories Product Slider End -->
<!-- Brand Product Slider Start-->
<%
	'custom_category_id = "01"
	custom_category_index = 3
%>
<!--#INCLUDE FILE="../custom/include_custom_productlist.phtml"-->
<!-- Brand Product Slider End -->
<!-- Brand Logo Carousel Start-->
<%
	g_static_block_code = "TPL_MARKETSHOP1_INDEX_BRAND_LOGO"
%>
<!--#INCLUDE FILE="../../../core/cms/include_show_static_block.phtml"-->
<!-- Brand Logo Carousel End -->