<!-- JS Part Start-->
<script type="text/javascript" src="<%=skin_base_url%>theme/<%=THEME_TEMPLATE%>/js/jquery-2.1.1.min.js"></script>
<script type="text/javascript" src="<%=skin_base_url%>theme/<%=THEME_TEMPLATE%>/js/bootstrap/js/bootstrap.min.js"></script>
<script type="text/javascript" src="<%=skin_base_url%>theme/<%=THEME_TEMPLATE%>/js/jquery.easing-1.3.min.js"></script>
<script type="text/javascript" src="<%=skin_base_url%>theme/<%=THEME_TEMPLATE%>/js/jquery.dcjqaccordion.min.js"></script>
<script type="text/javascript" src="<%=skin_base_url%>theme/<%=THEME_TEMPLATE%>/js/owl.carousel.min.js"></script>
<script type="text/javascript" src="<%=skin_base_url%>theme/<%=THEME_TEMPLATE%>/js/custom.js"></script>
<!-- JS Part End-->