
<!--#INCLUDE FILE="../custom/include_best_sellers.phtml"-->
<!--#INCLUDE FILE="../custom/include_specials.phtml"-->
<%
	g_static_block_code = "TPL_MARKETSHOP1_LEFT1"
%>
<!--#INCLUDE FILE="../../../core/cms/include_show_static_block.phtml"-->
<%
	g_static_block_code = "TPL_MARKETSHOP1_LEFT2"
%>
<!--#INCLUDE FILE="../../../core/cms/include_show_static_block.phtml"-->
<!--#INCLUDE FILE="../custom/include_latest.phtml"-->