<div class="container">
	<!-- Breadcrumb Start-->
	<ul class="breadcrumb">
		<li><a href="index.html"><i class="fa fa-home"></i></a></li>
		<li><a href="login.html">Account</a></li>
		<li><a href="login.html">Login</a></li>
	</ul>
	<!-- Breadcrumb End-->
	<% if Len(error_msg) > 0 then %>
	<div class="alert alert-danger"><i class="fa fa-exclamation-circle"></i> <%=error_msg%></div>
	<% end if %>
	<div class="row">
		<!--Middle Part Start-->
		<form action="<%=g_secure_url %>tp_login.phtml" method="post" id="login-form">
		<div id="content" class="col-sm-12">
			<h1 class="title"><%=a("Account Login")%></h1>
			<div class="row">
				<div class="col-sm-6">
					<h2 class="subtitle"><%=a("New Customer")%></h2>
					<p>
						<strong><%=a("Register Account")%></strong>
					</p>
					<p>
						<%=a("By creating an account you will be able to shop faster, be up to date on an order's status, and keep track of the orders you have previously made.")%>
					</p>
					<a href="register.phtml" class="btn btn-primary"><%=a("Continue")%></a>
				</div>
				<div class="col-sm-6">
					<h2 class="subtitle"><%=a("Registered Customers")%></h2>
					<p>
						<strong><%=a("I am a returning customer")%></strong>
					</p>
			  
					<div class="form-group">
						<label class="control-label" for="login_email"><%=a("E-Mail Address")%></label>
						<input type="text" name="login_email" value="" placeholder="<%=a("E-Mail Address")%>" id="login_email" class="form-control"/>
					</div>
					<div class="form-group">
						<label class="control-label" for="login_password"><%=a("Password")%></label>
						<input type="password" name="login_password" value="" placeholder="<%=a("Password")%>" id="login_password" class="form-control"/>
						<br/>
						<a href="#"><%=a("Forgot Password?")%></a>
					</div>
					<input type="submit" value="<%=a("Login")%>" class="btn btn-primary"/>
				</div>
			</div>
		</div>
		<!--Middle Part End -->
		<input type="hidden" name="agreeterms" value="1">
		</form>
		
	</div>
</div>