<h3 class="subtitle">Account</h3>
<div class="list-group">
	<ul class="list-item">
		<li><a href="<%=g_secure_url%>account_profile.phtml">Account Dashboard</a></li>
		<li><a href="<%=g_secure_url%>chgpwd.phtml">Account Information</a></li>
		<li><a href="<%=g_secure_url%>billing_list.phtml">Billing Information</a></li>
		<li><a href="<%=g_secure_url%>shipping_list.phtml">Shipping Information</a></li>
		<li><a href="<%=g_secure_url%>mywishlist.phtml">My Wishlist</a></li>
	</ul>
</div>
<h3 class="subtitle">My Orders</h3>
<div class="list-group">
	<ul class="list-item">
		<li><a href="<%=g_secure_url%>order_status_list.phtml?ss_order_filter=recent_orders">Recent Orders</a></li>
		<li><a href="<%=g_secure_url%>order_status_list.phtml?ss_order_filter=all_orders">All Orders</a></li>
		<li><a href="<%=g_secure_url%>order_status_list.phtml?ss_order_filter=pen_orders">Open Orders</a></li>
		<li><a href="<%=g_secure_url%>order_status_list.phtml?ss_order_filter=shipped_orders">Shipped Orders</a></li>
	</ul>
</div>
<h3 class="subtitle">My Quotes</h3>
<div class="list-group">
	<ul class="list-item">
		<li><a href="<%=g_secure_url%>quote_status_list.phtml?ss_Quote_filter=recent_quotes">Recent Quotes</a></li>
		<li><a href="<%=g_secure_url%>quote_status_list.phtml?ss_Quote_filter=all_quotes">All Quotes</a></li>
		<li><a href="<%=g_secure_url%>quote_status_list.phtml?ss_Quote_filter=pen_quotes">Open Quotes</a></li>
	</ul>
</div>