<div class="container">
	<!-- Breadcrumb Start-->
	<ul class="breadcrumb">
		<li itemscope itemtype="http://data-vocabulary.org/Breadcrumb"><a href="index.html" itemprop="url"><span itemprop="title"><i class="fa fa-home"></i></span></a></li>
		<li itemscope itemtype="http://data-vocabulary.org/Breadcrumb"><a href="category.html" itemprop="url"><span itemprop="title">Electronics</span></a></li>
		<li itemscope itemtype="http://data-vocabulary.org/Breadcrumb"><a href="product.html" itemprop="url"><span itemprop="title">Laptop Silver black</span></a></li>
	</ul>
	<!-- Breadcrumb End-->
	<div class="row">
		<!--Middle Part Start-->
		<div id="content" class="col-sm-9">
			<div itemscope itemtype="http://schema.org/Product">
				<h1 class="title" itemprop="name"><%=x_prod_name%></h1>
				<div class="row product-info">
					<div class="col-sm-6">
						<div class="image">
							<img class="img-responsive" itemprop="image" id="zoom_01" src="<%=x_prod_image%>" title="<%=x_prod_name%>" alt="<%=x_prod_name%>" data-zoom-image="<%=x_prod_zoom_image%>"/>
						</div>
						<div class="center-block text-center">
							<span class="zoom-gallery"><i class="fa fa-search"></i> Click image for Gallery</span>
						</div>
						<div class="image-additional" id="gallery_01">
							<a class="thumbnail" href="#" data-zoom-image="<%=x_prod_zoom_image%>" data-image="<%=x_prod_image%>"><img src="<%=x_prod_thumb_image%>"/></a>
							<%
								sql = "SELECT * FROM " & g_storeid & "_product_image WHERE pf_id = '" & pf_id & "' AND image_name <> '" & x_prod_image_file & "'"
								set rs = dbconn.Execute(sql)
								do while not rs.EOF
									cloudImg = Trim(rs("cloud_url"))
									ssImg = Replace(cloudImg, "upload/", ssImgSize)
									ssImg1 = Replace(cloudImg, "upload/", ssThumbSize)
									ssImg2 = Replace(cloudImg, "upload/", ssZoomSize)
									
							%>
							<a class="thumbnail" href="#" data-zoom-image="<%=ssImg2%>" data-image="<%=ssImg%>"><img src="<%=ssImg1%>"/></a>
							<%
									rs.MoveNext
								loop
								rs.Close
								set rs = nothing
							%></div>
					</div>
					<div class="col-sm-6">

						<ul class="list-unstyled description">
							<% if Len(x_vendor_name) > 0 then %>
							<li><b><%=a("Brand")%>:</b> <a href="#"><span itemprop="brand"><%=x_vendor_name%></span></a></li>
							<% end if %>
							<% if Len(x_prod_manu_part_num) > 0 then %>
							<li><b><%=a("Mfg. Part #")%>:</b> <a href="#"><span itemprop="brand"><%=x_prod_manu_part_num%></span></a></li>
							<% end if %>
							<li><b><%=a("SKU")%>:</b><span itemprop="mpn"><%=x_prod_sku%></span></li>
							<li><b><%=a("Availability")%>:</b> <span class="instock"><%=x_prod_stock_status_display%></span></li>
						</ul>
						<div><%=x_prod_desc%></div>
						<ul class="price-box">
							<li class="price" itemprop="offers" itemscope itemtype="http://schema.org/Offer">
								<% if x_prod_on_sale = 1 then %>
								<span class="price-old">$<%=FormatNumber(x_prod_group_price,2)%></span>
								<span itemprop="price">$<%=FormatNumber(x_prod_sale_price,2)%><span itemprop="availability" content="<%=x_prod_stock_status_display%>"></span></span>
								<% else %>
								<span itemprop="price">$<%=FormatNumber(x_prod_group_price,2)%><span itemprop="availability" content="<%=x_prod_stock_status_display%>"></span></span>
								<% end if %>
							</li>
							<li></li>
						</ul>
						<div id="product">
							<!--
							<h3 class="subtitle">Available Options</h3>
							<div class="form-group required">
								<label class="control-label">Color</label>
								<select class="form-control" id="input-option200" name="option[200]">
									<option value=""> --- Please Select --- </option>
									<option value="4">Black </option>
									<option value="3">Silver </option>
									<option value="1">Green </option>
									<option value="2">Blue </option>
								</select>
							</div>
							-->
							<div class="cart">
								<div>
									<div class="qty">
										<label class="control-label" for="input-quantity">Qty</label>
										<input type="text" name="quantity" value="1" size="2" id="input-quantity" class="form-control"/>
										<a class="qtyBtn plus" href="javascript:void(0);">+</a><br/>
										<a class="qtyBtn mines" href="javascript:void(0);">-</a>
										<div class="clear">
										</div>
									</div>
									<button type="button" id="button-cart" class="btn btn-primary btn-lg">Add to Cart</button>
								</div>
								<div>
									<button type="button" class="wishlist" onclick=""><i class="fa fa-heart"></i> Add to Wish List</button>
								</div>
							</div>
						</div>
						<div class="rating" itemprop="aggregateRating" itemscope itemtype="http://schema.org/AggregateRating">
							<meta itemprop="ratingValue" content="0"/>
							<p>
								<%
									for ii =1 to 5
									
										if x_review_avg >= ii then
											Response.Write("<span class=""fa fa-stack""><i class=""fa fa-star fa-stack-2x""></i><i class=""fa fa-star-o fa-stack-2x""></i></span>")
										else
											Response.Write("<span class=""fa fa-stack""><i class=""fa fa-star-o fa-stack-2x""></i></span>")
										end if
								
									next
								%>
								<a onclick="$('a[href=\'#tab-review\']').trigger('click'); return false;" href=""><span itemprop="reviewCount"><%=x_review_count%> reviews</span></a> 
								<% if x_bWriteReview then %>
								/ <a onclick="$('a[href=\'#tab-review\']').trigger('click'); return false;" href="">Write a review</a>
								<% end if %>
							</p>
						</div>
						<hr>
						<!-- AddThis Button BEGIN -->
						<!-- AddThis Button BLOCK -->
						<!-- AddThis Button END -->
					</div>
				</div>
				<ul class="nav nav-tabs">
					<li class="active"><a href="#tab-description" data-toggle="tab">Details</a></li>
					<% for ii = 1 to 5 %>
					<% if pf_tab_show(ii) = 1 then %>
					<li><a href="#tab<%=ii%>" data-toggle="tab"><%=pf_tab_name(ii)%></a></li>
					<% end if %>
					<% next %>
					<li><a href="#tab-review" data-toggle="tab">Reviews (<%=x_review_count%>)</a></li>
				</ul>
				<div class="tab-content">
					<div itemprop="description" id="tab-description" class="tab-pane active">
						<div>
							<%=x_prod_detail%>
						</div>
					</div>
					<% for ii = 1 to 5 %>
					<% if pf_tab_show(ii) = 1 then %>
					<div id="tab<%=ii%>" class="tab-pane">
					<%=GetTabContent(pf_id, ii, pf_tab_type(ii))%>
					</div>
					<% end if %>
					<% next %>
					<div id="tab-review" class="tab-pane">
						<form action="tp_write_review.phtml" class="form-horizontal" method="post" id="review-form">
						<input type="hidden" name="pf_id" value="<%=pf_id%>" />
							<div id="review">
								<div>
									<%
										sql = "SELECT * FROM " & g_storeid & "_Rating WHERE ProductID = '" & pf_id & "' ORDER BY CreatedOn DESC"
										set rsRating = dbconn.Execute(sql)
										do while not rsRating.EOF
											review_rating = rsRating("rating")
											review_comment = rsRating("Comments")
											review_date = FormatDateTime(rsRating("CreatedOn"),2)
											if Len(review_comment) > 0 then
												review_comment = Replace(review_comment, VbCrLF, "<br>")
											end if
											shopper_sql = "SELECT * FROM " & g_storeid & "_shopper WHERE shopper_id = '" & rsRating("CustomerID") & "'"
											set shopper = dbconn.Execute(shopper_sql)
											
											if not shopper.EOF then
												review_owner_name = shopper("FirstName") & " " & shopper("LastName")
											else
												review_owner_name = ""
											end if 
											shopper.Close
											set shopper = nothing
									%>
									<table class="table table-striped table-bordered">
									<tbody>
									<tr>
										<td style="width: 50%;">
											<strong><span><%=rsRating("ReviewTitle")%> | <%=review_owner_name%></span></strong>
										</td>
										<td class="text-right">
											<span><%=review_date%></span>
										</td>
									</tr>
									<tr>
										<td colspan="2">
											<p>
												<%=review_comment%>
											</p>
											<div class="rating">
												<%
													for ii =1 to 5
													
														if review_rating >= ii then
															Response.Write("<span class=""fa fa-stack""><i class=""fa fa-star fa-stack-2x""></i><i class=""fa fa-star-o fa-stack-2x""></i></span>")
														else
															Response.Write("<span class=""fa fa-stack""><i class=""fa fa-star-o fa-stack-2x""></i></span>")
														end if
												
													next
												%>
											</div>
										</td>
									</tr>
									</tbody>
									</table>
									<%
											rsRating.MoveNext
										loop
										
										rsRating.Close
										set rsRating = nothing
									%>
								</div>
								<div class="text-right">
								</div>
							</div>
							
							<% if x_bWriteReview then %>
							<h2><%=a("Write a review")%></h2>
							<div class="form-group required">
								<div class="col-sm-12">
									<label for="input-title" class="control-label"><%=a("Title")%></label>
									<input type="text" class="form-control" id="title" value="" name="title">
								</div>
							</div>
							<div class="form-group required">
								<div class="col-sm-12">
									<label for="input-review" class="control-label"><%=a("Your Review")%></label>
									<textarea class="form-control" id="review" rows="5" name="review"></textarea>
									<div class="help-block">
										<span class="text-danger">Note:</span> <%=a("HTML is not translated!")%>
									</div>
								</div>
							</div>
							<div class="form-group required">
								<div class="col-sm-12">
									<label class="control-label" for="rating"><%=a("Rating")%></label>
									&nbsp;&nbsp;&nbsp; Bad&nbsp; <input type="radio" value="1" name="rating">
									&nbsp; <input type="radio" value="2" name="rating">
									&nbsp; <input type="radio" value="3" name="rating">
									&nbsp; <input type="radio" value="4" name="rating">
									&nbsp; <input type="radio" value="5" name="rating">
									&nbsp;Good
								</div>
							</div>
							<div class="buttons">
								<div class="pull-right">
									<button class="btn btn-primary" id="button-review" type="submit"><%=a("Continue")%></button>
								</div>
							</div>
							<% End If %>
						</form>
					</div>
				</div>
				<h3 class="subtitle">Related Products</h3>
				<div class="owl-carousel related_pro">
					<div class="product-thumb">
						<div class="image">
							<a href="product.html"><img src="image/product/samsung_tab_1-200x200.jpg" alt="Aspire Ultrabook Laptop" title="Aspire Ultrabook Laptop" class="img-responsive"/></a>
						</div>
						<div class="caption">
							<h4><a href="product.html">Aspire Ultrabook Laptop</a></h4>
							<p class="price">
								<span class="price-new">$230.00</span><span class="price-old">$241.99</span><span class="saving">-5%</span>
							</p>
							<div class="rating">
								<span class="fa fa-stack"><i class="fa fa-star fa-stack-2x"></i><i class="fa fa-star-o fa-stack-2x"></i></span><span class="fa fa-stack"><i class="fa fa-star fa-stack-2x"></i><i class="fa fa-star-o fa-stack-2x"></i></span><span class="fa fa-stack"><i class="fa fa-star fa-stack-2x"></i><i class="fa fa-star-o fa-stack-2x"></i></span><span class="fa fa-stack"><i class="fa fa-star fa-stack-2x"></i><i class="fa fa-star-o fa-stack-2x"></i></span><span class="fa fa-stack"><i class="fa fa-star-o fa-stack-2x"></i></span>
							</div>
						</div>
						<div class="button-group">
							<button class="btn-primary" type="button" onclick=""><span>Add to Cart</span></button>
							<div class="add-to-links">
								<button type="button" data-toggle="tooltip" title="Add to wishlist" onclick=""><i class="fa fa-heart"></i></button>
								<button type="button" data-toggle="tooltip" title="Add to compare" onclick=""><i class="fa fa-exchange"></i></button>
							</div>
						</div>
					</div>
					<div class="product-thumb">
						<div class="image">
							<a href="product.html"><img src="image/product/macbook_pro_1-200x200.jpg" alt=" Strategies for Acquiring Your Own Laptop " title=" Strategies for Acquiring Your Own Laptop " class="img-responsive"/></a>
						</div>
						<div class="caption">
							<h4><a href="product.html"> Strategies for Acquiring Your Own Laptop </a></h4>
							<p class="price">
								<span class="price-new">$1,400.00</span><span class="price-old">$1,900.00</span><span class="saving">-26%</span>
							</p>
						</div>
						<div class="button-group">
							<button class="btn-primary" type="button" onclick=""><span>Add to Cart</span></button>
							<div class="add-to-links">
								<button type="button" data-toggle="tooltip" title="Add to wishlist" onclick=""><i class="fa fa-heart"></i></button>
								<button type="button" data-toggle="tooltip" title="Add to compare" onclick=""><i class="fa fa-exchange"></i></button>
							</div>
						</div>
					</div>
					<div class="product-thumb">
						<div class="image">
							<a href="product.html"><img src="image/product/macbook_1-200x200.jpg" alt="Ideapad Yoga 13-59341124 Laptop" title="Ideapad Yoga 13-59341124 Laptop" class="img-responsive"/></a>
						</div>
						<div class="caption">
							<h4><a href="product.html">Ideapad Yoga 13-59341124 Laptop</a></h4>
							<p class="price">
								 $2.00
							</p>
							<div class="rating">
								<span class="fa fa-stack"><i class="fa fa-star fa-stack-2x"></i><i class="fa fa-star-o fa-stack-2x"></i></span><span class="fa fa-stack"><i class="fa fa-star fa-stack-2x"></i><i class="fa fa-star-o fa-stack-2x"></i></span><span class="fa fa-stack"><i class="fa fa-star fa-stack-2x"></i><i class="fa fa-star-o fa-stack-2x"></i></span><span class="fa fa-stack"><i class="fa fa-star fa-stack-2x"></i><i class="fa fa-star-o fa-stack-2x"></i></span><span class="fa fa-stack"><i class="fa fa-star-o fa-stack-2x"></i></span>
							</div>
						</div>
						<div class="button-group">
							<button class="btn-primary" type="button" onclick=""><span>Add to Cart</span></button>
							<div class="add-to-links">
								<button type="button" data-toggle="tooltip" title="Add to wishlist" onclick=""><i class="fa fa-heart"></i></button>
								<button type="button" data-toggle="tooltip" title="Add to compare" onclick=""><i class="fa fa-exchange"></i></button>
							</div>
						</div>
					</div>
					<div class="product-thumb">
						<div class="image">
							<a href="product.html"><img src="image/product/ipod_shuffle_1-200x200.jpg" alt="Hp Pavilion G6 2314ax Notebok Laptop" title="Hp Pavilion G6 2314ax Notebok Laptop" class="img-responsive"/></a>
						</div>
						<div class="caption">
							<h4><a href="product.html">Hp Pavilion G6 2314ax Notebok Laptop</a></h4>
							<p class="price">
								 $122.00
							</p>
						</div>
						<div class="button-group">
							<button class="btn-primary" type="button" onclick=""><span>Add to Cart</span></button>
							<div class="add-to-links">
								<button type="button" data-toggle="tooltip" title="Add to wishlist" onclick=""><i class="fa fa-heart"></i></button>
								<button type="button" data-toggle="tooltip" title="Add to compare" onclick=""><i class="fa fa-exchange"></i></button>
							</div>
						</div>
					</div>
					<div class="product-thumb">
						<div class="image">
							<a href="product.html"><img src="image/product/ipod_touch_1-200x200.jpg" alt="Samsung Galaxy S4" title="Samsung Galaxy S4" class="img-responsive"/></a>
						</div>
						<div class="caption">
							<h4><a href="product.html">Samsung Galaxy S4</a></h4>
							<p class="price">
								<span class="price-new">$62.00</span><span class="price-old">$122.00</span><span class="saving">-50%</span>
							</p>
						</div>
						<div class="button-group">
							<button class="btn-primary" type="button" onclick=""><span>Add to Cart</span></button>
							<div class="add-to-links">
								<button type="button" data-toggle="tooltip" title="Add to wishlist" onclick=""><i class="fa fa-heart"></i></button>
								<button type="button" data-toggle="tooltip" title="Add to compare" onclick=""><i class="fa fa-exchange"></i></button>
							</div>
						</div>
					</div>
					<div class="product-thumb">
						<div class="image">
							<a href="product.html"><img src="image/product/ipod_shuffle_1-200x200.jpg" alt="Hp Pavilion G6 2314ax Notebok Laptop" title="Hp Pavilion G6 2314ax Notebok Laptop" class="img-responsive"/></a>
						</div>
						<div class="caption">
							<h4><a href="product.html">Hp Pavilion G6 2314ax Notebok Laptop</a></h4>
							<p class="price">
								 $122.00
							</p>
						</div>
						<div class="button-group">
							<button class="btn-primary" type="button" onclick=""><span>Add to Cart</span></button>
							<div class="add-to-links">
								<button type="button" data-toggle="tooltip" title="Add to wishlist" onclick=""><i class="fa fa-heart"></i></button>
								<button type="button" data-toggle="tooltip" title="Add to compare" onclick=""><i class="fa fa-exchange"></i></button>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!--Middle Part End -->
		<!--Right Part Start -->
		<aside id="column-right" class="col-sm-3 hidden-xs">
		<h3 class="subtitle">Bestsellers</h3>
		<div class="side-item">
			<div class="product-thumb clearfix">
				<div class="image">
					<a href="product.html"><img src="image/product/apple_cinema_30-50x50.jpg" alt="Brand Fashion Cotton T-Shirt" title="Brand Fashion Cotton T-Shirt" class="img-responsive"/></a>
				</div>
				<div class="caption">
					<h4><a href="product.html">Brand Fashion Cotton T-Shirt</a></h4>
					<p class="price">
						<span class="price-new">$110.00</span><span class="price-old">$122.00</span><span class="saving">-10%</span>
					</p>
				</div>
			</div>
			<div class="product-thumb clearfix">
				<div class="image">
					<a href="product.html"><img src="image/product/iphone_1-50x50.jpg" alt="iPhone5" title="iPhone5" class="img-responsive"/></a>
				</div>
				<div class="caption">
					<h4><a href="product.html">iPhone5</a></h4>
					<p class="price">
						 $123.20
					</p>
					<div class="rating">
						<span class="fa fa-stack"><i class="fa fa-star fa-stack-2x"></i><i class="fa fa-star-o fa-stack-2x"></i></span><span class="fa fa-stack"><i class="fa fa-star fa-stack-2x"></i><i class="fa fa-star-o fa-stack-2x"></i></span><span class="fa fa-stack"><i class="fa fa-star fa-stack-2x"></i><i class="fa fa-star-o fa-stack-2x"></i></span><span class="fa fa-stack"><i class="fa fa-star fa-stack-2x"></i><i class="fa fa-star-o fa-stack-2x"></i></span><span class="fa fa-stack"><i class="fa fa-star-o fa-stack-2x"></i></span>
					</div>
				</div>
			</div>
			<div class="product-thumb clearfix">
				<div class="image">
					<a href="product.html"><img src="image/product/macbook_1-50x50.jpg" alt="Ideapad Yoga 13-59341124 Laptop" title="Ideapad Yoga 13-59341124 Laptop" class="img-responsive"/></a>
				</div>
				<div class="caption">
					<h4><a href="product.html">Ideapad Yoga 13-59341124 Laptop</a></h4>
					<p class="price">
						 $2.00
					</p>
					<div class="rating">
						<span class="fa fa-stack"><i class="fa fa-star fa-stack-2x"></i><i class="fa fa-star-o fa-stack-2x"></i></span><span class="fa fa-stack"><i class="fa fa-star fa-stack-2x"></i><i class="fa fa-star-o fa-stack-2x"></i></span><span class="fa fa-stack"><i class="fa fa-star fa-stack-2x"></i><i class="fa fa-star-o fa-stack-2x"></i></span><span class="fa fa-stack"><i class="fa fa-star fa-stack-2x"></i><i class="fa fa-star-o fa-stack-2x"></i></span><span class="fa fa-stack"><i class="fa fa-star-o fa-stack-2x"></i></span>
					</div>
				</div>
			</div>
			<div class="product-thumb clearfix">
				<div class="image">
					<a href="product.html"><img src="image/product/sony_vaio_1-50x50.jpg" alt="Xitefun Causal Wear Fancy Shoes" title="Xitefun Causal Wear Fancy Shoes" class="img-responsive"/></a>
				</div>
				<div class="caption">
					<h4><a href="product.html">Xitefun Causal Wear Fancy Shoes</a></h4>
					<p class="price">
						<span class="price-new">$902.00</span><span class="price-old">$1,202.00</span><span class="saving">-25%</span>
					</p>
					<div class="rating">
						<span class="fa fa-stack"><i class="fa fa-star fa-stack-2x"></i><i class="fa fa-star-o fa-stack-2x"></i></span><span class="fa fa-stack"><i class="fa fa-star fa-stack-2x"></i><i class="fa fa-star-o fa-stack-2x"></i></span><span class="fa fa-stack"><i class="fa fa-star fa-stack-2x"></i><i class="fa fa-star-o fa-stack-2x"></i></span><span class="fa fa-stack"><i class="fa fa-star fa-stack-2x"></i><i class="fa fa-star-o fa-stack-2x"></i></span><span class="fa fa-stack"><i class="fa fa-star-o fa-stack-2x"></i></span>
					</div>
				</div>
			</div>
			<div class="product-thumb clearfix">
				<div class="image">
					<a href="product.html"><img src="image/product/FinePix-Long-Zoom-Camera-50x50.jpg" alt="FinePix S8400W Long Zoom Camera" title="FinePix S8400W Long Zoom Camera" class="img-responsive"/></a>
				</div>
				<div class="caption">
					<h4><a href="product.html">FinePix S8400W Long Zoom Camera</a></h4>
					<p class="price">
						$122.00
					</p>
				</div>
			</div>
		</div>
		<div class="list-group">
			<h3 class="subtitle">Custom Content</h3>
			<p>
				This is a CMS block edited from admin. You can insert any content (HTML, Text, Images) Here.
			</p>
			<p>
				Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.
			</p>
			<p>
				It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.
			</p>
		</div>
		<h3 class="subtitle">Specials</h3>
		<div class="side-item">
			<div class="product-thumb clearfix">
				<div class="image">
					<a href="product.html"><img src="image/product/macbook_pro_1-50x50.jpg" alt=" Strategies for Acquiring Your Own Laptop " title=" Strategies for Acquiring Your Own Laptop " class="img-responsive"/></a>
				</div>
				<div class="caption">
					<h4><a href="product.html">Strategies for Acquiring Your Own Laptop</a></h4>
					<p class="price">
						<span class="price-new">$1,400.00</span><span class="price-old">$1,900.00</span><span class="saving">-26%</span>
					</p>
				</div>
			</div>
			<div class="product-thumb clearfix">
				<div class="image">
					<a href="product.html"><img src="image/product/samsung_tab_1-50x50.jpg" alt="Aspire Ultrabook Laptop" title="Aspire Ultrabook Laptop" class="img-responsive"/></a>
				</div>
				<div class="caption">
					<h4><a href="product.html">Aspire Ultrabook Laptop</a></h4>
					<p class="price">
						<span class="price-new">$230.00</span><span class="price-old">$241.99</span><span class="saving">-5%</span>
					</p>
					<div class="rating">
						<span class="fa fa-stack"><i class="fa fa-star fa-stack-2x"></i><i class="fa fa-star-o fa-stack-2x"></i></span><span class="fa fa-stack"><i class="fa fa-star fa-stack-2x"></i><i class="fa fa-star-o fa-stack-2x"></i></span><span class="fa fa-stack"><i class="fa fa-star fa-stack-2x"></i><i class="fa fa-star-o fa-stack-2x"></i></span><span class="fa fa-stack"><i class="fa fa-star fa-stack-2x"></i><i class="fa fa-star-o fa-stack-2x"></i></span><span class="fa fa-stack"><i class="fa fa-star-o fa-stack-2x"></i></span>
					</div>
				</div>
			</div>
			<div class="product-thumb clearfix">
				<div class="image">
					<a href="product.html"><img src="image/product/apple_cinema_30-50x50.jpg" alt="Brand Fashion Cotton T-Shirt" title="Brand Fashion Cotton T-Shirt" class="img-responsive"/></a>
				</div>
				<div class="caption">
					<h4><a href="http://demo.harnishdesign.net/opencart/marketshop/v1/index.php?route=product/product&amp;product_id=42">Brand Fashion Cotton T-Shirt</a></h4>
					<p class="price">
						<span class="price-new">$110.00</span><span class="price-old">$122.00</span><span class="saving">-10%</span>
					</p>
				</div>
			</div>
			<div class="product-thumb clearfix">
				<div class="image">
					<a href="product.html"><img src="image/product/nikon_d300_1-50x50.jpg" alt="Digital Camera for Elderly" title="Digital Camera for Elderly" class="img-responsive"/></a>
				</div>
				<div class="caption">
					<h4><a href="product.html">Digital Camera for Elderly</a></h4>
					<p class="price">
						<span class="price-new">$92.00</span><span class="price-old">$98.00</span><span class="saving">-6%</span>
					</p>
				</div>
			</div>
			<div class="product-thumb clearfix">
				<div class="image">
					<a href="product.html"><img src="image/product/nikon_d300_5-50x50.jpg" alt="Hair Care Products" title="Hair Care Products" class="img-responsive"/></a>
				</div>
				<div class="caption">
					<h4><a href="product.html">Hair Care Products</a></h4>
					<p class="price">
						<span class="price-new">$66.80</span><span class="price-old">$90.80</span><span class="saving">-27%</span>
					</p>
					<div class="rating">
						<span class="fa fa-stack"><i class="fa fa-star fa-stack-2x"></i><i class="fa fa-star-o fa-stack-2x"></i></span><span class="fa fa-stack"><i class="fa fa-star-o fa-stack-2x"></i></span><span class="fa fa-stack"><i class="fa fa-star-o fa-stack-2x"></i></span><span class="fa fa-stack"><i class="fa fa-star-o fa-stack-2x"></i></span><span class="fa fa-stack"><i class="fa fa-star-o fa-stack-2x"></i></span>
					</div>
				</div>
			</div>
			<div class="product-thumb clearfix">
				<div class="image">
					<a href="product.html"><img src="image/product/macbook_air_1-50x50.jpg" alt="Laptop Silver black" title="Laptop Silver black" class="img-responsive"/></a>
				</div>
				<div class="caption">
					<h4><a href="product.html">Laptop Silver black</a></h4>
					<p class="price">
						<span class="price-new">$1,142.00</span><span class="price-old">$1,202.00</span><span class="saving">-5%</span>
					</p>
				</div>
			</div>
		</div>
		</aside>
		<!--Right Part End -->
	</div>
</div>