<h1 class="title"><%=g_dept_name%></h1>

<div class="product-filter">
	<div class="row">
		<div class="col-md-4 col-sm-5">
			<div class="btn-group">
				<button type="button" id="list-view" class="btn btn-default" data-toggle="tooltip" title="List"><i class="fa fa-th-list"></i></button>
				<button type="button" id="grid-view" class="btn btn-default" data-toggle="tooltip" title="Grid"><i class="fa fa-th"></i></button>
			</div>
		</div>
		<div class="col-sm-2 text-right">
			<label class="control-label" for="input-sort">Sort By:</label>
		</div>
		<div class="col-md-3 col-sm-2 text-right">
			<select id="input-sort" class="form-control col-sm-3" onchange="setLocation(this.value)">
				<!--
				<option value="" selected="selected">Default</option>onchange="setLocation(this.value)"
				-->
				<option value="<%=strSortURL_Name %>" <% if so="0" then %>selected="selected" <%end if %>>Name (A - Z)</option>
				<option value="<%=strSortURL_Name_desc %>" <% if so="1" then %>selected="selected" <%end if %>>Name (Z - A)</option>
				<option value="<%=strSortURL_Price %>" <% if so="8" then %>selected="selected" <%end if %>>Price (Low &gt; High)</option>
				<option value="<%=strSortURL_Price_desc %>" <% if so="9" then %>selected="selected" <%end if %>>Price (High &gt; Low)</option>
				<option value="<%=strSortURL_PartNumber %>" <% if so="6" then %>selected="selected" <%end if %>>SKU (A - Z)</option>
				<option value="<%=strSortURL_PartNumber_desc %>" <% if so="7" then %>selected="selected" <%end if %>>SKU (Z - A)</option>
			</select>
		</div>
		<div class="col-sm-1 text-right">
			<label class="control-label" for="input-limit">Show:</label>
		</div>
		<div class="col-sm-2 text-right">
			<select id="input-limit" class="form-control" onchange="setLocation(this.value);">
				<option value="<%=strSortURL_10 %>" <% if show="10" then %>selected="selected" <%end if %>>
				10 </option>
				<option value="<%=strSortURL_20 %>" <% if show="20" then %>selected="selected" <%end if %>>
				20 </option>
				<option value="<%=strSortURL_40 %>" <% if show="40" then %>selected="selected" <%end if %>>
				40 </option>
				<option value="<%=strSortURL_60 %>" <% if show="60" then %>selected="selected" <%end if %>>
				60 </option>
				<option value="<%=strSortURL_80 %>" <% if show="80" then %>selected="selected" <%end if %>>
				80 </option>
			</select>
		</div>
	</div>
</div>
<br/>
<div class="row products-category">
	<!--#INCLUDE FILE="../../../core/catalog/include_dept_productlist_loop_start.phtml"-->
	<%
		'TEMPLATE FIX
		if Len(g_prod_name) > 60 then
			g_prod_name = Left(g_prod_name, 60) & "..."
		end if
		g_prod_description = Replace(g_prod_description, "<ul>", "<ul class='description description1'>")
		g_prod_description = Replace(g_prod_description, "<div class=""pProductHighlight clearfix"" data-selenium=""ProductHighlight"">", "<div class='description description1'>")
	%>
	<div class="product-layout product-list col-xs-12">
		<div class="product-thumb">
			<div class="image">
				<a href="<%=g_product_link%>"><img src="<%=g_thumb_image_link%>" alt="<%=g_prod_name%>" title="<%=g_prod_name%>" class="img-responsive"/></a>
			</div>
			<div>
				<div class="caption">
					<h4><a href="<%=g_product_link%>"><%=g_prod_name%></a></h4>
				</div>
				<p class="description">
					<%=g_prod_description%>
				</p>
			</div>
			<div class="button-group" style="vertical-align:bottom">
				<p class="price">
					<% if g_prod_on_sale = 1 then %>
						<span class="price-new">$<%=FormatNumber(g_prod_sale_price,2)%></span><span class="price-old">$<%=FormatNumber(g_prod_group_price,2)%></span><span class="saving">-26%</span>
					<% else %>
						$<%=FormatNumber(g_prod_group_price,2)%>
					<% end if %>
				</p>
				<button class="btn-primary" type="button" onclick=""><span>Add to Cart</span></button>
				<div class="add-to-links">
					<button type="button" data-toggle="tooltip" title="Add to Wish List" onclick=""><i class="fa fa-heart"></i><span>Add to Wish List</span></button>
				</div>
			</div>
		</div>
	</div>
	<!--#INCLUDE FILE="../../../core/catalog/include_dept_productlist_loop_end.phtml"-->
</div>
<div class="row">
	<div class="col-sm-6 text-left">
		<ul class="pagination">
			<%
				rest = page mod block_size
				if rest = 0 then rest = block_size end if
				start = page - rest + 1
			%>
			<%if start-block_size > 0 Then %>
					<li>
					<a class="previous" href="<%=strPageURL %>&page=<%=start-block_size%>" title="Previous">
					Prev </a>
					</li>
			<% end if %>

			<%
				for xp = start to start+block_size-1
				if xp <= page_count then
				if xp = page then
			%>
				<li class="active"><span><%=xp%></span></li>
			<%
				else
			%>
				<li><a href="<%=strPageURL %>&page=<%=xp%>"><%=xp%></a></li>
			<%
				end if
			end if
			next
			%>

			<% if start+block_size <= page_count Then %>
				<li>
				<a class="next" href="<%=strPageURL %>&page=<%=start+block_size%>" title="Next">
				Next </a>
				</li>
			<% end if %>
			<!--
			<li class="active"><span>1</span></li>
			<li><a href="#">2</a></li>
			<li><a href="#">&gt;</a></li>
			<li><a href="#">&gt;|</a></li>
			-->
		</ul>
	</div>
	<div class="col-sm-6 text-right">
		Showing <%=i_start%> to <%=i_last%> of <%=list_count%>
	</div>
</div>