<!--#INCLUDE FILE="../../local/local.phtml"-->
<!--#INCLUDE FILE="../../language_pack.phtml"-->
<!--#INCLUDE FILE="../../util/xt_func_session.phtml"-->
<!--#INCLUDE FILE="../../i_initsession.phtml"-->
<%
	Session("shopper_id") = GetSession(Session("SESSIONKEY"), "sCID")
	Session("Shopper_Name") = GetSession(Session("SESSIONKEY"), "sCName")
	Session("PARTNER") = GetSession(Session("SESSIONKEY"), "sAffID")
%>
<!--#INCLUDE FILE="../../i_adodb.phtml"-->
<!--#INCLUDE FILE="../../util/xt_func_string.phtml"-->
<!--#INCLUDE FILE="../../util/xt_func_seo.phtml"-->
<!--#INCLUDE File="../../util/xt_func_util.phtml" -->

<%
	dept_ID = Request("dept_id")
	dept_ID = FilterSKUString(dept_ID)
	
	sql = "SELECT dept_name FROM " & Session("StoreID") & "_system_dept WHERE dept_id='" & dept_ID & "'"
	Set rsDeptName = Conn.Execute(sql)
							
	if not rsDeptName.EOF then
	  dept_name = rsDeptName("dept_name")
	  dept_ok = true
	else
	  dept_name = ""
	  dept_ok = false
	end if
	rsDeptName.Close
%>