<!--#INCLUDE FILE="../../local/local.phtml"-->
<!--#INCLUDE FILE="../i_initsession.phtml"-->
<!--#INCLUDE FILE="../i_adoopen.phtml"-->
<!--#INCLUDE FILE="../../language_pack.phtml"-->
<!--#INCLUDE FILE="../../util/xt_func_session.phtml"-->
<!--#INCLUDE FILE="../../util/xt_func_string.phtml"-->
<!--#INCLUDE FILE="../../util/xt_func_util.phtml"-->
<!--#INCLUDE FILE="../../util/xt_func_shoppingcart.phtml"-->
<Script language="VBScript" RUNAT=SERVER>
function GetSystemFlatModel(ByRef str_db, ByRef str_config_id, ByRef markup, ByRef system_price)

	sql = "SELECT markup_price, dept_id FROM :9_system_config WHERE config_id='" & str_config_id & "' AND dept_id IN ("
	sql = sql & "SELECT sysdept_id FROM :9_sysdept WHERE config_id='" & str_config_id & "' AND sysdept_mode=0 AND NOT (allow_none=1 AND none_default=1)) "
	sql = sql & "ORDER BY dept_id, row_id"
	sql = Replace(sql, ":9", g_storeid)

	set rs1 = dbconn.Execute(sql)

	temp_dept = ""
	system_price = 0

	do while not rs1.EOF

	markup_price = rs1("markup_price")
	if not rs1("dept_id") = temp_dept then
		system_price = system_price + markup_price
		temp_dept = rs1("dept_id")
	end if
	rs1.MoveNext
	loop
	rs1.Close

	'system_price = system_price + (system_price * markup/100)
	'Add Hidden Cost..
	sql = "SELECT SUM(sysdept_cost) FROM :9_sysdept WHERE config_id='" & str_config_id & "' AND sysdept_mode=2"
	sql = Replace(sql, ":9", g_storeid)
	set rsPart = dbconn.Execute(sql)
	if not rsPart.EOF then
		if isNumeric(rsPart(0)) then
			system_price = system_price + rsPart(0)
		end if
	end if
	rsPart.close
	system_price = system_price + (system_price * markup/100)

	GetSystemFlatModel = true
  
end function
</Script>

<%
	config_id = Request("config_id")
	config_id = FilterStringEX(config_id, "^0-9a-zA-Z _/-")
	
	if (Session("LOGINGROUP") = "") then
		member_group = "D"
	else
		member_group = Session("LOGINGROUP")
	end if
	
	sql = "SELECT * FROM " & g_storeid & "_system_product WHERE pf_id='" & config_id & "'"
	set rsSystem = dbconn.Execute(sql)
	
	if not rsSystem.EOF then
		system_name = rsSystem("name")
		system_sku = rsSystem("sku") 
		sys_desc = rsSystem("description")
		sys_desc2 = rsSystem("description2")
		sys_details = rsSystem("details")
		sys_image_file = rsSystem("image_file")
		sys_image = Trim(rsSystem("thumb_image"))
		sys_image2 = Trim(rsSystem("thumb_image2"))
		sys_image3 = Trim(rsSystem("thumb_image3"))
		sys_image4 = Trim(rsSystem("thumb_image4"))
		sys_mm_type = rsSystem("mm_type")
		base_price = rsSystem("price_"& member_group)
		pricing_model = rsSystem("pricing_model")
		option_mode = rsSystem("option_mode")
		u_markup_value = rsSystem("u_markup_"& member_group)
		
		'If IsNull(sys_image) or sys_image = "" or sys_image = "--" Then
		  'sys_image = g_noimage_url
		'Else
		  'sys_image = "sys_img/" & sys_image
		'End If
		if pricing_model = 1 then
			if GetSystemFlatModel(Session("ConnectionString"), config_id, u_markup_value, system_price) then
				base_price = system_price
			end if
		end if
	  
		sys_enable_upload = rsSystem("sys_enable_upload")
    
	else
		system_name = "..."
		pricing_model = 0
		option_mode = 2
		u_markup_value = 0
		base_price = 0
		sys_enable_upload = 0
		
		Response.Write(Session("StoreURL"))
	end if	
	rsSystem.Close
	
	
	'====================================================================================================
	'Images
	'====================================================================================================
	ssThumbSize = "upload/w_" & EC_thumbWidth & ",h_" & EC_thumbHeight & ",c_pad/"
	ssImgSize = "upload/w_" & EC_imageWidth & ",h_" & EC_imageHeight & ",c_pad/"
	ssZoomSize = "upload/w_" & EC_zoomWidth & ",h_" & EC_zoomHeight & ",c_pad/"
	
	if sys_image_file = "--" then
		cloudImg = g_noimage_url
		ssImg = Replace(cloudImg, "upload/", ssImgSize)
		ssImg1 = Replace(cloudImg, "upload/", ssThumbSize)
		ssImg2 = Replace(cloudImg, "upload/", ssZoomSize)
	else
		if sys_mm_type = 1 then
			sql = "SELECT * FROM " & g_storeid & "_product_image WHERE image_name = '" & sys_image_file & "'"
			Set rsCloudImage2 = dbconn.Execute(sql)
			If Not rsCloudImage2.EOF Then
				cloudImg = Trim(rsCloudImage2("cloud_url"))
			Else
				cloudImg = g_noimage_url
			End If
			rsCloudImage2.Close
			Set rsCloudImage2 = Nothing
			ssImg = Replace(cloudImg, "upload/", ssImgSize)
			ssImg1 = Replace(cloudImg, "upload/", ssThumbSize)
			ssImg2 = Replace(cloudImg, "upload/", ssZoomSize)
		else
			ssImg = "http://a4.res.cloudinary.com/dd3llssvr/image/fetch/" & "w_" & EC_imageWidth & ",h_" & EC_imageHeight & ",c_pad/" & g_store_url & "assets/pmedia/prod_img/" & Server.URLEncode(prod_image_file)
			ssImg1 = "http://a4.res.cloudinary.com/dd3llssvr/image/fetch/" & "w_" & EC_thumbWidth & ",h_" & EC_thumbHeight & ",c_pad/" & g_store_url & "assets/pmedia/prod_img/" & Server.URLEncode(prod_image_file)
			ssImg2 = "http://a4.res.cloudinary.com/dd3llssvr/image/fetch/" & "w_" & EC_zoomWidth & ",h_" & EC_zoomHeight & ",c_pad/" & g_store_url & "assets/pmedia/prod_img/" & Server.URLEncode(prod_image_file)
		end if
	end if
	
	image_display_src = ssImg
	image_display_src_zoom = ssImg2
	image_display_src_thumb = ssImg1
	
	
	'==================================================================
	'DISPLAY
	'==================================================================
	
	g_system_name = system_name
	g_base_price = base_price
	g_sys_details = sys_details
	g_sys_desc = sys_desc
	g_sys_desc2 = sys_desc2
	
	image_display_src = ssImg
	image_display_src_zoom = ssImg2
	image_display_src_thumb = ssImg1
	
	'==================================================================
	'TEMPLATE
	'==================================================================
	
	x_prod_name = system_name
	x_page_title = g_page_title
	x_prod_sku = system_sku
	x_prod_desc = sys_desc
	x_prod_detail = sys_details
	x_prod_manu_part_num = ""
	x_vendor_name = ""
	
	x_prod_on_sale = 0
	x_prod_sale_price = 0
	x_prod_group_price = base_price
	x_prod_retail_price = 0
	
	x_prod_image = image_display_src
	x_prod_zoom_image = image_display_src_zoom
	x_prod_thumb_image = image_display_src_thumb
	x_prod_mm_type = sys_mm_type
	x_prod_image_file = sys_image_file
	
	x_prod_espec_sku = ""
	x_prod_use_icecat_images = 0
	'x_prod_image_file = ssImg
	
%>
