<!--#INCLUDE FILE="../../local/local.phtml"-->
<!--#INCLUDE FILE="../i_adoopen.phtml"-->
<!--#INCLUDE FILE="../../language_pack.phtml"-->
<!--#INCLUDE FILE="../../util/xt_func_session.phtml"-->
<!--#INCLUDE File="../../util/xt_func_util.phtml" -->
<!--#INCLUDE FILE="../../util/xt_func_string.phtml"-->
<!--#INCLUDE FILE="../../util/xt_func_seo.phtml"-->
<!--#INCLUDE FILE="../../i_initsession.phtml"-->
<!--#INCLUDE FILE="../i_login.phtml"-->
<script language="VBScript" RUNAT=SERVER>
function GetParentCategoryLink(ByRef str_db, ByRef str_dept_id)

	'Get Category Names...
	dim str_dept_link
	
	Set dbconnx = Server.CreateObject("ADODB.Connection")
	dbconnx.open str_db
	
	str_dept_link = ""
	dept_id_len = Len(str_dept_id)
	
	select case dept_id_len
	case 2 'Main category
		'no parent directory...					
	case 6 'Sub 1
		sql = "SELECT dept_id, dept_name FROM :9_dept WHERE dept_id IN ('" & Left(str_dept_id, InStr(str_dept_id, "-")-1) & "') ORDER BY dept_id"
		sql = Replace(sql, ":9", g_storeid)
		set rsDept=dbconnx.Execute(sql)
		
		do while not rsDept.EOF
			str_dept_link = str_dept_link & "<a href=""gdept.phtml?dept_id=" & rsDept("dept_id") & """>" & rsDept("dept_name") & "</a> > "
			rsDept.MoveNext
		loop
					
		rsDept.Close

	case 10 'Sub 2
		sql = "SELECT dept_id, dept_name FROM :9_dept WHERE dept_id IN ('" & Left(str_dept_id,2) & "', '" & Left(str_dept_id, 6) & "') ORDER BY dept_id"
		sql = Replace(sql, ":9", g_storeid)
		set rsDept=dbconn.Execute(sql)
		
		i = dept_level
		do while not rsDept.EOF
			str_dept_link = str_dept_link & "<a href=""gdept.phtml?dept_id=" & rsDept("dept_id") & """>" & rsDept("dept_name") & "</a> > "
			rsDept.MoveNext
		loop
					
		rsDept.Close
			
	case else
		
	end select
	
	dbconnx.close
	
	GetParentCategoryLink = str_dept_link
	
end function

function GetCategoryPriceRule(str_db, str_dept_id, str_dept_pricerule, str_default)
	
	'Initialize..
	f_pricerule = 0
	dim b_pricerule, a_pricerule
	
	b_pricerule = false
	a_pricerule = "0"
	
	Set dbconnx = Server.CreateObject("ADODB.Connection")
	dbconnx.open str_db
	
	sql = "SELECT pri_pricerule_flag, pub_pricerule_flag FROM :9_profile"
	sql = Replace(sql, ":9", g_storeid)
	set rsGlobal= dbconnx.Execute(sql)
					
	if not rsGlobal.EOF then	  	
		pri_pricerule_flag = rsGlobal("pri_pricerule_flag")
		pub_pricerule_flag = rsGlobal("pub_pricerule_flag")
		
		if str_default = "000" then
			if not (pri_pricerule_flag > 0) then
				a_pricerule = "0"
			else
				if pri_pricerule_flag = 1 then
					a_pricerule = str_default
				end if
			end if
		else
			if not (pub_pricerule_flag > 0) then
				a_pricerule = "0"
			else
				if pub_pricerule_flag = 1 then
					a_pricerule = str_default
				end if
			end if
		end if
	  	
	else
		a_pricerule = "0"
	end if
					
	rsGlobal.Close
	
	'GRP
	sql = "SELECT dept_pricerule FROM :9_dept WHERE dept_id='" & Left(str_dept_id,2) & "'"
  sql = Replace(sql, ":9", g_storeid)
  set rsSub=dbconnx.Execute(sql)
  
  if not rsSub.EOF then
		pricerule_flag = rsSub("dept_pricerule")
		if not (pricerule_flag > 0) then
			a_pricerule = "0"
		else
			if pricerule_flag = 1 then
				a_pricerule = Left(str_dept_id,2)
			end if
		end if
  else
		a_pricerule = "0"
  end if
  
  if Len(str_dept_id) > 2 then
		'CAT
		sql = "SELECT dept_pricerule FROM :9_dept WHERE dept_id='" & Left(str_dept_id,6) & "'"
		sql = Replace(sql, ":9", g_storeid)
		set rsSub=dbconnx.Execute(sql)
  
		if not rsSub.EOF then
			pricerule_flag = rsSub("dept_pricerule")
			if not (pricerule_flag > 0) then
				a_pricerule = "0"
			else
				if pricerule_flag = 1 then
					a_pricerule = Left(str_dept_id,6)
				end if
			end if
		else
			a_pricerule = "0"
		end if
  end if
  
  if Len(str_dept_id) > 6 then
		'CAT
		sql = "SELECT dept_pricerule FROM :9_dept WHERE dept_id='" & Left(str_dept_id,10) & "'"
		sql = Replace(sql, ":9", g_storeid)
		set rsSub=dbconnx.Execute(sql)
  
		if not rsSub.EOF then
			pricerule_flag = rsSub("dept_pricerule")
			if not (pricerule_flag > 0) then
				a_pricerule = "0"
			else
				if pricerule_flag = 1 then
					a_pricerule = Left(str_dept_id,10)
				end if
			end if
		else
			a_pricerule = "0"
		end if
  end if
  
  if a_pricerule = "0" then
		b_pricerule = false
  else
		b_pricerule = true
  end if
	
	str_dept_pricerule = a_pricerule
	
	dbconnx.Close
	
	GetCategoryPriceRule = b_pricerule
end function

function ApplyPriceRule(ByRef str_db, ByRef rule_dept, ByRef str_price)
	dim retPrice
	retPrice = 0
	
	call Numberize(str_price)
	
	set dbconnx = Server.CreateObject("ADODB.Connection")
	dbconnx.Open str_db
	
	sql = "SELECT pricerule_rule FROM :9_pricerule WHERE pricerule_from <= " & str_price & " AND pricerule_to > " & str_price & " AND pricerule_dept='" & rule_dept & "'"
	sql = Replace(sql, ":9", g_storeid)
	
	set rsPrice = dbconnx.Execute(sql)
	if not rsPrice.EOF then
		iRule = rsPrice("pricerule_rule")
		if IsNumeric(iRule) then
			retPrice = CDbl(str_price)*(iRule/100 + 1)
		else
			retPrice = 0
		end if
	else
		retPrice = 0
	end if
	rsPrice.Close
	
	dbconnx.Close
	ApplyPriceRule = FormatNumber(retPrice, 2,,,0)
	
end function
</script>

<%
	dept_ID = Trim(Request("dept_id"))
	dept_ID = FilterStringEx(dept_ID, "[^0-9-]")
	
	sub_id = Trim(Request("sub_id"))
	sub_id = FilterStringEx(sub_id, "[^0-9-]")
	
	so = Trim(Request("so"))
	so = FilterStringEx(so, "[^0-9]")
	show = Trim(Request("show"))
	show = FilterStringEx(show, "[^0-9]")
	mode = Trim(Request("mode"))

	if mode = "grid" then
	else
		mode = ""
	end if
	
	'=================================================================================================
	'overwrite pf_id if urlkey present
	'=================================================================================================
	url_key = Trim(Request("urlkey"))
	
	if Len(url_key) > 1 then
		url_key = Replace(url_key, "/", "")
		
		sql = "SELECT * FROM " & g_storeid & "_rewrite WHERE rewrite_request_path='" & url_key & "'"
		set rsRewrite = dbconn.Execute(sql)
		if not rsRewrite.EOF then
			rewrite_type = rsRewrite("rewrite_type")
			rewrite_system_type = rsRewrite("rewrite_system_type")
			rewrite_system_id = rsRewrite("rewrite_system_id")
			rewrite_redirect_type = rsRewrite("rewrite_redirect_type")
		else
			rewrite_type = 0
			rewrite_system_type = 0
			rewrite_system_id = ""
			rewrite_redirect_type = ""
		end if
		
		if rewrite_system_type = 1 AND Len(rewrite_system_id) > 1 then
			sType = "dept"
		end if
		
		dept_ID = rewrite_system_id
	end if
	
	'=================================================================================================
	
	'=================================================================================================
	' GET DEPT INFO
	'=================================================================================================
	
	sql = "SELECT * FROM " & g_storeid & "_dept WHERE dept_id='" & dept_ID & "'"
    Set rsDeptName = dbconn.Execute(sql)

    if not rsDeptName.EOF then
	    dept_name = Trim(rsDeptName("dept_name"))
	    parent_dept = rsDeptName("parent_dept")
	    dept_list_view = rsDeptName("dept_list_view")
	    dept_list_num = rsDeptName("dept_list_num")
	
	    if Len(Request("sort_order")) > 0 then
		    dept_sort_order = Request("sort_order")
	    else
		    dept_sort_order = CStr(rsDeptName("dept_sort_order"))
	    end if
	
	    dept_show_mfg = rsDeptName("dept_show_mfg")
	    dept_markup = rsDeptName("markup_" & Session("LOGINGROUP"))
	    dept_use_markup = rsDeptName("use_markup")
	    dept_detail = rsDeptName("dept_detail")
	    dept_title_name = rsDeptName("dept_title_name")
		
		icecat_category = rsDeptName("icecat_category")
		dept_url_key = rsDeptName("url_key")
		
	    cont_ok = true
    else
	    cont_ok = false
    end if

    rsDeptName.Close
	
	Set conn_ss = Server.CreateObject("ADODB.Connection")
	conn_ss.open g_connection_icecat_main

	Set conn_ss1 = Server.CreateObject("ADODB.Connection")
	conn_ss1.open g_connection_icecat_catalog
	
	if Len(sub_id) > 0 then
		icecat_category = sub_id
		catsql = "SELECT value FROM A_ICECAT_Category_Name WHERE EntityId=" & icecat_category
		set rscat = conn_ss1.Execute(catsql)
		if not rscat.EOF then
			g_dept_name = rscat(0)
		end if
		rscat.Close
		set rscat = nothing
	end if
	
	if cont_ok then
	
		if Len(icecat_category) > 0 then
			'==============================================================================
			' start of icecat catalog
			'==============================================================================
			sql = "SELECT * FROM " & g_storeid & "_profile"
			Set rsProfile = dbconn.Execute(sql)
			if (not rsProfile.EOF) then
				espec_part_number_mode = rsProfile("espec_part_number_mode")
			end if
			rsProfile.Close
			
			sPage = Trim(Request("page"))
			if Len(sPage) > 0then
			  if IsNumeric(sPage) then
				  page = CInt(Request("page"))
				  if page > 0 then
				  else
					page = 1
				  end if
				else
				  page = 1
				end if
			else
				page =1
			end if
			
			prod_listview = request("prod_listview")
			if prod_listview = "" then
				prod_listview = Session("PROD_LISTVIEW")
				if prod_listview = "" then
					prod_listview = "14"
				end if
			end if
			
			select case prod_listview
			case "0"
				str_sort = " ORDER BY DESCR"
				Session("PROD_LISTVIEW") = "0"
			case "1"
				str_sort = " ORDER BY DESCR DESC"
				Session("PROD_LISTVIEW") = "1"
			case "2"
				str_sort = " ORDER BY VEND_PART"
				Session("PROD_LISTVIEW") = "2"
			case "3"
				str_sort = " ORDER BY VEND_PART DESC"
				Session("PROD_LISTVIEW") = "3"
			case "4"
				str_sort = " ORDER BY VEND_NAME"
				Session("PROD_LISTVIEW") = "4"
			case "5"
				str_sort = " ORDER BY VEND_NAME DESC"
				Session("PROD_LISTVIEW") = "5"
			case "6"
				str_sort = " ORDER BY IM_ID"
				Session("PROD_LISTVIEW") = "6"
			case "7"
				str_sort = " ORDER BY IM_ID DESC"
				Session("PROD_LISTVIEW") = "7"
			case "8"
				str_sort = " ORDER BY TD_ID"
				Session("PROD_LISTVIEW") = "8"
			case "9"
				str_sort = " ORDER BY TD_ID DESC"
				ession("PROD_LISTVIEW") = "9"
			case "10"
				str_sort = " ORDER BY IM_COST"
				Session("PROD_LISTVIEW") = "10"
			case "11"
				str_sort = " ORDER BY IM_COST DESC"
				Session("PROD_LISTVIEW") = "11"
			case "12"
				str_sort = " ORDER BY TD_COST"
				Session("PROD_LISTVIEW") = "12"
			case "13"
				str_sort = " ORDER BY TD_COST DESC"
				Session("PROD_LISTVIEW") = "13"
			case "14"
				str_sort = " ORDER BY price_" & Session("LOGINGROUP") & ""
				Session("PROD_LISTVIEW") = "14"
			case "15"
				str_sort = " ORDER BY price_" & Session("LOGINGROUP") & " DESC"
				Session("PROD_LISTVIEW") = "15"
			case else
				str_sort = " ORDER BY price_" & Session("LOGINGROUP") & ""
				Session("PROD_LISTVIEW") = "14"
				prod_listview = "14"
			end select
			
			'=========================================================================
			if InStr(Session("SSCatalogConnectionString"), "SPECSOURCE2") > 0 then
				specsource_db = "SPECSOURCE2"
			else
				specsource_db = "SPECSOURCE"
			end if
			'=========================================================================
			x_manufacturer = Trim(Request("manufacturer"))
			x_manufacturer = FilterStringEx(x_manufacturer, "[^0-9]")
			if Len(x_manufacturer) > 0 then
				sql = "SELECT name FROM manufacturer WHERE manufacturerid=" & x_manufacturer
				set rs = conn_ss.Execute(sql)
				if not rs.EOF then
					xg_manufacturer = Trim(rs(0))
				end if
				rs.close
			end if
			manufacturer = Trim(Request("manufacturer"))
			manufacturer = FilterStringEx(manufacturer, "[^0-9]")
			
			'==============================================================================
			'NEW FEATUREID
			s_selectedFeatureIds = ""
			for each item in Request.QueryString
				If InStr(item, "ga_") Then
					If Len(Trim(Request(item))) > 0 then
						s_selectedFeatureIds = s_selectedFeatureIds & Replace(item, "ga_" , "") & ","
					End if
				End if
			Next
			'==============================================================================
			If Len(s_selectedFeatureIds) > 0 Then
				t_selectedFeatureIds = s_selectedFeatureIds
				s_selectedFeatureIds = Left(s_selectedFeatureIds, Len(s_selectedFeatureIds) - 1)
			End If
			
			range_min_price = Trim(Request("min"))
			range_max_price = Trim(Request("max"))

			If useAnchorCategory = 1 Then
				sql = "SELECT specsource_categoryid FROM " & g_storeid & "_ss_dept WHERE dept_id like '" & dept_id & "%'"
				set rsDept=dbconn.Execute(sql)
				ss_categoryid = ""
				Do While Not rsDept.EOF
					ss_categoryid = ss_categoryid & Trim(rsDept(0)) & ","
					rsDept.MoveNext
				Loop
				rsDept.Close
				If Len(ss_categoryid) > 1 Then
					ss_categoryid = Left(ss_categoryid, Len(ss_categoryid)-1)
				End If
			else
				sql = "SELECT specsource_categoryid FROM " & g_storeid & "_ss_dept WHERE dept_id='" & dept_id & "'"
				set rsDept=dbconn.Execute(sql)
				if not rsDept.EOF then
					ss_categoryid = Trim(rsDept(0))
				end if
				rsDept.Close
			End if
			
			'=======================================
			' Filter Strings...
			'=======================================
			asql = ""
			s_filter_url = ""
			If s_selectedFeatureIds <> "" Then 
				ga = Split(s_selectedFeatureIds, ",")
				for i=0 to UBound(ga)
					zsql = zsql & " icecat_id IN (SELECT productid FROM [192.168.5.134].[icecat].[dbo].[icecat_productattributes] WHERE featureid=" & ga(i) & " AND displayvalue='" & Trim(request("ga_" & ga(i))) & "' ) AND"
					s_filter_url = s_filter_url & "&ga_" & ga(i) & "=" & Trim(request("ga_" & ga(i)))
				Next
			End If
			
			'=======================================
			' Price range..
			'=======================================
			s_prcn= ""
			SELECT CASE prcn
			CASE "0"
				s_prcn = "(price_" & Session("LOGINGROUP") & " BETWEEN 0 AND 99.99)"
			CASE "1"
				s_prcn = "(price_" & Session("LOGINGROUP") & " BETWEEN 100 AND 499.99)"
			CASE "2"
				s_prcn = "(price_" & Session("LOGINGROUP") & " BETWEEN 500 AND 999.99)"
			CASE "3"
				s_prcn = "(price_" & Session("LOGINGROUP") & " BETWEEN 1000 AND 1999.99)"
			CASE "4"
				s_prcn = "(price_" & Session("LOGINGROUP") & " BETWEEN 2000 AND 100000)"
			END Select
			
			If IsNumeric(range_min_price) AND Len(range_min_price) > 0 AND IsNumeric(range_max_price)  AND Len(range_max_price) > 0 Then
				s_prcn = "(price_" & Session("LOGINGROUP") & " BETWEEN " & range_min_price & " AND " & range_max_price & ")"
				s_filter_url = s_filter_url & "&min=" & range_min_price & "&max=" & range_max_price
			End If

			If Len(manufacturer) > 0 then
				s_filter_url = s_filter_url & "&manufacturer=" & manufacturer
			End if

			if Len(zsql) > 0 then
				zsql = Left(zsql, Len(zsql)-4)
				filter_zsql = zsql
			end If

			zzsql = "SELECT sku FROM SPEC_PRICE.dbo." & g_storeid & "_ssprice WHERE hide_flag=0"
			if Len(x_manufacturer) > 0 then
				zzsql = zzsql & " AND VEND_ID=" & x_manufacturer
			end if
			
			bShowIcecatFilter = true
			catsql = "SELECT subs, ParentId FROM A_ICECAT_Category WHERE Id=" & icecat_category
			set rscat = conn_ss1.Execute(catsql)
			if not rscat.EOF then
				cat_subs = Trim(rscat(0))
				if rscat(1) = 2833 then
					bShowIcecatFilter = false
				end if
			end if
			rscat.close
			set rscat = nothing
			
			if Len(cat_subs) > 0 then
				ss_categoryid = icecat_category & "," & cat_subs
			else
				ss_categoryid = icecat_category
			end if
			
			sql = "SELECT * FROM " & g_storeid & "_ssprice WHERE catid IN (" & ss_categoryid & ") AND DESCR <> '' AND hide_flag=0"
			if Len(zsql) > 0 then
				sql = sql & " AND " & zsql
			end if
			if Len(x_manufacturer) > 0 then
				sql = sql & " AND VEND_ID=" & x_manufacturer
			end if
			if Len(s_prcn) > 0 then
				sql = sql & " AND " & s_prcn
			end if
			if Session("PROD_AVAIL") = "4" then
				sql = sql & " AND AVAIL=1"
			end if
			
			'================================================================
			' Improved sorting algorithm
			'=================================================================
			dept_list_num = "20"
			Select case show

			case "10"

			case "20"

			case "50"

			case "100"

			case "200"

			case else
				show = dept_list_num
			end Select

			Select case so

			case "0"
				str_sort = " ORDER BY DESCR"
			case "1"
				str_sort = " ORDER BY DESCR DESC"
			case "4"
				str_sort = " ORDER BY manu_name, DESCR"
			case "5"
				str_sort = " ORDER BY manu_name DESC, DESCR"
			case "6"
				str_sort = " ORDER BY sku"
			case "7"
				str_sort = " ORDER BY sku DESC"
			case "8"
				str_sort = " ORDER BY price_" &  Session("LOGINGROUP")
			case "9"
				str_sort = " ORDER BY price_" &  Session("LOGINGROUP") & " DESC"
			case else
				str_sort = " ORDER BY price_" &  Session("LOGINGROUP")
				so = "8"
			end Select

			page_size = show
			block_size = 5
			
			Set rsDept = Server.CreateObject("ADODB.RecordSet")
			rsDept.CursorLocation = 3
			rsDept.Open sql,Session("SSPriceConnectionString"),3,3
					
			if not rsDept.EOF then
				rsDept.Sort = Replace(str_sort, " ORDER BY ", "")
				rsDept.PageSize = page_size
				rsDept.AbsolutePage = page

				page_count = rsDept.PageCount
				num_total_product = rsDept.RecordCount
			end if

			start_num = (page-1)*page_size + 1
			end_num = start_num + page_size-1

			if end_num > num_total_product then
				end_num = num_total_product
			end if
			
			if Len(zsql) > 0 OR Len(x_manufacturer) > 0 OR Len(s_prcn) > 0 then
				bPageMode = 0
			else
				bPageMode = 1
			end if
			
			bPageMode = 0
			
			'========================================================================================
			' GET TOOLBAR VALUES
			if Len(dept_url_key) > 0 then
				If Len(s_filter_url) > 0 then
					strToolbarBaseURL = g_store_url & dept_url_key & ".html?" & s_filter_url
				Else
					strToolbarBaseURL = g_store_url & dept_url_key & ".html?" 
				End if
			else
				If Len(s_filter_url) > 0 then
					strToolbarBaseURL = g_store_url & "dept.phtml?dept_id=" & dept_id & s_filter_url
				Else
					strToolbarBaseURL = g_store_url & "dept.phtml?dept_id=" & dept_id 
				End if
			end if

			strSortURL_10 = strToolbarBaseURL & "&mode=" & mode & "&so=" & so & "&show=10"
			strSortURL_20 = strToolbarBaseURL & "&mode=" & mode & "&so=" & so & "&show=20"
			strSortURL_50 = strToolbarBaseURL & "&mode=" & mode & "&so=" & so & "&show=50"
			strSortURL_100 = strToolbarBaseURL & "&mode=" & mode & "&so=" & so & "&show=100"
			strSortURL_200 = strToolbarBaseURL & "&mode=" & mode & "&so=" & so & "&show=200"

			strSortURL_Name = strToolbarBaseURL & "&mode=" & mode & "&so=0&show=" & show
			strSortURL_PartNumber = strToolbarBaseURL & "&mode=" & mode & "&so=6&show=" & show
			strSortURL_Price = strToolbarBaseURL & "&mode=" & mode & "&so=8&show=" & show

			Select case so
				
			case "0"
				strSortURL_asc = strToolbarBaseURL & "&mode=" & mode & "&so=0&show=" & show
				strSortURL_desc = strToolbarBaseURL & "&mode=" & mode & "&so=1&show=" & show  	
			case "1"
				strSortURL_asc = strToolbarBaseURL & "&mode=" & mode & "&so=0&show=" & show
				strSortURL_desc = strToolbarBaseURL & "&mode=" & mode & "&so=1&show=" & show  	
			case "4"
				strSortURL_asc = strToolbarBaseURL & "&mode=" & mode & "&so=4&show=" & show
				strSortURL_desc = strToolbarBaseURL & "&mode=" & mode & "&so=5&show=" & show  	
			case "5"
				strSortURL_asc = strToolbarBaseURL & "&mode=" & mode & "&so=4&show=" & show
				strSortURL_desc = strToolbarBaseURL & "&mode=" & mode & "&so=5&show=" & show  	
			case "6"
				strSortURL_asc = strToolbarBaseURL & "&mode=" & mode & "&so=6&show=" & show
				strSortURL_desc = strToolbarBaseURL & "&mode=" & mode & "&so=7&show=" & show
			case "7"
				strSortURL_asc = strToolbarBaseURL & "&mode=" & mode & "&so=6&show=" & show
				strSortURL_desc = strToolbarBaseURL & "&mode=" & mode & "&so=7&show=" & show
			case "8"
				strSortURL_asc = strToolbarBaseURL & "&mode=" & mode & "&so=8&show=" & show
				strSortURL_desc = strToolbarBaseURL & "&mode=" & mode & "&so=9&show=" & show
			case "9"
				strSortURL_asc = strToolbarBaseURL & "&mode=" & mode & "&so=8&show=" & show
				strSortURL_desc = strToolbarBaseURL & "&mode=" & mode & "&so=9&show=" & show
			case else
				
			end Select

			strPageURL = strToolbarBaseURL & "&mode=" & mode & "&so=" & so & "&show=" & show
			strModeURL = strToolbarBaseURL & "&so=" & so & "&show=" & show
			'==============================================================================
			' end of icecat catalog
			'==============================================================================
		else
			'==============================================================================
			' start of private catalog
			'==============================================================================
			'==============================================================================
			' START OF FILTER
			'==============================================================================
			manufacturer = Trim(Request("manufacturer"))
			manufacturer = FilterStringEx(manufacturer, "[^0-9]")
			'===============================================================================
			'NEW FEATUREID
			s_selectedFeatureIds = ""
			for each item in Request.QueryString
				If InStr(item, "ga_") Then
					If Len(Trim(Request(item))) > 0 then
						s_selectedFeatureIds = s_selectedFeatureIds & "'" & Replace(item, "ga_" , "") & "',"
					End if
				End if
			Next
			'===============================================================================

			If Len(s_selectedFeatureIds) > 0 Then
				t_selectedFeatureIds = s_selectedFeatureIds
				s_selectedFeatureIds = Left(s_selectedFeatureIds, Len(s_selectedFeatureIds) - 1)
			End If
			
			range_min_price = Trim(Request("min"))
			range_max_price = Trim(Request("max"))
			
			asql = ""
			zsql = ""
			s_filter_url = ""

			If s_selectedFeatureIds <> "" Then 
				ga = Split(s_selectedFeatureIds, ",")
				for i=0 to UBound(ga)
					gx = Replace(ga(i), "'", "")
					zsql = zsql & " pf_id IN (SELECT productid FROM " & g_storeid & "_productattributes WHERE featurename='" & gx & "' AND displayvalue='" & Trim(request("ga_" & gx)) & "' ) AND"
					s_filter_url = s_filter_url & "&ga_" & gx & "=" & Trim(request("ga_" & gx))
				Next
			End If

			If IsNumeric(range_min_price) AND Len(range_min_price) > 0 AND IsNumeric(range_max_price)  AND Len(range_max_price) > 0 Then
				s_prcn = "(price_" & Session("LOGINGROUP") & " BETWEEN " & range_min_price & " AND " & range_max_price & ")"
				s_filter_url = s_filter_url & "&min=" & range_min_price & "&max=" & range_max_price
			End If

			If Len(manufacturer) > 0 then
				s_filter_url = s_filter_url & "&manufacturer=" & manufacturer
			End If
			
			if Len(zsql) > 0 then
				zsql = Left(zsql, Len(zsql)-4)
				filter_zsql = zsql
			end If
			
			'======================================================================================
			' END OF FILTER
			'======================================================================================
			
			if cont_ok then
				str_parent_dept = ""
				str_parent_dept = GetParentCategoryLink(g_connection_string,dept_ID)
				if (dept_use_markup) then
					current_markup = dept_markup
				else
					current_markup = CDbl(Session("PriMarkup_"& Session("LOGINGROUP")))
				
					dept_level = Len(Trim(dept_ID))
				
					Select case dept_level
					
					case 2
						'Do nothing.. use global markup...
					case 6
						sql = "SELECT markup_" & Session("LOGINGROUP") & " FROM :9_dept WHERE dept_id IN ('" & Left(dept_ID, 2) & "','" & dept_ID & "') AND use_markup=1 ORDER BY dept_id DESC"
						sql = replace(sql, ":9", g_storeid)
						Set rsDeptMarkup = dbconn.Execute(sql)
					
						if rsDeptMarkup.EOF then
							'Do nothing...
						else
							current_markup = rsDeptMarkup(0)
						end if
					
						rsDeptMarkup.Close
					case 10
					
						sql = "SELECT markup_" & Session("LOGINGROUP") & " FROM :9_dept WHERE dept_id IN ('" & Left(dept_ID, 2) & "','" & Left(dept_ID,6) & "','" & dept_ID & "') AND use_markup=1 ORDER BY dept_id DESC"
						sql = replace(sql, ":9", g_storeid)
						Set rsDeptMarkup = dbconn.Execute(sql)
					
						if rsDeptMarkup.EOF then
							'Do nothing...
						else
							current_markup = rsDeptMarkup(0)
						end if
					
						rsDeptMarkup.Close
					
					End Select
				
				end if
			
				'Get price rule dept...
				dept_pricerule = "0"
				if GetCategoryPriceRule(g_connection_string, dept_ID, dept_pricerule, "000") then
					b_use_pricerule = true
				else
					b_use_pricerule = false
				end if
			
				if so = "" then
					so = dept_sort_order
				end if
			
				Select case so
				
				case "0"
					str_sort = " ORDER BY name"
					sort_description = "Description <font face=webdings>6</font>"
				case "1"
					str_sort = " ORDER BY name DESC"
					sort_description = "Description <font face=webdings>5</font>"
				case "4"
					str_sort = " ORDER BY vendor_name, name"
					sort_description = "Manufacturer <font face=webdings>6</font>"
				case "5"
					str_sort = " ORDER BY vendor_name DESC, name"
					sort_description = "Manufacturer <font face=webdings>5</font>"
				case "6"
					str_sort = " ORDER BY SKU"
					sort_description = "Part Number <font face=webdings>6</font>"
				case "7"
					str_sort = " ORDER BY SKU DESC"
					sort_description = "Part Number <font face=webdings>5</font>"
				case "8"
					str_sort = " ORDER BY price_" &  Session("LOGINGROUP")
					sort_description = "Price <font face=webdings>6</font>"
				case "9"
					str_sort = " ORDER BY price_" &  Session("LOGINGROUP") & " DESC"
					sort_description = "Price <font face=webdings>5</font>"
				case else
					str_sort = " ORDER BY name"
					sort_description = "Description <font face=webdings>6</font>"
					so = "0"
				end Select

				Select case show
				
				case "3"
					
				case "5"
					
				case "10"
					
				case "15"
					
				case "20"
					
				case else
					show = dept_list_num
				end Select
			
				strSQL = "SELECT " & g_storeid & "_product.* FROM " & g_storeid & "_product WHERE pf_id IN(SELECT pf_id FROM " & g_storeid & "_dept_prod WHERE dept_id like '" & dept_ID & "%')"
			
				if Len(Session("CUSTOM_CATALOG_ID_FLAG")) > 0 then
					strSQL = strSQL & " AND CC" & Session("CUSTOM_CATALOG_ID_FLAG") & "_FLAG=1"
				end If

				if Len(zsql) > 0 then
					strSQL = strSQL & " AND " & zsql
						
				end if
			
				if Len(manufacturer) > 0 then
					strSQL = strSQL & " AND vendor_number='" & manufacturer & "'"
				end If

				if Len(s_prcn) > 0 then
					strSQL = strSQL & " AND " & s_prcn
				end if
					
				strSQL = strSQL & str_sort
			
				Set rsDept = Server.CreateObject("ADODB.RecordSet")
				rsDept.Open strSQL, g_connection_string, 1, 1
			
				page = FilterStringEx(Request("page"), "[^0-9]")
				
				if Len(page) > 0 then
					page = CInt(page)
				else
					page =1
				end if
			
				page_size = 10
				block_size = 5
			
				if not rsDept.EOF then
					rsDept.PageSize = show
					page_size = show
					page_count = rsDept.PageCount
					list_count = rsDept.RecordCount
					rsDept.AbsolutePage = page
					RowCount = 0
					i_start = page_size * (page-1) + 1
					i_last = page_size * page
				
					if i_last > list_count then
						i_last = list_count
					end if
				else
					list_count = 0
					i_start = 0
					i_last = 0
				end if
			
			end if 'cont_ok...

			If Len(dept_title_name) > 0 Then
				dept_page_title = stripHTML(dept_title_name)
			Else
				if Session("ENABLE_SEO") = 1 then
					dept_page_title = stripHTML(dept_name) & " - " & Session("StoreFullName")
				else
					dept_page_title = Session("StoreTitle") & " - Product List"
				end if
			End If

			'========================================================================================
			' GET TOOLBAR VALUES

			strSortURL_10 = Session("StoreURL") & "/dept.phtml?dept_id=" & dept_id & "&mode=" & mode & "&so=" & so & "&show=10"
			strSortURL_20 = Session("StoreURL") & "/dept.phtml?dept_id=" & dept_id & "&mode=" & mode & "&so=" & so & "&show=20"
			strSortURL_40 = Session("StoreURL") & "/dept.phtml?dept_id=" & dept_id & "&mode=" & mode & "&so=" & so & "&show=40"
			strSortURL_60 = Session("StoreURL") & "/dept.phtml?dept_id=" & dept_id & "&mode=" & mode & "&so=" & so & "&show=60"
			strSortURL_80 = Session("StoreURL") & "/dept.phtml?dept_id=" & dept_id & "&mode=" & mode & "&so=" & so & "&show=80"

			strSortURL_Name = Session("StoreURL") & "/dept.phtml?dept_id=" & dept_id & "&mode=" & mode & "&so=0&show=" & show
			strSortURL_Name_desc = Session("StoreURL") & "/dept.phtml?dept_id=" & dept_id & "&mode=" & mode & "&so=1&show=" & show
			strSortURL_PartNumber = Session("StoreURL") & "/dept.phtml?dept_id=" & dept_id & "&mode=" & mode & "&so=6&show=" & show
			strSortURL_PartNumber_desc= Session("StoreURL") & "/dept.phtml?dept_id=" & dept_id & "&mode=" & mode & "&so=7&show=" & show
			strSortURL_Price = Session("StoreURL") & "/dept.phtml?dept_id=" & dept_id & "&mode=" & mode & "&so=8&show=" & show
			strSortURL_Price_desc = Session("StoreURL") & "/dept.phtml?dept_id=" & dept_id & "&mode=" & mode & "&so=9&show=" & show

			Select case so
				
			case "0"
				strSortURL_asc = Session("StoreURL") & "/dept.phtml?dept_id=" & dept_id & "&mode=" & mode & "&so=0&show=" & show
				strSortURL_desc = Session("StoreURL") & "/dept.phtml?dept_id=" & dept_id & "&mode=" & mode & "&so=1&show=" & show  	
			case "1"
				strSortURL_asc = Session("StoreURL") & "/dept.phtml?dept_id=" & dept_id & "&mode=" & mode & "&so=0&show=" & show
				strSortURL_desc = Session("StoreURL") & "/dept.phtml?dept_id=" & dept_id & "&mode=" & mode & "&so=1&show=" & show  	
			case "4"
				strSortURL_asc = Session("StoreURL") & "/dept.phtml?dept_id=" & dept_id & "&mode=" & mode & "&so=4&show=" & show
				strSortURL_desc = Session("StoreURL") & "/dept.phtml?dept_id=" & dept_id & "&mode=" & mode & "&so=5&show=" & show  	
			case "5"
				strSortURL_asc = Session("StoreURL") & "/dept.phtml?dept_id=" & dept_id & "&mode=" & mode & "&so=4&show=" & show
				strSortURL_desc = Session("StoreURL") & "/dept.phtml?dept_id=" & dept_id & "&mode=" & mode & "&so=5&show=" & show  	
			case "6"
				strSortURL_asc = Session("StoreURL") & "/dept.phtml?dept_id=" & dept_id & "&mode=" & mode & "&so=6&show=" & show
				strSortURL_desc = Session("StoreURL") & "/dept.phtml?dept_id=" & dept_id & "&mode=" & mode & "&so=7&show=" & show
			case "7"
				strSortURL_asc = Session("StoreURL") & "/dept.phtml?dept_id=" & dept_id & "&mode=" & mode & "&so=6&show=" & show
				strSortURL_desc = Session("StoreURL") & "/dept.phtml?dept_id=" & dept_id & "&mode=" & mode & "&so=7&show=" & show
			case "8"
				strSortURL_asc = Session("StoreURL") & "/dept.phtml?dept_id=" & dept_id & "&mode=" & mode & "&so=8&show=" & show
				strSortURL_desc = Session("StoreURL") & "/dept.phtml?dept_id=" & dept_id & "&mode=" & mode & "&so=9&show=" & show
			case "9"
				strSortURL_asc = Session("StoreURL") & "/dept.phtml?dept_id=" & dept_id & "&mode=" & mode & "&so=8&show=" & show
				strSortURL_desc = Session("StoreURL") & "/dept.phtml?dept_id=" & dept_id & "&mode=" & mode & "&so=9&show=" & show
			case else
				
			end Select

			strPageURL = Session("StoreURL") & "/dept.phtml?dept_id=" & dept_id & "&mode=" & mode & "&so=" & so & "&show=" & show

			strModeURL = Session("StoreURL") & "/dept.phtml?dept_id=" & dept_id & "&so=" & so & "&show=" & show


			'==========================================================================================

			If Len(Session("shopper_id")) > 0 Then
				sql = "SELECT apple_authorized FROM " & g_storeid & "_shopper WHERE shopper_id='" & Session("shopper_id") & "'"
				Set rsAuthorized = dbconn.Execute(sql)
				If Not rsAuthorized.EOF Then
					apple_authorized = rsAuthorized(0)
				Else
					apple_authorized = 0
				End If
				rsAuthorized.Close
			Else
				apple_authorized = 0
			End If
			
			g_page_title = dept_page_title
			
			'==============================================================================
			' end of private catalog
			'==============================================================================
		
		end if 'icecat
		
	end if 'cont_ok
	
	'==============================================================================
	' DISPLAY VALUES
	'==============================================================================
	g_page_title = dept_page_title
	g_dept_name = dept_name
	g_dept_id = dept_id
	
	g_dept_name = TranslateX(g_dept_name, 1, g_dept_id, 1)
	'==============================================================================
	
%>