<!--#INCLUDE FILE="../../local/local.phtml"-->
<!--#INCLUDE FILE="../i_adoopen.phtml"-->
<!--#INCLUDE FILE="../../language_pack.phtml"-->
<!--#INCLUDE FILE="../../util/xt_func_session.phtml"-->
<!--#INCLUDE File="../../util/xt_func_util.phtml" -->
<!--#INCLUDE FILE="../../util/xt_func_string.phtml"-->
<!--#INCLUDE FILE="../../util/xt_func_seo.phtml"-->
<!--#INCLUDE FILE="../../util/xt_func_shoppingcart.phtml"-->
<!--#INCLUDE FILE="../../i_initsession.phtml"-->
<!--#INCLUDE FILE="../i_login.phtml"-->
<%
	dept_ID = Trim(Request("dept_id"))
	dept_ID = FilterSKUString(dept_ID)
	
	sql = "SELECT dept_name FROM " & g_storeid & "_system_dept WHERE dept_id='" & dept_ID & "'"
	Set rsDeptName = dbconn.Execute(sql)
							
	if not rsDeptName.EOF then
	  dept_name = rsDeptName("dept_name")
	  dept_ok = true
	else
	  dept_name = ""
	  dept_ok = false
	end if
	rsDeptName.Close
	
	if(Session("LOGINGROUP") = "")then
		member_group = "D"
	else
		member_group = Session("LOGINGROUP")
	end if
%>