<div id="footer">
	<%
		g_static_block_code = "TPL_JOURNAL4_FOOTER_1"
	%>
	<!--#INCLUDE FILE="../../../core/cms/include_show_static_block.phtml"-->
	
	<%
		g_static_block_code = "TPL_JOURNAL4_FOOTER_2"
	%>
	<!--#INCLUDE FILE="../../../core/cms/include_show_static_block.phtml"-->
	
</div>
<%
	g_static_block_code = "TPL_JOURNAL4_FOOTER_BAR"
%>
<!--#INCLUDE FILE="../../../core/cms/include_show_static_block.phtml"-->
	
