<meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no">
<meta name="format-detection" content="telephone=no">
<!--[if IE]><meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"/><![endif]-->
<title>Natural Hair Extensions : Human Hair Wigs : Kinky Twist : Weaving Supplies : Indian Remy Hair : Real Hair Extensions : HisandHer.com</title>
<base href="<%=skin_base_url%>"/>
<meta name="description" content="Find the best prices and variety of natural hair extensions, human hair wigs, kinky twist, weaving supplies, Indian Remi hair, real hair extensions and clip in hair extensions at Hisandher.com." />
<meta name="keywords" content="" />
<base href="<%=skin_base_url%>" />
<link rel="icon" href="http://www.hisandher.com/media/favicon/default/Untitled-1_1.png" type="image/x-icon" />
<link rel="shortcut icon" href="http://www.hisandher.com/media/favicon/default/Untitled-1_1.png" type="image/x-icon" />
<link rel="stylesheet" href="//fonts.googleapis.com/css?family=Playfair+Display:regular,700,italic%7CAbril+Fatface:regular%7CRoboto+Slab:regular&amp;subset=latin"/>
<link rel="stylesheet" href="<%=skin_base_url%>theme/<%=THEME_TEMPLATE%>/css/j-strap.css"/>
<link rel="stylesheet" href="<%=skin_base_url%>theme/<%=THEME_TEMPLATE%>/javascript/font-awesome/css/font-awesome.min.css"/>
<link rel="stylesheet" href="<%=skin_base_url%>theme/<%=THEME_TEMPLATE%>/lib/jquery.ui/jquery-ui-slider.min.css"/>
<link rel="stylesheet" href="<%=skin_base_url%>theme/<%=THEME_TEMPLATE%>/lib/owl-carousel/owl.carousel.css"/>
<link rel="stylesheet" href="<%=skin_base_url%>theme/<%=THEME_TEMPLATE%>/lib/owl-carousel/owl.transitions.css"/>
<link rel="stylesheet" href="<%=skin_base_url%>theme/<%=THEME_TEMPLATE%>/lib/magnific-popup/magnific-popup.css"/>
<link rel="stylesheet" href="<%=skin_base_url%>theme/<%=THEME_TEMPLATE%>/css/hint.min.css"/>
<link rel="stylesheet" href="<%=skin_base_url%>theme/<%=THEME_TEMPLATE%>/css/journal.css"/>
<link rel="stylesheet" href="<%=skin_base_url%>theme/<%=THEME_TEMPLATE%>/css/features.css"/>
<link rel="stylesheet" href="<%=skin_base_url%>theme/<%=THEME_TEMPLATE%>/css/header.css"/>
<link rel="stylesheet" href="<%=skin_base_url%>theme/<%=THEME_TEMPLATE%>/css/module.css"/>
<link rel="stylesheet" href="<%=skin_base_url%>theme/<%=THEME_TEMPLATE%>/css/pages.css"/>
<link rel="stylesheet" href="<%=skin_base_url%>theme/<%=THEME_TEMPLATE%>/css/account.css"/>
<link rel="stylesheet" href="<%=skin_base_url%>theme/<%=THEME_TEMPLATE%>/css/blog-manager.css"/>
<link rel="stylesheet" href="<%=skin_base_url%>theme/<%=THEME_TEMPLATE%>/css/side-column.css"/>
<link rel="stylesheet" href="<%=skin_base_url%>theme/<%=THEME_TEMPLATE%>/css/product.css"/>
<link rel="stylesheet" href="<%=skin_base_url%>theme/<%=THEME_TEMPLATE%>/css/category.css"/>
<link rel="stylesheet" href="<%=skin_base_url%>theme/<%=THEME_TEMPLATE%>/css/footer.css"/>
<link rel="stylesheet" href="<%=skin_base_url%>theme/<%=THEME_TEMPLATE%>/css/icons.css"/>
<link rel="stylesheet" href="<%=skin_base_url%>theme/<%=THEME_TEMPLATE%>/css/responsive.css"/>
<link rel="stylesheet" href="<%=skin_base_url%>theme/<%=THEME_TEMPLATE%>/css/custom.css"/>
<script type="text/javascript" src="<%=skin_base_url%>theme/<%=THEME_TEMPLATE%>/javascript/jquery/jquery-2.1.1.min.js"></script>
<script type="text/javascript" src="<%=skin_base_url%>theme/<%=THEME_TEMPLATE%>/javascript/bootstrap/js/bootstrap.min.js"></script>
<script type="text/javascript" src="<%=skin_base_url%>theme/<%=THEME_TEMPLATE%>/lib/jquery/jquery-migrate-1.2.1.min.js"></script>
<script type="text/javascript" src="<%=skin_base_url%>theme/<%=THEME_TEMPLATE%>/lib/jquery.ui/jquery-ui-slider.min.js"></script>
<script type="text/javascript" src="<%=skin_base_url%>theme/<%=THEME_TEMPLATE%>/javascript/common.js"></script>
<script type="text/javascript" src="<%=skin_base_url%>theme/<%=THEME_TEMPLATE%>/javascript/jquery/jquery.total-storage.min.js"></script>
<script type="text/javascript" src="<%=skin_base_url%>theme/<%=THEME_TEMPLATE%>/lib/jquery.tabs/tabs.js"></script>
<script type="text/javascript" src="<%=skin_base_url%>theme/<%=THEME_TEMPLATE%>/lib/owl-carousel/owl.carousel.js"></script>
<script type="text/javascript" src="<%=skin_base_url%>theme/<%=THEME_TEMPLATE%>/lib/magnific-popup/jquery.magnific-popup.min.js"></script>
<script type="text/javascript" src="<%=skin_base_url%>theme/<%=THEME_TEMPLATE%>/lib/actual/jquery.actual.min.js"></script>
<script type="text/javascript" src="<%=skin_base_url%>theme/<%=THEME_TEMPLATE%>/lib/countdown/jquery.countdown.js"></script>
<script type="text/javascript" src="<%=skin_base_url%>theme/<%=THEME_TEMPLATE%>/lib/image-zoom/jquery.imagezoom.min.js"></script>
<script type="text/javascript" src="<%=skin_base_url%>theme/<%=THEME_TEMPLATE%>/lib/lazy/jquery.lazy.1.6.min.js"></script>
<script type="text/javascript" src="<%=skin_base_url%>theme/<%=THEME_TEMPLATE%>/js/journal.js"></script>