<div id="container" class="container j-container">
	<ul class="breadcrumb">
		<li><a href="<%=g_store_url%>">Home</a></li>
		<li><a href="<%=g_secure_url%>/myaccount.phtml">Account</a></li>
		<li><a href<%=g_secure_url%>login.phtml">Login</a></li>
	</ul>
	<% if Len(error_msg) > 0 then %>
	<div class="alert alert-danger warning"><i class="fa fa-exclamation-circle"></i> <%=error_msg%></div>
	<% end if %>
	<div class="row">
		<div id="content" class="col-sm-12">
			<div class="row login-content">
				<div class="col-sm-6 left">
					<div class="well">
						<h2 class="secondary-title"><%=a("New Customer")%></h2>
						<div class="login-wrap">
							<p>
								<strong><%=a("Register Account")%></strong>
							</p>
							<p>
								<%=a("By creating an account you will be able to shop faster, be up to date on an order's status, and keep track of the orders you have previously made.")%>
							</p>
						</div>
						<hr/>
						<a href="register.phtml" class="btn btn-primary button"><%=a("Continue")%></a>
					</div>
				</div>
				<div class="col-sm-6 right">
					<div class="well">
						<h2 class="secondary-title"><%=a("Registered Customers")%></h2>
						<form action="<%=g_secure_url %>tp_login.phtml" method="post" id="login-form">
							<div class="login-wrap">
								<p>
									<%=a("I am a returning customer")%>
								</p>
								<div class="form-group">
									<label class="control-label" for="input-email"><%=a("E-Mail Address")%></label>
									<input type="text" name="login_email" value="" placeholder="<%=a("E-Mail Address")%>" id="login_email" class="form-control"/>
								</div>
								<div class="form-group">
									<label class="control-label" for="input-password"><%=a("Password")%></label>
									<input type="password" name="login_password" value="" placeholder="<%=a("Password")%>" id="login_password" class="form-control"/>
									<a href="#">Forgotten Password</a>
								</div>
							</div>
							<hr/>
							<input type="hidden" name="agreeterms" value="1">
							<input type="submit" value="Login" class="btn btn-primary button"/>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>