<%


%>
<div id="content" class="col-sm-12">
	<h1 class="title"><%=a("Your order has been received.")%></h1>
	
	 <p><%=Replace(a("Your order # is %s."), "%s", Session("OrderID")) %></p>
	 <p><%=a("You will receive an order confirmation email with details of your order and a link to track its progress.") %></p>
	 
	 <div class="buttons">
		<div class="pull-left">
			<a href="<%=g_store_url%>" class="btn btn-primary"><%=a("Continue Shopping")%></a>
		</div>
		<div class="pull-right">
		</div>
	</div>
	
</div>