<!--#INCLUDE FILE="../../local/local.phtml"-->
<!--#INCLUDE FILE="../i_adoopen.phtml"-->
<!--#INCLUDE FILE="../../util/xt_func_session.phtml"-->
<!--#INCLUDE FILE="../../util/xt_func_string.phtml"-->
<!--#INCLUDE FILE="../../util/xt_func_util.phtml"-->
<!-- #INCLUDE File="../../util/xt_func_rc4.phtml" -->
<!--#INCLUDE FILE="../../util/xt_func_shoppingcart.phtml"-->
<%
	sessionID = Request("sessionID")
	sessionID = FilterSessionString(sessionID)
	if Len(sessionID) > 0 then
		Session("SESSIONKEY") = sessionID
	else
		if Len(Session("SESSIONKEY")) > 0 then
			'session key exist
		else
			'no key information...
			Response.Redirect g_store_url
		end if
	end if
%>
<%
	If InStr(Request.ServerVariables("HTTP_REFERER"), "?") > 0 Then
		sp_http_referer = Split(Request.ServerVariables("HTTP_REFERER"), "?")
		http_referer = sp_http_referer(0)
	Else
		http_referer = Request.ServerVariables("HTTP_REFERER")
	End If
%>
<%
	flag = Trim(Request("flag"))
	op = Trim(Request("op"))
	id = Trim(Request("id"))
	
	SELECT CASE op
	CASE "edit"
	
		if id = "0" then
		
			sql = "SELECT * FROM " & g_storeid & "_shopper WHERE shopper_id='" & Session("shopper_id") & "'"
			Set rsShopper = dbconn.Execute(sql)
			if not rsShopper.EOF then
				
				shopper_FirstName = rsShopper("FirstName")
				shopper_LastName = rsShopper("LastName")
				shopper_Email = rsShopper("Email")
				shopper_billing_company = rsShopper("Company")
				shopper_billing_firstname = rsShopper("billing_firstname")
				shopper_billing_lastname = rsShopper("billing_lastname")
				shopper_billing_address = rsShopper("Address")
				shopper_billing_city = rsShopper("City")
				shopper_billing_state = rsShopper("State")
				shopper_billing_zip = rsShopper("ZipCode")
				shopper_billing_country = rsShopper("Country")
				shopper_billing_phone = rsShopper("Phone")
			else
				
			end if
			
		else
			
			sql = "SELECT * FROM " & g_storeid & "_shopper_billing_address WHERE billing_shopper_id = '" & Session("shopper_id") & "' AND billing_address_id = '" & id & "'"
			set rs = dbconn.Execute(sql)
			if not rs.EOF then
				alt_address_id = rs("billing_address_id")
				alt_shopper_id = rs("billing_shopper_id")
				alt_address_name = rs("billing_address_name")
				alt_firstname = rs("billing_firstname")
				alt_lastname = rs("billing_lastname")
				alt_address = rs("billing_address")
				alt_city = rs("billing_city")
				alt_state = rs("billing_state")
				alt_zip = rs("billing_zip")
				alt_country= rs("billing_country")
				alt_phone = rs("billing_phone")
				alt_set_default = rs("billing_set_default")
				
				shopper_billing_company = ""
				shopper_billing_firstname = alt_firstname
				shopper_billing_lastname = alt_lastname
				shopper_billing_address = alt_address
				shopper_billing_city = alt_city
				shopper_billing_state = alt_state
				shopper_billing_zip = alt_zip
				shopper_billing_country = alt_country
				shopper_billing_phone = alt_phone
			else
			end if
			
		end if
	
	END SELECT
	
%>