<!--#INCLUDE FILE="../../local/local.phtml"-->
<!--#INCLUDE FILE="../i_adoopen.phtml"-->
<!--#INCLUDE FILE="../../util/xt_func_session.phtml"-->
<!--#INCLUDE FILE="../../util/xt_func_string.phtml"-->
<!--#INCLUDE FILE="../../util/xt_func_util.phtml"-->
<!-- #INCLUDE File="../../util/xt_func_rc4.phtml" -->
<!--#INCLUDE FILE="../../util/xt_func_shoppingcart.phtml"-->
<%
	sessionID = Request("sessionID")
	sessionID = FilterSessionString(sessionID)
	if Len(sessionID) > 0 then
		Session("SESSIONKEY") = sessionID
	else
		if Len(Session("SESSIONKEY")) > 0 then
			'session key exist
		else
			'no key information...
			Response.Redirect g_store_url
		end if
	end if
%>
<!--#INCLUDE FILE="../i_login.phtml"-->
<%
	If InStr(Request.ServerVariables("HTTP_REFERER"), "?") > 0 Then
		sp_http_referer = Split(Request.ServerVariables("HTTP_REFERER"), "?")
		http_referer = sp_http_referer(0)
	Else
		http_referer = Request.ServerVariables("HTTP_REFERER")
	End If
%>
<%
	flag = Trim(Request("flag"))
	op = Trim(Request("op"))
	id = Trim(Request("id"))
	
	SELECT CASE op
	CASE "edit"
	
		if id = "0" then
		
			sql = "SELECT * FROM " & g_storeid & "_shopper WHERE shopper_id='" & Session("shopper_id") & "'"
			Set rsShopper = dbconn.Execute(sql)
			if not rsShopper.EOF then
				
				shopper_shipping_FirstName = rsShopper("shipping_FirstName")
				shopper_shipping_LastName = rsShopper("shipping_LastName")
				shopper_shipping_address = rsShopper("shipping_Address")
				shopper_shipping_city = rsShopper("shipping_City")
				shopper_shipping_state = rsShopper("shipping_State")
				shopper_shipping_zip = rsShopper("shipping_ZipCode")
				shopper_shipping_country = rsShopper("shipping_Country")
				shopper_shipping_phone = rsShopper("shipping_Phone")
				shopper_shipping_company = rsShopper("shipping_company")
		
			else
				
			end if
			
		else
			
			sql = "SELECT * FROM " & g_storeid & "_shopper_shipping_address WHERE shopper_id = '" & Session("shopper_id") & "' AND address_id = '" & id & "'"
			set rs = dbconn.Execute(sql)
			if not rs.EOF then
				alt_address_id = rs("address_id")
				alt_shopper_id = rs("shopper_id")
				alt_address_name = rs("address_name")
				alt_firstname = rs("firstname")
				alt_lastname = rs("lastname")
				alt_address = rs("address")
				alt_city = rs("city")
				alt_state = rs("state")
				alt_zip = rs("zip")
				alt_country= rs("country")
				alt_phone = rs("phone")
				alt_set_default = rs("set_default")
				alt_company = rs("company")
				alt_address_type = rs("address_type")
				
				shopper_shipping_FirstName = alt_firstname
				shopper_shipping_LastName = alt_lastname
				shopper_shipping_address = alt_address
				shopper_shipping_city = alt_city
				shopper_shipping_state =alt_state
				shopper_shipping_zip = alt_zip
				shopper_shipping_country = alt_country
				shopper_shipping_phone = alt_phone
				shopper_billing_company = ""
				
			else
			end if
			
		end if
	
	END SELECT
%>