<!--#INCLUDE FILE="../../local/local.phtml"-->
<!--#INCLUDE FILE="../../language_pack.phtml"-->
<!--#INCLUDE FILE="../../util/xt_func_session.phtml"-->
<!--#INCLUDE FILE="../../util/xt_func_string.phtml"-->
<%
	sessionID = Request("sessionID")
	sessionID = FilterSessionString(sessionID)
	if Len(sessionID) > 0 then
		Session("SESSIONKEY") = sessionID
	else
		if Len(Session("SESSIONKEY")) > 0 then
			'session key exist
		else
			'no key information...
			Response.Redirect Session("StoreURL") & "/index.phtml"
		end if
	end if
%>
<!--#INCLUDE FILE="../../i_login.phtml"-->
<!-- #INCLUDE File="../../util/xt_func_util.phtml" -->
<!-- #INCLUDE File="../../util/xt_func_shopper.phtml" -->
<!-- #INCLUDE File="../../util/xt_func_payment.phtml" -->
<!-- #INCLUDE File="../../util/xt_func_misc_option.phtml" -->
<!-- #INCLUDE File="../../util/xt_func_rc4.phtml" -->
<!--#INCLUDE FILE="../../i_adodb.phtml"-->
<%
	If InStr(Request.ServerVariables("HTTP_REFERER"), "?") > 0 Then
		sp_http_referer = Split(Request.ServerVariables("HTTP_REFERER"), "?")
		http_referer = sp_http_referer(0)
	Else
		http_referer = Request.ServerVariables("HTTP_REFERER")
	End If
%>
<%
	flag = Trim(Request("flag"))
	op = Trim(Request("op"))
	
	if op = "edit" then
		
		bill_firstname = Trim(Request.Form("billing_firstname"))
		bill_lastname = Trim(Request.Form("billing_lastname"))
		bill_address = Trim(Request.Form("bill_address"))
		bill_city = Trim(Request.Form("bill_city"))
		bill_state = Trim(Request.Form("bill_state"))
		bill_zip = Trim(Request.Form("bill_zip"))
		bill_phone = Trim(Request.Form("bill_phone"))
		bill_country = Trim(Request.Form("bill_country"))
		bill_company = Trim(Request.Form("bill_company"))

		ccType = Trim(Request.Form("ccType"))
		ccNumber = Trim(Request.Form("ccNumber"))
		ccExp_Month = Trim(Request.Form("ccExp_Month"))
		ccExp_Year = Trim(Request.Form("ccExp_Year")) 
		cardname = Trim(Request.Form("cardname")) 
  
  
		Set rsUpdate = Server.CreateObject("ADODB.Recordset")
		with rsUpdate
			.ActiveConnection = conn
			.CursorLocation = 3
			.CursorType = 1
			.LockType = 3
			.Source = g_storeid & "_shopper WHERE shopper_id='" &  Session("shopper_id") & "'"
			.Open
		end with
		
		rsUpdate("firstname") = bill_firstname
		rsUpdate("lastname") = bill_lastname
		rsUpdate("address") = bill_address
		rsUpdate("city") = bill_city
		rsUpdate("state") = bill_state
		rsUpdate("zipcode") = bill_zip
		rsUpdate("company") = bill_company
		If Len(bill_country) > 0 Then
			rsUpdate("country") = bill_country
		Else
			rsUpdate("country") = "US"
		End If
		rsUpdate("phone") = bill_phone
		rsUpdate("CC_Type") = ccType
		
		rsUpdate("CC_ExpMonth") = ccExp_Month
		rsUpdate("CC_ExpYear") = ccExp_Year
		rsUpdate("CardName") = cardname
				
		if InStr(ccNumber, "...") then
		else
			if Len(ccNumber) > 0 then
				ccNumber = EnDeCrypt(ccNumber, g_crypt_key)
			end if
			
			rsUpdate("CC_Number") = ccNumber
			
		end if
		
		If dbconn.Errors.Count > 0 Then
			dbconn.Errors.Clear
			rsUpdate.CancelUpdate
		else
			rsUpdate.Update
		End If
		
		rsUpdate.Close
		set rsUpdate = nothing
		
		if flag = "co" then
			Response.Redirect (g_secure_url & "checkout.phtml")
		end if
		
		
	end if
	
	sql = "SELECT * FROM " & g_storeid & "_shopper WHERE shopper_id = '" & Session("shopper_id") & "'"
	set rs=conn.Execute(sql)
	if not rs.EOF then
	
		cc_type = rs("cc_type")
		cc_expmonth = rs("cc_expmonth")
		cc_expyear = rs("cc_expyear")
		cc_number = rs("cc_number")
		billing_firstname = rs("firstname")
		billing_lastname = rs("lastname")
		bill_company = rs("company")
		bill_address = rs("address")
		bill_city = rs("city")
		bill_zip = rs("zipcode")
		bill_state = rs("state")
		bill_country = rs("country")
		bill_phone = rs("phone")
		'cardname = rs("CardName")
		if Len(cc_number) > 0 then
			cc_number = EnDeCrypt(cc_number, g_crypt_key)
			cc_number = Left(cc_number,1) & "..." & Right(cc_number,4)
		end if
	end if
	rs.Close
	set rs = nothing
	
	if Len(bill_country) > 1 then
	else
		bill_country = "US"
	end if
%>