<script language="VBScript" RUNAT=Server>
Function IsHTMLTable(str_in)
	if (Instr(LCase(str_in), "<table")> 0) or (Instr(LCase(str_in), "<scrip")> 0) or (Instr(LCase(str_in), "<br")> 0)then
		IsHTMLTable = true
	else
		IsHTMLTable = false
	end if
end function
</script>

<%
  'Code for preventing SQL Injection

  array_split_item = Array("–", ";", "/*", "*/", "@@", "@",_

                  "char", "nchar", "varchar", "nvarchar",_

                  "alter", "begin", "cast", "create", "cursor",_

                  "declare", "delete", "drop", "end", "exec",_

                  "execute", "fetch", "insert", "kill", "open",_

                  "select", "sys", "sysobjects", "syscolumns",_

                  "table", "update", "<script", "</script>")
  
  for each item in Request.QueryString
    
    ixq = 0

    for array_counter = lbound(array_split_item) to ubound(array_split_item)

        item_postion1 = InStr(lcase(Request(item)),array_split_item(array_counter))       

        if item_postion1 > 0  then

            ixq = ixq + 1
            if ixq > 1 then
              Response.End()
            end if

        end if

    next

  next
  
%>

