<script language="VBScript" RUNAT=Server>
Function IsHTMLTable(str_in)
	if (Instr(LCase(str_in), "<table")> 0) or (Instr(LCase(str_in), "<scrip")> 0) or (Instr(LCase(str_in), "<br")> 0)then
		IsHTMLTable = true
	else
		IsHTMLTable = false
	end if
end function
</script>

<OBJECT RUNAT=SERVER PROGID=ADODB.Connection id=Conn></OBJECT>
<%

  'Code for preventing SQL Injection

  array_split_item = Array("–", ";", "/*", "*/", "@@", "@",_

                  "char", "nchar", "varchar", "nvarchar",_

                  "alter", "begin", "cast", "create", "cursor",_

                  "declare", "delete", "drop", "end", "exec",_

                  "execute", "fetch", "insert", "kill", "open",_

                  "select", "sys", "sysobjects", "syscolumns",_

                  "table", "update", "<script", "</script>")
  
  for each item in Request.QueryString
    
    ixq = 0

    for array_counter = lbound(array_split_item) to ubound(array_split_item)

        item_postion1 = InStr(lcase(Request(item)),array_split_item(array_counter))       

        if item_postion1 > 0  then

            ixq = ixq + 1
            if ixq > 1 then
              Response.End()
            end if

        end if

    next

  next
  
%>
<%
Conn.open Session("ConnectionString")
%>
<%

  SELECT CASE Session("TEMPLATEID")
  CASE "01"
    g_store_width = "100%"
    g_leftspace_width = "5"
    g_rightspace_width = "5"
    g_content_background = "#FFFFFF"

    'Color Table...
    g_menuline = "#003366"
    if Session("LEFT_DISPLAY_MODE") = 1 then 
    g_leftmenu_bg = "bgcolor='#EEEEEE'"
    else
    g_leftmenu_bg = "background='site_img/bg_left_01.gif'"
    end if

    g_bbs_font_light = "#FFFFFF"
    g_bbs_font_dark = "#000000"

    g_bbs_lb_title_bg = "#CCCCCC"

    g_bbs_content_line = "#000000"
    g_bbs_content_bg = "#FFFFFF"
    g_bbs_content_title = "#336666"
    g_bbs_content_btm_left = "#D5DFCD"
    g_bbs_content_btm_right = "#A5AF9D"

    g_rm_Title = "#CACFB5"
    g_rm_SubTitle = "#E7ECDA"
    g_rm_bg_main = "#FFFFFF"
    g_rm_btm = "#F9FBF2"
    g_rm_Border = "#9DA97D"

    g_config_system = "#EEEEEE"

    g_basket_line = "#BFBFBF"
    g_chkout_title = "#006699"
    g_chkout_title_text = "#FFFFFF"
    g_basket_bg = "#FFFFFF"

    g_lm_box_color = "#003366"
    g_lm_box_spacer_color = "#f7f7e7"

    g_footer_bg = "#003366"
    g_footer_text = "#FFFFFF"

    g_left_box_arrow = "site_img/c_arrow_" & Session("TEMPLATEID") & ".gif"
    g_left_item_box_class = "lmboxtd"

    g_chkout_content = "#FFFFFF" //new
    g_chkout_content_text = "#000000" //new
    
  CASE "02"
    
    g_store_width = "100%"
    g_leftspace_width = "5"
    g_rightspace_width = "5"
    g_content_background = "#FFFFFF"

    'Color Table...
    g_menuline = "#336666"	
    g_leftmenu_bg = "bgcolor='#EFF1D8'"

    g_bbs_font_light = "#FFFFFF"
    g_bbs_font_dark = "#000000"

    g_bbs_lb_title_bg = "#CCCCCC"

    g_bbs_content_line = "#000000"
    g_bbs_content_bg = "#FFFFFF"
    g_bbs_content_title = "#336666"
    g_bbs_content_btm_left = "#D5DFCD"
    g_bbs_content_btm_right = "#A5AF9D"

    g_rm_Title = "#CACFB5"
    g_rm_SubTitle = "#E7ECDA"
    g_rm_bg_main = "#FFFFFF"
    g_rm_btm = "#F9FBF2"
    g_rm_Border = "#9DA97D"

    g_config_system = "#EEEEEE"

    g_basket_line = "#BFBFBF"
    g_chkout_title = "#006699"
    g_chkout_title_text = "#FFFFFF"
    g_basket_bg = "#FFFFFF"

    g_lm_box_color = "#005500"
    g_lm_box_spacer_color = "#f7f7e7"

    g_footer_bg = "#EFF1D8"
    g_footer_text = "#333333"

    g_left_box_arrow = "site_img/c_arrow_" & Session("TEMPLATEID") & ".gif"
    g_left_item_box_class = "lmboxtd"

    g_chkout_content = "#FFFFFF" //new
    g_chkout_content_text = "#000000" //new
    
  CASE "03"
  
    g_store_width = "100%"
    g_leftspace_width = "5"
    g_rightspace_width = "5"
    g_content_background = "#FFFFFF"

    'Color Table...
    g_menuline = "#000000"	

    if Session("LEFT_DISPLAY_MODE") = 1 then
    g_leftmenu_bg = "bgcolor='#E4E3E3'"
    else
    g_leftmenu_bg = "bgcolor='#000000'"
    end if

    g_bbs_font_light = "#FFFFFF"
    g_bbs_font_dark = "#000000"

    g_bbs_lb_title_bg = "#CCCCCC"

    g_bbs_content_line = "#000000"
    g_bbs_content_bg = "#FFFFFF"
    g_bbs_content_title = "#777777"
    g_bbs_content_btm_left = "#EDEDED"
    g_bbs_content_btm_right = "#999999"

    g_rm_Title = "#BBB9B9"
    g_rm_SubTitle = "#E4E3E3"
    g_rm_bg_main = "#FFFFFF"
    g_rm_btm = "#FDFCFC"
    g_rm_Border = "#969494"

    g_config_system = "#EEEEEE"

    g_basket_line = "#777777"
    g_chkout_title = "#777777"
    g_chkout_title_text = "#FFFFFF"
    g_basket_bg = "#FFFFFF"

    g_lm_box_color = "#333333"
    g_lm_box_spacer_color = "#f7f7e7"

    g_footer_bg = "#000000"
    g_footer_text = "#FFFFFF"

    g_left_box_arrow = "site_img/c_arrow_" & Session("TEMPLATEID") & ".gif"
    g_left_item_box_class = "lmboxtd"

    g_chkout_content = "#FFFFFF" //new
    g_chkout_content_text = "#000000" //new
    
  CASE "04"
    
    g_store_width = "100%"
    g_leftspace_width = "5"
    g_rightspace_width = "5"
    g_content_background = "#FFFFFF"

    'Color Table...
    g_menuline = "#333333"	
    g_leftmenu_bg = "bgcolor='#dddddd'"

    g_bbs_font_light = "#FFFFFF"
    g_bbs_font_dark = "#000000"

    g_bbs_lb_title_bg = "#CCCCCC"

    g_bbs_content_line = "#000000"
    g_bbs_content_bg = "#FFFFFF"
    g_bbs_content_title = "#336666"
    g_bbs_content_btm_left = "#D5DFCD"
    g_bbs_content_btm_right = "#A5AF9D"

    g_rm_Border = "#000000"
    g_rm_Title = "#CACFB5"
    g_rm_SubTitle = "#E7ECDA"
    g_rm_bg_main = "#FFFFFF"
    g_rm_btm = "#F9FBF2"

    g_config_system = "#EEEEEE"

    g_basket_line = "#BFBFBF"
    g_chkout_title = "#658A40"
    g_chkout_title_text = "#FFFFFF"
    g_basket_bg = "#FFFFFF"

    g_lm_box_color = "#254A10"
    g_lm_box_spacer_color = "#f7f7e7"

    g_footer_bg = "#254A10"
    g_footer_text = "#FFFFFF"

    g_left_box_arrow = "site_img/c_arrow_" & Session("TEMPLATEID") & ".gif"
    g_left_item_box_class = "lmboxtd"

    g_chkout_content = "#FFFFFF" //new
    g_chkout_content_text = "#000000" //new
    
  CASE "06"
    g_store_width = "100%"
    g_leftspace_width = "5"
    g_rightspace_width = "5"
    g_content_background = "#FFFFFF"
      
    'Color Table...
    g_menuline = "#83AFDC"	
    g_leftmenu_bg = "bgcolor='#FFFFFF'"

    g_bbs_font_light = "#FFFFFF"
    g_bbs_font_dark = "#000000"

    g_bbs_lb_title_bg = "#CCCCCC"

    g_bbs_content_line = "#000000"
    g_bbs_content_bg = "#FFFFFF"
    g_bbs_content_title = "#336666"
    g_bbs_content_btm_left = "#D5DFCD"
    g_bbs_content_btm_right = "#A5AF9D"

    g_rm_Border = "#C9C8C8"
    g_rm_Title = "#CFCFCF"
    g_rm_SubTitle = "#E8E6E6"
    g_rm_bg_main = "#FFFFFF"
    g_rm_btm = "#F1F0F0"
    g_rm_Border = "#C9C8C8"

    g_config_system = "#EEEEEE"

    g_basket_line = "#BFBFBF"
    g_chkout_title = "#006699"
    g_chkout_title_text = "#FFFFFF"
    g_chkout_content = "#FFFFFF" //new
    g_chkout_content_text = "#000000" //new
    g_basket_bg = "#FFFFFF"

    g_footer_bg = "#83AFDC"
    g_footer_text = "#FFFFFF"

    g_lm_box_color = "#83AFDC"
    g_lm_box_spacer_color = "#f7f7e7"

    g_left_box_arrow = "site_img/c_arrow_" & Session("TEMPLATEID") & ".gif"
    g_left_item_box_class = "lmboxtd"
    
  CASE "07"
    g_store_width = "100%"
    g_leftspace_width = "5"
    g_rightspace_width = "5"
    g_content_background = "#FFFFFF"

    'Color Table...
    g_menuline = "#555555"'"#AFA8AF"	
    g_leftmenu_bg = "bgcolor='#F7F7F7'"

    g_bbs_font_light = "#FFFFFF"
    g_bbs_font_dark = "#000000"

    g_bbs_lb_title_bg = "#AFADAD"

    g_bbs_content_line = "#000000"
    g_bbs_content_bg = "#FFFFFF"
    g_bbs_content_title = "#777777"
    g_bbs_content_btm_left = "#EDEDED"
    g_bbs_content_btm_right = "#999999"

    g_rm_Title = "#BBB9B9"
    g_rm_SubTitle = "#E4E3E3"
    g_rm_bg_main = "#FFFFFF"
    g_rm_btm = "#FDFCFC"
    g_rm_Border = "#969494"

    g_config_system = "#EEEEEE"

    g_basket_line = "#777777"
    g_chkout_title = "#777777"
    g_chkout_title_text = "#FFFFFF"
    g_basket_bg = "#FFFFFF"

    g_lm_box_color = "#555555"
    g_lm_box_spacer_color = "#f7f7e7"

    g_footer_bg = "#EDEDED"
    g_footer_text = "#333333"

    g_left_box_arrow = "site_img/c_arrow_" & Session("TEMPLATEID") & ".gif"
    g_left_item_box_class = "lmboxtd"

    g_chkout_content = "#FFFFFF" //new
    g_chkout_content_text = "#000000" //new
    
  CASE "08"
    g_store_width = "100%"
    g_leftspace_width = "5"
    g_rightspace_width = "5"
    g_content_background = "#FFFFFF"

    'Color Table...
    g_menuline = "#000066"	
    g_leftmenu_bg = "background='site_img/bg_left_08.gif'"

    g_bbs_font_light = "#FFFFFF"
    g_bbs_font_dark = "#000000"

    g_bbs_lb_title_bg = "#CCCCCC"

    g_bbs_content_line = "#000000"
    g_bbs_content_bg = "#FFFFFF"
    g_bbs_content_title = "#336666"
    g_bbs_content_btm_left = "#D5DFCD"
    g_bbs_content_btm_right = "#A5AF9D"

    g_rm_Border = "#C9C8C8"
    g_rm_Title = "#CFCFCF"
    g_rm_SubTitle = "#E8E6E6"
    g_rm_bg_main = "#FFFFFF"
    g_rm_btm = "#F1F0F0"
    g_rm_Border = "#C9C8C8"

    g_config_system = "#EEEEEE"

    g_basket_line = "#BFBFBF"
    g_chkout_title = "#04006D"
    g_chkout_title_text = "#FFFFFF"
    g_basket_bg = "#FFFFFF"

    g_footer_bg = "#04006D"
    g_footer_text = "#FFFFFF"

    g_lm_box_color = "#000066"
    g_lm_box_spacer_color = "#f7f7e7"

    g_left_box_arrow = "site_img/c_arrow_" & Session("TEMPLATEID") & ".gif"
    g_left_item_box_class = "lmboxtd"

    g_chkout_content = "#FFFFFF" //new
    g_chkout_content_text = "#000000" //new
    
  CASE "09"
    
    g_store_width = "100%"
    g_leftspace_width = "5"
    g_rightspace_width = "5"
    g_content_background = "#FFFFFF"

    'Color Table...
    g_menuline = "#6F94EA"	
    g_leftmenu_bg = "bgcolor='#FFFFFF'"

    g_bbs_font_light = "#FFFFFF"
    g_bbs_font_dark = "#000000"

    g_bbs_lb_title_bg = "#CCCCCC"

    g_bbs_content_line = "#000000"
    g_bbs_content_bg = "#FFFFFF"
    g_bbs_content_title = "#336666"
    g_bbs_content_btm_left = "#D5DFCD"
    g_bbs_content_btm_right = "#A5AF9D"

    g_rm_Border = "#C9C8C8"
    g_rm_Title = "#CFCFCF"
    g_rm_SubTitle = "#E8E6E6"
    g_rm_bg_main = "#FFFFFF"
    g_rm_btm = "#F1F0F0"
    g_rm_Border = "#C9C8C8"

    g_config_system = "#EEEEEE"

    g_basket_line = "#B9C4D6"
    g_chkout_title = "#355793"
    g_chkout_title_text = "#FFFFFF"
    g_basket_bg = "#FFFFFF"

    g_footer_bg = "#6F94EA"
    g_footer_text = "#FFFFFF"

    g_lm_box_color = "#6F94EA"
    g_lm_box_spacer_color = "#f7f7e7"

    g_left_box_arrow = "site_img/c_arrow_" & Session("TEMPLATEID") & ".gif"
    g_left_item_box_class = "lmboxtd"

    g_chkout_content = "#FFFFFF" //new
    g_chkout_content_text = "#000000" //new
    
  CASE "11"
    
    g_store_width = "100%"
    g_leftspace_width = "5"
    g_rightspace_width = "5"
    g_content_background = "#FFFFFF"

    'Color Table...
    g_menuline = "#336666"	
    g_leftmenu_bg = "bgcolor='#EEEEEE'"

    g_bbs_font_light = "#FFFFFF"
    g_bbs_font_dark = "#000000"

    g_bbs_lb_title_bg = "#CCCCCC"

    g_bbs_content_line = "#000000"
    g_bbs_content_bg = "#FFFFFF"
    g_bbs_content_title = "#336666"
    g_bbs_content_btm_left = "#D5DFCD"
    g_bbs_content_btm_right = "#A5AF9D"

    g_rm_Title = "#CACFB5"
    g_rm_SubTitle = "#E7ECDA"
    g_rm_bg_main = "#FFFFFF"
    g_rm_btm = "#F9FBF2"
    g_rm_Border = "#9DA97D"

    g_config_system = "#EEEEEE"

    g_checkout_line = "#336699"

    g_basket_line = "#BFBFBF"
    g_chkout_title = "#006699"
    g_chkout_title_text = "#FFFFFF"
    g_basket_bg = "#FFFFFF"

    g_lm_box_color = "#336666"
    g_lm_box_spacer_color = "#f7f7e7"

    g_footer_bg = "#336666"
    g_footer_text = "#FFFFFF"

    g_left_box_arrow = "site_img/c_arrow_" & Session("TEMPLATEID") & ".gif"
    g_left_item_box_class = "lmboxtd"

    g_chkout_content = "#FFFFFF" //new
    g_chkout_content_text = "#000000" //new
    
  CASE "12"
    g_store_width = "100%"
    g_leftspace_width = "5"
    g_rightspace_width = "5"
    g_content_background = "#FFFFFF"

    'Color Table...
    g_menuline = "#333333"	
    g_leftmenu_bg = "bgcolor='#eeeeee'"

    g_bbs_font_light = "#FFFFFF"
    g_bbs_font_dark = "#000000"

    g_bbs_lb_title_bg = "#CCCCCC"

    g_bbs_content_line = "#535353"
    g_bbs_content_bg = "#FFFFFF"
    g_bbs_content_title = "#828080"
    g_bbs_content_btm_left = "#E4E2E2"
    g_bbs_content_btm_right = "#CECCCC"

    g_rm_Title = "#C3C3C3"
    g_rm_SubTitle = "#E4E3E3"
    g_rm_bg_main = "#FFFFFF"
    g_rm_btm = "#F1F0F0"
    g_rm_Border = "#AEAEAE"

    g_config_system = "#EEEEEE"

    g_basket_line = "#BFBFBF"
    g_chkout_title = "#F3C034"
    g_chkout_title_text = "#15120B"
    g_basket_bg = "#FFFFFF"

    g_lm_box_color = "#F3C034"
    g_lm_box_spacer_color = "#f7f7e7"

    g_footer_bg = "#F3C034"
    g_footer_text = "#333333"

    g_left_box_arrow = "site_img/c_arrow_" & Session("TEMPLATEID") & ".gif"
    g_left_item_box_class = "lmboxtd"

    g_chkout_content = "#FFFFFF" //new
    g_chkout_content_text = "#000000" //new
    
  CASE "51"
    
    g_store_width = "100%"
    g_leftspace_width = "5"
    g_rightspace_width = "5"
    g_content_background = "#FFFFFF"

    'Color Table...
    g_menuline = "#336666"	
    g_leftmenu_bg = "bgcolor='#339900'"
    if Session("LEFT_DISPLAY_MODE") = 1 then
    g_leftmenu_bg = "bgcolor='#f7f7e7'"
    else
    g_leftmenu_bg = "bgcolor='#339900'"
    end if

    g_bbs_font_light = "#FFFFFF"
    g_bbs_font_dark = "#000000"

    g_bbs_lb_title_bg = "#CCCCCC"

    g_bbs_content_line = "#000000"
    g_bbs_content_bg = "#FFFFFF"
    g_bbs_content_title = "#336666"
    g_bbs_content_btm_left = "#D5DFCD"
    g_bbs_content_btm_right = "#A5AF9D"

    g_rm_Title = "#EAD546"
    g_rm_SubTitle = "#EFE7AF"
    g_rm_bg_main = "#FFFFFF"
    g_rm_btm = "#F9F6E4"
    g_rm_Border = "#9DA97D"

    g_config_system = "#EEEEEE"

    g_basket_line = "#BFBFBF"
    g_chkout_title = "#339900"
    g_chkout_title_text = "#FFFFFF"
    g_basket_bg = "#FFFFFF"

    g_lm_box_color = "#CC0000"
    g_lm_box_spacer_color = "#f7f7e7"

    g_footer_bg = "#CC0000"
    g_footer_text = "#EAD546"

    g_left_box_arrow = "site_img/c_arrow_" & Session("TEMPLATEID") & ".gif"
    g_left_item_box_class = "lmboxtd"

    g_chkout_content = "#FFFFFF" //new
    g_chkout_content_text = "#000000" //new

  CASE "52"
    
    g_store_width = "100%"
    g_leftspace_width = "5"
    g_rightspace_width = "5"
    g_content_background = "#FFFFFF"

    'Color Table...
    g_menuline = "#FDD43E"

    if Session("LEFT_DISPLAY_MODE") = 1 then
    g_leftmenu_bg = "bgcolor='#EFEFF0'"
    else
    g_leftmenu_bg = "bgcolor='#FDD43E'"
    end if


    g_bbs_font_light = "#FFFFFF"
    g_bbs_font_dark = "#000000"

    g_bbs_lb_title_bg = "#CCCCCC"

    g_bbs_content_line = "#000000"
    g_bbs_content_bg = "#FFFFFF"
    g_bbs_content_title = "#336666"
    g_bbs_content_btm_left = "#D5DFCD"
    g_bbs_content_btm_right = "#A5AF9D"

    g_rm_Title = "#CFD8DF"
    g_rm_SubTitle = "#EFEFF0"
    g_rm_bg_main = "#FFFFFF"
    g_rm_btm = "#EFEFF0"
    g_rm_Border = "#9DA97D"

    g_config_system = "#EEEEEE"

    g_basket_line = "#BFBFBF"
    g_chkout_title = "#336666"
    g_chkout_title_text = "#FFFFFF"
    g_basket_bg = "#FFFFFF"

    g_lm_box_color = "#CFD8DF"
    g_lm_box_spacer_color = "#f7f7e7"

    g_footer_bg = "#CFD8DF"
    g_footer_text = "#333333"

    g_left_box_arrow = "site_img/c_arrow_" & Session("TEMPLATEID") & ".gif"
    g_left_item_box_class = "lmboxtd"

    g_chkout_content = "#FFFFFF" //new
    g_chkout_content_text = "#000000" //new
  

  CASE "53"
    
    g_store_width = "100%"
    g_leftspace_width = "5"
    g_rightspace_width = "5"
    g_content_background = "#FFFFFF"

    'Color Table...
    g_menuline = "#F9E9B2"	
    g_leftmenu_bg = "bgcolor='#EEEEEE'"

    g_bbs_font_light = "#FFFFFF"
    g_bbs_font_dark = "#000000"

    g_bbs_lb_title_bg = "#CCCCCC"

    g_bbs_content_line = "#000000"
    g_bbs_content_bg = "#FFFFFF"
    g_bbs_content_title = "#336666"
    g_bbs_content_btm_left = "#D5DFCD"
    g_bbs_content_btm_right = "#A5AF9D"

    g_rm_Title = "#CACFB5"
    g_rm_SubTitle = "#E7ECDA"
    g_rm_bg_main = "#FFFFFF"
    g_rm_btm = "#F9FBF2"
    g_rm_Border = "#9DA97D"

    g_config_system = "#EEEEEE"

    g_checkout_line = "#336699"

    g_basket_line = "#BFBFBF"
    g_chkout_title = "#006699"
    g_chkout_title_text = "#FFFFFF"
    g_basket_bg = "#FFFFFF"

    g_lm_box_color = "#000066"
    g_lm_box_spacer_color = "#f7f7e7"

    g_footer_bg = "#F9E9B2"
    g_footer_text = "#FFFFFF"

    g_left_box_arrow = "site_img/c_arrow_" & Session("TEMPLATEID") & ".gif"
    g_left_item_box_class = "lmboxtd"

    g_chkout_content = "#FFFFFF" //new
    g_chkout_content_text = "#000000" //new
    
  CASE "54"
    
    g_store_width = "100%"
    g_leftspace_width = "5"
    g_rightspace_width = "5"
    g_content_background = "#FFFFFF"

    'Color Table...
    g_menuline = "#336666"	
    g_leftmenu_bg = "bgcolor='#277198'"

    g_bbs_font_light = "#FFFFFF"
    g_bbs_font_dark = "#000000"

    g_bbs_lb_title_bg = "#CCCCCC"

    g_bbs_content_line = "#000000"
    g_bbs_content_bg = "#FFFFFF"
    g_bbs_content_title = "#336666"
    g_bbs_content_btm_left = "#D5DFCD"
    g_bbs_content_btm_right = "#A5AF9D"

    g_rm_Title = "#CACFB5"
    g_rm_SubTitle = "#E7ECDA"
    g_rm_bg_main = "#FFFFFF"
    g_rm_btm = "#F9FBF2"
    g_rm_Border = "#9DA97D"

    g_config_system = "#EEEEEE"

    g_checkout_line = "#336699"

    g_basket_line = "#BFBFBF"
    g_chkout_title = "#006699"
    g_chkout_title_text = "#FFFFFF"
    g_basket_bg = "#FFFFFF"

    g_lm_box_color = "#004B73"
    g_lm_box_spacer_color = "#FFFFFF"

    g_footer_bg = "#DFDFDF"
    g_footer_text = "#333333"

    g_left_box_arrow = "site_img/c_arrow_" & Session("TEMPLATEID") & ".gif"
    g_left_item_box_class = "lmboxtd"

    g_chkout_content = "#FFFFFF" //new
    g_chkout_content_text = "#000000" //new
    
  CASE "55"
    
    g_store_width = "100%"
    g_leftspace_width = "5"
    g_rightspace_width = "5"
    g_content_background = "#FFFFFF"

    'Color Table...
    g_menuline = "#336666"	
    g_leftmenu_bg = "bgcolor='#F1F1F1'"

    g_bbs_font_light = "#FFFFFF"
    g_bbs_font_dark = "#000000"

    g_bbs_lb_title_bg = "#CCCCCC"

    g_bbs_content_line = "#000000"
    g_bbs_content_bg = "#FFFFFF"
    g_bbs_content_title = "#336666"
    g_bbs_content_btm_left = "#D5DFCD"
    g_bbs_content_btm_right = "#A5AF9D"

    g_rm_Title = "#A83333"
    g_rm_title_text = "#FFFFFF"
    g_rm_SubTitle = "#FDE1E6"
    g_rm_subtitle_text = "#354366"
    g_rm_bg_main = "#FFFFFF"
    g_rm_btm = "#FDE1E6"
    g_rm_Border = "#A80000"

    g_config_system = "#EEEEEE"

    g_checkout_line = "#042E74"

    g_basket_line = "#BFBFBF"
    g_chkout_title = "#042E74"
    g_chkout_title_text = "#FFFFFF"
    g_basket_bg = "#FFFFFF"

    g_lm_box_color = "#004B73"
    g_lm_box_spacer_color = "#FFFFFF"

    g_footer_bg = "#000066"
    g_footer_text = "#FFFFFF"

    g_left_box_arrow = "site_img/c_arrow_" & Session("TEMPLATEID") & ".gif"
    g_left_item_box_class = "lmboxtd"

    g_chkout_content = "#FFFFFF" //new
    g_chkout_content_text = "#000000" //new

  CASE ELSE
    

  END SELECT



%>
