<%

	Session("shopper_id") = GetSession(Session("SESSIONKEY"), "sCID")
	Session("Shopper_Name") = GetSession(Session("SESSIONKEY"), "sCName")
	Session("LOGINGROUP") = GetSession(Session("SESSIONKEY"), "sCGroup")
	Session("IMFILEID") = GetSession(Session("SESSIONKEY"), "sCIM")
	Session("CUSTOM_CATALOG_ID_FLAG") = GetSession(Session("SESSIONKEY"), "sCustomCatalog")
	Session("SalesMode") = GetSession(Session("SESSIONKEY"), "sSaleMode")
	Session("PARTNER") = GetSession(Session("SESSIONKEY"), "sAffID")
	Session("Affiliate") = GetSession(Session("SESSIONKEY"), "sAffPtnr")
	Session("LANGUAGE") = GetSession(Session("SESSIONKEY"), "sLanguage")
	Session("LN") = GetSession(Session("SESSIONKEY"), "sLN")

	Session("REFERER_URL") = GetSession(Session("SESSIONKEY"), "sREFERER")
	
	
	if Session("LoginOption") = 1 or Session("LoginOption") = 2 then
		if Session("shopper_id") = "" then
		  Session("REFERER_URL2") = curPageURL()
		  UpdateSession Session("SESSIONKEY"), "sREFERER2", Session("REFERER_URL2")
			Response.Redirect "login.phtml?st=1"
		end if
	else
	  if forceLogin then
	    
	    if Session("shopper_id") = "" then
	      if InStr(curPageURL(), "basket.phtml") >= 1 then
	        Session("REFERER_URL2") = Request.ServerVariables("HTTP_REFERER")
	      else
	        Session("REFERER_URL2") = curPageURL()
	      end if
		    UpdateSession Session("SESSIONKEY"), "sREFERER2", Session("REFERER_URL2")
			  Response.Redirect "login.phtml?st=1"
		  end if
	  end if
	end if

%>
