<%

	Session("shopper_id") = GetSession(Session("SESSIONKEY"), "sCID")
	Session("Shopper_Name") = GetSession(Session("SESSIONKEY"), "sCName")
	Session("LOGINGROUP") = GetSession(Session("SESSIONKEY"), "sCGroup")
	Session("IMFILEID") = GetSession(Session("SESSIONKEY"), "sCIM")
	Session("CUSTOM_CATALOG_ID_FLAG") = GetSession(Session("SESSIONKEY"), "sCustomCatalog")
	Session("SalesMode") = GetSession(Session("SESSIONKEY"), "sSaleMode")
	Session("PARTNER") = GetSession(Session("SESSIONKEY"), "sAffID")
	Session("Affiliate") = GetSession(Session("SESSIONKEY"), "sAffPtnr")
	Session("LANGUAGE") = GetSession(Session("SESSIONKEY"), "sLanguage")
	Session("LN") = GetSession(Session("SESSIONKEY"), "sLN")

	Session("REFERER_URL") = GetSession(Session("SESSIONKEY"), "sREFERER")
	
	
	if Session("LoginOption") = 1 or Session("LoginOption") = 2 then
		if Session("shopper_id") = "" then
		  Session("REFERER_URL2") = curPageURL()
		  UpdateSession Session("SESSIONKEY"), "sREFERER2", Session("REFERER_URL2")
			Response.Redirect "login.asp?st=1"
		end if
	else
	  if forceLogin then
	    
	    if Session("shopper_id") = "" then
	      if InStr(curPageURL(), "basket.asp") >= 1 then
	        Session("REFERER_URL2") = Request.ServerVariables("HTTP_REFERER")
	      else
	        Session("REFERER_URL2") = curPageURL()
	      end if
		    UpdateSession Session("SESSIONKEY"), "sREFERER2", Session("REFERER_URL2")
			  Response.Redirect "login.asp?st=1"
		  end if
	  end if
	end if
	
	'===============================================================================================
	
	function curPageURL()
	 dim s, protocol, port

	 if Request.ServerVariables("HTTPS") = "on" then 
		 s = "s"
	 else 
		 s = ""
	 end if  
	 
	 protocol = strleft(LCase(Request.ServerVariables("SERVER_PROTOCOL")), "/") & s 

	 if Request.ServerVariables("SERVER_PORT") = "80" then
		 port = ""
	 else
		 port = ":" & Request.ServerVariables("SERVER_PORT")
	 end If
	 
	 qString1 = LCase(Request.ServerVariables("QUERY_STRING"))

	 curPageURL = protocol & "://" & Request.ServerVariables("SERVER_NAME") &_ 
								port & Request.ServerVariables("SCRIPT_NAME")

		If Len(qString1) > 0 Then
			curPageURL = curPageURL & "?" & qString1
		End if
	end function

	function strLeft(str1,str2)
	 strLeft = Left(str1,InStr(str1,str2)-1)
	end function
	
	function getCountryCodeByIP(strIPAddress)

	country_code = ""
	
	If InStr(strIPAddress, ".") Then

    arr_str_ip_address = Split(strIPAddress, ".")
    tmpIPNumber = 16777216 * Trim(arr_str_ip_address(0)) + 65536 * Trim(arr_str_ip_address(1)) + 256 * Trim(arr_str_ip_address(2)) + Trim(arr_str_ip_address(3))

    Set Rs = Server.CreateObject("ADODB.recordSet")

		With Rs

		.Open "SELECT COUNTRYCODE FROM A_COUNTRY_IP WHERE " & tmpIPNumber & " BETWEEN LONGFROM AND LONGTO", Session("ConnectionString")

		If Not(.EOF or .BOF) Then
			country_code = Trim(.Fields(0))
		Else
			country_code = ""
		End If

		.Close

		End With

		Set Rs = Nothing

	Else

		country_code = ""

	End If
  	
	getCountryCodeByIP = country_code

end function

Response.Write(Session("HTML_DECLARATION"))

%>
