<%
	'=====================================================================================================
	Set t_conn = Server.CreateObject("ADODB.Connection")
	t_conn.open g_connection_string
	
	sql = "SELECT setting_values FROM " &  g_storeid & "_setting WHERE setting_type='THEME_TEMPLATE'"
	Set rsSetting = t_conn.Execute(sql)
	if not rsSetting.EOF then
		THEME_TEMPLATE = Trim(rsSetting(0))
	else
		THEME_TEMPLATE = ""
	end if
	rsSetting.Close
	set rsSetting = nothing

	
	'THEME_TEMPLATE = "marketshop1"
	'=====================================================================================================
%>