<%
	Response.CodePage = 65001
	Response.CharSet = "UTF-8"
	g_route_page_id = "config"
%>
<!--#INCLUDE FILE="template_setting.phtml"-->
<!--#INCLUDE FILE="../../core/catalog/include_config_start.phtml"-->
<!DOCTYPE html>
<html>
<head>
<!--#INCLUDE FILE="include/head.phtml"-->
</head>
<body>
<div class="wrapper-wide">
	<!--#INCLUDE FILE="include/header.phtml"-->
	<div id="container">
		<div class="container">
			<div class="row">
				<!--Middle Part Start-->
				<div id="content" class="col-sm-12">
					<!--#INCLUDE FILE="include/config.phtml"-->
				</div>
				<!--Middle Part End -->
			</div>
		</div>
	</div>
	<!--#INCLUDE FILE="include/footer.phtml"-->
</div>
<!--#INCLUDE FILE="include/js.phtml"-->
<!--#INCLUDE FILE="include/before_body_end.phtml"-->
<!--#INCLUDE FILE="include/AbsoluteFooter.phtml"-->
</body>
</html>
<!--#INCLUDE FILE="../../core/catalog/include_config_end.phtml"-->