<%
	'Response.CodePage = 1252 
	'Response.CharSet = "windows-1252" 
	Response.CodePage = 65001
	Response.CharSet = "UTF-8"
%>
<!--#INCLUDE FILE="../../core/include_index_start.phtml"-->
<!--#INCLUDE FILE="template_setting.phtml"-->

<!DOCTYPE html>
<html>
<head>
<!--#INCLUDE FILE="include/head.phtml"-->
</head>
<body>
<!--#INCLUDE FILE="include/after_body_start.phtml"-->
<div class="wrapper-wide">
	<!--#INCLUDE FILE="include/header.phtml"-->
	<div id="container">
		<!--#INCLUDE FILE="include/index.phtml"-->
	</div>
	<!--#INCLUDE FILE="include/footer.phtml"-->
</div>
<!--#INCLUDE FILE="include/js.phtml"-->
<!--#INCLUDE FILE="include/before_body_end.phtml"-->
<!--#INCLUDE FILE="include/AbsoluteFooter.phtml"-->
<!--#INCLUDE FILE="../../core/include_index_end.phtml"-->
</body>
</html>
