<%
	Response.CodePage = 1252 
	Response.CharSet = "windows-1252" 
%>
<!--#INCLUDE FILE="../../core/include_index_start.phtml"-->
<!--#INCLUDE FILE="template_setting.phtml"-->
<!DOCTYPE html>
<html>
<head>
<!--#INCLUDE FILE="include/head.phtml"-->
</head>
<body>
<div class="wrapper-wide">
	<!--#INCLUDE FILE="include/after_body_start.phtml"-->
	<!--#INCLUDE FILE="include/header.phtml"-->
	<div id="container">
		<!--#INCLUDE FILE="include/index.phtml"-->
	</div>
	<!--#INCLUDE FILE="include/footer.phtml"-->
</div>
<!--#INCLUDE FILE="include/js.phtml"-->
<!--#INCLUDE FILE="include/before_body_end.phtml"-->
<!--#INCLUDE FILE="include/AbsoluteFooter.phtml"-->
</body>
</html>
<!--#INCLUDE FILE="../../core/include_index_end.phtml"-->