<%
	Response.CodePage = 65001
	Response.CharSet = "UTF-8"
	g_route_page_id = "checkout"
%>
<!--#INCLUDE FILE="template_setting.phtml"-->
<!--#INCLUDE FILE="../../core/checkout/include_checkout_start.phtml"-->
<!DOCTYPE html>
<html dir="ltr" lang="en" class="webkit chrome chrome53 win journal-desktop is-guest skin-4 header-center header-center-sticky product-grid-second-image product-list-second-image home-page layout-1 route-common-home oc2 one-column">
<head>
<!--#INCLUDE FILE="include/head.phtml"-->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>
</head>
<body>
<!--#INCLUDE FILE="include/after_body_start.phtml"-->
<header class="journal-header-center nolang-nocurr">
<!--#INCLUDE FILE="include/header.phtml"-->
</header>
<div class="extended-container">
<!--#INCLUDE FILE="include/checkout.phtml"-->
</div>
<footer class="boxed-footer">
<!--#INCLUDE FILE="include/footer.phtml"-->
</footer>
<div class="scroll-top">
</div>
<!--#INCLUDE FILE="include/js.phtml"-->
<!--#INCLUDE FILE="include/before_body_end.phtml"-->
<!--#INCLUDE FILE="include/AbsoluteFooter.phtml"-->
</body>
</html>
<!--#INCLUDE FILE="../../core/checkout/include_checkout_end.phtml"-->