<%
	Response.CodePage = 65001
	Response.CharSet = "UTF-8"
%>
<!--#INCLUDE FILE="../../core/include_index_start.phtml"-->
<!--#INCLUDE FILE="template_setting.phtml"-->
<!DOCTYPE html>
<html>
<head>
<!--#INCLUDE FILE="include/head.phtml"-->
</head>
<body>
<!--#INCLUDE FILE="include/after_body_start.phtml"-->
<header class="journal-header-center nolang-nocurr">
<!--#INCLUDE FILE="include/header.phtml"-->
</header>
<div class="extended-container">
<!--#INCLUDE FILE="include/index.phtml"-->	
</div>
<footer class="boxed-footer">
<!--#INCLUDE FILE="include/footer.phtml"-->
</footer>
<div class="scroll-top">
</div>
<!--#INCLUDE FILE="include/js.phtml"-->
<!--#INCLUDE FILE="include/before_body_end.phtml"-->
<!--#INCLUDE FILE="include/AbsoluteFooter.phtml"-->
</body>
</html>
<!--#INCLUDE FILE="../../core/include_index_end.phtml"-->
