<%
'=====================================GLOBAL=================================================================
If Request.ServerVariables("HTTPS") = "off" then 
	skin_base_url = g_skin_base_url
else
	skin_base_url = g_skin_base_secure_url
End If

If Len(g_page_title) > 0 Then
Else
	g_page_title = Session("StoreTitle")
End if
	
'=====================================THEME OPTIONS====================================================================
THEME_TEMPLATE = "journal4"
EC_imageListWidth = "250"
EC_imageListWidth = "250"
EC_thumbWidth = "150"
EC_thumbHeight = "150"
EC_imageWidth = "500"
EC_imageHeight = "500"
EC_zoomWidth = "700"
EC_zoomHeight = "700"
EC_miniCartWidth = "100"
EC_miniCartHeight = "100"
%>