<!--#INCLUDE FILE="../../local/local.phtml"-->
<!--#INCLUDE FILE="../../language_pack.phtml"-->
<!--#INCLUDE FILE="../../util/xt_func_session.phtml"-->
<!--#INCLUDE FILE="../../i_initsession.phtml"-->
<%
	Session("shopper_id") = GetSession(Session("SESSIONKEY"), "sCID")
	Session("Shopper_Name") = GetSession(Session("SESSIONKEY"), "sCName")
	Session("PARTNER") = GetSession(Session("SESSIONKEY"), "sAffID")
%>
<!--#INCLUDE FILE="../../i_adodb.phtml"-->
<!--#INCLUDE FILE="../../util/xt_func_string.phtml"-->
<!--#INCLUDE FILE="../../util/xt_func_seo.phtml"-->
<!--#INCLUDE File="../../util/xt_func_util.phtml" -->

<Script language="VBScript" RUNAT=SERVER>
function GetSystemFlatModel(ByRef str_db, ByRef str_config_id, ByRef markup, ByRef system_price)

  set dbconn=server.CreateObject("ADODB.Connection")
  dbconn.Open str_db
  
  sql = "SELECT markup_price, dept_id FROM :9_system_config WHERE config_id='" & str_config_id & "' AND dept_id IN ("
  sql = sql & "SELECT sysdept_id FROM :9_sysdept WHERE config_id='" & str_config_id & "' AND sysdept_mode=0 AND NOT (allow_none=1 AND none_default=1)) "
  sql = sql & "ORDER BY dept_id, row_id"
  sql = Replace(sql, ":9", Session("StoreID"))
  
  set rs1 = dbconn.Execute(sql)
  
  temp_dept = ""
  system_price = 0
  
  do while not rs1.EOF
  
	markup_price = rs1("markup_price")
	if not rs1("dept_id") = temp_dept then
	  system_price = system_price + markup_price
	  temp_dept = rs1("dept_id")
	end if
	rs1.MoveNext
  loop
  rs1.Close
  
  'system_price = system_price + (system_price * markup/100)
  'Add Hidden Cost..
  sql = "SELECT SUM(sysdept_cost) FROM :9_sysdept WHERE config_id='" & str_config_id & "' AND sysdept_mode=2"
  sql = Replace(sql, ":9", Session("StoreID"))
  set rsPart = Conn.Execute(sql)
  if not rsPart.EOF then
    if isNumeric(rsPart(0)) then
      system_price = system_price + rsPart(0)
    end if
  end if
  rsPart.close
  system_price = system_price + (system_price * markup/100)
  
  GetSystemFlatModel = true
  
end function
</Script>

<%
	pid = FilterStringEx(Trim(Request("pid")), "[^0-9]")
	
	If pid = "" Then
		pid = "0"
	End If
	
	'=================================================================================================
	'overwrite pf_id if urlkey present
	'=================================================================================================
	url_key = Trim(Request("urlkey"))
	
	if Len(url_key) > 1 then
		url_key = Replace(url_key, "/", "")
		
		sql = "SELECT * FROM " & g_storeid & "_rewrite WHERE rewrite_request_path='" & url_key & "'"
		set rsRewrite = conn.Execute(sql)
		if not rsRewrite.EOF then
			rewrite_type = rsRewrite("rewrite_type")
			rewrite_system_type = rsRewrite("rewrite_system_type")
			rewrite_system_id = rsRewrite("rewrite_system_id")
			rewrite_redirect_type = rsRewrite("rewrite_redirect_type")
		else
			rewrite_type = 0
			rewrite_system_type = 0
			rewrite_system_id = ""
			rewrite_redirect_type = ""
		end if
		
		if rewrite_system_type = 3 AND Len(rewrite_system_id) > 1 then
			sType = "cms"
		end if
		
		pid = rewrite_system_id
	end if
	
	'=================================================================================================

	sql = "SELECT * FROM " & g_storeid & "_pages WHERE page_id=" & pid
	set rsPage = Conn.Execute(sql)
	
	if not rsPage.EOF then
		page_title = rsPage("page_title")
		page_showleft = rsPage("page_showleft")
		page_showright = rsPage("page_showright")
		page_text = rsPage("page_text")
		custom_page_title = rsPage("custom_page_title")
		b_cont = true
		
		select case (page_showleft + page_showright)
		case 0
			main_len = 700
		case 1
			main_len = 550
		case 2
			main_len = 410
		case else
			main_len = 410
		End select
		
	else
		page_showleft =	1
		page_showright = 1
		main_len = 410
		b_cont = false
	end if

	If Len(custom_page_title) > 0 Then
			t1_page_title = stripHTML(custom_page_title)
	Else
			t1_page_title = Session("StoreTitle") & " - " & stripHTML(page_title)

	End If
%>