<!--#INCLUDE FILE="../../local/local.phtml"-->
<!--#INCLUDE FILE="../i_adoopen.phtml"-->
<!--#INCLUDE FILE="../../util/xt_func_session.phtml"-->
<!--#INCLUDE FILE="../../i_initsession.phtml"-->
<!--#INCLUDE FILE="../../util/xt_func_string.phtml"-->
<!--#INCLUDE FILE="../../util/xt_func_seo.phtml"-->
<!--#INCLUDE File="../../util/xt_func_util.phtml" -->
<!--#INCLUDE FILE="../../util/xt_func_shoppingcart.phtml"-->
<%
	Session("shopper_id") = GetSession(Session("SESSIONKEY"), "sCID")
	Session("Shopper_Name") = GetSession(Session("SESSIONKEY"), "sCName")
	Session("PARTNER") = GetSession(Session("SESSIONKEY"), "sAffID")
%>


<%
	pid = FilterStringEx(Trim(Request("pid")), "[^0-9]")
	If pid = "" Then
		pid = "0"
	End If
	'=================================================================================================
	'overwrite pf_id if urlkey present
	'=================================================================================================
	url_key = Trim(Request("urlkey"))
	
	if Len(url_key) > 1 then
		url_key = Replace(url_key, "/", "")
		
		sql = "SELECT * FROM " & g_storeid & "_rewrite WHERE rewrite_request_path='" & url_key & "'"
		set rsRewrite = dbconn.Execute(sql)
		if not rsRewrite.EOF then
			rewrite_type = rsRewrite("rewrite_type")
			rewrite_system_type = rsRewrite("rewrite_system_type")
			rewrite_system_id = rsRewrite("rewrite_system_id")
			rewrite_redirect_type = rsRewrite("rewrite_redirect_type")
		else
			rewrite_type = 0
			rewrite_system_type = 0
			rewrite_system_id = ""
			rewrite_redirect_type = ""
		end if
		
		if rewrite_system_type = 3 AND Len(rewrite_system_id) > 1 then
			sType = "cms"
		end if
		
		pid = rewrite_system_id
	end if
	
	'=================================================================================================

	sql = "SELECT * FROM " & g_storeid & "_pages WHERE page_id=" & pid
	set rsPage = dbconn.Execute(sql)
	
	if not rsPage.EOF then
		page_title = rsPage("page_title")
		page_showleft = rsPage("page_showleft")
		page_showright = rsPage("page_showright")
		page_text = rsPage("page_text")
		custom_page_title = rsPage("custom_page_title")
		b_cont = true
		
		select case (page_showleft + page_showright)
		case 0
			main_len = 700
		case 1
			main_len = 550
		case 2
			main_len = 410
		case else
			main_len = 410
		End select
		
	else
		page_showleft =	1
		page_showright = 1
		main_len = 410
		b_cont = false
	end if

	If Len(custom_page_title) > 0 Then
			t1_page_title = stripHTML(custom_page_title)
	Else
			t1_page_title = Session("StoreTitle") & " - " & stripHTML(page_title)

	End If
	
	'======================================================================================
	g_page_text = page_text
%>