<%@ Language=VBScript %>
<%
	Response.CodePage = 65001
	Response.CharSet = "UTF-8"
%>
<!-- #INCLUDE File="local/local.phtml" -->
<!-- #INCLUDE File="../util/xt_func_util.phtml" -->
<!-- #INCLUDE File="../util/xt_func_misc_option.phtml" -->
<!-- #INCLUDE File="../util/xt_func_rc4.phtml" -->
<!-- #INCLUDE File="include/i_login.phtml" -->
<%
	d_id = Trim(Request("d_id"))
	status_msg = Request("status_msg")

	strSQL = "SELECT * FROM DISTRIBU_DM WHERE D_NO='" & d_id & "'"

	Set rsShopper = dbconn_backoffice.Execute(strSQL)

	if not rsShopper.EOF then
		
		s_d_no = rsShopper("D_NO")
		s_d_uid = rsShopper("D_UID")
		s_lastname = rsShopper("D_LASTNAME")
		s_firstname = rsShopper("D_FIRSTNAME")
		s_d_krname = rsShopper("D_KRNAME")
		s_d_idno= rsShopper("D_IDNO")
		s_d_birth= rsShopper("D_BIRTH")
		s_email = rsShopper("D_EMAIL")
		s_phone = rsShopper("D_TEL")
		s_d_country = rsShopper("D_CONTRY")
		s_d_pass = rsShopper("D_PASS")
		s_d_pass2 = rsShopper("D_PASS2")
		s_d_passpin = rsShopper("D_PASSPIN")
		s_d_gccnum = rsShopper("D_GCCNUM")
		
		s_name = s_lastname & ", " & s_firstname & " (" & s_d_krname  & ")"
	
	else	  
		
	end if

	rsShopper.Close

%>
<!--#INCLUDE FILE="include/doctype.phtml"-->
<head>
<!--#INCLUDE FILE="include/head.phtml"-->
<!-- BEGIN PAGE LEVEL PLUGINS -->
<link rel="stylesheet" href="assets/plugins/jquery-ui/jquery-ui-1.10.4.custom.min.css" />
<!-- END PAGE LEVEL PLUGINS -->
<!--#INCLUDE FILE="include/head_bottom.phtml"-->
</head>

<body class="page-container-bg-solid">
<div class="page-wrapper">
	<div class="page-wrapper-row">
		<div class="page-wrapper-top">
			<!--#INCLUDE FILE="include/header.phtml"-->
		</div>
	</div>
	<div class="page-wrapper-row full-height">
		<div class="page-wrapper-middle">
			<!-- BEGIN CONTAINER -->
			<div class="page-container">
				<!-- BEGIN CONTENT -->
				<div class="page-content-wrapper">
					<!-- BEGIN CONTENT BODY -->
					<!-- BEGIN PAGE HEAD-->
					<!-- END PAGE HEAD-->
					<!-- BEGIN PAGE CONTENT BODY -->
					<div class="page-content">
						<div class="container-fluid">
							<!-- BEGIN PAGE CONTENT INNER -->
							<div class="page-content-inner">
								<div class="row">
									<div class="col-md-12">
										<form id="form_edit_1" class="form-horizontal form-row-seperated" action="#">
										<input type="hidden" name="shopper_id" id="shopper_id" value="<%=shopper_id%>">
											<div class="portlet">
												<div class="portlet-title">
													<div class="caption">
													<i class="fa fa-shopping-cart"></i>
													<%
													if sd_id ="0" then
														Response.Write("New Member")
													else
														Response.Write(s_name)
													end if
													%>
													</div>
													<div class="actions btn-set">
													
														<button type="button" onclick="location.href='backoffice_members.phtml';" name="back" class="btn btn-default">
															<i class="fa fa-angle-left"></i> Back
														</button>
														<button class="btn btn-success" onclick="savebutton='1';">
															<i class="fa fa-check"></i> Save
														</button>
														<button class="btn btn-success" onclick="savebutton='0';">
															<i class="fa fa-check-circle"></i> Save & Continue Edit
														</button>
														<div class="btn-group">
															<a class="btn btn-success dropdown-toggle" href="javascript:;" data-toggle="dropdown">
																<i class="fa fa-share"></i> More
																<i class="fa fa-angle-down"></i>
															</a>
															<div class="dropdown-menu pull-right">
																<li>
																	<a href="#"> De-Activate </a>
																</li>
															</div>
														</div> 
													</div>
												</div>
												<div class="alert alert-danger display-hide">
												<button class="close" data-close="alert"></button> You have some form errors. Please check below. 
												</div>
												<div class="alert alert-success display-hide">
												<button class="close" data-close="alert"></button> The information has been saved.
												</div>
												<div class="alert alert-warning display-hide">
												<button class="close" data-close="alert"></button> The information has not been saved properly. Please contact system administrator.
												</div>
												<div class="portlet-body">
													<div class="tabbable-bordered">
														<ul class="nav nav-tabs">
															<li class="active">
																<a href="#panel_tab4_example1" data-toggle="tab">
																	General
																</a>
															</li>
														</ul>
														<div class="tab-content">
															<div class="tab-pane active" id="panel_tab4_example1">
																<div class="row">
																	<div class="col-md-12 col-sm-12">
																		<div class="portlet green-soft box">
																			<div class="portlet-title">
																				<div class="caption">
																					<i class="fa fa-cogs"></i>General </div>
																				<div class="actions">
																					
																				</div>
																			</div>
																			<div class="portlet-body">
																				<div class="form-group">
																					<label class="col-sm-2 control-label" for="form-field-1">
																						No <span class="symbol required">*</span> 
																					</label>
																					<div class="col-sm-5">
																						<input type="text" placeholder="" id="D_NO" name="D_NO" class="form-control input-sm" value="<%=s_d_no%>" readonly>
																					</div>
																				</div>
																				<div class="form-group">
																					<label class="col-sm-2 control-label" for="form-field-1">
																						ID <span class="symbol required">*</span> 
																					</label>
																					<div class="col-sm-5">
																						<input type="text" placeholder="" id="D_UID" name="D_UID" class="form-control input-sm" value="<%=s_d_uid%>">
																					</div>
																				</div>
																				<div class="form-group">
																					<label class="col-sm-2 control-label" for="form-field-1">
																						First Name <span class="symbol required">*</span> 
																					</label>
																					<div class="col-sm-5">
																						<input type="text" placeholder="" id="D_FIRSTNAME" name="D_FIRSTNAME" class="form-control input-sm" value="<%=s_firstname%>">
																					</div>
																				</div>
																				<div class="form-group">
																					<label class="col-sm-2 control-label" for="form-field-1">
																						Last Name <span class="symbol required">*</span> 
																					</label>
																					<div class="col-sm-5">
																						<input type="text" placeholder="" id="D_LASTNAME" name="D_LASTNAME" class="form-control input-sm" value="<%=s_lastname%>">
																					</div>
																				</div>
																				<div class="form-group">
																					<label class="col-sm-2 control-label" for="form-field-1">
																						Korean Name <span class="symbol required">*</span> 
																					</label>
																					<div class="col-sm-5">
																						<input type="text" placeholder="" id="D_KRNAME" name="D_KRNAME" class="form-control input-sm" value="<%=s_d_krname%>">
																					</div>
																				</div>
																				<div class="form-group">
																					<label class="col-sm-2 control-label" for="form-field-1">
																						SSN <span class="symbol required">*</span> 
																					</label>
																					<div class="col-sm-5">
																						<input type="text" placeholder="" id="D_IDNO" name="D_IDNO" class="form-control input-sm" value="<%=s_d_idno%>">
																					</div>
																				</div>
																				<div class="form-group">
																					<label class="col-sm-2 control-label" for="form-field-1">
																						Date of Birth <span class="symbol required">*</span> 
																					</label>
																					<div class="col-sm-5">
																						<input type="text" placeholder="" id="D_BIRTH" name="D_BIRTH" class="form-control input-sm" value="<%=s_d_birth%>">
																					</div>
																				</div>
																				<div class="form-group">
																					<label class="col-sm-2 control-label" for="form-field-1">
																						Email <span class="symbol required">*</span> 
																					</label>
																					<div class="col-sm-5">
																						<input type="text" placeholder="" id="D_EMAIL" name="D_EMAIL" class="form-control input-sm" value="<%=s_email%>">
																					</div>
																				</div>
																				<div class="form-group">
																					<label class="col-sm-2 control-label" for="form-field-1">
																						Phone <span class="symbol required">*</span> 
																					</label>
																					<div class="col-sm-5">
																						<input type="text" placeholder="" id="D_TEL" name="D_TEL" class="form-control input-sm" value="<%=s_phone%>">
																					</div>
																				</div>
																				<div class="form-group">
																					<label class="col-sm-2 control-label" for="D_CONTRY">
																						Country <%=s_d_country%>
																					</label>
																					<div class="col-sm-4">
																						<select id="D_CONTRY" name="D_CONTRY" class="form-control input-sm">
																							<option value=""></option>
																							<option value="19" <%if s_d_country = "19" then%>selected<%end if%>>Argentina</option>
																							<option value="35" <%if s_d_country = "35" then%>selected<%end if%>>Australia</option>
																							<option value="03" <%if s_d_country = "03" then%>selected<%end if%>>Brazil</option>
																							<option value="18" <%if s_d_country = "18" then%>selected<%end if%>>Canada</option>
																							<option value="05" <%if s_d_country = "05" then%>selected<%end if%>>Chile</option>
																							<option value="06" <%if s_d_country = "06" then%>selected<%end if%>>China</option>
																							<option value="07" <%if s_d_country = "07" then%>selected<%end if%>>Colombia</option>
																							<option value="08" <%if s_d_country = "08" then%>selected<%end if%>>France</option>
																							<option value="09" <%if s_d_country = "09" then%>selected<%end if%>>Germany</option>
																							<option value="10" <%if s_d_country = "10" then%>selected<%end if%>>Greece</option>
																							<option value="11" <%if s_d_country = "11" then%>selected<%end if%>>Guatemala</option>
																							<option value="12" <%if s_d_country = "12" then%>selected<%end if%>>Honduras</option>
																							<option value="39" <%if s_d_country = "39" then%>selected<%end if%>>Hong Kong</option>
																							<option value="13" <%if s_d_country = "13" then%>selected<%end if%>>Hungary</option>
																							<option value="14" <%if s_d_country = "14" then%>selected<%end if%>>India</option>
																							<option value="40" <%if s_d_country = "40" then%>selected<%end if%>>Indonesia</option>
																							<option value="17" <%if s_d_country = "17" then%>selected<%end if%>>Italy</option>
																							<option value="04" <%if s_d_country = "04" then%>selected<%end if%>>Japan</option>
																							<option value="01" <%if s_d_country = "01" then%>selected<%end if%>>Korea</option>
																							<option value="20" <%if s_d_country = "20" then%>selected<%end if%>>Malaysia</option>
																							<option value="21" <%if s_d_country = "21" then%>selected<%end if%>>Mexico</option>
																							<option value="23" <%if s_d_country = "23" then%>selected<%end if%>>New Zealand</option>
																							<option value="41" <%if s_d_country = "41" then%>selected<%end if%>>Nigeria</option>
																							<option value="25" <%if s_d_country = "25" then%>selected<%end if%>>Peru</option>
																							<option value="26" <%if s_d_country = "26" then%>selected<%end if%>>Philippines</option>
																							<option value="27" <%if s_d_country = "27" then%>selected<%end if%>>Poland</option>
																							<option value="16" <%if s_d_country = "16" then%>selected<%end if%>>Rusia</option>
																							<option value="28" <%if s_d_country = "28" then%>selected<%end if%>>Singapore</option>
																							<option value="29" <%if s_d_country = "29" then%>selected<%end if%>>Spain</option>
																							<option value="30" <%if s_d_country = "30" then%>selected<%end if%>>Sweden</option>
																							<option value="31" <%if s_d_country = "31" then%>selected<%end if%>>Switzerland</option>
																							<option value="32" <%if s_d_country = "32" then%>selected<%end if%>>Taiwan</option>
																							<option value="33" <%if s_d_country = "33" then%>selected<%end if%>>Thailand</option>
																							<option value="34" <%if s_d_country = "34" then%>selected<%end if%>>United Kingdom</option>
																							<option value="02" <%if s_d_country = "02" then%>selected<%end if%>>United States</option>
																							<option value="36" <%if s_d_country = "36" then%>selected<%end if%>>Urguay</option>
																							<option value="37" <%if s_d_country = "37" then%>selected<%end if%>>Venezuela</option>
																							<option value="38" <%if s_d_country = "38" then%>selected<%end if%>>Vietnam</option>
																						</select>
																					</div>
																				</div>
																				<div class="form-group">
																					<label class="col-sm-2 control-label" for="form-field-1">
																						i-Payout Card #  
																					</label>
																					<div class="col-sm-5">
																						<input type="text" placeholder="" id="D_GCCNUM" name="D_GCCNUM" class="form-control input-sm" value="<%=s_d_gccnum%>">
																					</div>
																				</div>
																			</div>
																		</div>
																	</div>
																</div>
																<div class="row">
																	<div class="col-md-12 col-sm-12">
																		<div class="portlet green-soft box">
																			<div class="portlet-title">
																				<div class="caption">
																					<i class="fa fa-cogs"></i>Password </div>
																				<div class="actions">
																					
																				</div>
																			</div>
																			<div class="portlet-body">
																				<div class="form-group">
																					<label class="col-sm-2 control-label" for="form-field-1">
																						Password <span class="symbol required">*</span> 
																					</label>
																					<div class="col-sm-5">
																						<input type="text" placeholder="" id="D_PASS" name="D_PASS" class="form-control input-sm" value="<%=s_d_pass%>">
																					</div>
																				</div>
																				<div class="form-group">
																					<label class="col-sm-2 control-label" for="form-field-1">
																						E-money Password <span class="symbol required">*</span> 
																					</label>
																					<div class="col-sm-5">
																						<input type="text" placeholder="" id="D_PASS2" name="D_PASS2" class="form-control input-sm" value="<%=s_d_pass2%>">
																					</div>
																				</div>
																				<div class="form-group">
																					<label class="col-sm-2 control-label" for="form-field-1">
																						PIN <span class="symbol required">*</span> 
																					</label>
																					<div class="col-sm-5">
																						<input type="text" placeholder="" id="D_PASSPIN" name="D_PASSPIN" class="form-control input-sm" value="<%=s_d_passpin%>">
																					</div>
																				</div>
																			</div>
																		</div>
																	</div>
																</div>
															</div>
														</div>
													</div>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
							<!-- END PAGE CONTENT INNER -->
						</div>
					</div>
					<!-- END PAGE CONTENT BODY -->
					<!-- END CONTENT BODY -->
				</div>
				<!-- END CONTENT -->
			</div>
			<!-- END CONTAINER -->
		</div>
	</div>
	<div class="page-wrapper-row">
		<div class="page-wrapper-bottom">
			<!--#INCLUDE FILE="include/footer.phtml"-->
		</div>
	</div>
</div>
<div id="dialog-confirm" title="Delete Customer?" style="display:none;">
  <p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>This customer will be permanently deleted and cannot be recovered. Are you sure?</p>
</div>
<div class="modal fade" id="stack2" tabindex="-1" data-width="960" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
<!--#INCLUDE FILE="include/js.phtml"-->
<!-- BEGIN PAGE LEVEL PLUGINS -->
<script src="assets/plugins/jquery-ui/jquery-ui-1.10.1.custom.min.js" type="text/javascript"></script>
<script src="../assets/global/plugins/jquery-validation/js/jquery.validate.min.js" type="text/javascript"></script>
<script src="../assets/global/plugins/jquery-validation/js/additional-methods.min.js" type="text/javascript"></script>
<!-- END PAGE LEVEL PLUGINS -->

<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script language="javascript">
var savebutton = "1";
</script>
<script language="javascript">
var FormValidator = function () {
	
	var runValidator1 = function() {
		// for more info visit the official plugin documentation: 
			// http://docs.jquery.com/Plugins/Validation

			var form1 = $('#form_edit_1');
			var error1 = $('.alert-danger', form1);
			var success1 = $('.alert-success', form1);
			var warning1 = $('.alert-warning', form1);

			form1.validate({
				errorElement: 'span', //default input error message container
				errorClass: 'help-block help-block-error', // default input error message class
				focusInvalid: false, // do not focus the last invalid input
				ignore: "",  // validate all fields including form hidden input
				//RULES
				rules: {
					new_email: {
						required: true,
						email: true,
						remote:
						{
						  url: 'util/check_duplicate_email_address.phtml',
						  type: "post"
						}

					},
					shopper_firstname: {
						minlength: 3,
						required: true
					},
					shopper_lastname: {
						minlength: 3,
						required: true
					},
					shopper_password_new: {
						minlength: 8
					}
				},
				
				messages: {
					new_email: {
						required: "Please enter a valid email address",
						remote: "The specified email address is already registered."
					}
				},
				
				invalidHandler: function (event, validator) { //display error alert on form submit              
					success1.hide();
					error1.show();
					App.scrollTo(error1, -200);
				},

				errorPlacement: function (error, element) { // render error placement for each input type
					var cont = $(element).parent('.input-group');
					if (cont) {
						cont.after(error);
					} else {
						element.after(error);
					}
				},

				highlight: function (element) { // hightlight error inputs

					$(element)
						.closest('.form-group').addClass('has-error'); // set error class to the control group
				},

				unhighlight: function (element) { // revert the change done by hightlight
					$(element)
						.closest('.form-group').removeClass('has-error'); // set error class to the control group
				},

				success: function (label) {
					label
						.closest('.form-group').removeClass('has-error'); // set success class to the control group
				},

				submitHandler: function (form) {
					success1.hide();
					error1.hide();
					warning1.hide();
					
					$.ajax({
						type: "POST",
						url: "api/sp_backoffice_member_update.phtml",
						data: $("#form_edit_1").serialize(),
						success: function() {
							window.scrollTo(0,0);
							success1.show();
							
							if (savebutton == "1")
							{
								setTimeout(function () {
										window.location.replace("backoffice_members.phtml");
									}, 500);
							}
						},
						error: function() {
							warning1.show();
						}
					});
				}
			});


	};
	
	/*
	var runValidator1 = function () {
		var form1 = $('#form');
		var errorHandler1 = $('#errorHandler1', form1);
		var errorHandler2 = $('#errorHandler2', form1);
		var successHandler1 = $('.successHandler', form1);
		$.validator.addMethod("FullDate", function () {
			//if all values are selected
			if ($("#dd").val() != "" && $("#mm").val() != "" && $("#yyyy").val() != "") {
				return true;
			} else {
				return false;
			}
		}, 'Please select a day, month, and year');
		$('#form').validate({
			errorElement: "span", // contain the error msg in a span tag
			errorClass: 'help-block',
			errorPlacement: function (error, element) { // render error placement for each input type
				if (element.attr("type") == "radio" || element.attr("type") == "checkbox") { // for chosen elements, need to insert the error after the chosen container
					error.insertAfter($(element).closest('.form-group').children('div').children().last());
				} else if (element.attr("name") == "dd" || element.attr("name") == "mm" || element.attr("name") == "yyyy") {
					error.insertAfter($(element).closest('.form-group').children('div'));
				} else {
					error.insertAfter(element);
					// for other inputs, just perform default behavior
				}
			},
			ignore: "",
			
			//RULES
			rules: {
				new_email: {
					required: true,
					email: true,
					remote:
					{
					  url: 'util/check_duplicate_email_address.phtml',
					  type: "post"
					}

				},
				shopper_firstname: {
					minlength: 3,
					required: true
				},
				shopper_lastname: {
					minlength: 3,
					required: true
				},
				shopper_password_new: {
					minlength: 8
				}
			},
			
			messages: {
				new_email: {
					required: "Please enter a valid email address",
					remote: "The specified email address is already registered."
				}
			},
			//END OF RULES
			
			invalidHandler: function (event, validator) { //display error alert on form submit
				successHandler1.hide();
				errorHandler1.show();
			},
			highlight: function (element) {
				$(element).closest('.help-block').removeClass('valid');
				$(element).closest('.form-group').removeClass('has-success').addClass('has-error').find('.symbol').removeClass('ok').addClass('required');
			},
			unhighlight: function (element) { 
				$(element).closest('.form-group').removeClass('has-error');
			},
			success: function (label, element) {
				label.addClass('help-block valid');
				$(element).closest('.form-group').removeClass('has-error').addClass('has-success').find('.symbol').removeClass('required').addClass('ok');
			},
			submitHandler: function (form) {
				successHandler1.hide();
				errorHandler1.hide();
				errorHandler2.hide();
				$.ajax({
					type: "POST",
					url: "api/sp_customer_manage_customer_update.phtml",
					data: $("#form").serialize(),
					success: function() {
						window.scrollTo(0,0);
						successHandler1.show();
						setTimeout(function () {
							window.location.replace("customer_manage_customer.phtml");
						}, 1000);
					},
					error: function() {
						errorHandler2.show();
					}
				});
			}
		});
	};
	*/
	return {
		//main function to initiate template pages
		init: function () {
			runValidator1();
		}
	};
}();
</script>
<script>
	jQuery(document).ready(function() {
		//Main.init();
		FormValidator.init();
		
		$('#DeleteCust').on('click', function () {
			$( "#dialog-confirm" ).dialog({
			  resizable: false,
			  width:360,
			  height:180,
			  modal: true,
			  buttons: {
				"Delete item": function() {
					$( this ).dialog( "close" );
					location.replace('api/tp_customer_update.phtml?shopper_id=<%=shopper_id%>')
				},
				Cancel: function() {
					$( this ).dialog( "close" );
				}
			  }
			});
		});
		
	});
</script>

<!-- END PAGE LEVEL SCRIPTS -->
</body>
</html>