<!-- #INCLUDE File="local/local.phtml" -->
<!-- #INCLUDE File="util/xt_func_util.phtml" -->
<!-- #INCLUDE File="util/xt_func_string.phtml" -->
<!-- #INCLUDE File="include/i_login.phtml" -->
<!--#INCLUDE FILE="include/doctype.phtml"-->
<head>
<!--#INCLUDE FILE="include/head.phtml"-->
<!-- BEGIN PAGE LEVEL PLUGINS -->
<link href="../assets/global/plugins/datatables/datatables.min.css" rel="stylesheet" type="text/css" />
<link href="../assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css" rel="stylesheet" type="text/css" />
<link href="../assets/global/plugins/bootstrap-datepicker/css/bootstrap-datepicker3.min.css" rel="stylesheet" type="text/css" />
<link href="../assets/global/plugins/fancybox/source/jquery.fancybox.css" rel="stylesheet" type="text/css" />
<!-- END PAGE LEVEL PLUGINS -->
</head>

<body class="page-container-bg-solid">
<div class="page-wrapper">
	<div class="page-wrapper-row">
		<div class="page-wrapper-top">
			<!--#INCLUDE FILE="include/header.phtml"-->
		</div>
	</div>
	<div class="page-wrapper-row full-height">
		<div class="page-wrapper-middle">
			<!-- BEGIN CONTAINER -->
			<div class="page-container">
				<!-- BEGIN CONTENT -->
				<div class="page-content-wrapper">
					<!-- BEGIN CONTENT BODY -->
					
					<!-- BEGIN PAGE CONTENT BODY -->
					<div class="page-content">
						<div class="container-fluid">
							<!-- BEGIN PAGE CONTENT INNER -->
							<div class="page-content-inner">
								<div class="row">
									<div class="col-md-12">
										<!-- Begin: life time stats -->
										<div class="portlet light portlet-fit portlet-datatable">
											<div class="portlet-title">
												<div class="caption">
													<i class="fa fa-shopping-cart"></i>Product Listing 
												</div>
												<div class="actions">
													<a href="catalog_product_detail.phtml?pf_id=0" class="btn btn-circle btn-info">
														<i class="fa fa-plus"></i>
														<span class="hidden-xs"> New Product </span>
													</a>
													<div class="btn-group">
														<a class="btn btn-circle btn-default dropdown-toggle" href="javascript:;" data-toggle="dropdown">
															<i class="fa fa-share"></i>
															<span class="hidden-xs"> Tools </span>
															<i class="fa fa-angle-down"></i>
														</a>
														<div class="dropdown-menu pull-right">
															<li>
																<a href="javascript:;"> Export to Excel </a>
															</li>
															<li>
																<a href="javascript:;"> Export to CSV </a>
															</li>
															<li>
																<a href="javascript:;"> Export to XML </a>
															</li>
															<li class="divider"></li>
															<li>
															<a href="javascript:;"> Print Invoices </a>
															</li>
														</div>
													</div>
												</div>
											</div>
											<div class="portlet-body">
												<div class="table-container">
													<div class="table-actions-wrapper">
														<span> </span>
														<select class="table-group-action-input form-control input-inline input-small input-sm">
															<option value="">Select...</option>
															<option value="publish">Publish</option>
															<option value="unpublished">Un-publish</option>
															<option value="delete">Delete</option>
														</select>
														<button class="btn btn-sm btn-success table-group-action-submit">
															<i class="fa fa-check"></i> Submit</button>
													</div>
													<table class="table table-striped table-bordered table-hover table-checkable" id="datatable_products">
														<thead>
															<tr role="row" class="heading">
																<th width="1%">
																	<label class="mt-checkbox mt-checkbox-single mt-checkbox-outline">
																		<input type="checkbox" class="group-checkable" data-set="#sample_2 .checkboxes" />
																		<span></span>
																	</label>
																</th>
																<th width="8%"> ID </th>
																<th width="5%"> &nbsp; </th>
																<th width="200"> Product&nbsp;Name </th>
																<th width="100"> SKU </th>
																<th width="8%"> Cost </th>
																<th width="8%"> Price (D) </th>
																<th width="8%"> Quantity </th>
																<th width="10%"> Status </th>
																<th width="5%"> Actions </th>
															</tr>
															<tr role="row" class="filter">
																<td> </td>
																<td>
																	<input type="text" class="form-control form-filter input-sm" name="product_id"> 
																</td>
																<td> </td>
																<td>
																	<input type="text" class="form-control form-filter input-sm" name="product_name"> 
																</td>
																<td>
																	<input type="text" class="form-control form-filter input-sm" name="product_sku"> 
																</td>
																<td>
																	<div class="margin-bottom-5">
																		<input type="text" class="form-control form-filter input-sm" name="product_cost_from" placeholder="From" /> 
																	</div>
																	<input type="text" class="form-control form-filter input-sm" name="product_cost_to" placeholder="To" /> 
																</td>
																<td>
																	<div class="margin-bottom-5">
																		<input type="text" class="form-control form-filter input-sm" name="product_price_from" placeholder="From" /> 
																	</div>
																	<input type="text" class="form-control form-filter input-sm" name="product_price_to" placeholder="To" /> 
																</td>
																<td>
																	<div class="margin-bottom-5">
																		<input type="text" class="form-control form-filter input-sm" name="product_quantity_from" placeholder="From" /> 
																	</div>
																	<input type="text" class="form-control form-filter input-sm" name="product_quantity_to" placeholder="To" /> 
																</td>
																<td>
																	<select name="product_status" class="form-control form-filter input-sm">
																		<option value="">Select...</option>
																		<option value="0">Active</option>
																		<option value="1">Call for Avaialability</option>
																		<option value="2">Inactive</option>
																	</select>
																</td>
																<td>
																	<div class="margin-bottom-5">
																		<button class="btn btn-sm btn-success filter-submit margin-bottom">
																			<i class="fa fa-search"></i> Search</button>
																	</div>
																	<button class="btn btn-sm btn-default filter-cancel">
																		<i class="fa fa-times"></i> Reset</button>
																</td>
															</tr>
														</thead>
														<tbody> </tbody>
													</table>
												</div>
											</div>
										</div>
										<!-- End: life time stats -->
									</div>
								</div>
							</div>
							<!-- END PAGE CONTENT INNER -->
						</div>
					</div>
					<!-- END PAGE CONTENT BODY -->
					<!-- END CONTENT BODY -->
				</div>
				<!-- END CONTENT -->
			</div>
			<!-- END CONTAINER -->
		</div>
	</div>
	<div class="page-wrapper-row">
		<div class="page-wrapper-bottom">
			<!--#INCLUDE FILE="include/footer.phtml"-->
		</div>
	</div>
</div>
<!--#INCLUDE FILE="include/js.phtml"-->
<!-- BEGIN PAGE LEVEL PLUGINS -->
<script src="../assets/global/plugins/jquery-validation/js/jquery.validate.min.js" type="text/javascript"></script>
<script src="../assets/global/plugins/jquery-validation/js/additional-methods.min.js" type="text/javascript"></script>
<script src="../assets/global/scripts/datatable.js" type="text/javascript"></script>
<script src="../assets/global/plugins/datatables/datatables.min.js" type="text/javascript"></script>
<script src="../assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js" type="text/javascript"></script>
<script src="../assets/global/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js" type="text/javascript"></script>
<script src="../assets/global/plugins/bootstrap-maxlength/bootstrap-maxlength.min.js" type="text/javascript"></script>
<script src="../assets/global/plugins/fancybox/source/jquery.fancybox.pack.js" type="text/javascript"></script>
<!-- END PAGE LEVEL PLUGINS -->
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script type="text/javascript">
var EcommerceProducts = function () {

    var initPickers = function () {
        //init date pickers
        $('.date-picker').datepicker({
            rtl: App.isRTL(),
            autoclose: true
        });
    }

    var handleProducts = function() {
        var grid = new Datatable();

        grid.init({
            src: $("#datatable_products"),
            onSuccess: function (grid) {
                // execute some code after table records loaded
            },
            onError: function (grid) {
                // execute some code on network or other general error  
            },
            loadingMessage: 'Loading...',
            dataTable: { // here you can define a typical datatable settings from http://datatables.net/usage/options 

                // Uncomment below line("dom" parameter) to fix the dropdown overflow issue in the datatable cells. The default datatable layout
                // setup uses scrollable div(table-scrollable) with overflow:auto to enable vertical scroll(see: assets/global/scripts/datatable.js). 
                // So when dropdowns used the scrollable div should be removed. 
                //"dom": "<'row'<'col-md-8 col-sm-12'pli><'col-md-4 col-sm-12'<'table-group-actions pull-right'>>r>t<'row'<'col-md-8 col-sm-12'pli><'col-md-4 col-sm-12'>>",
				
				columnDefs: [ 
					{ orderable: false, targets: [0,2,9] },
					{ className: "text-center", targets: [2,8] },
					{ className: "text-right", targets: [5,6,7] }
				],
				"bStateSave": true,
                "lengthMenu": [
                    [10, 20, 50, 100, 150],
                    [10, 20, 50, 100, 150] // change per page values here 
                ],
                "pageLength": 20, // default record count per page
                "ajax": {
                    "url": "api/sp_product_list.phtml", // ajax source
                },
                "order": [
                    [1, "asc"]
                ] // set first column as a default sort by asc
            }
        });

         // handle group actionsubmit button click
        grid.getTableWrapper().on('click', '.table-group-action-submit', function (e) {
            e.preventDefault();
            var action = $(".table-group-action-input", grid.getTableWrapper());
            if (action.val() != "" && grid.getSelectedRowsCount() > 0) {
                grid.setAjaxParam("customActionType", "group_action");
                grid.setAjaxParam("customActionName", action.val());
                grid.setAjaxParam("id", grid.getSelectedRows());
                grid.getDataTable().ajax.reload();
                grid.clearAjaxParams();
            } else if (action.val() == "") {
                App.alert({
                    type: 'danger',
                    icon: 'warning',
                    message: 'Please select an action',
                    container: grid.getTableWrapper(),
                    place: 'prepend'
                });
            } else if (grid.getSelectedRowsCount() === 0) {
                App.alert({
                    type: 'danger',
                    icon: 'warning',
                    message: 'No record selected',
                    container: grid.getTableWrapper(),
                    place: 'prepend'
                });
            }
        });
    }

    return {

        //main function to initiate the module
        init: function () {

            handleProducts();
            initPickers();
            
        }

    };

}();

jQuery(document).ready(function() {    
   EcommerceProducts.init();
});	
</script>
<!-- END PAGE LEVEL SCRIPTS -->
</body>
</html>