<%
	Response.CodePage = 65001
	Response.CharSet = "UTF-8"
	
	storeviewid = Trim(Request("storeviewid"))
	if Len(storeviewid) > 0 then
		Session("CURRENT_ADMIN_VIEW_ID")  = storeviewid
	end if
%>
<!-- #INCLUDE File="local/local.phtml" -->
<!-- #INCLUDE File="util/xt_func_util.phtml" -->
<!-- #INCLUDE File="util/xt_func_string.phtml" -->
<!-- #INCLUDE File="include/i_login.phtml" -->
<%
	attribute_id = Trim(Request("id"))
	
	sql = "SELECT * FROM " & g_storeid & "_eav_attribute WHERE attribute_id=" & attribute_id
	set rs = dbconn.Execute(sql)
	if not rs.EOF then
		admin_label = rs("admin_label")
		frontend_label = rs("frontend_label")
		configurable = rs("configurable")
	end if
	rs.Close
	set rs = nothing
	
	if Session("CURRENT_ADMIN_VIEW_ID") <> "1" then
		frontend_label = TranslateX(frontend_label, 20, attribute_id, 1)
	end if
		
	'===============================================================================================
	'Options
	'===============================================================================================
	s_data = ""
	
	
		
	
%>
<!--#INCLUDE FILE="include/doctype.phtml"-->
<head>
<!--#INCLUDE FILE="include/head.phtml"-->
<!-- BEGIN PAGE LEVEL PLUGINS -->
<link rel="stylesheet" href="assets/plugins/jquery-ui/jquery-ui-1.10.4.custom.min.css" />
<link href="../assets/global/plugins/datatables/datatables.min.css" rel="stylesheet" type="text/css" />
<link href="../assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css" rel="stylesheet" type="text/css" />
<link href="../assets/global/plugins/bootstrap-datepicker/css/bootstrap-datepicker3.min.css" rel="stylesheet" type="text/css" />
<link href="../assets/global/plugins/fancybox/source/jquery.fancybox.css" rel="stylesheet" type="text/css" />
<!-- END PAGE LEVEL PLUGINS -->
<!--#INCLUDE FILE="include/head_bottom.phtml"-->
</head>

<body class="page-container-bg-solid">
<div class="page-wrapper">
	<div class="page-wrapper-row">
		<div class="page-wrapper-top">
			<!--#INCLUDE FILE="include/header.phtml"-->
		</div>
	</div>
	<div class="page-wrapper-row full-height">
		<div class="page-wrapper-middle">
			<!-- BEGIN CONTAINER -->
			<div class="page-container">
				<!-- BEGIN CONTENT -->
				<div class="page-content-wrapper">
					<!-- BEGIN CONTENT BODY -->
					<!-- BEGIN PAGE HEAD-->
					
					<!-- END PAGE HEAD-->
					<!-- BEGIN PAGE CONTENT BODY -->
					<div class="page-content">
						<div class="container-fluid">
							<!-- BEGIN PAGE CONTENT INNER -->
							<div class="page-content-inner">
								<div class="row">
									<div class="col-md-12">
										<form id="form_edit_1" class="form-horizontal form-row-seperated" action="#">
										<input type="hidden" id="attribute_id" name="attribute_id" value="<%=attribute_id%>">
											<div class="portlet">
												<div class="portlet-title">
													<div class="caption">
													<%
													if Len(frontend_label) > 0 then
														Response.Write(frontend_label)
													else
														Response.Write("New Filter")
													end if
													%>
													</div>
													<div class="actions btn-set">
														<button type="button" onclick="location.href='catalog_attribute.phtml';" name="back" class="btn btn-default">
															<i class="fa fa-angle-left"></i> Back
														</button>
														<button class="btn btn-success" onclick="savebutton='1';">
															<i class="fa fa-check"></i> Save
														</button>
														<button class="btn btn-success" onclick="savebutton='0';">
															<i class="fa fa-check-circle"></i> Save & Continue Edit
														</button>
														<div class="btn-group">
															<a class="btn btn-success dropdown-toggle" href="javascript:;" data-toggle="dropdown">
																<i class="fa fa-share"></i> More
																<i class="fa fa-angle-down"></i>
															</a>
															<div class="dropdown-menu pull-right">
																<!--
																<li>
																	<a href="javascript:;" id="DuplicateEntry"> Duplicate </a>
																</li>
																-->
																<li>
																	<a href="#" id="DeleteEntry"> Delete </a>
																</li>
															</div>
														</div>
													</div>
												</div>
												<div class="alert alert-danger display-hide">
												<button class="close" data-close="alert"></button> You have some form errors. Please check below. 
												</div>
												<div class="alert alert-success display-hide">
												<button class="close" data-close="alert"></button> The information has been saved.
												</div>
												<div class="alert alert-warning display-hide">
												<button class="close" data-close="alert"></button> The information has not been saved properly. Please contact system administrator.
												</div>
												<div class="portlet-body">
													<div class="tabbable-bordered">
														<ul id="myTab3" class="nav nav-tabs">
															<li class="active">
																<a href="#panel_tab4_example1" data-toggle="tab">
																	<i class="pink fa fa-info"></i> Information
																</a>
															</li>
															<% if attribute_id <> "0" then %>
															<li class="">
																<a href="#panel_tab4_example2" data-toggle="tab">
																	<i class="blue fa fa-info-circle"></i> Manage Options
																</a>
															</li>
															<% end if %>
														</ul>
														
														<div class="tab-content">
															<div class="tab-pane active" id="panel_tab4_example1">
																<div class="row">
																	<div class="col-sm-6">
																		<div class="form-group">
																			<label class="col-sm-4 control-label" for="admin_label">
																				Name <span class="symbol required"></span> 
																			</label>
																			<div class="col-sm-8">
																				<input type="text" placeholder="" id="admin_label" name="admin_label" class="form-control input-sm" value="<%=admin_label%>">
																			</div>
																		</div>
																		<div class="form-group">
																			<label class="col-sm-4 control-label" for="frontend_label">
																				Display Name <span class="symbol required"></span> 
																			</label>
																			<div class="col-sm-8">
																				<input type="text" placeholder="" id="frontend_label" name="frontend_label" class="form-control input-sm" value="<%=frontend_label%>">
																			</div>
																		</div>
																		<div class="form-group">
																			<label class="col-sm-4 control-label" for="configurable">
																				Use for Configurable <span class="symbol required"></span> 
																			</label>
																			<div class="col-sm-8">
																				<select class="form-control input-sm" name="configurable" id="configurable">
																					<option value="0" <%if configurable=0 then%>selected<%end if%>>No</option>
																					<option value="1" <%if configurable=1 then%>selected<%end if%>>Yes</option>
																				</select>
																			</div>
																		</div>
																	</div>
																</div>
															</div>
															<div class="tab-pane" id="panel_tab4_example2">
																<div class="row">
																	<div class="col-md-12">
																		<div class="table-container">
																			<div class="table-actions-wrapper">
																				<span> </span>
																				<select class="table-group-action-input form-control input-inline input-small input-sm">
																					<option value="">Select...</option>
																					<option value="active">Active</option>
																					<option value="inactive">Inactive</option>
																					<option value="delete">Delete</option>
																				</select>
																				<button class="btn btn-sm btn-success table-group-action-submit">
																					<i class="fa fa-check"></i> Submit</button>
																			</div>
																			<table class="table table-striped table-bordered table-hover table-checkable" id="datatable_products">
																				<thead>
																					<tr role="row" class="heading">
																						<th width="1%">
																							<label class="mt-checkbox mt-checkbox-single mt-checkbox-outline">
																								<input type="checkbox" class="group-checkable" data-set="#sample_2 .checkboxes" />
																								<span></span>
																							</label>
																						</th>
																						<th width="8%"> ID </th>
																						<th width="5%"> &nbsp; </th>
																						<th width="100"> Option Name </th>
																						<th width="100"> Option Display </th>
																						<th width="100"> Description </th>
																						<th width="8%"> Manufacturer </th>
																						<th width="8%"> Sort Order </th>
																						<th width="5%"> Actions </th>
																					</tr>
																					<tr role="row" class="filter">
																						<td> </td>
																						<td>
																							
																						</td>
																						<td> </td>
																						<td>
																							<input type="text" class="form-control form-filter input-sm" name="option_name" value=""> 
																						</td>
																						<td>
																							<input type="text" class="form-control form-filter input-sm" name="option_display_name" value=""> 
																						</td>
																						<td>
																							<input type="text" class="form-control form-filter input-sm" name="option_description" value=""> 
																						</td>
																						<td>
																							<select name="option_mfg" class="form-control form-filter input-sm">
																								<option value="">Select...</option>
																								<%
																									sql = "SELECT * FROM " & g_storeid & "_mfg ORDER BY mfg_name"
																									set rsM = dbconn.Execute(sql)
																									do while not rsM.EOF
																								%>
																								<option value="<%=rsM("mfg_id")%>"><%=rsM("mfg_name")%></option>
																								<%
																										rsM.MoveNext
																									loop
																									rsM.Close
																									set rsM = nothing
																								%>
																							</select>
																						</td>
																						<td>
																							
																						</td>
																						<td>
																							<div class="margin-bottom-5">
																								<button class="btn btn-sm btn-success filter-submit margin-bottom">
																									<i class="fa fa-search"></i> Search</button>
																							</div>
																							<button class="btn btn-sm btn-default filter-cancel">
																								<i class="fa fa-times"></i> Reset</button>
																						</td>
																					</tr>
																				</thead>
																				<tbody> </tbody>
																			</table>
																		</div>
																	</div>
																	<input type="hidden" name="attribute_option_data" id="attribute_option_data" value="">
																</div>
															</div>
														</div>
													</div>
												</div>
											</div>
										</form>
									</div>
								</div>
							</div>
							<!-- END PAGE CONTENT INNER -->
						</div>
					</div>
					<!-- END PAGE CONTENT BODY -->
					<!-- END CONTENT BODY -->
				</div>
				<!-- END CONTENT -->
			</div>
			<!-- END CONTAINER -->
		</div>
	</div>
	<div class="page-wrapper-row">
		<div class="page-wrapper-bottom">
			<!--#INCLUDE FILE="include/footer.phtml"-->
		</div>
	</div>
</div>
<!--#INCLUDE FILE="include/js.phtml"-->
<!-- BEGIN PAGE LEVEL PLUGINS -->
<script src="../assets/global/plugins/jquery-validation/js/jquery.validate.min.js" type="text/javascript"></script>
<script src="../assets/global/plugins/jquery-validation/js/additional-methods.min.js" type="text/javascript"></script>
<script src="assets/plugins/jquery-ui/jquery-ui-1.10.1.custom.min.js" type="text/javascript"></script>
<script src="../assets/global/scripts/datatable.js" type="text/javascript"></script>
<script src="../assets/global/plugins/datatables/datatables.min.js" type="text/javascript"></script>
<script src="../assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js" type="text/javascript"></script>
<script src="../assets/global/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js" type="text/javascript"></script>
<script src="../assets/global/plugins/bootstrap-maxlength/bootstrap-maxlength.min.js" type="text/javascript"></script>
<script src="../assets/global/plugins/fancybox/source/jquery.fancybox.pack.js" type="text/javascript"></script>
<!-- END PAGE LEVEL PLUGINS -->

<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script>
var data0, grid0, dialog0;
</script>
<script type="text/javascript">
 var grid;
var iFilter = 1;

var EcommerceOptions = function () {

    var initPickers = function () {
        //init date pickers
        $('.date-picker').datepicker({
            rtl: App.isRTL(),
            autoclose: true
        });
    }

    var handleOptions = function() {
        grid = new Datatable();

        grid.init({
            src: $("#datatable_products"),
            onSuccess: function (grid) {
               
            },
            onError: function (grid) {
                // execute some code on network or other general error  
            },
            loadingMessage: 'Loading...',
            dataTable: { // here you can define a typical datatable settings from http://datatables.net/usage/options 

                // Uncomment below line("dom" parameter) to fix the dropdown overflow issue in the datatable cells. The default datatable layout
                // setup uses scrollable div(table-scrollable) with overflow:auto to enable vertical scroll(see: assets/global/scripts/datatable.js). 
                // So when dropdowns used the scrollable div should be removed. 
                //"dom": "<'row'<'col-md-8 col-sm-12'pli><'col-md-4 col-sm-12'<'table-group-actions pull-right'>>r>t<'row'<'col-md-8 col-sm-12'pli><'col-md-4 col-sm-12'>>",
				
				columnDefs: [ 
					{ orderable: false, targets: [0] }
				],
				"bStateSave": true,
                "lengthMenu": [
                    [10, 20, 50, 100, 150],
                    [10, 20, 50, 100, 150] // change per page values here 
                ],
                "pageLength": 20, // default record count per page
                "ajax": {
                    "url": "api/sp_catalog_attribute_options.phtml?attribute_id=<%=attribute_id%>", // ajax source
                },
                "order": [
                    [1, "desc"]
                ] // set first column as a default sort by asc
            }
        });
		
    }

    return {

        //main function to initiate the module
        init: function () {

            handleOptions();
            initPickers();
            
        },
		
		 submitFilter: function () {

            grid.submitFilter();
        }

    };

}();
</script>
<script language="javascript">
var savebutton = "1";
var FormValidation = function () {
	// basic validation
	var handleValidation1 = function() {
		var form1 = $('#form_edit_1');
		var error1 = $('.alert-danger', form1);
		var success1 = $('.alert-success', form1);
		var warning1 = $('.alert-warning', form1);

		form1.validate({
			errorElement: 'span', //default input error message container
			errorClass: 'help-block help-block-error', // default input error message class
			focusInvalid: false, // do not focus the last invalid input
			ignore: "",  // validate all fields including form hidden input
			//RULES
			rules: {
				
				pf_name: {
					minlength: 2,
					required: true
				}
				
			},

			invalidHandler: function (event, validator) { //display error alert on form submit              
				success1.hide();
				warning1.hide();
				error1.show();
				App.scrollTo(error1, -200);
			},

			errorPlacement: function (error, element) { // render error placement for each input type
				var cont = $(element).parent('.input-group');
				if (cont) {
					cont.after(error);
				} else {
					element.after(error);
				}
			},

			highlight: function (element) { // hightlight error inputs

				$(element)
					.closest('.form-group').addClass('has-error'); // set error class to the control group
			},

			unhighlight: function (element) { // revert the change done by hightlight
				$(element)
					.closest('.form-group').removeClass('has-error'); // set error class to the control group
			},

			success: function (label) {
				label
					.closest('.form-group').removeClass('has-error'); // set success class to the control group
			},

			submitHandler: function (form) {
				success1.hide();
				error1.hide
				warning1.hide();
				
				window.scrollTo(0,0);
				
				$.ajax({
					type: "POST",
					url: "api/sp_catalog_attribute_update.phtml",
					data: form1.serialize(),
					success: function() {
						success1.show();
						if (savebutton == "1")
						{
						setTimeout(function () {
								window.location.replace("catalog_attribute.phtml");
							}, 500);
						}
					},
					error: function() {
						warning1.show();
					}
				});
			}
		});


	}
	return {
		//main function to initiate the module
		init: function () {
			handleValidation1();
		}
	};

}();
</script>
<script>
jQuery(document).ready(function() {
	FormValidation.init();
	EcommerceOptions.init();
});
</script>
<!-- END PAGE LEVEL SCRIPTS -->
</body>
</html>