<%
	Response.CodePage = 65001
	Response.CharSet = "UTF-8"
%>
<!-- #INCLUDE File="local/local.phtml" -->
<!-- #INCLUDE File="util/xt_func_util.phtml" -->
<!-- #INCLUDE File="util/xt_func_string.phtml" -->
<!-- #include file="aspuploader/include_aspuploader.asp" -->
<!-- #INCLUDE File="include/i_login.phtml" -->
<%
	g_access_key = "02-a"
%>
<!-- #INCLUDE File="include/i_access.phtml" -->
<!--#INCLUDE FILE="include/doctype.phtml"-->
<head>
<!--#INCLUDE FILE="include/head.phtml"-->
<!-- BEGIN PAGE LEVEL PLUGINS -->
<link rel="stylesheet" href="assets/plugins/jquery-ui/jquery-ui-1.10.4.custom.min.css" />
<link rel="stylesheet" href="assets/plugins/dynatree/src/skin-vista/ui.dynatree.css">
<link href="../assets/global/plugins/datatables/datatables.min.css" rel="stylesheet" type="text/css" />
<link href="../assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css" rel="stylesheet" type="text/css" />
<link href="../assets/global/plugins/bootstrap-datepicker/css/bootstrap-datepicker3.min.css" rel="stylesheet" type="text/css" />
<link href="../assets/global/plugins/fancybox/source/jquery.fancybox.css" rel="stylesheet" type="text/css" />
<link href="../assets/global/plugins/bootstrap-modal/css/bootstrap-modal-bs3patch.css" rel="stylesheet" type="text/css" />
<link href="../assets/global/plugins/bootstrap-modal/css/bootstrap-modal.css" rel="stylesheet" type="text/css" />
<!-- END PAGE LEVEL PLUGINS -->
</head>

<body class="page-container-bg-solid">
<div class="page-wrapper">
	<div class="page-wrapper-row">
		<div class="page-wrapper-top">
			<!--#INCLUDE FILE="include/header.phtml"-->
		</div>
	</div>
	<div class="page-wrapper-row full-height">
		<div class="page-wrapper-middle">
			<!-- BEGIN CONTAINER -->
			<div class="page-container">
				<!-- BEGIN CONTENT -->
				<div class="page-content-wrapper">
					<!-- BEGIN CONTENT BODY -->
					<!-- BEGIN PAGE CONTENT BODY -->
					<div class="page-content">
						<div class="container-fluid">
							<!-- BEGIN PAGE CONTENT INNER -->
							<div class="page-content-inner">
								<div class="page-content">
									<div class="container-fluid">
										<!-- BEGIN PAGE CONTENT INNER -->
										<div class="page-content-inner">
											<div class="row">
												<div class="col-md-12">
													<form id="form_edit_1" class="form-horizontal form-row-seperated" action="#">
														<div class="portlet">
															<div class="portlet-title">
																<div class="caption">
																<i class="fa fa-shopping-cart"></i>
																Category
																</div>
																<div class="actions btn-set">
																	<button class="btn btn-success">
																		<i class="fa fa-check"></i> Save
																	</button>
																	<div class="btn-group">
																		<a class="btn btn-success dropdown-toggle" href="javascript:;" data-toggle="dropdown">
																			<i class="fa fa-share"></i> More
																			<i class="fa fa-angle-down"></i>
																		</a>
																		<div class="dropdown-menu pull-right">
																			<li>
																				<a href="javascript:;" id="DeleteCategory"> Delete </a>
																			</li>
																		</div>
																	</div>
																</div>
															</div>
															<div class="alert alert-danger display-hide">
															<button class="close" data-close="alert"></button> You have some form errors. Please check below. 
															</div>
															<div class="alert alert-success display-hide">
															<button class="close" data-close="alert"></button> Your form validation is successful! 
															</div>
															<div class="portlet-body">
																<div class="row">
																	<div class="col-md-3">
																		<div class="row">
																			<div class="col-md-12">
																			<!-- start: DEFAULT TREE PANEL -->
																			<div class="panel panel-primary">
																				<div class="panel-heading">
																					<h4 class="panel-title">Categories</h4>
																				</div>
																				<div class="panel-body">
																					<% if Session("CURRENT_ADMIN_VIEW_ID") = "1" then %>
																					<div class="row" style="padding-bottom: 10px;">
																						<div class="col-md-12">
																							<a data-toggle="modal" class="btn btn-primary btn-sm" role="button" href="#myModal1">
																							<i class="clip-plus-circle"></i> Add Root</a>
																							<a data-toggle="modal" class="btn btn-primary btn-sm" role="button" href="#myModal2">
																							<i class="clip-plus-circle"></i> Add Sub</a>
																						</div>
																					</div>
																					<% end if %>
																					<div id="tree3"></div>
																				</div>
																				
																			</div>
																			<!-- end: DEFAULT TREE PANEL -->
																			</div>
																		</div>
																	</div>
																	<div class="col-md-9">
																		<div class="panel panel-primary">
																			<div class="panel-heading">
																				<h4 class="panel-title" id="mainTitle1">Category Detail</h4>
																			</div>
																			<div class="panel-body">
																				<div class="row">
																					<div class="col-md-12">
																						<span id="dept_detail">
																						<p>Select existing category on the left or click on the "add" button to add new category.
																						</span>
																					</div>
																				</div>
																			</div>
																		</div>
																	</div>
																</div>
															</div>
														</div>
													</div>
												</div>
											</div>
										</div>
									</div>
								</div>										
							</div>
							<!-- END PAGE CONTENT INNER -->
						</div>
					</div>
					<!-- END PAGE CONTENT BODY -->
					<!-- END CONTENT BODY -->
				</div>
				<!-- END CONTENT -->
			</div>
			<!-- END CONTAINER -->
		</div>
	</div>
	<div class="page-wrapper-row">
		<div class="page-wrapper-bottom">
			<!--#INCLUDE FILE="include/footer.phtml"-->
		</div>
	</div>
</div>

<div class="modal fade" id="myModal1" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
			&times;
		</button>
		<h4 class="modal-title">Add New Category</h4>
	</div>
	<div class="modal-body">
		<p>
			Would you like to add new Root Cateogry?
		</p>
	</div>
	<div class="modal-footer">
		<button aria-hidden="true" data-dismiss="modal" class="btn btn-default">
			Close
		</button>
		<button class="btn btn-primary" data-dismiss="modal" id="btn-add-root-category-confirm">
			Confirm
		</button>
	</div>
</div>

<div class="modal fade" id="myModal2" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
			&times;
		</button>
		<h4 class="modal-title">Add Sub Category</h4>
	</div>
	<div class="modal-body">
		<p>
			Would you like to add Sub Category under currently selected category?
		</p>
	</div>
	<div class="modal-footer">
		<button aria-hidden="true" data-dismiss="modal" class="btn btn-default">
			Close
		</button>
		<button class="btn btn-primary" data-dismiss="modal" id="btn-add-sub-category-confirm">
			Confirm
		</button>
	</div>
</div>
<div id="loading-mask" style="display:none">
	<p class="loader" id="loading_mask_loader"><img src="assets/images/ajax-loader-primary.gif" alt="Loading..."/><br/>Please wait...</p>
</div>
<div id="dialog-confirm" title="Confirmation Required">
  Are you sure you want to do this?
</div>
<!--#INCLUDE FILE="include/js.phtml"-->
<!-- BEGIN PAGE LEVEL PLUGINS -->
<script src="../assets/global/plugins/jquery-validation/js/jquery.validate.min.js" type="text/javascript"></script>
<script src="../assets/global/plugins/jquery-validation/js/additional-methods.min.js" type="text/javascript"></script>
<script src="assets/plugins/jquery-ui/jquery-ui-1.10.1.custom.min.js" type="text/javascript"></script>
<script src="assets/plugins/dynatree/src/jquery.dynatree.js"></script>
<script src="../assets/global/scripts/datatable.js" type="text/javascript"></script>
<script src="../assets/global/plugins/datatables/datatables.min.js" type="text/javascript"></script>
<script src="../assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js" type="text/javascript"></script>
<script src="../assets/global/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js" type="text/javascript"></script>
<script src="../assets/global/plugins/bootstrap-maxlength/bootstrap-maxlength.min.js" type="text/javascript"></script>
<script src="../assets/global/plugins/fancybox/source/jquery.fancybox.pack.js" type="text/javascript"></script>
<script src="../assets/global/plugins/bootstrap-modal/js/bootstrap-modalmanager.js" type="text/javascript"></script>
<script src="../assets/global/plugins/bootstrap-modal/js/bootstrap-modal.js" type="text/javascript"></script>
<!-- END PAGE LEVEL PLUGINS -->
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script language="javascript">
var FormValidation = function () {

	// basic validation
	var handleValidation1 = function() {
		// for more info visit the official plugin documentation: 
		// http://docs.jquery.com/Plugins/Validation

		var form1 = $('#form_edit_1');
		var error1 = $('.alert-danger', form1);
		var success1 = $('.alert-success', form1);

		form1.validate({
			errorElement: 'span', //default input error message container
			errorClass: 'help-block help-block-error', // default input error message class
			focusInvalid: false, // do not focus the last invalid input
			ignore: "",  // validate all fields including form hidden input
			//RULES
			rules: {
				dept_name: {
					minlength: 2,
					required: true
				},
				dept_markup_A: {
					number: true
				},
				url_key: {
					minlength: 3,
					"remote":
					{
					  url: 'api/sp_product_check_url_key.phtml?pf_id=' + $('#dept_id').val(),
					  type: "post"
					}
				}
			},
			messages: {
				dept_name: "Please specify category name",
				url_key:
				{
					minlength: "The URL Key must be greater than 3 chracter length.",
					remote: "The specified URL Key is not unique."
				}
			},

			invalidHandler: function (event, validator) { //display error alert on form submit              
				success1.hide();
				error1.show();
				App.scrollTo(error1, -200);
			},

			highlight: function (element) { // hightlight error inputs

				$(element)
					.closest('.form-group').addClass('has-error'); // set error class to the control group
			},

			unhighlight: function (element) { // revert the change done by hightlight
				$(element)
					.closest('.form-group').removeClass('has-error'); // set error class to the control group
			},

			success: function (label) {
				label
					.closest('.form-group').removeClass('has-error'); // set success class to the control group
			},

			submitHandler: function (form) {
				success1.hide();
				error1.hide();
				
				$.ajax({
					type: "POST",
					url: "api/sp_catalog_category_update.phtml",
					data: $("#form_edit_1").serialize(),
					success: function() {
						success1.show();
						window.scrollTo(0,0);
						$("#tree3").dynatree("getTree").reload();
						
					},
					error: function() {
						error1.show();
						window.scrollTo(0,0);
					}
				});
			}
		});

	}
	return {
		//main function to initiate the module
		init: function () {
			handleValidation1();
		}
	};

}();
</script>
<script language="javascript">
var theActivatedCategory = "0";

var UITreeview = function () {
	//function to initiate jquery.dynatree
	var runTreeView = function () {
		//External data 
		$("#tree3").dynatree({
			initAjax: {
				url: "api/sp_catalog_category_get_tree_list.phtml",
				data: { mode: "funnyMode" }
			},
			
			onActivate: function (node) {
				theActivatedCategory = node.data.key;
				$('#loading-mask').show();
				jQuery.ajax({
					type:"get",
					url: "api/sp_catalog_category_get_edit_detail_html.phtml",
					data: {'category_id' : node.data.key, 'isAjax':true},
					dataType: 'html',
					success: function(data) {
						jQuery("#dept_detail").html(data);
					},
					complete: function(){
						$('#loading-mask').hide();
						$('#mainTitle1').html(node.data.title + " (ID:" + node.data.key + ")");
						$('#mainTitle2').html(node.data.title + " (ID:" + node.data.key + ")");
						window.scrollTo(0,0);
						$('a[data-toggle="tab"]').on('shown.bs.tab', function (e) {
							var target = $(e.target).attr("href") // activated tab
							//alert(target);
							jQuery.ajax({
								type:"get",
								url: "api/save_tab_session.phtml",
								data: {'tabtarget' : target, 'tabpage' : 'catalog_category_tab', 'isAjax':true},
								dataType: 'html',
								success: function(data) {
									//
								}
							});
						  
						  //
						});
					}
				});
			},
			onDeactivate: function (node) {
				//$("#echoActive").text("-");
			},
			
			onCreate: function(node, nodeSpan) {
				$("#tree3").dynatree("getTree").activateKey(jQuery("#dept_id").val());
			},
			
			dnd: {
				preventVoidMoves: true, // Prevent dropping nodes 'before self', etc.
				onDragStart: function (node) {
					/** This function MUST be defined to enable dragging for the tree.
					 *  Return false to cancel dragging of node.
					 */
					return true;
				},
				onDragEnter: function (node, sourceNode) {
					/** sourceNode may be null for non-dynatree droppables.
					 *  Return false to disallow dropping on node. In this case
					 *  onDragOver and onDragLeave are not called.
					 *  Return 'over', 'before, or 'after' to force a hitMode.
					 *  Return ['before', 'after'] to restrict available hitModes.
					 *  Any other return value will calc the hitMode from the cursor position.
					 */
					// Prevent dropping a parent below another parent (only sort
					// nodes under the same parent)
					if (node.parent !== sourceNode.parent) {
						return false;
					}
					// Don't allow dropping *over* a node (would create a child)
					return ["before", "after"];
					//return true;
				},
				onDrop: function (node, sourceNode, hitMode, ui, draggable) {
					/** This function MUST be defined to enable dropping of items on
					 *  the tree.
					 */
					var souce_key = "";
					var dest_key = "";

					souce_key = sourceNode.data.key;
					dest_key = node.data.key;

					//alert(souce_key);
					//alert(dest_key);
					sourceNode.move(node, hitMode);

					jQuery.ajax({
						type: "get",
						url: "api/sp_catalog_category_update.phtml",
						data: { 'config_id': '<%=config_id%>', 'mode': 'gsort', 'skey': souce_key, 'dkey': dest_key, isAjax: true },
						dataType: 'json',
						success: function (data) {
							//$("#tree3").dynatree("getTree").reload();
						}
					});
					
				}
			}
		});
		
	};
	return {
		//main function to initiate template pages
		init: function () {
			runTreeView();
		}
	};
}();

</script>
<script type="text/javascript">
jQuery(document).ready(function() {    
   //EcommerceProductsEdit.init();
   UITreeview.init();
   FormValidation.init();
   
	$("#dialog-confirm").dialog({
	  autoOpen: false,
	  modal: true
	});
	
	jQuery("#DeleteCategory").click(function(e) {
		e.preventDefault();
		jQuery("#dialog-confirm").html('Are you sure you want to delete "' + jQuery("#dept_name").val() + '"? <br>This will delete current category as well as all sub categories.');
		jQuery("#dialog-confirm").dialog({
		  autoOpen: false,
		  modal: true,
		  buttons : {
			"Confirm" : function() {
				window.location.href = "api/tp_catalog_category_delete.phtml?category_id=" + jQuery("#dept_id").val();
			},
			"Cancel" : function() {
			  $(this).dialog("close");
			}
		  }
		});
		jQuery("#dialog-confirm").dialog("open");

	});
			
   jQuery("#btn-add-root-category-confirm").click(function() {
		$('#loading-mask').show();
			jQuery.ajax({
				type:"get",
				url: "api/sp_catalog_category_get_edit_detail_html.phtml",
				data: {'category_id' : '0', 'parent_id' : '0', 'isAjax':true},
				dataType: 'html',
				success: function(data) {
					jQuery("#dept_detail").html(data);
				},
				complete: function(){
					$('#loading-mask').hide();
					$('#mainTitle1').html("New Category");
					$('#mainTitle2').html("New Category");
					window.scrollTo(0,0);
					$('a[data-toggle="tab"]').on('shown.bs.tab', function (e) {
						var target = $(e.target).attr("href") // activated tab
						jQuery.ajax({
							type:"get",
							url: "api/save_tab_session.phtml",
							data: {'tabtarget' : target, 'tabpage' : 'catalog_category_tab', 'isAjax':true},
							dataType: 'html',
							success: function(data) {
								//
							}
						});
					  
					  //
					});
				}
			});
	});
	
	jQuery("#btn-add-sub-category-confirm").click(function() {
		if (theActivatedCategory == '0')
		{
			alert("Please select category first")
		}
		else
		{
			$('#loading-mask').show();
			jQuery.ajax({
				type:"get",
				url: "api/sp_catalog_category_get_edit_detail_html.phtml",
				data: {'category_id' :'0', 'parent_id' : theActivatedCategory, 'isAjax':true},
				dataType: 'html',
				success: function(data) {
					jQuery("#dept_detail").html(data);
				},
				complete: function(){
					$('#loading-mask').hide();
					$('#mainTitle1').html(node.data.title + "(ID:" + node.data.key + ")");
					$('#mainTitle2').html(node.data.title + "(ID:" + node.data.key + ")");
					window.scrollTo(0,0);
					$('a[data-toggle="tab"]').on('shown.bs.tab', function (e) {
						var target = $(e.target).attr("href") // activated tab
						//alert(target);
						jQuery.ajax({
							type:"get",
							url: "api/save_tab_session.phtml",
							data: {'tabtarget' : target, 'tabpage' : 'catalog_category_tab', isAjax:true},
							dataType: 'html',
							success: function(data) {
								//
							}
						});
					  
					  //
					});
				}
			});
		}
	});
} );
</script>
<!-- END PAGE LEVEL SCRIPTS -->
</body>
</html>