<!-- #INCLUDE File="local/local.phtml" -->
<!-- #INCLUDE File="util/xt_func_util.phtml" -->
<!-- #INCLUDE File="util/xt_func_string.phtml" -->
<!-- #INCLUDE File="include/i_login.phtml" -->
<!--#INCLUDE FILE="include/doctype.phtml"-->
<head>
<!--#INCLUDE FILE="include/head.phtml"-->
<!-- BEGIN PAGE LEVEL PLUGINS -->
<!-- END PAGE LEVEL PLUGINS -->
</head>

<body class="page-container-bg-solid">
<div class="page-wrapper">
	<div class="page-wrapper-row">
		<div class="page-wrapper-top">
			<!--#INCLUDE FILE="include/header.phtml"-->
		</div>
	</div>
	<div class="page-wrapper-row full-height">
		<div class="page-wrapper-middle">
			<!-- BEGIN CONTAINER -->
			<div class="page-container">
				<!-- BEGIN CONTENT -->
				<div class="page-content-wrapper">
					<!-- BEGIN CONTENT BODY -->
					<!-- BEGIN PAGE HEAD-->
					<div class="page-head">
						<div class="container-fluid">
							<!-- BEGIN PAGE TITLE -->
							<div class="page-title">
								<h1>ICECAT Browser
									<small>overview & list</small>
								</h1>
							</div>
							<!-- END PAGE TITLE -->
						</div>
					</div>
					<!-- END PAGE HEAD-->
					<!-- BEGIN PAGE CONTENT BODY -->
					<div class="page-content">
						<div class="container-fluid">
							<!-- BEGIN PAGE CONTENT INNER -->
							<div class="page-content-inner">
								<div class="panel-group accordion" id="accordion3">
									<%
										iii = 1
										sql = "SELECT * FROM A_ICECAT_Category as a, A_ICECAT_Category_Name as b WHERE a.Id = b.EntityId AND a.ParentId = 2833"
										set rs1 = dbconn_icecat.Execute(sql)
										do while not rs1.EOF
									%>
									<div class="panel panel-default">
										<div class="panel-heading">
											<h4 class="panel-title">
												<a class="accordion-toggle accordion-toggle-styled collapsed" data-toggle="collapse" data-parent="#accordion3" href="#collapse_3_<%=iii%>"> <%=rs1("value")%> </a>
											</h4>
										</div>
										<div id="collapse_3_<%=iii%>" class="panel-collapse collapse">
											<div class="panel-body" style="height:200px; overflow-y:auto;">
												<%
													sql = "SELECT * FROM A_ICECAT_Category as a, A_ICECAT_Category_Name as b WHERE a.Id = b.EntityId AND a.ParentId = " & rs1(0)
													set rs2 = dbconn_icecat.Execute(sql)
													do while not rs2.EOF
												%>
												<a href="#" class="btn btn-green btn-sm margin-bottom-10" onclick="window.location.href='catalog_icecat_browser_list.phtml?categoryid=<%=rs2(0)%>'"><%=rs2("value")%></a>
												<%
														rs2.MoveNext
													loop
													rs2.Close
													set rs2 = nothing
												%>
											</div>
										</div>
									</div>
									<%
											iii = iii + 1
											rs1.MoveNext
										loop
										rs1.Close
										set rs1 = nothing
									%>
								</div>
							</div>
							<!-- END PAGE CONTENT INNER -->
						</div>
					</div>
					<!-- END PAGE CONTENT BODY -->
					<!-- END CONTENT BODY -->
				</div>
				<!-- END CONTENT -->
			</div>
			<!-- END CONTAINER -->
		</div>
	</div>
	<div class="page-wrapper-row">
		<div class="page-wrapper-bottom">
			<!--#INCLUDE FILE="include/footer.phtml"-->
		</div>
	</div>
</div>
<!--#INCLUDE FILE="include/js.phtml"-->
<!-- BEGIN PAGE LEVEL PLUGINS -->

<!-- END PAGE LEVEL PLUGINS -->

<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script type="text/javascript">
	
</script>
<!-- END PAGE LEVEL SCRIPTS -->
</body>
</html>