<%
	Response.CodePage = 65001
	Response.CharSet = "UTF-8"
%>
<!-- #INCLUDE File="local/local.phtml" -->
<!-- #INCLUDE File="util/xt_func_util.phtml" -->
<!-- #INCLUDE File="util/xt_func_string.phtml" -->
<!-- #INCLUDE File="include/i_login.phtml" -->
<!--#INCLUDE FILE="include/doctype.phtml"-->
<head>
<!--#INCLUDE FILE="include/head.phtml"-->
<!-- BEGIN PAGE LEVEL PLUGINS -->
<!-- END PAGE LEVEL PLUGINS -->
</head>

<body class="page-container-bg-solid">
<div class="page-wrapper">
	<div class="page-wrapper-row">
		<div class="page-wrapper-top">
			<!--#INCLUDE FILE="include/header.phtml"-->
		</div>
	</div>
	<div class="page-wrapper-row full-height">
		<div class="page-wrapper-middle">
			<!-- BEGIN CONTAINER -->
			<div class="page-container">
				<!-- BEGIN CONTENT -->
				<div class="page-content-wrapper">
					<!-- BEGIN CONTENT BODY -->
					
					<!-- BEGIN PAGE CONTENT BODY -->
					<div class="page-content">
						<div class="container-fluid">
							<!-- BEGIN PAGE CONTENT INNER -->
							<div class="page-content-inner">
								<div class="row">
									<div class="col-md-12">
										<!-- Begin: life time stats -->
										<div class="portlet light portlet-fit portlet-datatable">
											<div class="portlet-title">
												<div class="caption">
													<i class="fa fa-shopping-cart"></i>Filter Attibutes
												</div>
												<div class="actions">
													<% if Session("CURRENT_ADMIN_VIEW_ID") = "1" then %>
													<a href="catalog_attribute_detail.phtml?id=0" class="btn btn-circle btn-info">
													<i class="fa fa-plus"></i> Add New Filter
													</a>
													<% end if %>
													<div class="btn-group">
														
													</div>
												</div>
											</div>
											<div class="portlet-body">
												<div class="table-container">
													<table class="table table-hover" id="sample-table-1">
														<thead>
															<tr>
																<th class="center">#</th>
																<th>Filter Name</th>
																<th></th>
															</tr>
														</thead>
														<tbody>
															<%
																sql = "SELECT * FROM " & g_storeid & "_eav_attribute"
																set rs = dbconn.Execute(sql)
																do while not rs.EOF
																	attribute_id = rs("attribute_id")
																	frontend_label = rs("frontend_label")
																	if Session("CURRENT_ADMIN_VIEW_ID") <> "1" then
																		frontend_label = TranslateX(frontend_label, 20, attribute_id, 1)
																	end if
															%>
															<tr>
																<td class="center"><%=attribute_id%></td>
																<td><%=frontend_label%></td>
																<td class="center">
																<div class="visible-md visible-lg hidden-sm hidden-xs">
																	<a href="catalog_attribute_detail.phtml?id=<%=attribute_id%>" class="btn btn-transparent btn-xs" tooltip-placement="top" tooltip="Edit"><i class="fa fa-pencil"></i></a>
																</div>
																<div class="visible-xs visible-sm hidden-md hidden-lg">
																	<div class="btn-group" dropdown is-open="status.isopen">
																		<button type="button" class="btn btn-primary btn-o btn-sm dropdown-toggle" dropdown-toggle>
																			<i class="fa fa-cog"></i>&nbsp;<span class="caret"></span>
																		</button>
																		<ul class="dropdown-menu pull-right dropdown-light" role="menu">
																			<li>
																				<a href="catalog_attribute_detail.phtml?id=<%=attribute_id%>">
																					Edit
																				</a>
																			</li>
																		</ul>
																	</div>
																</div></td>
															</tr>
															<%
																	rs.MoveNext
																loop
																rs.Close
																set rs = nothing
															%>
														</tbody>
													</table>
												</div>
											</div>
										</div>
									</div>
								</div>
								
							</div>
							<!-- END PAGE CONTENT INNER -->
						</div>
					</div>
					<!-- END PAGE CONTENT BODY -->
					<!-- END CONTENT BODY -->
				</div>
				<!-- END CONTENT -->
			</div>
			<!-- END CONTAINER -->
		</div>
	</div>
	<div class="page-wrapper-row">
		<div class="page-wrapper-bottom">
			<!--#INCLUDE FILE="include/footer.phtml"-->
		</div>
	</div>
</div>
<!--#INCLUDE FILE="include/js.phtml"-->
<!-- BEGIN PAGE LEVEL PLUGINS -->

<!-- END PAGE LEVEL PLUGINS -->

<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script type="text/javascript">
	
</script>
<!-- END PAGE LEVEL SCRIPTS -->
</body>
</html>