<!-- #INCLUDE File="local/local.phtml" -->
<!-- #INCLUDE File="util/xt_func_util.phtml" -->
<!-- #INCLUDE File="util/xt_func_string.phtml" -->
<!-- #INCLUDE File="include/i_login.phtml" -->
<!--#INCLUDE FILE="include/doctype.phtml"-->
<head>
<!--#INCLUDE FILE="include/head.phtml"-->
<!-- BEGIN PAGE LEVEL PLUGINS -->
<link href="../assets/global/plugins/bootstrap-daterangepicker/daterangepicker.min.css" rel="stylesheet" type="text/css" />
<link href="../assets/global/plugins/fullcalendar/fullcalendar.min.css" rel="stylesheet" type="text/css" />
<link href="../assets/global/plugins/jqvmap/jqvmap/jqvmap.css" rel="stylesheet" type="text/css" />
<!-- END PAGE LEVEL PLUGINS -->
<!--#INCLUDE FILE="include/head_bottom.phtml"-->
</head>

<body class="page-container-bg-solid">
<div class="page-wrapper">
	<div class="page-wrapper-row">
		<div class="page-wrapper-top">
			<!--#INCLUDE FILE="include/header.phtml"-->
		</div>
	</div>
	<div class="page-wrapper-row full-height">
		<div class="page-wrapper-middle">
			<!-- BEGIN CONTAINER -->
			<div class="page-container">
				<!-- BEGIN CONTENT -->
				<div class="page-content-wrapper">
					<!-- BEGIN CONTENT BODY -->
					<!-- BEGIN PAGE HEAD-->
					<div class="page-head">
						<div class="container-fluid">
							<!-- BEGIN PAGE TITLE -->
							<div class="page-title">
								<h1>Dashboard
									<small>dashboard & statistics</small>
								</h1>
							</div>
							<!-- END PAGE TITLE -->
						</div>
					</div>
					<!-- END PAGE HEAD-->
					<!-- BEGIN PAGE CONTENT BODY -->
					<div class="page-content">
						<div class="container-fluid">
							<!-- BEGIN PAGE CONTENT INNER -->
							<div class="page-content-inner">
								<div class="row">
									<%
										order_lifetime_total = 0
										sql = "SELECT SUM(total) FROM " & g_storeid & "_order"
										set rs = dbconn.Execute(sql)
										if not rs.EOF then
											order_lifetime_total = rs(0)
										end if
										rs.Close
										set rs = nothing
										
										if IsNumeric(order_lifetime_total) then
										else
											order_lifetime_total = 0
										end if
									%>
									<div class="col-lg-4 col-md-4 col-sm-6 col-xs-12 margin-bottom-10">
										<div class="dashboard-stat blue">
											<div class="visual">
												<i class="fa fa-briefcase fa-icon-medium"></i>
											</div>
											<div class="details">
												<div class="number"> $<%=FormatNumber(order_lifetime_total,2) %> </div>
												<div class="desc"> Lifetime Sales </div>
											</div>
										</div>
									</div>
									<%
										order_lifetime_count = 0
										sql = "SELECT COUNT(order_id) FROM " & g_storeid & "_order"
										set rs = dbconn.Execute(sql)
										if not rs.EOF then
											order_lifetime_count = rs(0)
										end if
										rs.Close
										set rs = nothing
										
										if order_lifetime_count > 0 then
											order_lifetime_avg = order_lifetime_total / order_lifetime_count
										else
											order_lifetime_avg = 0
										end if
									%>
									<div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
										<div class="dashboard-stat red">
											<div class="visual">
												<i class="fa fa-shopping-cart"></i>
											</div>
											<div class="details">
												<div class="number"> <%=order_lifetime_count%> </div>
												<div class="desc"> Total Orders </div>
											</div>
										</div>
									</div>
									<div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
										<div class="dashboard-stat green">
											<div class="visual">
												<i class="fa fa-group fa-icon-medium"></i>
											</div>
											<div class="details">
												<div class="number"> $<%=FormatNumber(order_lifetime_avg,2) %> </div>
												<div class="desc"> Average Orders </div>
											</div>
										</div>
									</div>
								</div>
								<div class="row">
									<div class="col-md-6">
										<!-- Begin: life time stats -->
										<div class="portlet light ">
											<div class="portlet-title">
												<div class="caption">
													<i class="icon-share font-blue"></i>
													<span class="caption-subject font-blue bold uppercase">Overview</span>
													<span class="caption-helper">report overview...</span>
												</div>
												<div class="actions">
													
												</div>
											</div>
											<div class="portlet-body">
												<div class="tabbable-line">
													<ul class="nav nav-tabs">
														<!--
														<li class="active">
															<a href="#overview_1" data-toggle="tab"> Top Selling </a>
														</li>
														<li>
															<a href="#overview_2" data-toggle="tab"> Most Viewed </a>
														</li>
														-->
														<li class="active">
															<a href="#overview_3" data-toggle="tab"> New Customers </a>
														</li>
														<li>
															<a href="#overview_4" data-toggle="tab"> New Orders </a>
														</li>
													</ul>
													<div class="tab-content">
														<!--
														<div class="tab-pane active" id="overview_1">
															<div class="table-responsive">
																<table class="table table-striped table-hover table-bordered">
																	<thead>
																		<tr>
																			<th> Product Name </th>
																			<th> Price </th>
																			<th> Sold </th>
																			<th> </th>
																		</tr>
																	</thead>
																	<tbody>
																		<tr>
																			<td>
																				<a href="javascript:;"> Apple iPhone 4s - 16GB - Black </a>
																			</td>
																			<td> $625.50 </td>
																			<td> 809 </td>
																			<td>
																				<a href="javascript:;" class="btn btn-sm btn-default">
																					<i class="fa fa-search"></i> View </a>
																			</td>
																		</tr>
																		<tr>
																			<td>
																				<a href="javascript:;"> Samsung Galaxy S III SGH-I747 - 16GB </a>
																			</td>
																			<td> $915.50 </td>
																			<td> 6709 </td>
																			<td>
																				<a href="javascript:;" class="btn btn-sm btn-default">
																					<i class="fa fa-search"></i> View </a>
																			</td>
																		</tr>
																		<tr>
																			<td>
																				<a href="javascript:;"> Motorola Droid 4 XT894 - 16GB - Black </a>
																			</td>
																			<td> $878.50 </td>
																			<td> 784 </td>
																			<td>
																				<a href="javascript:;" class="btn btn-sm btn-default">
																					<i class="fa fa-search"></i> View </a>
																			</td>
																		</tr>
																		<tr>
																			<td>
																				<a href="javascript:;"> Samsung Galaxy Note 4 </a>
																			</td>
																			<td> $925.50 </td>
																			<td> 21245 </td>
																			<td>
																				<a href="javascript:;" class="btn btn-sm btn-default">
																					<i class="fa fa-search"></i> View </a>
																			</td>
																		</tr>
																		<tr>
																			<td>
																				<a href="javascript:;"> Regatta Luca 3 in 1 Jacket </a>
																			</td>
																			<td> $25.50 </td>
																			<td> 1245 </td>
																			<td>
																				<a href="javascript:;" class="btn btn-sm btn-default">
																					<i class="fa fa-search"></i> View </a>
																			</td>
																		</tr>
																		<tr>
																			<td>
																				<a href="javascript:;"> Samsung Galaxy Note 3 </a>
																			</td>
																			<td> $925.50 </td>
																			<td> 21245 </td>
																			<td>
																				<a href="javascript:;" class="btn btn-sm btn-default">
																					<i class="fa fa-search"></i> View </a>
																			</td>
																		</tr>
																	</tbody>
																</table>
															</div>
														</div>
														<div class="tab-pane" id="overview_2">
															<div class="table-responsive">
																<table class="table table-striped table-hover table-bordered">
																	<thead>
																		<tr>
																			<th> Product Name </th>
																			<th> Price </th>
																			<th> Views </th>
																			<th> </th>
																		</tr>
																	</thead>
																	<tbody>
																		<tr>
																			<td>
																				<a href="javascript:;"> Metronic - Responsive Admin + Frontend Theme </a>
																			</td>
																			<td> $20.00 </td>
																			<td> 11190 </td>
																			<td>
																				<a href="javascript:;" class="btn btn-sm btn-default">
																					<i class="fa fa-search"></i> View </a>
																			</td>
																		</tr>
																		<tr>
																			<td>
																				<a href="javascript:;"> Regatta Luca 3 in 1 Jacket </a>
																			</td>
																			<td> $25.50 </td>
																			<td> 1245 </td>
																			<td>
																				<a href="javascript:;" class="btn btn-sm btn-default">
																					<i class="fa fa-search"></i> View </a>
																			</td>
																		</tr>
																		<tr>
																			<td>
																				<a href="javascript:;"> Motorola Droid 4 XT894 - 16GB - Black </a>
																			</td>
																			<td> $878.50 </td>
																			<td> 784 </td>
																			<td>
																				<a href="javascript:;" class="btn btn-sm btn-default">
																					<i class="fa fa-search"></i> View </a>
																			</td>
																		</tr>
																		<tr>
																			<td>
																				<a href="javascript:;"> Apple iPhone 4s - 16GB - Black </a>
																			</td>
																			<td> $625.50 </td>
																			<td> 809 </td>
																			<td>
																				<a href="javascript:;" class="btn btn-sm btn-default">
																					<i class="fa fa-search"></i> View </a>
																			</td>
																		</tr>
																		<tr>
																			<td>
																				<a href="javascript:;"> Samsung Galaxy S III SGH-I747 - 16GB </a>
																			</td>
																			<td> $915.50 </td>
																			<td> 6709 </td>
																			<td>
																				<a href="javascript:;" class="btn btn-sm btn-default">
																					<i class="fa fa-search"></i> View </a>
																			</td>
																		</tr>
																		<tr>
																			<td>
																				<a href="javascript:;"> Motorola Droid 4 XT894 - 16GB - Black </a>
																			</td>
																			<td> $878.50 </td>
																			<td> 784 </td>
																			<td>
																				<a href="javascript:;" class="btn btn-sm btn-default">
																					<i class="fa fa-search"></i> View </a>
																			</td>
																		</tr>
																	</tbody>
																</table>
															</div>
														</div>
														-->
														<div class="tab-pane active" id="overview_3">
															<div class="table-responsive">
																<table class="table table-striped table-hover table-bordered">
																	<thead>
																		<tr>
																			<th> Customer Name </th>
																			<th> Total Orders </th>
																			<th> Total Amount </th>
																			<th> </th>
																		</tr>
																	</thead>
																	<tbody>
																		<%
																			sql = "SELECT TOP 5 * FROM " & g_storeid & "_shopper ORDER BY DateEntered DESC"
																			set rs = dbconn.Execute(sql)
																			do while not rs.EOF
																				x_shopper_id = rs("shopper_id")
																				x_order_number = 0
																				sqlx = "SELECT COUNT(order_id) FROM " & g_storeid & "_order WHERE shopper_id='" & x_shopper_id & "'"
																				set rsx = dbconn.Execute(sqlx)
																				if not rsx.EOF then
																					x_order_number = rsx(0)
																				end if
																				rsx.Close
																				set rsx = nothing
																				
																				x_order_total = 0
																				sqlx = "SELECT SUM(total) FROM " & g_storeid & "_order WHERE shopper_id='" & x_shopper_id & "'"
																				set rsx = dbconn.Execute(sqlx)
																				if not rsx.EOF then
																					x_order_total = rsx(0)
																				end if
																				rsx.Close
																				set rsx = nothing
																				
																				if IsNumeric(x_order_number) then
																				else
																					x_order_number = 0
																				end if
																				
																				if IsNumeric(x_order_total) then
																				else
																					x_order_total = 0
																				end if
																			
																		%>
																		<tr>
																			<td>
																				<a href="javascript:;"> <%=rs("firstname") & " "  & rs("lastname") %> </a>
																			</td>
																			<td> <%=x_order_number%> </td>
																			<td> $<%=FormatNumber(x_order_total,2)%> </td>
																			<td>
																				<a href="customer_manage_customer_detail.phtml?shopper_id=<%=x_shopper_id%>" class="btn btn-sm btn-default">
																					<i class="fa fa-search"></i> View </a>
																			</td>
																		</tr>
																		<%
																				rs.MoveNext
																			Loop
																			rs.Close
																			set rs = nothing
																		%>
																	</tbody>
																</table>
															</div>
														</div>
														<div class="tab-pane" id="overview_4">
															<div class="table-responsive">
																<table class="table table-striped table-hover table-bordered">
																	<thead>
																		<tr>
																			<th> Customer Name </th>
																			<th> Items </th>
																			<th> Amount </th>
																			<th> Status </th>
																			<th> </th>
																		</tr>
																	</thead>
																	<tbody>
																		<%
																			sql = "SELECT TOP 5 * FROM " & g_storeid & "_order ORDER BY date_entered DESC"
																			set rs = dbconn.Execute(sql)
																			do while not rs.EOF
																				x_order_id = rs("order_id")
																				x_order_item = 0
																				sqlx = "SELECT SUM(quantity) FROM " & g_storeid & "_order_item WHERE order_id='" & x_order_id & "'"
																				set rsx = dbconn.Execute(sqlx)
																				if not rsx.EOF then
																					x_order_item = rsx(0)
																				end if
																				rsx.Close
																				set rsx = nothing
																		%>
																		<tr>
																			<td>
																				<a href="javascript:;"> <%=rs("bill_contact") %> </a>
																			</td>
																			<td> <%=x_order_item%> </td>
																			<td> $<%=FormatNumber(rs("total"),2)%> </td>
																			<td>
																				 <%=rs("status")%> 
																			</td>
																			<td>
																				<a href="sales_order_detail.phtml?so_id=<%=x_order_id%>" class="btn btn-sm btn-default">
																					<i class="fa fa-search"></i> View </a>
																			</td>
																		</tr>
																					<%
																				rs.MoveNext
																			Loop
																			rs.Close
																			set rs = nothing
																		%>
																		
																	</tbody>
																</table>
															</div>
														</div>
													</div>
												</div>
											</div>
										</div>
										<!-- End: life time stats -->
									</div>
									<div class="col-md-6">
										<!-- Begin: life time stats -->
										<!-- BEGIN PORTLET-->
										<div class="portlet light ">
											<div class="portlet-title tabbable-line">
												<div class="caption">
													<i class="icon-globe font-red"></i>
													<span class="caption-subject font-red bold uppercase">Revenue</span>
												</div>
												<ul class="nav nav-tabs">
													<li class="active">
														<a href="#portlet_ecommerce_tab_1" data-toggle="tab"> Amounts </a>
													</li>
													<li>
														<a href="#portlet_ecommerce_tab_2" id="statistics_orders_tab" data-toggle="tab"> Orders </a>
													</li>
												</ul>
											</div>
											<div class="portlet-body">
												<div class="tab-content">
													<div class="tab-pane active" id="portlet_ecommerce_tab_1">
														<div id="statistics_1" class="chart"> </div>
													</div>
													<div class="tab-pane" id="portlet_ecommerce_tab_2">
														<div id="statistics_2" class="chart"> </div>
													</div>
												</div>
												
												<%
													order_10_total = 0
													order_10_tax = 0
													order_10_SH = 0
													
													sql = "SELECT SUM(total), SUM(TAX), SUM (SH) FROM " & g_storeid & "_order"
													sql = sql & " WHERE (10 - DATEDIFF ( d , date_entered , GETDATE ( )))  > 0 "
													set rs = dbconn.Execute(sql)
													if not rs.EOF then
														order_10_total = rs(0)
														order_10_tax = rs(1)
														order_10_SH = rs(2)
													end if
													rs.Close
													set rs = nothing
													
													if IsNumeric(order_10_total) then
													else
														order_10_total = 0
													end if
													
													if IsNumeric(order_10_tax) then
													else
														order_10_tax = 0
													end if
													
													if IsNumeric(order_10_SH) then
													else
														order_10_SH = 0
													end if
													
													order_10_count = 0
													sql = "SELECT COUNT(order_id) FROM " & g_storeid & "_order"
													sql = sql & " WHERE (10 - DATEDIFF ( d , date_entered , GETDATE ( )))  > 0 "
													set rs = dbconn.Execute(sql)
													if not rs.EOF then
														order_10_count = rs(0)
													end if
													rs.Close
													set rs = nothing
												%>
									
												<div class="well margin-top-20">
													<div class="row">
														<div class="col-md-3 col-sm-3 col-xs-6 text-stat">
															<span class="label label-success"> Revenue: </span>
															<h3>$<%=FormatNumber(order_10_total,2) %></h3>
														</div>
														<div class="col-md-3 col-sm-3 col-xs-6 text-stat">
															<span class="label label-info"> Tax: </span>
															<h3>$<%=FormatNumber(order_10_tax,2) %></h3>
														</div>
														<div class="col-md-3 col-sm-3 col-xs-6 text-stat">
															<span class="label label-danger"> Shipment: </span>
															<h3>$<%=FormatNumber(order_10_SH,2) %></h3>
														</div>
														<div class="col-md-3 col-sm-3 col-xs-6 text-stat">
															<span class="label label-warning"> Orders: </span>
															<h3><%=order_10_count%></h3>
														</div>
													</div>
												</div>
											</div>
										</div>
										<!-- End: life time stats -->
									</div>
								</div>
							</div>
							<!-- END PAGE CONTENT INNER -->
						</div>
					</div>
					<!-- END PAGE CONTENT BODY -->
					<!-- END CONTENT BODY -->
				</div>
				<!-- END CONTENT -->
			</div>
			<!-- END CONTAINER -->
		</div>
	</div>
	<div class="page-wrapper-row">
		<div class="page-wrapper-bottom">
			<!--#INCLUDE FILE="include/footer.phtml"-->
		</div>
	</div>
</div>
<!--#INCLUDE FILE="include/js.phtml"-->
<!-- BEGIN PAGE LEVEL PLUGINS -->
<script src="../assets/global/plugins/moment.min.js" type="text/javascript"></script>
<script src="../assets/global/plugins/bootstrap-daterangepicker/daterangepicker.min.js" type="text/javascript"></script>
<script src="../assets/global/plugins/fullcalendar/fullcalendar.min.js" type="text/javascript"></script>
<script src="../assets/global/plugins/flot/jquery.flot.min.js" type="text/javascript"></script>
<script src="../assets/global/plugins/flot/jquery.flot.resize.min.js" type="text/javascript"></script>
<script src="../assets/global/plugins/flot/jquery.flot.categories.min.js" type="text/javascript"></script>
<script src="../assets/global/plugins/jquery-easypiechart/jquery.easypiechart.min.js" type="text/javascript"></script>
<script src="../assets/global/plugins/jquery.sparkline.min.js" type="text/javascript"></script>
<script src="../assets/global/plugins/jqvmap/jqvmap/jquery.vmap.js" type="text/javascript"></script>
<script src="../assets/global/plugins/jqvmap/jqvmap/maps/jquery.vmap.russia.js" type="text/javascript"></script>
<script src="../assets/global/plugins/jqvmap/jqvmap/maps/jquery.vmap.world.js" type="text/javascript"></script>
<script src="../assets/global/plugins/jqvmap/jqvmap/maps/jquery.vmap.europe.js" type="text/javascript"></script>
<script src="../assets/global/plugins/jqvmap/jqvmap/maps/jquery.vmap.germany.js" type="text/javascript"></script>
<script src="../assets/global/plugins/jqvmap/jqvmap/maps/jquery.vmap.usa.js" type="text/javascript"></script>
<script src="../assets/global/plugins/jqvmap/jqvmap/data/jquery.vmap.sampledata.js" type="text/javascript"></script>
<!-- END PAGE LEVEL PLUGINS -->
<%
	dim chart_order_count(30)
	for iii = 0 to 30
		chart_order_count(iii) = "0"
	next
	sql = "SELECT TOP 30 30 - DATEDIFF ( d , date_entered , GETDATE ( )) as a, COUNT(order_id) FROM " & g_storeid & "_order "
	sql = sql & " WHERE (30 - DATEDIFF ( d , date_entered , GETDATE ( )))  > 0 "
	sql = sql & " GROUP BY 30 - DATEDIFF ( d , date_entered , GETDATE ( )) ORDER BY a"
	set rsChart = dbconn.execute(sql)
	do while not rsChart.EOF
		if (rsChart(0) > -1) then
			chart_order_count(rsChart(0)) = FormatNumber(rsChart(1),0)
		end if
		rsChart.MoveNext
	loop
	rsChart.Close
	set rsChart = nothing
	
	'Response.Write(sql)
	
	'--------------------------------------------
	dim chart_order_amount(30)
	for iii = 0 to 30
		chart_order_amount(iii) = "0.00"
	next
	sql = "SELECT TOP 30 30 - DATEDIFF ( d , date_entered , GETDATE ( )) as a, SUM(total) FROM " & g_storeid & "_order "
	sql = sql & " WHERE (30 - DATEDIFF ( d , date_entered , GETDATE ( )))  > 0 "
	sql = sql & " GROUP BY 30 - DATEDIFF ( d , date_entered , GETDATE ( )) ORDER BY a"
	set rsChart = dbconn.execute(sql)
	do while not rsChart.EOF
		if (rsChart(0) > -1) then
		chart_order_amount(rsChart(0)) = FormatNumber(rsChart(1),2,,,0)
		end if
		rsChart.MoveNext
	loop
	rsChart.Close
	set rsChart = nothing
%>
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script type="text/javascript">
	var EcommerceDashboard = function() {

		function showTooltip(x, y, labelX, labelY) {
			$('<div id="tooltip" class="chart-tooltip">' + (labelY.toFixed(2).replace(/(\d)(?=(\d{3})+\.)/g, '$1,')) + 'USD<\/div>').css({
				position: 'absolute',
				display: 'none',
				top: y - 40,
				left: x - 60,
				border: '0px solid #ccc',
				padding: '2px 6px',
				'background-color': '#fff'
			}).appendTo("body").fadeIn(200);
		}

		var initChart1 = function() {

			var data = [
				['<%=DateAdd("D", -10, date)%>', <%=chart_order_amount(20)%>],
				['<%=DateAdd("D", -9, date)%>', <%=chart_order_amount(21)%>],
				['<%=DateAdd("D", -8, date)%>', <%=chart_order_amount(22)%>],
				['<%=DateAdd("D", -7, date)%>', <%=chart_order_amount(23)%>],
				['<%=DateAdd("D", -6, date)%>', <%=chart_order_amount(24)%>],
				['<%=DateAdd("D", -5, date)%>', <%=chart_order_amount(25)%>],
				['<%=DateAdd("D", -4, date)%>', <%=chart_order_amount(26)%>],
				['<%=DateAdd("D", -3, date)%>', <%=chart_order_amount(27)%>],
				['<%=DateAdd("D", -2, date)%>', <%=chart_order_amount(28)%>],
				['<%=DateAdd("D", -1, date)%>', <%=chart_order_amount(29)%>],
				['<%=DateAdd("D", 0, date)%>', <%=chart_order_amount(30)%>]
			];

			var plot_statistics = $.plot(
				$("#statistics_1"), [{
					data: data,
					lines: {
						fill: 0.6,
						lineWidth: 0
					},
					color: ['#f89f9f']
				}, {
					data: data,
					points: {
						show: true,
						fill: true,
						radius: 5,
						fillColor: "#f89f9f",
						lineWidth: 3
					},
					color: '#fff',
					shadowSize: 0
				}], {

					xaxis: {
						tickLength: 0,
						tickDecimals: 0,
						mode: "categories",
						min: 2,
						font: {
							lineHeight: 15,
							style: "normal",
							variant: "small-caps",
							color: "#6F7B8A"
						}
					},
					yaxis: {
						ticks: 3,
						tickDecimals: 0,
						tickColor: "#f0f0f0",
						font: {
							lineHeight: 15,
							style: "normal",
							variant: "small-caps",
							color: "#6F7B8A"
						}
					},
					grid: {
						backgroundColor: {
							colors: ["#fff", "#fff"]
						},
						borderWidth: 1,
						borderColor: "#f0f0f0",
						margin: 0,
						minBorderMargin: 0,
						labelMargin: 20,
						hoverable: true,
						clickable: true,
						mouseActiveRadius: 6
					},
					legend: {
						show: false
					}
				}
			);

			var previousPoint = null;

			$("#statistics_1").bind("plothover", function(event, pos, item) {
				$("#x").text(pos.x.toFixed(2));
				$("#y").text(pos.y.toFixed(2));
				if (item) {
					if (previousPoint != item.dataIndex) {
						previousPoint = item.dataIndex;

						$("#tooltip").remove();
						var x = item.datapoint[0].toFixed(2),
							y = item.datapoint[1].toFixed(2);

						showTooltip(item.pageX, item.pageY, item.datapoint[0], item.datapoint[1]);
					}
				} else {
					$("#tooltip").remove();
					previousPoint = null;
				}
			});

		}

		var initChart2 = function() {

			var data = [
				['<%=DateAdd("D", -10, date)%>', <%=chart_order_count(20)%>],
				['<%=DateAdd("D", -9, date)%>', <%=chart_order_count(21)%>],
				['<%=DateAdd("D", -8, date)%>', <%=chart_order_count(22)%>],
				['<%=DateAdd("D", -7, date)%>', <%=chart_order_count(23)%>],
				['<%=DateAdd("D", -6, date)%>', <%=chart_order_count(24)%>],
				['<%=DateAdd("D", -5, date)%>', <%=chart_order_count(25)%>],
				['<%=DateAdd("D", -4, date)%>', <%=chart_order_count(26)%>],
				['<%=DateAdd("D", -3, date)%>', <%=chart_order_count(27)%>],
				['<%=DateAdd("D", -2, date)%>', <%=chart_order_count(28)%>],
				['<%=DateAdd("D", -1, date)%>', <%=chart_order_count(29)%>],
				['<%=DateAdd("D", 0, date)%>', <%=chart_order_count(30)%>]
			];

			var plot_statistics = $.plot(
				$("#statistics_2"), [{
					data: data,
					lines: {
						fill: 0.6,
						lineWidth: 0
					},
					color: ['#BAD9F5']
				}, {
					data: data,
					points: {
						show: true,
						fill: true,
						radius: 5,
						fillColor: "#BAD9F5",
						lineWidth: 3
					},
					color: '#fff',
					shadowSize: 0
				}], {

					xaxis: {
						tickLength: 0,
						tickDecimals: 0,
						mode: "categories",
						min: 2,
						font: {
							lineHeight: 14,
							style: "normal",
							variant: "small-caps",
							color: "#6F7B8A"
						}
					},
					yaxis: {
						ticks: 3,
						tickDecimals: 0,
						tickColor: "#f0f0f0",
						font: {
							lineHeight: 14,
							style: "normal",
							variant: "small-caps",
							color: "#6F7B8A"
						}
					},
					grid: {
						backgroundColor: {
							colors: ["#fff", "#fff"]
						},
						borderWidth: 1,
						borderColor: "#f0f0f0",
						margin: 0,
						minBorderMargin: 0,
						labelMargin: 20,
						hoverable: true,
						clickable: true,
						mouseActiveRadius: 6
					},
					legend: {
						show: false
					}
				}
			);

			var previousPoint = null;

			$("#statistics_2").bind("plothover", function(event, pos, item) {
				$("#x").text(pos.x.toFixed(2));
				$("#y").text(pos.y.toFixed(2));
				if (item) {
					if (previousPoint != item.dataIndex) {
						previousPoint = item.dataIndex;

						$("#tooltip").remove();
						var x = item.datapoint[0].toFixed(2),
							y = item.datapoint[1].toFixed(2);

						showTooltip(item.pageX, item.pageY, item.datapoint[0], item.datapoint[1]);
					}
				} else {
					$("#tooltip").remove();
					previousPoint = null;
				}
			});

		}

		return {

			//main function
			init: function() {
				initChart1();

				$('#statistics_orders_tab').on('shown.bs.tab', function(e) {
					initChart2();
				});
			}

		};

	}();

	jQuery(document).ready(function() {    
	   EcommerceDashboard.init();
	});
</script>
<!-- END PAGE LEVEL SCRIPTS -->
</body>
</html>