<%
	Response.CodePage = 65001
	Response.CharSet = "UTF-8"
%>
<!-- #INCLUDE File="local/local.phtml" -->
<!-- #INCLUDE File="../util/xt_func_util.phtml" -->
<!-- #INCLUDE File="../util/xt_func_string.phtml" -->
<!-- #INCLUDE File="../util/xt_func_user_access.phtml" -->
<!-- #INCLUDE File="include/i_login.phtml" -->
<!--#INCLUDE FILE="include/doctype.phtml"-->
<head>
<!--#INCLUDE FILE="include/head.phtml"-->
<!-- BEGIN PAGE LEVEL PLUGINS -->
<link href="../assets/global/plugins/datatables/datatables.min.css" rel="stylesheet" type="text/css" />
<link href="../assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css" rel="stylesheet" type="text/css" />
<link href="../assets/global/plugins/bootstrap-datepicker/css/bootstrap-datepicker3.min.css" rel="stylesheet" type="text/css" />
<link href="../assets/global/plugins/fancybox/source/jquery.fancybox.css" rel="stylesheet" type="text/css" />
<!-- END PAGE LEVEL PLUGINS -->
</head>

<body class="page-container-bg-solid">
<div class="page-wrapper">
	<div class="page-wrapper-row">
		<div class="page-wrapper-top">
			<!--#INCLUDE FILE="include/header.phtml"-->
		</div>
	</div>
	<div class="page-wrapper-row full-height">
		<div class="page-wrapper-middle">
			<!-- BEGIN CONTAINER -->
			<div class="page-container">
				<!-- BEGIN CONTENT -->
				<div class="page-content-wrapper">
					<!-- BEGIN CONTENT BODY -->
					<!-- BEGIN PAGE HEAD-->
					
					<!-- END PAGE HEAD-->
					<!-- BEGIN PAGE CONTENT BODY -->
					<div class="page-content">
						<div class="container-fluid">
							<!-- BEGIN PAGE CONTENT INNER -->
							<div class="page-content-inner">
								<div class="row">
									<div class="col-md-12">
										<!-- Begin: life time stats -->
										<div class="portlet light portlet-fit portlet-datatable">
											<div class="portlet-title">
												<div class="caption">
													<i class="fa fa-shopping-cart"></i>CMS Listing 
												</div>
												<div class="actions">
													<a href="design_cms_page_edit.phtml?pid=0" class="btn btn-circle btn-info">
														<i class="fa fa-plus"></i>
														<span class="hidden-xs"> New Page </span>
													</a>
													<div class="btn-group">
														<a class="btn btn-circle btn-default dropdown-toggle" href="javascript:;" data-toggle="dropdown">
															<i class="fa fa-share"></i>
															<span class="hidden-xs"> Tools </span>
															<i class="fa fa-angle-down"></i>
														</a>
														<div class="dropdown-menu pull-right">
															<li>
																<a href="javascript:;"> Export to Excel </a>
															</li>
															<li>
																<a href="javascript:;"> Export to CSV </a>
															</li>
															<li>
																<a href="javascript:;"> Export to XML </a>
															</li>
															<li class="divider"></li>
															<li>
															<a href="javascript:;"> Print Invoices </a>
															</li>
														</div>
													</div>
												</div>
											</div>
											<div class="portlet-body">
												<div class="table-container">
													<table class="table table-striped table-bordered table-hover table-checkable" id="design_cms_1">
														<thead>
														<tr>
															<th>Page ID</th>
															<th>Title</th>
															<th>Date Created</th>
															<th>
															Last Modified
															<%
																  SELECT CASE Session("STORETIMEZONE")
																  CASE "0"
																	  Response.Write("(PST)")
																  CASE "1"
																	  Response.Write("(MST)")
																  CASE "2"
																	  Response.Write("(CST)")
																  CASE "3"
																	  Response.Write("(EST)")
																  CASE ELSE
																	  Response.Write("(PST)")
																  END SELECT
															  %>
															</th>
															<th width="2%" nowrap>Page Size</th>
															<th width="2%">Preview</th>
														</tr>
														
														</thead>
														<tbody>
															<tr>
																<td colspan="11" class="dataTables_empty">Loading data from server</td>
															</tr>
														</tbody>
													</table>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
							<!-- END PAGE CONTENT INNER -->
						</div>
					</div>
					<!-- END PAGE CONTENT BODY -->
					<!-- END CONTENT BODY -->
				</div>
				<!-- END CONTENT -->
			</div>
			<!-- END CONTAINER -->
		</div>
	</div>
	<div class="page-wrapper-row">
		<div class="page-wrapper-bottom">
			<!--#INCLUDE FILE="include/footer.phtml"-->
		</div>
	</div>
</div>
<!--#INCLUDE FILE="include/js.phtml"-->
<!-- BEGIN PAGE LEVEL PLUGINS -->
<script src="../assets/global/scripts/datatable.js" type="text/javascript"></script>
<script src="../assets/global/plugins/datatables/datatables.min.js" type="text/javascript"></script>
<script src="../assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js" type="text/javascript"></script>
<script src="../assets/global/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js" type="text/javascript"></script>
<script src="../assets/global/plugins/bootstrap-maxlength/bootstrap-maxlength.min.js" type="text/javascript"></script>
<script src="../assets/global/plugins/fancybox/source/jquery.fancybox.pack.js" type="text/javascript"></script>
<!-- END PAGE LEVEL PLUGINS -->

<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script type="text/javascript">
		
var oTable;
var v1 = "All";
var v2 = "All";
var v3 = "All";

var TableData = function () {
	//function to initiate DataTable
	//DataTable is a highly flexible tool, based upon the foundations of progressive enhancement, 
	//which will add advanced interaction controls to any HTML table
	//For more information, please visit https://datatables.net/
	var runDataTable = function () {
		oTable = $('#design_cms_1').dataTable({
			"bProcessing": true,
			"bStateSave": false,
			"bJQueryUI": false,
			"iDisplayLength": 20,
			"bServerSide": true,
			"bAutoWidth": false,
			"sAjaxSource": "api/sp_cms.phtml",
			"aoColumns": [ 
				/* Page ID */  { "sClass": "center" },
				/* Page Title */  { "sClass": "left" },
				/* Created Date */  { "sClass": "center" },
				/* Last Updated */ { "sClass": "center" },
				/* Page Size */ { "sClass": "center" },
				/* Preview */ { "sClass": "center","bSortable": false }
			  ],
			  
			"aaSorting": [[0, 'desc']],
			"aLengthMenu": [
				[10, 20, 30, 40, 50, 100],
				[10, 20, 30, 40, 50, 100] // change per page values here
			],
			
			"oLanguage": {
				"sLengthMenu": "Show _MENU_ Rows",
				"sSearch": "",
				"sProcessing": '<img src="assets/images/ajax-loader-primary.gif"/>',
				"oPaginate": {
					"sPrevious": "",
					"sNext": ""
				}
			},
			
			'fnServerData' : function ( sSource, aoData, fnCallback ) {
				aoData.push( { 'name' : 'min', 'value' : $("#min").val() } );
				aoData.push( { 'name' : 'max', 'value' : $("#max").val() } );
				$.ajax({
					'dataType' : 'json',
					'data' : aoData,
					'type' : 'GET',
					'url' : sSource,
					'success' : fnCallback
				});
			} 
		});
		
		$('#sample_1').on( 'draw.dt', function () {
			//UIModals.init();
			var $modal = $('#ajax-modal');
			$('.ajax .demo').on('click', function () {
				// create the backdrop and wait for next modal to be triggered
				$('body').modalmanager('loading');
				modal_po_id = $(this).data('id');
				setTimeout(function () {
					$modal.load('modal_ajax_po_email.phtml?po_id=' + modal_po_id, '', function () {
						$modal.modal();
					});
				}, 1000);
			});
		} );
		
	};

	return {
		//main function to initiate template pages
		init: function () {
			runDataTable();
		},
		
		reload: function(theURL) {
			if ( theURL ) {
				oTable.fnReloadAjax(theURL);
			}
			else {
				oTable.fnReloadAjax('sp_cms.phtml?v1=&v2=&z1=');
			}
		}
	};
}();

function StatusFilter (theObj)
{
	oTable.fnReloadAjax('api/sp_cms.phtml?v1=&v2=' + theObj.value + '&z1=');
}
function DateFilter()
{
	oTable.fnReloadAjax('api/sp_cms.phtml?v1=&v2=<%=cms_filter%>&DF=' + document.getElementById('DateRange').value + '&z1=');
}

$('#daterange').on('apply.daterangepicker', function(ev, picker) { 
	oTable.fnReloadAjax('api/sp_cms.phtml?v1=&v2=<%=cms_filter%>&DF=' + document.getElementById('DateRange').value + '&z1=');
	//do something, like clearing an input
 $('#daterange').val(''); 
}); 
function DeletePages()
{
	if(confirm("You are about to delete these pages.  Do you want to continue?"))
		document.pageDelete.submit();
	else
		return false;
}

</script>

<script>
	jQuery(document).ready(function() {
		TableData.init();
	});
</script>
<!-- END PAGE LEVEL SCRIPTS -->
</body>
</html>