<!-- #INCLUDE File="local/local.phtml" -->
<!-- #INCLUDE File="util/xt_func_util.phtml" -->
<!-- #INCLUDE File="util/xt_func_string.phtml" -->
<!-- #INCLUDE File="include/i_login.phtml" -->
<%
	sql = "SELECT setting_values FROM " &  g_storeid & "_setting WHERE setting_type='THEME_TEMPLATE'"
	Set rsSetting = dbconn.Execute(sql)
	if not rsSetting.EOF then
		THEME_TEMPLATE = Trim(rsSetting(0))
	else
		THEME_TEMPLATE = "porto"
	end if
	rsSetting.Close
%>
<!--#INCLUDE FILE="include/doctype.phtml"-->
<head>
<!--#INCLUDE FILE="include/head.phtml"-->
<!-- BEGIN PAGE LEVEL PLUGINS -->
<!-- END PAGE LEVEL PLUGINS -->
</head>

<body class="page-container-bg-solid">
<div class="page-wrapper">
	<div class="page-wrapper-row">
		<div class="page-wrapper-top">
			<!--#INCLUDE FILE="include/header.phtml"-->
		</div>
	</div>
	<div class="page-wrapper-row full-height">
		<div class="page-wrapper-middle">
			<!-- BEGIN CONTAINER -->
			<div class="page-container">
				<!-- BEGIN CONTENT -->
				<div class="page-content-wrapper">
					<!-- BEGIN CONTENT BODY -->
					<!-- BEGIN PAGE HEAD-->
					<div class="page-head">
						<div class="container-fluid">
							<!-- BEGIN PAGE TITLE -->
							<div class="page-title">
								<h1>Template Design & Settings
									<small>overview & settings</small>
								</h1>
							</div>
							<!-- END PAGE TITLE -->
						</div>
					</div>
					<!-- END PAGE HEAD-->
					<!-- BEGIN PAGE CONTENT BODY -->
					<div class="page-content">
						<div class="container-fluid">
							<!-- BEGIN PAGE CONTENT INNER -->
							<div class="page-content-inner">
								<iframe src="theme/<%=THEME_TEMPLATE%>/config.phtml" width="100%" height="800" frameborder="0" style="border:1px solid #333333"></iframe>
							</div>
							<!-- END PAGE CONTENT INNER -->
						</div>
					</div>
					<!-- END PAGE CONTENT BODY -->
					<!-- END CONTENT BODY -->
				</div>
				<!-- END CONTENT -->
			</div>
			<!-- END CONTAINER -->
		</div>
	</div>
	<div class="page-wrapper-row">
		<div class="page-wrapper-bottom">
			<!--#INCLUDE FILE="include/footer.phtml"-->
		</div>
	</div>
</div>
<!--#INCLUDE FILE="include/js.phtml"-->
<!-- BEGIN PAGE LEVEL PLUGINS -->

<!-- END PAGE LEVEL PLUGINS -->

<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script type="text/javascript">
	
</script>
<!-- END PAGE LEVEL SCRIPTS -->
</body>
</html>