<%@ Language=VBScript %>
<!-- #INCLUDE File="../local/local.phtml" -->
<!-- #INCLUDE File="../util/xt_func_string.phtml" -->
<!-- #INCLUDE FILE="../util/xt_func_session.phtml" -->
<!-- #INCLUDE FILE="../util/xt_class_security.phtml" -->
<!-- #INCLUDE FILE="../util/xt_func_util.phtml" -->
<%
	sessionID = Trim(Request("sessionID"))
	sessionID = FilterSessionString(sessionID)
	if Len(sessionID) > 0 then
		Session("SESSIONKEY") = sessionID
	else
		if Len(Session("SESSIONKEY")) > 0 then
			'session key exist
		else
			'no key information...
			InitializeSession()
		end if
	end if
	
%>

<script runat="server" language="VBScript">
function SaveLoginInfo(ByRef str_db,ByRef str_storeid, ByRef str_uid,ByRef str_pwd, ByRef str_ipaddr, ByRef str_status)

	dim sql,conn
	Dim field_names,field_values,str_sql

	if((str_storeid="")Or(str_db="")Or(str_uid="")) then
		SaveLoginInfo=false
		exit function
	end if
	
	select case str_status
		case "0"
			status = "Administrator Log in Successful"
		case "1"
			status = "Master Administrator Log in Successful"
		case "2"
			status = "User Log in Successful"
		case "3"
			status = "Log in Fail"
		case "4"
			status = "error"
		case else
	end select
	
 	field_names = field_names & "store_id" & ","
 	field_values = field_values &"'"& str_storeid & "',"

 	field_names = field_names & "user_id" & ","
 	field_values = field_values & "'" & str_uid & "',"
	
	field_names = field_names & "password" & ","
 	field_values = field_values & "'',"
 	
	field_names = field_names & "ip_addr" & ","
 	field_values = field_values & "'" & Request.ServerVariables("REMOTE_ADDR") & "',"
 	
	field_names = field_names & "log_date" & ","
 	field_values = field_values & "'" & now() & "',"
 	
	field_names = field_names & "status" & ","
 	field_values = field_values & "'" & status & "',"
 	
 	'strip the trailing commas
	field_names = Left(field_names,Len(field_names)-1)
	field_values = Left(field_values,Len(field_values)-1)

	sql="INSERT INTO A_MANAGER_LOG ("& field_names &") VALUES("& field_values &")"
	
	set conn=server.CreateObject("ADODB.Connection")
	conn.Open str_db
	conn.Execute sql
		
	SaveLoginInfo = true
end function

</script>
<%
	dim err_msg
	err_msg = ""

	if Request.Form("login")= "1" then
		method = "Login"
	end if

	if Request("logoff") = "1" then
		Session("ADMINSTATUS") = ""
		Session("SalesMode") = "0"
		Session("AdminName") = ""
		Session("AdminID") = ""
		Session("shopper_id") = ""
		
		UpdateSession Session("SESSIONKEY"), "sSaleMode", "0"

		Response.cookies(g_storeid)("ADMINLOGIN") = ""
		Response.cookies(g_storeid)("ADMINSESSIONKEY") = ""
		Response.cookies(g_storeid).Expires = DateAdd("d", 1, date())
	end if

	if Len(method) > 0 then
	else
		method = Request("method")
	end if

	select case method

	case "Login"
	
		str_uid = FilterString(Trim(Request("Username")))
		str_password = FilterPassword(Trim(Request("Password")))

		chk_savelogin = Request.Form("chkSaveLogin")
				
		Set lconn = Server.CreateObject("ADODB.Connection")
		lconn.open g_connection_string
		sql = "SELECT Email FROM " & g_storeid & "_profile WHERE UserID='"& str_uid & "' AND Password='" & str_password & "'"
		set rs = lconn.Execute(sql)
		
		if not rs.EOF then
		
		
			if Session("use_ip_security") = "1" then
		  
				strSQL = "SELECT * FROM :9_ip_addr where ip_addr='"& Request.ServerVariables("REMOTE_ADDR") &"'"
				strSQL = Replace(strSQL, ":9", g_storeid)
				set rsStation = lconn.Execute(strSQL)

				if not rsStation.EOF then 
					Session("ADMINSTATUS") = "5"
					Ret = 1
					Session("SalesMode") = "1"
					Session("AdminName") = "System Admin"
					Session("AdminID") = "SA"
					Session("shopper_id") = "GUEST"
					
					UpdateSession Session("SESSIONKEY"), "sSaleMode", "1"
					UpdateSession Session("SESSIONKEY"), "sCID", Session("shopper_id")
				
					if SaveLoginInfo(g_connection_string,g_storeid,str_uid,str_password,ip_addr,"0") then
				
					end if
				  
				else
					status_msg = "This stations is not registered."
				end if

				rsStation.Close
				
			else
			  
				Session("ADMINSTATUS") = "5"
				Ret = 1
				Session("SalesMode") = "1"
				Session("AdminName") = "System Admin"
				Session("AdminID") = "SA"
				Session("shopper_id") = "GUEST"

				UpdateSession Session("SESSIONKEY"), "sSaleMode", "1"
				UpdateSession Session("SESSIONKEY"), "sCID", Session("shopper_id")

				if SaveLoginInfo(g_connection_string,g_storeid,str_uid,str_password,ip_addr,"0") then

				end if
			  
			end if
				
			
		else
		
			sql = "SELECT * FROM A_Master_ID where admin_id='" & str_uid & "' and 1 = pwdcompare('" &  str_password & "', password)"
			set rsMasterID = lconn.Execute(sql)
			
			if not rsMasterID.EOF then
				Session("ADMINSTATUS") = "5"
				Ret = 1
				Session("SalesMode") = "1"
				Session("AdminName") = ".."
				Session("AdminID") = ".."
				Session("shopper_id") = "GUEST"
				
				UpdateSession Session("SESSIONKEY"), "sSaleMode", "1"
				UpdateSession Session("SESSIONKEY"), "sCID", Session("shopper_id")
				if SaveLoginInfo(g_connection_string,g_storeid,str_uid,str_password,ip_addr,"1") then
					
				end if
				
			else
				status_msg = "Please verify your user id and password."
			end if
			rsMasterID.Close
			
		end if

		rs.Close
		
		if not Ret = 1 then
			'Check for additional users...
			sql = "SELECT user_id, LastName, FirstName, user_flag FROM " & g_storeid & "_users WHERE user_id='"& str_uid & "' AND pwd='" & str_password & "' AND user_disable=0"
			set rs = lconn.Execute(sql)

			if not rs.EOF then
				
				if Session("use_ip_security") = "1" then
					strSQL = "SELECT * FROM " & g_storeid & "_ip_addr where ip_addr='"& Request.ServerVariables("REMOTE_ADDR") &"'"
					set rsStation = lconn.Execute(strSQL)

					if not rsStation.EOF then 
						Session("ADMINSTATUS") = CStr(rs("user_flag"))
						Ret = 1
						status_msg = ""
						Session("SalesMode") = "1"
						Session("AdminName") = rs("FirstName") & " " & rs("LastName")
						Session("AdminID") = rs("user_id")
						Session("shopper_id") = "GUEST"

						UpdateSession Session("SESSIONKEY"), "sSaleMode", "1"
						UpdateSession Session("SESSIONKEY"), "sCID", Session("shopper_id")
						if SaveLoginInfo(g_connection_string,g_storeid,str_uid,str_password,ip_addr,"2") then

						end if
					  
					else
						status_msg = "This stations is not registered."
					end if

					rsStation.Close
				
				else

					Session("ADMINSTATUS") = CStr(rs("user_flag"))
					Ret = 1
					status_msg = ""
					Session("SalesMode") = "1"
					Session("AdminName") = rs("FirstName") & " " & rs("LastName")
					Session("AdminID") = rs("user_id")
					Session("shopper_id") = "GUEST"
					
					UpdateSession Session("SESSIONKEY"), "sSaleMode", "1"
					UpdateSession Session("SESSIONKEY"), "sCID", Session("shopper_id")
					if SaveLoginInfo(g_connection_string,g_storeid,str_uid,str_password,ip_addr,"2") then
						
					end if

				end if

			else
				if SaveLoginInfo(g_connection_string,g_storeid,str_uid,str_password,ip_addr,"3") then
					
				end if
				
				if Len(status_msg) > 0 then
				else
				status_msg = "Please verify your user id and password."
				end if
			end if
		
			rs.close
			
		end if
		
		lconn.close
		

		if Ret = 1 AND chk_savelogin = "1" then
			'Write login information to cookie.
			Response.cookies(g_storeid)("ADMINLOGIN") = Session("AdminID")
			Response.cookies(g_storeid)("ADMINSESSIONKEY") = Session("SESSIONKEY")
			Response.cookies(g_storeid).Expires = DateAdd("d", 1, date())
			Response.cookies(g_storeid & "**")("SAVELOGIN")  = "1"
			Response.cookies(g_storeid & "**").Expires = DateAdd("m", 1, date())
		else
			Response.cookies(g_storeid)("ADMINLOGIN") = ""
			Response.cookies(g_storeid)("ADMINSESSIONKEY") = ""
			Response.cookies(g_storeid).Expires = DateAdd("d", 1, date())
			Response.cookies(g_storeid & "**")("SAVELOGIN")  = "0"
			Response.cookies(g_storeid & "**").Expires = DateAdd("m", 1, date())
		end if
		
	case else

		c_ADMINLOGIN = Request.cookies(g_storeid)("ADMINLOGIN")
		c_ADMINSESSIONKEY = Request.cookies(g_storeid)("ADMINSESSIONKEY")

		c_SAVELOGIN = Request.cookies(g_storeid&"**")("SAVELOGIN")
		if c_SAVELOGIN = "" then
			c_SAVELOGIN = "1"
		end if

		if Len(c_ADMINLOGIN) > 0 then
			'Read login info.. set it..

			SELECT CASE c_ADMINLOGIN
			CASE "SA"

				Session("ADMINSTATUS") = "5"
				Ret = 1
				Session("SalesMode") = "1"
				Session("AdminName") = "System Admin"
				Session("AdminID") = "SA"
				Session("shopper_id") = "GUEST"
				
				UpdateSession c_ADMINSESSIONKEY, "sSaleMode", "1"
				UpdateSession c_ADMINSESSIONKEY, "sCID", Session("shopper_id")

			CASE ".."

				Session("ADMINSTATUS") = "5"
				Ret = 1
				Session("SalesMode") = "1"
				Session("AdminName") = ".."
				Session("AdminID") = ".."
				Session("shopper_id") = "GUEST"
				
				UpdateSession c_ADMINSESSIONKEY, "sSaleMode", "1"
				UpdateSession c_ADMINSESSIONKEY, "sCID", Session("shopper_id")

			CASE ELSE
				
				set rconn = Server.CreateObject("ADODB.Connection")
				rconn.open g_connection_string

				sql = "SELECT user_id, LastName, FirstName, user_flag FROM " & g_storeid & "_users WHERE user_id='"& c_ADMINLOGIN & "' AND user_disable=0"
				set rs = rconn.Execute(sql)

				if not rs.EOF then
				
					Session("ADMINSTATUS") = CStr(rs("user_flag"))
					Ret = 1
					status_msg = ""
					Session("SalesMode") = "1"
					Session("AdminName") = rs("FirstName") & " " & rs("LastName")
					Session("AdminID") = rs("user_id")
					Session("shopper_id") = "GUEST"
					
					UpdateSession c_ADMINSESSIONKEY, "sSaleMode", "1"
					UpdateSession c_ADMINSESSIONKEY, "sCID", Session("shopper_id")

				end if

				rs.Close
				rconn.close

			END SELECT

		else

			Session("ADMINSTATUS") = ""
			Session("shopper_id") = ""

		end if

	end select
	
	if Ret = 1 then
		if Len(Session("REFERER_URL")) > 0 Then
			'response.redirect Session("REFERER_URL")
			response.redirect "dashboard.phtml"
		Else
			response.redirect "dashboard.phtml"
		End If
	end if

%>
<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
    <!--<![endif]-->
    <!-- BEGIN HEAD -->
    <head>
        <meta charset="utf-8" />
        <title>G2SHOP | Admin Login</title>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta content="" name="description" />
        <meta content="" name="author" />
        <!-- BEGIN GLOBAL MANDATORY STYLES -->
        <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet" type="text/css" />
        <link href="../assets/global/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
        <link href="../assets/global/plugins/simple-line-icons/simple-line-icons.min.css" rel="stylesheet" type="text/css" />
        <link href="../assets/global/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
        <link href="../assets/global/plugins/bootstrap-switch/css/bootstrap-switch.min.css" rel="stylesheet" type="text/css" />
        <!-- END GLOBAL MANDATORY STYLES -->
        <!-- BEGIN PAGE LEVEL PLUGINS -->
        <link href="../assets/global/plugins/select2/css/select2.min.css" rel="stylesheet" type="text/css" />
        <link href="../assets/global/plugins/select2/css/select2-bootstrap.min.css" rel="stylesheet" type="text/css" />
        <!-- END PAGE LEVEL PLUGINS -->
        <!-- BEGIN THEME GLOBAL STYLES -->
        <link href="../assets/global/css/components.min.css" rel="stylesheet" id="style_components" type="text/css" />
        <link href="../assets/global/css/plugins.min.css" rel="stylesheet" type="text/css" />
        <!-- END THEME GLOBAL STYLES -->
        <!-- BEGIN PAGE LEVEL STYLES -->
        <link href="../assets/pages/css/login-4.min.css" rel="stylesheet" type="text/css" />
        <!-- END PAGE LEVEL STYLES -->
        <!-- BEGIN THEME LAYOUT STYLES -->
        <!-- END THEME LAYOUT STYLES -->
        <link rel="shortcut icon" href="favicon.ico" /> </head>
    <!-- END HEAD -->

    <body class=" login">
        <!-- BEGIN LOGO -->
        <div class="logo">
				<img src="assets/images/g2shop_logo2a.png" width="106">
        </div>
        <!-- END LOGO -->
        <!-- BEGIN LOGIN -->
        <div class="content">
            <!-- BEGIN LOGIN FORM -->
			<form class="login-form" method="post" action="login.phtml">
				<input type="hidden" id="login" name="login" value="1">
                <h3 class="form-title">Login to your account</h3>
                <div class="alert alert-danger display-hide">
                    <button class="close" data-close="alert"></button>
                    <span> Enter any username and password. </span>
                </div>
                <div class="form-group">
                    <!--ie8, ie9 does not support html5 placeholder, so we just show field title for that-->
                    <label class="control-label visible-ie8 visible-ie9">Username</label>
                    <div class="input-icon">
                        <i class="fa fa-user"></i>
                        <input class="form-control placeholder-no-fix" type="text" autocomplete="off" placeholder="Username" name="username" /> </div>
                </div>
                <div class="form-group">
                    <label class="control-label visible-ie8 visible-ie9">Password</label>
                    <div class="input-icon">
                        <i class="fa fa-lock"></i>
                        <input class="form-control placeholder-no-fix" type="password" autocomplete="off" placeholder="Password" name="password" /> </div>
                </div>
                <div class="form-actions">
                    <label class="rememberme mt-checkbox mt-checkbox-outline">
                        <input type="checkbox" name="chkSaveLogin" value="1" /> Keep me signed in
                        <span></span>
                    </label>
                    <button type="submit" class="btn green pull-right"> Login </button>
                </div>
                <div class="forget-password">
                    <h4>Forgot your password ?</h4>
                    <p> no worries, click
                        <a href="javascript:;" id="forget-password"> here </a> to reset your password. </p>
                </div>
            </form>
            <!-- END LOGIN FORM -->
            <!-- BEGIN FORGOT PASSWORD FORM -->
            <form class="forget-form" action="index.html" method="post">
                <h3>Forget Password ?</h3>
                <p> Enter your e-mail address below to reset your password. </p>
                <div class="form-group">
                    <div class="input-icon">
                        <i class="fa fa-envelope"></i>
                        <input class="form-control placeholder-no-fix" type="text" autocomplete="off" placeholder="Email" name="email" /> </div>
                </div>
                <div class="form-actions">
                    <button type="button" id="back-btn" class="btn red btn-outline">Back </button>
                    <button type="submit" class="btn green pull-right"> Submit </button>
                </div>
            </form>
            <!-- END FORGOT PASSWORD FORM -->
        </div>
        <!-- END LOGIN -->
        <!-- BEGIN COPYRIGHT -->
        <div class="copyright"> 2016 &copy; Olive Commerce </div>
        <!-- END COPYRIGHT -->
        <!--[if lt IE 9]>
		<script src="../assets/global/plugins/respond.min.js"></script>
		<script src="../assets/global/plugins/excanvas.min.js"></script> 
		<![endif]-->
        <!-- BEGIN CORE PLUGINS -->
        <script src="../assets/global/plugins/jquery.min.js" type="text/javascript"></script>
        <script src="../assets/global/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
        <script src="../assets/global/plugins/js.cookie.min.js" type="text/javascript"></script>
        <script src="../assets/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
        <script src="../assets/global/plugins/jquery.blockui.min.js" type="text/javascript"></script>
        <script src="../assets/global/plugins/bootstrap-switch/js/bootstrap-switch.min.js" type="text/javascript"></script>
        <!-- END CORE PLUGINS -->
        <!-- BEGIN PAGE LEVEL PLUGINS -->
        <script src="../assets/global/plugins/jquery-validation/js/jquery.validate.min.js" type="text/javascript"></script>
        <script src="../assets/global/plugins/jquery-validation/js/additional-methods.min.js" type="text/javascript"></script>
        <script src="../assets/global/plugins/select2/js/select2.full.min.js" type="text/javascript"></script>
        <script src="../assets/global/plugins/backstretch/jquery.backstretch.min.js" type="text/javascript"></script>
        <!-- END PAGE LEVEL PLUGINS -->
        <!-- BEGIN THEME GLOBAL SCRIPTS -->
        <script src="../assets/global/scripts/app.min.js" type="text/javascript"></script>
        <!-- END THEME GLOBAL SCRIPTS -->
        <!-- BEGIN PAGE LEVEL SCRIPTS -->
        <script src="../assets/pages/scripts/login-4.min.js" type="text/javascript"></script>
        <!-- END PAGE LEVEL SCRIPTS -->
        <!-- BEGIN THEME LAYOUT SCRIPTS -->
        <!-- END THEME LAYOUT SCRIPTS -->
    </body>

</html>