<!-- #INCLUDE File="local/local.phtml" -->
<!-- #INCLUDE File="util/xt_func_util.phtml" -->
<!-- #INCLUDE File="util/xt_func_string.phtml" -->
<!-- #INCLUDE File="include/i_login.phtml" -->
<!--#INCLUDE FILE="include/doctype.phtml"-->
<head>
<!--#INCLUDE FILE="include/head.phtml"-->
<!-- BEGIN PAGE LEVEL PLUGINS -->
<link href="../assets/global/plugins/datatables/datatables.min.css" rel="stylesheet" type="text/css" />
<link href="../assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css" rel="stylesheet" type="text/css" />
<link href="../assets/global/plugins/bootstrap-datepicker/css/bootstrap-datepicker3.min.css" rel="stylesheet" type="text/css" />
<link href="../assets/global/plugins/bootstrap-modal/css/bootstrap-modal-bs3patch.css" rel="stylesheet" type="text/css" />
<link href="../assets/global/plugins/bootstrap-modal/css/bootstrap-modal.css" rel="stylesheet" type="text/css" />
<!-- END PAGE LEVEL PLUGINS -->
<!--#INCLUDE FILE="include/head_bottom.phtml"-->
</head>

<body class="page-container-bg-solid">
<div class="page-wrapper">
	<div class="page-wrapper-row">
		<div class="page-wrapper-top">
			<!--#INCLUDE FILE="include/header.phtml"-->
		</div>
	</div>
	<div class="page-wrapper-row full-height">
		<div class="page-wrapper-middle">
			<!-- BEGIN CONTAINER -->
			<div class="page-container">
				<!-- BEGIN CONTENT -->
				<div class="page-content-wrapper">
					<!-- BEGIN CONTENT BODY -->
					<!-- BEGIN PAGE HEAD-->
					<!-- END PAGE HEAD-->
					<!-- BEGIN PAGE CONTENT BODY -->
					<div class="page-content">
						<div class="container-fluid">
							<!-- BEGIN PAGE CONTENT INNER -->
							<div class="page-content-inner">
								<div class="row">
									<div class="col-md-12">
										<!-- Begin: Demo Datatable 1 -->
										<div class="portlet light portlet-fit portlet-datatable ">
											<div class="portlet-title">
												<div class="caption">
													<i class="icon-settings font-dark"></i>
													<span class="caption-subject font-dark sbold uppercase">Sales Order List</span>
												</div>
												<div class="actions">
													<a class="btn green btn-circle" data-toggle="modal" href="#stack2"> 
														<i class="fa fa-plus"></i>
														Create New Order
													</a>
													<div class="btn-group">
														<!--
														<a class="btn green-haze btn-outline btn-circle" href="javascript:;" data-toggle="dropdown">
															<i class="fa fa-share"></i>
															<span class="hidden-xs"> Tools </span>
															<i class="fa fa-angle-down"></i>
														</a>
														<ul class="dropdown-menu pull-right">
															<li class="divider"> </li>
															<li>
																<a href="javascript:;"> Export to CSV </a>
															</li>
															<li>
																<a href="javascript:;"> Export to XML </a>
															</li>
															<li class="divider"> </li>
															<li>
																<a href="javascript:;"> Print Invoices </a>
															</li>
														</ul>
														-->
													</div>
												</div>
											</div>
											<div class="portlet-body">
												<div class="table-container">
													<div class="table-actions-wrapper">
														<span> </span>
														<select class="table-group-action-input form-control input-inline input-small input-sm">
															<option value="">Select...</option>
															<option value="Print">Print</option>
															<option value="">Change Status to ...</option>
															<option value="pending">..........Pending</option>
															<option value="processing">..........Processing</option>
															<option value="holded">..........On Hold</option>
															<option value="complete">..........Complete</option>
															<option value="closed">..........Closed</option>
															<option value="closed">..........Cancelled</option>
															<option value="Export">Export</option>
															<option value="Duplicate">Duplicate</option>
															<option value="Delete">Delete</option>
														</select>
														<button class="btn btn-sm green table-group-action-submit">
															<i class="fa fa-check"></i> Submit</button>
													</div>
													<table class="table table-striped table-bordered table-hover table-checkable" id="datatable_ajax">
														<thead>
															<tr role="row" class="heading">
																<th width="2%">
																	<label class="mt-checkbox mt-checkbox-single mt-checkbox-outline">
																		<input type="checkbox" class="group-checkable" data-set="#sample_2 .checkboxes" />
																		<span></span>
																	</label>
																</th>
																<th width="8%"> Order&nbsp;# </th>
																<th width="15%"> Date </th>
																<th width="150"> Bill&nbsp;To </th>
																<th width="150"> Ship&nbsp;To </th>
																<th width="10%"> Amount </th>
																<th width="10%"> Status </th>
																<th width="5%"> Quote </th>
																<th width="5%"> Actions </th>
															</tr>
															<tr role="row" class="filter">
																<td> </td>
																<td>
																	<input type="text" class="form-control form-filter input-sm" name="order_id"> </td>
																<td>
																	<div class="input-group date date-picker margin-bottom-5" data-date-format="mm/dd/yyyy">
																		<input type="text" class="form-control form-filter input-sm" readonly name="order_date_from" placeholder="From">
																		<span class="input-group-btn">
																			<button class="btn btn-sm default" type="button">
																				<i class="fa fa-calendar"></i>
																			</button>
																		</span>
																	</div>
																	<div class="input-group date date-picker" data-date-format="mm/dd/yyyy">
																		<input type="text" class="form-control form-filter input-sm" readonly name="order_date_to" placeholder="To">
																		<span class="input-group-btn">
																			<button class="btn btn-sm default" type="button">
																				<i class="fa fa-calendar"></i>
																			</button>
																		</span>
																	</div>
																</td>
																<td>
																	<input type="text" class="form-control form-filter input-sm" name="order_customer_name"> 
																</td>
																<td>
																	<input type="text" class="form-control form-filter input-sm" name="order_ship_to"> 
																</td>
																<td>
																	<div class="margin-bottom-5">
																		<input type="text" class="form-control form-filter input-sm" name="order_price_from" placeholder="From" /> 
																	</div>
																	<input type="text" class="form-control form-filter input-sm" name="order_price_to" placeholder="To" /> 
																</td>
																<td>
																	<select name="order_status" class="form-control form-filter input-sm">
																		<option value="">Select...</option>
																		<option value="pending">Pending</option>
																		<option value="processing">Processing</option>
																		<option value="holded">On Hold</option>
																		<option value="complete">Complete</option>
																		<option value="closed">Closed</option>
																		<option value="canceled">Canceled</option>
																	</select>
																</td>
																<td>
																	<input type="text" class="form-control form-filter input-sm" name="order_quote"> 
																</td>
																<td>
																	<div class="margin-bottom-5">
																		<button class="btn btn-sm green btn-outline filter-submit margin-bottom">
																			<i class="fa fa-search"></i> Search</button>
																	</div>
																	<button class="btn btn-sm red btn-outline filter-cancel">
																		<i class="fa fa-times"></i> Reset</button>
																</td>
															</tr>
														</thead>
														<tbody> </tbody>
													</table>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
							<!-- END PAGE CONTENT INNER -->
						</div>
					</div>
					<!-- END PAGE CONTENT BODY -->
					<!-- END CONTENT BODY -->
				</div>
				<!-- END CONTENT -->
			</div>
			<!-- END CONTAINER -->
		</div>
	</div>
	<div class="page-wrapper-row">
		<div class="page-wrapper-bottom">
			<!--#INCLUDE FILE="include/footer.phtml"-->
		</div>
	</div>
</div>
<div id="stack2" class="modal fade container" tabindex="-1" data-focus-on="input:first">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
		<h4 class="modal-title">Customer Search</h4>
	</div>
	<div class="modal-body">
		<div class="row">
			<div class="col-md-12">
				<div class="portlet light portlet-fit portlet-datatable">
					<div class="portlet-body">
						<div class="table-container">
							<table class="table table-striped table-bordered table-hover table-full-width" id="sample_2">
								<thead>
								<tr>
									<th>ID</th>
									<th>First Name</th>
									<th>Last Name</th>
									<th>Email</th>
									<th>Customer Since</th>
									<th>Status</th>
									<th></th>
								</tr>
								</thead>
								<tbody>
									<tr>
										<td colspan="8" class="dataTables_empty">Loading data from server</td>
									</tr>
								</tbody>
							</table>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<!--#INCLUDE FILE="include/js.phtml"-->
<!-- BEGIN PAGE LEVEL PLUGINS -->
<script src="../assets/global/scripts/datatable.js" type="text/javascript"></script>
<script src="../assets/global/plugins/datatables/datatables.min.js" type="text/javascript"></script>
<script src="../assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js" type="text/javascript"></script>
<script src="../assets/global/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js" type="text/javascript"></script>
<script src="../assets/global/plugins/bootstrap-modal/js/bootstrap-modalmanager.js" type="text/javascript"></script>
<script src="../assets/global/plugins/bootstrap-modal/js/bootstrap-modal.js" type="text/javascript"></script>
<!-- END PAGE LEVEL PLUGINS -->
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script type="text/javascript">

var oTable;
var oTabel2;
var v1 = "All";
var v2 = "All";
var v3 = "All";
var grid
	
var TableDatatablesAjax = function () {

    var initPickers = function () {
        //init date pickers
        $('.date-picker').datepicker({
            rtl: App.isRTL(),
            autoclose: true
        });
    }

    var runDataTable = function () {

        grid = new Datatable();

        grid.init({
            src: $("#datatable_ajax"),
            onSuccess: function (grid, response) {
                // grid:        grid object
                // response:    json object of server side ajax response
                // execute some code after table records loaded
            },
            onError: function (grid) {
                // execute some code on network or other general error  
            },
            onDataLoad: function(grid) {
                // execute some code on ajax data load
            },
            loadingMessage: 'Loading...',
            dataTable: { // here you can define a typical datatable settings from http://datatables.net/usage/options 

                // Uncomment below line("dom" parameter) to fix the dropdown overflow issue in the datatable cells. The default datatable layout
                // setup uses scrollable div(table-scrollable) with overflow:auto to enable vertical scroll(see: assets/global/scripts/datatable.js). 
                // So when dropdowns used the scrollable div should be removed. 
                //"dom": "<'row'<'col-md-8 col-sm-12'pli><'col-md-4 col-sm-12'<'table-group-actions pull-right'>>r>t<'row'<'col-md-8 col-sm-12'pli><'col-md-4 col-sm-12'>>",
                columnDefs: [ 
					{ orderable: false, targets: [0,7,8] },
					{ className: "text-center", targets: [6,7,8] },
					{ className: "text-right", targets: [5] }
				],
					
                "bStateSave": true, // save datatable state(pagination, sort, etc) in cookie.

                "lengthMenu": [
                    [10, 20, 50, 100, 150, -1],
                    [10, 20, 50, 100, 150, "All"] // change per page values here
                ],
                "pageLength": 20, // default record count per page
                "ajax": {
                    "url": "api/sp_order_list.phtml", // ajax source
                },
                "order": [
                    [2, "desc"]
                ]// set first column as a default sort by asc
            }
        });

        // handle group actionsubmit button click
        grid.getTableWrapper().on('click', '.table-group-action-submit', function (e) {
            e.preventDefault();
            var action = $(".table-group-action-input", grid.getTableWrapper());
            if (action.val() != "" && grid.getSelectedRowsCount() > 0) {
                grid.setAjaxParam("customActionType", "group_action");
                grid.setAjaxParam("customActionName", action.val());
                grid.setAjaxParam("id", grid.getSelectedRows());
                grid.getDataTable().ajax.reload();
                grid.clearAjaxParams();
            } else if (action.val() == "") {
                App.alert({
                    type: 'danger',
                    icon: 'warning',
                    message: 'Please select an action',
                    container: grid.getTableWrapper(),
                    place: 'prepend'
                });
            } else if (grid.getSelectedRowsCount() === 0) {
                App.alert({
                    type: 'danger',
                    icon: 'warning',
                    message: 'No record selected',
                    container: grid.getTableWrapper(),
                    place: 'prepend'
                });
            }
        });
		
        //grid.setAjaxParam("customActionType", "group_action");
        //grid.getDataTable().ajax.reload();
        //grid.clearAjaxParams();
    };
	
	var runDataTable2 = function () {
		oTable1 = $('#sample_2').dataTable({
			"bProcessing": true,
			"bStateSave": false,
			"bJQueryUI": false,
			"iDisplayLength": 20,
			"bServerSide": true,
			"bAutoWidth": false,
			"responsive": true,
			"sAjaxSource": "api/sp_customer_list_2.phtml?v1=" + v1 + "&v2=" + v2 + "&v3=" + v3 + "&z1=",
			"aoColumns": [ 
				/* ID */  { "sClass": "left" },
				/* First Name */  { "sClass": "left"},
				/* Last Name */  { "sClass": "left" },
				/* Email */  { "sClass": "left"},
				/* Customer Since */  { "sClass": "left"},
				/* Status */ { "sClass": "center" ,"bSortable": false},
				/* Action */  { "sClass": "left"}
			  ],
			  
			"aaSorting": [[0, 'desc']],
			
			"aLengthMenu": [
				[10, 20, 30, 40, 50],
				[10, 20, 30, 40, 50] // change per page values here
			],
			
			"oLanguage": {
				"sLengthMenu": "Show _MENU_ Rows",
				"sSearch": "",
				"oPaginate": {
					"sPrevious": "",
					"sNext": ""
				}
			},
			
		});
		
		$('#sample_1_wrapper .dataTables_filter input').addClass("form-control input-sm").attr("placeholder", "Search");
		// modify table search input
		$('#sample_1_wrapper .dataTables_length select').addClass("m-wrap small");
		// modify table per page dropdown
	};
	
    return {

        //main function to initiate the module
        init: function () {

            initPickers();
            runDataTable();
			runDataTable2();
        },
		
		 submitFilter: function () {

            grid.submitFilter();
        }

    };

}();

jQuery(document).ready(function() {
    TableDatatablesAjax.init();
	$('.form-filter').keypress(function (e) {
	  if (e.which == 13) {
		TableDatatablesAjax.submitFilter();
		return false; 
	  }
	});
});	
</script>
<!-- END PAGE LEVEL SCRIPTS -->
</body>
</html>