<%
	Response.CodePage = 65001
	Response.CharSet = "UTF-8"
%>
<!-- #INCLUDE File="local/local.phtml" -->
<!-- #INCLUDE File="util/xt_func_util.phtml" -->
<!-- #INCLUDE File="../util/xt_func_rc4.phtml" -->
<!-- #INCLUDE File="util/xt_func_string.phtml" -->
<!-- #INCLUDE File="include/i_login.phtml" -->
<%
	order_id = Trim(Request("so_id"))
	
	sql = "SELECT * FROM " & g_storeid & "_sales_order WHERE order_id='" & order_id & "'"
	set rsOrder = dbconn.Execute(sql)
	if not rsOrder.EOF then
		
		order_id = rsOrder("order_id")
		increment_id = rsOrder("increment_id")
		order_date = rsOrder("date_entered")
		order_status = rsOrder("status")
		order_ip = rsOrder("order_ip_addr")
		order_po_number = rsOrder("po_number")
		order_salesrep_id = rsOrder("salesrep_id")
		
		shopper_email = rsOrder("shopper_email")
		shopper_firstname = rsOrder("shopper_firstname")
		shopper_lastname = rsOrder("shopper_lastname")
		shopper_prefix = rsOrder("shopper_prefix")
		
		order_customer_name = ""
		if Len(shopper_prefix) > 0 then
			order_customer_name = shopper_prefix & "&nbsp;"
		end if
		if Len(shopper_firstname) > 0 then
			order_customer_name = order_customer_name & shopper_firstname & "&nbsp;"
		end if
		if Len(shopper_lastname) > 0 then
			order_customer_name = order_customer_name & shopper_lastname
		end if
		
		order_taxable = rsOrder("order_taxable")
		order_price_group = rsOrder("order_price_group")
		if Len(order_price_group) > 0 then
		else	
			order_price_group = "D"
		end if
		
		'--------------------------------------------------------------------------------
		billing_address_id = rsOrder("billing_address_id")
		order_billing_company = rsOrder("BillCompany")
		order_billing_firstname = rsOrder("BillFirstName")
		order_billing_lastname = rsOrder("BillLastName")
		order_billing_address = rsOrder("BillAddress")
		order_billing_city = rsOrder("BillCity")
		order_billing_state = rsOrder("BillState")
		order_billing_zip = rsOrder("BillZip")
		order_billing_country = rsOrder("BillCountry")
		order_billing_phone = rsOrder("BillPhone")
		order_billing_prefix = rsOrder("BillPrefix")
		
		order_billing_name = ""
		if Len(order_billing_prefix) > 0 then
			order_billing_name = order_billing_prefix & "&nbsp;"
		end if
		if Len(order_billing_firstname) > 0 then
			order_billing_name = order_billing_name & order_billing_firstname & "&nbsp;"
		end if
		if Len(order_billing_lastname) > 0 then
			order_billing_name = order_billing_name & order_billing_lastname
		end if
		
		'--------------------------------------------------------------------------------
		shipping_address_id = rsOrder("shipping_address_id")
		order_shipping_company = rsOrder("ShipCompany")
		order_shipping_firstname = rsOrder("ShipFirstName")
		order_shipping_lastname = rsOrder("ShipLastName")
		order_shipping_address = rsOrder("ShipAddress")
		order_shipping_city = rsOrder("ShipCity")
		order_shipping_state = rsOrder("ShipState")
		order_shipping_phone = rsOrder("ShipPhone")
		order_shipping_zip = rsOrder("ShipZIP")
		order_shipping_country = rsOrder("ShipCountry")
		order_shipping_prefix = rsOrder("ShipPrefix")
		
		order_shipping_name = ""
		if Len(order_shipping_prefix) > 0 then
			order_shipping_name = order_shipping_prefix & "&nbsp;"
		end if
		if Len(order_shipping_firstname) > 0 then
			order_shipping_name = order_shipping_name & order_shipping_firstname & "&nbsp;"
		end if
		if Len(order_shipping_lastname) > 0 then
			order_shipping_name = order_shipping_name & order_shipping_lastname
		end if
		
		'--------------------------------------------------------------------------------
		order_payment_method = rsOrder("PaymentMethod")
		order_payment_card_type = rsOrder("CardType")
		order_payment_card_number = rsOrder("CardNumber")
		order_customer_card_name = rsOrder("CardName")
		order_customer_card_exp_month = rsOrder("CardExpirationMonth")
		order_customer_card_exp_year = rsOrder("CardExpirationYear")
		
		AuthNumber = rsOrder("AuthNumber")
		RefNumber = rsOrder("RefNumber")
		
		'--------------------------------------------------------------------------------
		order_shipping_sh_method = rsOrder("SH_method")
		order_shipping_sh = rsOrder("SH")
		order_shipping_sh = FormatNumber(order_shipping_sh,2)
		order_tax = rsOrder("tax")
		order_tax = FormatNumber(order_tax)
		order_total = rsOrder("total")
		order_total = FormatNumber(order_total)
		order_tax_rate = rsOrder("order_tax_rate")
		order_tax_rate = FormatNumber(order_tax_rate,2)
		'--------------------------------------------------------------------------------
		discount_amount = rsOrder("discount_amount")
		discount_amount = FormatNumber(discount_amount,2)
		coupon_id = rsOrder("coupon_id")
		'--------------------------------------------------------------------------------
		if Len(order_comment) > 0 then
		else
			order_comment = ""
		end if
	
		if Len(order_notes) > 0 then
		else
			order_notes = ""
		end if
		
	end if
	rsOrder.Close
	set rsOrder = nothing
	
	bShowUPS = false
	bShowFedEx = false
	bShowUSPS = false
	bShowCustomFlatTable = false
	bShowCustomShippingTable = false
	sql = "SELECT * FROM " & g_storeid & "_profile"
	set rsProfile = dbconn.Execute(sql)
	if not rsProfile.EOF then
		SH_display_flag = rsProfile("SH_display_flag")
		
		if InStr(SH_display_flag, "UPS") then
			bShowUPS = true
		end if
		
		if InStr(SH_display_flag, "FedEx") then
			bShowFedEx = true
		end if
		
		if InStr(SH_display_flag, "USPS") then
			bShowUSPS = true
		end if
		
	end if
	rsProfile.Close
	set rsProfile = nothing

%>
<!--#INCLUDE FILE="include/doctype.phtml"-->
<head>
<!--#INCLUDE FILE="include/head.phtml"-->
<!-- BEGIN PAGE LEVEL PLUGINS -->
<link href="../assets/global/plugins/datatables/datatables.min.css" rel="stylesheet" type="text/css" />
<link href="../assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css" rel="stylesheet" type="text/css" />
<link href="../assets/global/plugins/bootstrap-datepicker/css/bootstrap-datepicker3.min.css" rel="stylesheet" type="text/css" />
<link href="../assets/global/plugins/bootstrap-datetimepicker/css/bootstrap-datetimepicker.min.css" rel="stylesheet" type="text/css" />
<link href="../assets/global/plugins/bootstrap-modal/css/bootstrap-modal-bs3patch.css" rel="stylesheet" type="text/css" />
<link href="../assets/global/plugins/bootstrap-modal/css/bootstrap-modal.css" rel="stylesheet" type="text/css" />
<link href="../assets/global/plugins/bootstrap-editable/bootstrap-editable/css/bootstrap-editable.css" rel="stylesheet" type="text/css" />
<!-- END PAGE LEVEL PLUGINS -->
<!--#INCLUDE FILE="include/head_bottom.phtml"-->
</head>

<body class="page-container-bg-solid ">
<div class="page-wrapper">
	<div class="page-wrapper-row">
		<div class="page-wrapper-top">
			<!--#INCLUDE FILE="include/header.phtml"-->
		</div>
	</div>
	<div class="page-wrapper-row full-height">
		<div class="page-wrapper-middle">
			<!-- BEGIN CONTAINER -->
			<div class="page-container">
				<!-- BEGIN CONTENT -->
				<div class="page-content-wrapper">
					<!-- BEGIN CONTENT BODY -->
					<!-- BEGIN PAGE HEAD-->
					<!-- END PAGE HEAD-->
					<!-- BEGIN PAGE CONTENT BODY -->
					<div class="page-content">
						<div class="container-fluid">
							<!-- BEGIN PAGE CONTENT INNER -->
							<div class="page-content-inner">
								
								<div class="row">
									<div class="col-md-12">
										<!-- Begin: life time stats -->
										<div class="portlet light portlet-fit portlet-datatable ">
											<div class="portlet-title">
												<div class="caption">
													<i class="icon-settings font-dark"></i>
													<span class="caption-subject font-dark sbold uppercase"> Order #<%=increment_id%>
														<span class="hidden-xs">| <%=order_date%> </span>
													</span>
												</div>
												<div class="actions btn-set">
													<button type="button" onclick="location.href='sales_order.phtml';" name="back" class="btn btn-default">
														<i class="fa fa-angle-left"></i> Back
													</button>
												</div>
											</div>
											<div class="portlet-body">
												<div class="tabbable-line">
													<ul class="nav nav-tabs nav-tabs-lg">
														<li class="active">
															<a href="#tab_1" data-toggle="tab">
																Information
															</a>
														</li>
														<li class="">
															<a href="#tab_2" data-toggle="tab">
																Shipment
															</a>
														</li>
														<li class="">
															<a href="#tab_3" data-toggle="tab">
																 Email
															</a>
														</li>
														<!--
														<li class="active">
															<a href="#tab_1" data-toggle="tab"> Details </a>
														</li>
														<li>
															<a href="#tab_2" data-toggle="tab"> Invoices
																<span class="badge badge-success">4</span>
															</a>
														</li>
														-->
														<li>
															<a href="#tab_4" data-toggle="tab"> Refund History </a>
														</li>
														<!--
														<li>
															<a href="#tab_4" data-toggle="tab"> Shipments
																<span class="badge badge-danger"> 2 </span>
															</a>
														</li>
														<li>
															<a href="#tab_5" data-toggle="tab"> History </a>
														</li>
														-->
													</ul>
													<div class="tab-content">
														<div class="tab-pane active" id="tab_1">
															<div class="row">
																<div class="col-md-6 col-sm-12">
																	<div class="portlet yellow-crusta box">
																		<div class="portlet-title">
																			<div class="caption">
																				<i class="fa fa-cogs"></i>Order Details </div>
																			<div class="actions">
																				
																			</div>
																		</div>
																		<div class="portlet-body">
																			<div class="row static-info">
																				<div class="col-md-5 name"> Order #: </div>
																				<div class="col-md-7 value"> <%=increment_id%>
																					<!--
																					<span class="label label-info label-sm"> Email confirmation was sent </span>
																					-->
																				</div>
																			</div>
																			<div class="row static-info">
																				<div class="col-md-5 name"> Order Date & Time: </div>
																				<div class="col-md-7 value"> <%=order_date%> </div>
																			</div>
																			<div class="row static-info">
																				<div class="col-md-5 name"> Order Status: </div>
																				<div class="col-md-7 value">
																					<a href="#" id="order_status" data-type="select" data-pk="<%=order_id%>" data-value="<%=order_status%>" data-original-title="Update Order Status">
																					<%=order_status%>
																					</a>
																				</div>
																			</div>
																			<div class="row static-info">
																				<div class="col-md-5 name"> P.O. #: </div>
																				<div class="col-md-7 value"> <%=order_po_number%> </div>
																			</div>
																			<div class="row static-info">
																				<div class="col-md-5 name"> Placed from IP: </div>
																				<div class="col-md-7 value"> <%=order_ip%> </div>
																			</div>
																		</div>
																	</div>
																</div>
																<div class="col-md-6 col-sm-12">
																	<div class="portlet blue-hoki box">
																		<div class="portlet-title">
																			<div class="caption">
																				<i class="fa fa-cogs"></i>Customer Information </div>
																			<div class="actions">
																			</div>
																		</div>
																		<div class="portlet-body">
																			<div class="row static-info">
																				<div class="col-md-5 name"> Customer Name: </div>
																				<div class="col-md-7 value"> <%=order_customer_name%> </div>
																			</div>
																			<div class="row static-info">
																				<div class="col-md-5 name"> Email: </div>
																				<div class="col-md-7 value"> 
																					<a href="#" id="shopper_email" data-type="text" data-pk="<%=order_id%>" data-placeholder="Required" data-original-title="Enter Customer Email Adddress">
																					<%=shopper_email%>
																					</a>
																				</div>
																			</div>
																			<div class="row static-info">
																				<div class="col-md-5 name"> Price Group: </div>
																				<div class="col-md-7 value"> Group <%=order_price_group%> </div>
																			</div>
																			<div class="row static-info">
																				<div class="col-md-5 name"> Sales Rep.: </div>
																				<div class="col-md-7 value"> <%=order_salesrep_id%> </div>
																			</div>
																		</div>
																	</div>
																</div>
															</div>
															<div class="row">
																<div class="col-md-6 col-sm-12">
																	<div class="portlet green-meadow box">
																		<div class="portlet-title">
																			<div class="caption">
																				<i class="fa fa-cogs"></i>Billing Address </div>
																			<div class="actions">
																				<a href="#" class="btn btn-default btn-sm" id="modal_ajax_billing" href="#" data-toggle="modal">
																					<i class="fa fa-pencil"></i> Edit 
																				</a>
																			</div>
																		</div>
																		<div class="portlet-body" id="panel_body_billing_address">
																			<div class="row">
																				<label class="col-sm-12">
																					<%=order_billing_name%>
																				</label>
																			</div>
																			<div class="row">
																				<label class="col-sm-12">
																					<%=order_billing_company%>
																				</label>
																			</div>
																			<div class="row">
																				<label class="col-sm-12">
																					<%=order_billing_address%>
																				</label>
																			</div>
																			<div class="row">
																				<label class="col-sm-12">
																					<%=order_billing_city%>, 
																					<%=order_billing_state%>&nbsp;<%=order_billing_zip%>
																				</label>
																			</div>
																			<div class="row">
																				<label class="col-sm-12">
																					<%=order_billing_country%>
																				</label>
																			</div>
																			<div class="row">
																				<label class="col-sm-12">
																					<i class="fa fa-phone"></i>&nbsp;<%=order_billing_phone%>
																				</label>
																			</div>
																		</div>
																	</div>
																</div>
																<div class="col-md-6 col-sm-12">
																	<div class="portlet red-sunglo box">
																		<div class="portlet-title">
																			<div class="caption">
																				<i class="fa fa-cogs"></i>Shipping Address </div>
																			<div class="actions">
																				<a id="modal_ajax_shipping" href="#" data-toggle="modal" class="btn btn-default btn-sm">
																					<i class="fa fa-pencil"></i> Edit </a>
																			</div>
																		</div>
																		<div class="portlet-body" id="panel_body_shipping_address">
																			<div class="row">
																				<label class="col-sm-12">
																					<%=order_shipping_name%>
																				</label>
																			</div>
																			<div class="row">
																				<label class="col-sm-12">
																					<%=order_shipping_company%>
																				</label>
																			</div>
																			<div class="row">
																				<label class="col-sm-12">
																					<%=order_shipping_address%>
																				</label>
																			</div>
																			<div class="row">
																				<label class="col-sm-12">
																					<%=order_shipping_city%>, 
																					<%=order_shipping_state%>&nbsp;<%=order_shipping_zip%>
																				</label>
																			</div>
																			<div class="row">
																				<label class="col-sm-12">
																					<%=order_shipping_country%>
																				</label>
																			</div>
																			<div class="row">
																				<label class="col-sm-12">
																					<i class="fa fa-phone"></i>&nbsp;<%=order_shipping_phone%>
																				</label>
																			</div>
																		</div>
																	</div>
																</div>
															</div>
															<div class="row">
																<div class="col-md-6 col-sm-12">
																	<div class="portlet blue-hoki box">
																		<div class="portlet-title">
																			<div class="caption">
																				<i class="fa fa-cogs"></i>Payment Information </div>
																			<div class="actions">
																				
																			</div>
																		</div>
																		<div class="portlet-body">
																			<% if order_payment_method = "PayPal Express Checkout" then %>
																				<div class="row static-info">
																					<div class="col-md-5 name"> Payment: </div>
																					<div class="col-md-7 value"> <%=order_payment_method%></div>
																				</div>
																				<% if Len(AuthNumber) > 0 then %>
																				<div class="row static-info">
																					<div class="col-md-5 name"> Transaction ID: </div>
																					<div class="col-md-7 value"> <%=AuthNumber%></div>
																				</div>
																				<% end if %>
																				<% if Len(RefNumber) > 0 then %>
																				<div class="row static-info">
																					<div class="col-md-5 name"> Payer Email: </div>
																					<div class="col-md-7 value"> <%=RefNumber%></div>
																				</div>
																				<% end if %>
																			<% else %>
																				<div class="row static-info">
																					<div class="col-md-5 name"> Payment: </div>
																					<div class="col-md-7 value"> <%=order_payment_method%></div>
																				</div>
																				<div class="row static-info">
																					<div class="col-md-5 name"> Credit Card Type: </div>
																					<div class="col-md-7 value"> <%=order_payment_card_type%> </div>
																				</div>
																				<div class="row static-info">
																					<div class="col-md-5 name"> Credit Card Number: </div>
																					<div class="col-md-7 value">
																						xxxx-<%=Right(order_payment_card_number,4)%>
																					</div>
																				</div>
																				<!--
																				<div class="row static-info">
																					<div class="col-md-5 name"> Name on the Card: </div>
																					<div class="col-md-7 value"> <%=order_card_name%></div>
																				</div>
																				-->
																				<div class="row static-info">
																					<div class="col-md-5 name"> Expiration Date: </div>
																					<div class="col-md-7 value"> <%=order_customer_card_exp_month%>/<%=order_customer_card_exp_year%> </div>
																				</div>
																				<% if Len(AuthNumber) > 0 then %>
																				<div class="row static-info">
																					<div class="col-md-5 name"> Auth Number: </div>
																					<div class="col-md-7 value"> <%=AuthNumber%></div>
																				</div>
																				<% end if %>
																				<% if Len(RefNumber) > 0 then %>
																				<div class="row static-info">
																					<div class="col-md-5 name"> Ref Number: </div>
																					<div class="col-md-7 value"> <%=RefNumber%></div>
																				</div>
																				<% end if %>
																			<% end if %>
																		</div>
																	</div>
																</div>
																<div class="col-md-6 col-sm-12">
																	<div class="portlet blue-hoki box">
																		<div class="portlet-title">
																			<div class="caption">
																				<i class="fa fa-cogs"></i>Shipping &amp; Handling </div>
																			<div class="actions">
																			</div>
																		</div>
																		<div class="portlet-body">
																			<div class="row static-info">
																				<div class="col-md-5 name"> Ship Via: </div>
																				<div class="col-md-7 value">
																					<a href="#" id="ship_via" data-type="select" data-pk="<%=order_id%>" data-value="<%=order_shipping_sh_method%>" data-original-title="Ship Via">
																					<%=order_shipping_sh_method%>
																					</a>
																				</div>
																			</div>
																			<div class="row static-info">
																				<div class="col-md-5 name"> Shipping Total: </div>
																				<div class="col-md-7 value"> $<span id="sh_panel_shipping_total"><%=order_shipping_sh%></span> </div>
																			</div>
																			<!--
																			<div class="row static-info">
																				<div class="col-md-5 name"> Taxable: </div>
																				<div class="col-md-7 value"> 
																					<a href="#" id="order_taxable" data-type="select" data-pk="<%=order_id%>" data-value="<%=order_taxable%>" data-original-title="Charge Sales Tax on Sales Order">
																					<% if order_taxable then %>
																					Yes
																					<% else %>
																					No
																					<% end if %>
																					</a>
																				</div>
																			</div>
																			<div class="row static-info">
																				<div class="col-md-5 name"> Tax Rate: </div>
																				<div class="col-md-7 value"> 
																					<%=order_tax_rate%>%
																				</div>
																			</div>
																			-->
																		</div>
																	</div>
																</div>
															</div>
															<%
																i_subtotal = 0
																sql = "SELECT * FROM " & g_storeid & "_order_item WHERE order_id='" & order_id & "' ORDER BY row_id"
																set rsOrderItems = dbconn.Execute(sql)
																do while not rsOrderItems.EOF
																	order_item_description = rsOrderItems("item_description")
																	order_item_sku = rsOrderItems("sku")
																	order_item_row_id = rsOrderItems("row_id")
																	order_item_options = rsOrderItems("options")
																	order_item_quantity = rsOrderItems("quantity")
																	order_item_adjusted_price = FormatNumber(rsOrderItems("adjusted_price"),2)
																	'order_item_cost = FormatNumber(rsOrderItems("cost"),2)
																	'order_item_pack_quantity = rsOrderItems("pack_quantity")
																	order_item_cost = 0
																	'if order_item_pack_quantity = 0 then
																		order_item_pack_quantity = 1
																	'end if
																	
																	order_item_subtotal = FormatNumber(order_item_quantity * order_item_adjusted_price * order_item_pack_quantity,2)
																	i_subtotal = i_subtotal + (order_item_quantity * order_item_adjusted_price* order_item_pack_quantity)
																	
																	
															
																	rsOrderItems.MoveNext
																loop
																rsOrderItems.Close
																set rsOrderItems = nothing
															%>
															<div class="row">
																<div class="col-md-12 col-sm-12">
																	<div class="portlet grey-cascade box">
																		<div class="portlet-title">
																			<div class="caption">
																				<i class="fa fa-cogs"></i>Items Ordered</div>
																			<div class="actions">
																				
																			</div>
																		</div>
																		<div class="portlet-body">
																			<table class="table table-hover table-striped" id="sample-table-1">
																				<thead>
																					<tr>
																						<th class="center">Product</th>
																						<th class="center">Qty</th>
																						<th class="text-right">Unit Price</th>
																						<th class="hidden-xs text-right">Sub Total</th>
																						<th class="center"></th>
																					</tr>
																				</thead>
																				<tbody id="order_detail">
																				
																				
																				</tbody>
																				<tfoot>
																					<tr>
																						<td colspan="6">
																						<a class="demo btn green" data-toggle="modal" href="#stack2"><i class="fa fa-plus"></i> Add Item </a>
																						</td>
																					</tr>
																				</tfoot>
																			</table>
																			<div class="table-responsive">
																				
																			</div>
																		</div>
																	</div>
																</div>
															</div>
															<div class="row">
																<div class="col-md-6"> 
																
																	<div class="portlet yellow-crusta box">
																		<div class="portlet-title">
																			<div class="caption">
																				<i class="fa fa-cogs"></i>Comment &amp; Note </div>
																			<div class="actions">
																				
																			</div>
																		</div>
																		<div class="portlet-body">
																			<div class="row static-info">
																				<div class="col-md-5 name"> Comments: </div>
																				<div class="col-md-7 value"> 
																					<a href="#" id="order_comments" data-type="textarea" data-pk="<%=order_id%>" data-placeholder="Your comments here..." data-original-title="Enter comments"><%=order_comment%></a>
																				</div>
																			</div>
																			<div class="row static-info">
																				<div class="col-md-5 name"> Internal Note: </div>
																				<div class="col-md-7 value"> 
																					<a href="#" id="order_notes" data-type="textarea" data-pk="<%=order_id%>" data-placeholder="Your internal note here..." data-original-title="Internal note"><%=order_notes%></a>
																				</div>
																			</div>
																			
																		</div>
																	</div>
																
																</div>
																<div class="col-md-6">
																	<div class="well">
																		<div class="row static-info align-reverse">
																			<div class="col-md-8 name"> Sub Total: </div>
																			<div class="col-md-3 value"> $<span id="order_subtotal"><%=FormatNumber(i_subtotal,2)%></span></div>
																		</div>
																		<div class="row static-info align-reverse">
																			<div class="col-md-8 name"> Shipping: </div>
																			<div class="col-md-3 value"> $<a href="#" id="order_shipping_sh" data-type="text" data-pk="<%=order_id%>" data-placeholder="Required" data-original-title="Enter Shipping Charge"><%=order_shipping_sh%></a> </div>
																		</div>
																		<div class="row static-info align-reverse">
																			<div class="col-md-8 name"> 
																			Discount
																			<% if Len(coupon_id) > 0 then %>
																			(<%=coupon_id%>)
																			<% end if %>
																			: 
																			</div>
																			<div class="col-md-3 value"> $<a href="#" id="discount_amount" data-type="text" data-pk="<%=order_id%>" data-placeholder="Required" data-original-title="Enter Discount"><%=discount_amount%></a> </div>
																		</div>
																		<div class="row static-info align-reverse">
																			<div class="col-md-8 name"> Tax: </div>
																			<div class="col-md-3 value"> <span id="order_tax"><%=order_tax%></span> </div>
																		</div>
																		<div class="row static-info align-reverse">
																			<div class="col-md-8 name"> Grand Total: </div>
																			<div class="col-md-3 value"> $<span id="order_grand_total"><%=order_total%></span> </div>
																		</div>
																	</div>
																</div>
															</div>
														</div>
														<div class="tab-pane" id="tab_2">
															<div class="row">
																<div class="col-md-12 col-sm-12">
																	<div class="portlet  green-meadow box">
																		<div class="portlet-title">
																			<div class="caption">
																				<i class="fa fa-cogs"></i>Tracking List</div>
																			<div class="actions">
																				
																			</div>
																		</div>
																		<div class="portlet-body">
																			<div class="table-container">
																				<div class="table-actions-wrapper">
																					
																				</div>
																				<table class="table table-striped table-bordered table-hover" id="sample-table-tn">
																					<thead>
																						<tr>
																							<th class="center">Tracking Number</th>
																							<th class="hidden-xs center">Shipped Date</th>
																							<th class="center">Carrier</th>
																						</tr>
																					</thead>
																					<tbody id="tn_list">
																					<%
																						sql = "SELECT * FROM " & g_storeid & "_order_tn WHERE order_id='" & order_id & "'"
																						set rsTN = dbconn.Execute(sql)
																						do while not rsTN.EOF
																							tracking_number = rsTN("tracking_number")
																							shipped_date = rsTN("shipped_date")
																							carrier = rsTN("carrier")
																							
																					%>
																						<tr>
																							<td class="center"><%=tracking_number%></td>
																							<td class="center"><%=shipped_date%></td>
																							<td class="center"><%=carrier%></td>
																						</tr>
																					<%
																							rsTN.MoveNext
																						loop
																						rsTN.Close
																						set rsTN = nothing
																					%>
																					</tbody>
																				</table>
																			</div>
																		</div>
																	</div>
																</div>
															</div>
															<div class="row">
																<div class="col-md-12 col-sm-12">
																	<div class="portlet  green-meadow box">
																		<div class="portlet-title">
																			<div class="caption">
																				<i class="fa fa-cogs"></i>New Tracking Information</div>
																			<div class="actions">
																				
																			</div>
																		</div>
																		<div class="portlet-body">
																			<form role="form" id="tn_form" name="tn_form" method=post class="form-horizontal">
																				<input type="hidden" name="order_id" id="order_id" value="<%=order_id%>">
																				<div class="col-md-12">
																					<div class="alert alert-danger display-hide">
																					<button class="close" data-close="alert"></button> You have some form errors. Please check below. 
																					</div>
																					<div class="alert alert-success display-hide">
																					<button class="close" data-close="alert"></button> Information is saved successfully.
																					</div>
																				</div>
																				
																				<div class="form-group">
																					<label class="col-sm-2 control-label" for="tn_tracking_number">
																						Tracking Number: <span class="symbol required"></span>
																					</label>
																					<div class="col-sm-9">
																						<input type="text" placeholder="" id="tn_tracking_number" name="tn_tracking_number" class="form-control" value="">
																					</div>
																				</div>
																				
																				<div class="form-group">
																					<label class="col-sm-2 control-label" for="tn_shipped_date">
																						Shipped Date: <span class="symbol required"></span>
																					</label>
																					<div class="col-sm-3">
																						<input id="tn_shipped_date" name="tn_shipped_date"class="form-control format-datepicker" type="text" data-date-viewmode="years" data-date-format="dd-mm-yyyy">
																					</div>
																					<div class="col-sm-6">
																					</div>
																				</div>
																				
																				<div class="form-group">
																					<label class="col-sm-2 control-label" for="tn_carrier">
																						Carrier: <span class="symbol required"></span>
																					</label>
																					<div class="col-sm-3">
																						<select id="tn_carrier" name="tn_carrier" class="form-control">
																							<option value=''>Select Carrier</option>
																							<option value='UPS'>UPS</option>
																							<option value='USPS'>USPS</option>
																							<option value='FEDEX'>FedEx</option>
																							<option value='OTHERS'>Others</option>
																						</select>
																					</div>
																					<div class="col-sm-6">
																					</div>
																				</div>
																				
																				<div class="row">
																					<div class="col-md-2">&nbsp;
																					</div>
																					<div class="col-md-4">
																						
																						<button class="btn blue btn-sm" type="submit">
																							<i class="fa fa-check-square"></i> Add New Tracking Number 
																						</button>
																					</div>
																				</div>
													
																			</form>
																		</div>
																	</div>
																</div>
															</div>
														</div>
														<div class="tab-pane" id="tab_3">
															<div class="row">
																<div class="col-md-12 col-sm-12">
																	<div class="portlet yellow-crusta box">
																		<div class="portlet-title">
																			<div class="caption">
																				<i class="fa fa-cogs"></i>Email History</div>
																			<div class="actions">
																				
																			</div>
																		</div>
																		<div class="portlet-body">
																			<div class="table-container">
																				<table class="table table-striped table-bordered table-hover"id="sample-table-email">
																					<thead>
																						<tr>
																							<th class="center">ID</th>
																							<th class="center">Date</th>
																							<th class="hidden-xs center">Subject</th>
																							<th class="center">Recipient Name</th>
																							<th class="hidden-xs center">Recipient Email</th>
																							<th></th>
																						</tr>
																					</thead>
																					<tbody id="email_log_list">
																					<%
																						sql = "SELECT * FROM " & g_storeid & "_email_log WHERE email_type='order' AND type_id='" & order_id & "' ORDER BY id DESC"
																						set rsEmailLog = dbconn.Execute(sql)
																						do while not rsEmailLog.EOF
																							log_id = rsEmailLog("id")
																							log_date = rsEmailLog("date")
																							log_subject = rsEmailLog("subject")
																							log_to_name = rsEmailLog("to_name")
																							log_to_email = rsEmailLog("to_email")
																							
																					%>
																						<tr>
																							<td class="center"><%=log_id%></td>
																							<td class="center"><%=log_date%></td>
																							<td class="center"><%=log_subject%></td>
																							<td class="center"><%=log_to_name%></td>
																							<td class="center"><%=log_to_email%></td>
																							<td class="center">
																								<div class="visible-md visible-lg hidden-sm hidden-xs">
																								<a href="#" class="btn btn-xs btn-teal tooltips modal-view-email"  data-toggle="modal" data-id="<%=log_id%>" data-placement="top" data-original-title="Edit"><i class="fa fa-envelope"></i></a>
																								</div>
																							</td>
																						</tr>
																					<%
																							rsEmailLog.MoveNext
																						loop
																						rsEmailLog.Close
																						set rsEmailLog = nothing
																					%>
																					</tbody>
																					
																				</table>
																			</div>
																		</div>
																	</div>
																</div>
															</div>
															<div class="row">
																<div class="col-md-12 col-sm-12">
																	<div class="portlet yellow-crusta box">
																		<div class="portlet-title">
																			<div class="caption">
																				<i class="fa fa-cogs"></i>New Tracking Information</div>
																			<div class="actions">
																				
																			</div>
																		</div>
																		<div class="portlet-body">
																			<form role="form" id="message_form" name="message_form" method=post class="form-horizontal">
																				<input type="hidden" name="order_id" id="order_id" value="<%=order_id%>">
																				<div class="col-md-12">
																					<div class="alert alert-danger display-hide">
																					<button class="close" data-close="alert"></button> You have some form errors. Please check below. 
																					</div>
																					<div class="alert alert-success display-hide">
																					<button class="close" data-close="alert"></button> Information is saved successfully.
																					</div>
																				</div>
																				
																				<div class="form-group">
																					<label class="col-sm-2 control-label" for="pf_email_to">
																						Email To: <span class="symbol required"></span>
																					</label>
																					<div class="col-sm-9">
																						<input type="text" placeholder="" id="pf_email_to" name="pf_email_to" class="form-control" value="<%=pf_email_to%>">
																					</div>
																				</div>
																				
																				<div class="form-group">
																					<label class="col-sm-2 control-label" for="pf_email_to_name">
																						Name To: <span class="symbol required"></span>
																					</label>
																					<div class="col-sm-9">
																						<input type="text" placeholder="" id="pf_email_to_name" name="pf_email_to_name" class="form-control" value="<%=pf_email_to_name%>">
																					</div>
																				</div>
																				
																				<div class="form-group">
																					<label class="col-sm-2 control-label" for="pf_email_cc">
																						Cc: 
																					</label>
																					<div class="col-sm-9">
																						<input type="text" placeholder="" id="pf_email_cc" name="pf_email_cc" class="form-control" value="<%=pf_email_cc%>">
																					</div>
																				</div>
																				
																				<div class="form-group">
																					<label class="col-sm-2 control-label" for="pf_email_subject">
																						Subject: <span class="symbol required"></span>
																					</label>
																					<div class="col-sm-9">
																						<input type="text" placeholder="" id="pf_email_subject" name="pf_email_subject" class="form-control" value="<%=pf_email_subject%>">
																					</div>
																				</div>
																				<div class="form-group">
																					<label class="col-sm-2 control-label" for="pf_email_include_invoice">
																						Include Invoice: <span class="symbol required"></span>
																					</label>
																					<div class="col-sm-4">
																						<select id="pf_email_include_invoice" name="pf_email_include_invoice" class="form-control">
																							<option value='0'>No</option>
																							<option value='1'>Yes</option>
																						</select>
																					</div>
																					<div class="col-sm-5">
																						<span id="order_email_pdf"></span>
																					</div>
																				</div>
																				
																				<div class="form-group">
																					<label class="col-sm-2 control-label" for="pf_email_content">
																						Content
																					</label>
																					<div class="col-sm-9">
																						<textarea rows="10" id="pf_email_content" name="pf_email_content" class="form-control limited"><%=pf_email_content%></textarea>
																					</div>
																				</div>
																				
																				<div class="row">
																					<div class="col-md-2">&nbsp;
																					</div>
																					<div class="col-md-4">
																						
																						<button class="btn blue btn-sm" type="submit">
																							<i class="fa fa-check-square"></i> Send 
																						</button>
																					</div>
																				</div>
																			</form>
																		</div>
																	</div>
																</div>
															</div>
														</div>
														<div class="tab-pane" id="tab_4">
															Refund History
														</div>
													</div>
												</div>
											</div>
										</div>
										<!-- End: life time stats -->
									</div>
								</div>
								
								
								
								
								
								
								
								
								
								
								
								
								
								
								
							</div>
							<!-- END PAGE CONTENT INNER -->
						</div>
					</div>
					<!-- END PAGE CONTENT BODY -->
					<!-- END CONTENT BODY -->
				</div>
				<!-- END CONTENT -->
			</div>
			<!-- END CONTAINER -->
		</div>
	</div>
	<div class="page-wrapper-row">
		<div class="page-wrapper-bottom">
			<!--#INCLUDE FILE="include/footer.phtml"-->
		</div>
	</div>
</div>

<div id="ajax-modal" class="modal fade" tabindex="-1" style="display: none;"></div>
<div id="ajax-modal2" class="modal fade" tabindex="-1" style="display: none;"></div>
<div id="ajax-modal3" class="modal fade" tabindex="-1" style="display: none;"></div>
<div id="ajax-modal4" class="modal fade" tabindex="-1" style="display: none;"></div>
<div id="dialog-confirm" title="Delete Item from Sales Order?" style="display:none;">
  <p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>This item will be permanently deleted and cannot be recovered. Are you sure?</p>
</div>
<div class="modal fade" id="stack2" tabindex="-1" data-width="960" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
<!--
<div class="modal fade" id="stack2" style="width:960px">
-->
	<div class="modal-content">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
				&times;
			</button>
			<h4 class="modal-title">Product Search</h4>
		</div>
		<div class="modal-body">
			<input id="s_sku" name="s_sku" class="form-control" data-tabindex="1" type="hidden">
			<div class="row">
				<div class="col-sm-12">
					<div class="tabbable">
						<ul id="myTab3" class="nav nav-tabs tab-green">
							<li class="active">
								<a href="#panel_tab4_example11" data-toggle="tab">
									<i class="pink fa fa-cube"></i> Your Catalog
								</a>
							</li
							<% if g_store_use_icecat_catalog = "1" then %>
							<li class="">
								<a href="#panel_tab4_example12" data-toggle="tab">
									<i class="blue fa fa-cubes"></i> ICECAT Catalog
								</a>
							</li>
							<% end if %>
							<% if g_store_use_system = "1" then %>
							<li class="">
								<a href="#panel_tab4_example13" data-toggle="tab">
									<i class="blue fa fa-laptop"></i> System
								</a>
							</li>
							<% end if %>
							<li class="">
								<a href="#panel_tab4_example14" data-toggle="tab">
									<i class="blue fa fa-pencil-square-o"></i> Manual Entry
								</a>
							</li>
						</ul>
						
						<div class="tab-content">
							<div class="tab-pane active" id="panel_tab4_example11">
								<div class="row">
									<div class="col-sm-3">
										<div class="form-group">
											<select class="form-control input-sm" id="catalog_category1">
											</select>
										</div>
									</div>
									<div class="col-sm-3">
										<div class="form-group">
											<select class="form-control input-sm" id="catalog_category2">
											</select>
										</div>
									</div>
									<div class="col-sm-3">
										<div class="form-group">
											<select class="form-control input-sm" id="catalog_category3">
											</select>
										</div>
									</div>
									<div class="col-sm-3">
										<div class="form-group">
											<select class="form-control input-sm" id="catalog_category4">
											</select>
										</div>
									</div>
								</div>
								<div class="row"><div class="col-md-12">
								<table class="table table-striped table-bordered table-hover table-full-width table-condensed" id="sample_1">
									<thead>
									<tr>
										<th>Product ID</th>
										<th>Thumbnail</th>
										<th>Name</th>
										<th>SKU</th>
										<th>Price</th>
										<th>Stock Qty.</th>
										<th>Status</th>
										<th>Action</th>
									</tr>
									</thead>
									<tbody>
										<tr>
											<td colspan="9" class="dataTables_empty">Loading data from server</td>
										</tr>
									</tbody>
								</table>
								</div></div>
							</div>
							<div class="tab-pane" id="panel_tab4_example12">
								<div class="row">
									<div class="col-sm-3">
										<div class="form-group">
											<select class="form-control input-sm" id="icecat_category1">
											</select>
										</div>
									</div>
									<div class="col-sm-3">
										<div class="form-group">
											<select class="form-control input-sm" id="icecat_category2">
											</select>
										</div>
									</div>
									<div class="col-sm-3">
										<div class="form-group">
											<select class="form-control input-sm" id="icecat_category3">
											</select>
										</div>
									</div>
									<div class="col-sm-3">
										<div class="form-group">
											<select class="form-control input-sm" id="icecat_category4">
											</select>
										</div>
									</div>
								</div>
								<div class="row"><div class="col-md-12">
								<table class="table table-striped table-bordered table-hover table-full-width table-condensed" id="sample_2">
									<thead>
									<tr>
										<th>SKU</th>
										<th>Thumbnail</th>
										<th>Name</th>
										<th>Manufacturer</th>
										<th>Mfg.Part #</th>
										<th>Cost</th>
										<th width="80">Qty.<br>(IM/TD/SY/DH)</th>
										<th>Status</th>
										<th>Action</th>
									</tr>
									</thead>
									<tbody>
										<tr>
											<td colspan="9" class="dataTables_empty">Loading data from server</td>
										</tr>
									</tbody>
								</table>
								</div></div>
							</div>
							<div class="tab-pane" id="panel_tab4_example13">
								.....
							</div>
							<div class="tab-pane" id="panel_tab4_example14">
								.....
							</div>
						</div>
					</div>
				</div>
			</div>
			
		</div>
	</div>
</div>

<!--#INCLUDE FILE="include/js.phtml"-->
<!-- BEGIN PAGE LEVEL PLUGINS -->
<script src="../assets/global/plugins/jquery-validation/js/jquery.validate.min.js" type="text/javascript"></script>
<script src="../assets/global/plugins/jquery-validation/js/additional-methods.min.js" type="text/javascript"></script>
<script src="../assets/global/scripts/datatable.js" type="text/javascript"></script>
<script src="../assets/global/plugins/datatables/datatables.min.js" type="text/javascript"></script>
<script src="../assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js" type="text/javascript"></script>
<script src="../assets/global/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js" type="text/javascript"></script>
<script src="../assets/global/plugins/bootstrap-datetimepicker/js/bootstrap-datetimepicker.min.js" type="text/javascript"></script>
<script src="../assets/global/plugins/bootstrap-maxlength/bootstrap-maxlength.min.js" type="text/javascript"></script>
<script src="../assets/global/plugins/bootstrap-modal/js/bootstrap-modalmanager.js" type="text/javascript"></script>
<script src="../assets/global/plugins/bootstrap-modal/js/bootstrap-modal.js" type="text/javascript"></script>
<script src="../assets/global/plugins/bootstrap-editable/bootstrap-editable/js/bootstrap-editable.js" type="text/javascript"></script>
<!-- END PAGE LEVEL PLUGINS -->
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script type="text/javascript">
	
var oTable1;
var oTable2;
var v1 = "";
var v2 = "";
var v3 = "";
var v4 = "";

var w1 = "";
var w2 = "";
var w3 = "";
var w4 = "";

var TableData = function () {
	//function to initiate DataTable
	//DataTable is a highly flexible tool, based upon the foundations of progressive enhancement, 
	//which will add advanced interaction controls to any HTML table
	//For more information, please visit https://datatables.net/
	var runDataTable = function () {
		oTable1 = $('#sample_1').dataTable({
			"bProcessing": true,
			"bStateSave": false,
			"bJQueryUI": false,
			"iDisplayLength": 10,
			"bServerSide": true,
			"bAutoWidth": false,
			"sAjaxSource": "api/sp_sales_order_product_list_v1.phtml?v1=" + v1 + "&v2=" + v2 + "&v3=" + v3 + "&z1=",
			"aoColumns": [ 
				/* Product ID */  { "sClass": "text-left" },
				/* Thumbnail */  { "sClass": "center","bSortable": false },
				/* Name */  { "sClass": "text-left" },
				/* sku */  { "sClass": "center" },
				/* Price */  { "sClass": "text-right"},
				/* Qty */ { "sClass": "text-right"},
				/* Status*/  { "sClass": "center" ,"bSortable": false},
				/* Action*/  { "sClass": "center" ,"bSortable": false}
			  ],
			  
			"aaSorting": [[0, 'desc']],
			
			"searchDelay": 500,
			
			"aLengthMenu": [
				[5, 10, 15, 20, 30, 40],
				[5, 10, 15, 20, 30, 40] // change per page values here
			],
			
			"oLanguage": {
				"sLengthMenu": "Show _MENU_ Rows",
				"sSearch": "",
				"sProcessing": '<img src="assets/images/ajax-loader-primary.gif"/>',
				"oPaginate": {
					"sPrevious": "",
					"sNext": ""
				}
			}
		});
		

		$('#sample_1_wrapper .dataTables_filter input').addClass("form-control input-sm").attr("placeholder", "Search");
		// modify table search input
		//$('#sample_1_wrapper .dataTables_length select').addClass("m-wrap small");
		// modify table per page dropdown
		//$('#sample_1_wrapper .dataTables_length select').select2();
		// initialzie select2 dropdown
	};
	
	var runDataTable2 = function () {
		oTable2 = $('#sample_2').dataTable({
			"bProcessing": true,
			"bStateSave": false,
			"bJQueryUI": false,
			"iDisplayLength": 10,
			"bServerSide": true,
			"bAutoWidth": false,
			"sAjaxSource": "api/sp_sales_order_icecat_list_v1.phtml?v1=" + w1 + "&v2=" + w2 + "&v3=" + w3 + "&z1=",
			"aoColumns": [ 
				/* Product ID */  { "sClass": "text-left" },
				/* Thumbnail */  { "sClass": "center","bSortable": false },
				/* Name */  { "sClass": "text-left" },
				/* sku */  { "sClass": "center" },
				/* Product ID */  { "sClass": "text-left" },
				/* Price */  { "sClass": "text-right"},
				/* Qty */ { "sClass": "text-right","bSortable": false},
				/* Status*/  { "sClass": "center" ,"bSortable": false},
				/* Action*/  { "sClass": "center" ,"bSortable": false}
			  ],
			  
			"aaSorting": [[0, 'desc']],
			
			"aLengthMenu": [
				[5, 10, 15, 20, 30, 40],
				[5, 10, 15, 20, 30, 40] // change per page values here
			],
			
			"searchDelay": 500,
			
			"oLanguage": {
				"sLengthMenu": "Show _MENU_ Rows",
				"sSearch": "",
				"sProcessing": '<img src="assets/images/ajax-loader-primary.gif"/>',
				"oPaginate": {
					"sPrevious": "",
					"sNext": ""
				}
			}
		});
		
		$('#sample_2_wrapper .dataTables_filter input').addClass("form-control input-sm").attr("placeholder", "Search");
		// modify table search input
		//$('#sample_2_wrapper .dataTables_length select').addClass("m-wrap small");
		// modify table per page dropdown
		//$('#sample_2_wrapper .dataTables_length select').select2();
		// initialzie select2 dropdown
	};
	
	return {
		//main function to initiate template pages
		init: function () {
			runDataTable();
			<% if g_store_use_icecat_catalog = "1" then %>
			runDataTable2();
			<% end if %>
		}
	};
}();

/*
function StatusFilter (theObj)
{
	v3 = theObj.value;
	oTable.fnReloadAjax("sp_sales_order_product_list.phtml?v1=" + v1 + "&v2=" + v2 + "&v3=" + theObj.value + "&z1=");
}

function VisibilityFilter (theObj)
{
	v2 = theObj.value;
	oTable.fnReloadAjax("sp_sales_order_product_list.phtml?v1=" + v1 + "&v2=" + theObj.value + "&v3=" + v3 + "&z1=");
}

function TypeFilter (theObj)
{
	v1 = theObj.value;
	oTable.fnReloadAjax("sp_sales_order_product_list.phtml?v1=" + theObj.value + "&v2=" + v2 + "&v3=" + v3 + "&z1=");
}
*/
function isValidEmailAddress(emailAddress) {
	var pattern = new RegExp(/^((([a-z]|\d|[!#\$%&'\*\+\-\/=\?\^_`{\|}~]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+(\.([a-z]|\d|[!#\$%&'\*\+\-\/=\?\^_`{\|}~]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+)*)|((\x22)((((\x20|\x09)*(\x0d\x0a))?(\x20|\x09)+)?(([\x01-\x08\x0b\x0c\x0e-\x1f\x7f]|\x21|[\x23-\x5b]|[\x5d-\x7e]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(\\([\x01-\x09\x0b\x0c\x0d-\x7f]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]))))*(((\x20|\x09)*(\x0d\x0a))?(\x20|\x09)+)?(\x22)))@((([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.)+(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.?$/i);
	return pattern.test(emailAddress);
};

</script>
<script>
//MODAL
	var UIModals = function () {
		//function to initiate bootstrap extended modals
		var initModals = function () {
			$.fn.modalmanager.defaults.resize = true;
			$.fn.modal.defaults.spinner = $.fn.modalmanager.defaults.spinner =
				'<div class="loading-spinner" style="width: 200px; margin-left: -100px;">' +
				'<div class="progress progress-striped active">' +
				'<div class="progress-bar" style="width: 100%;"></div>' +
				'</div>' +
				'</div>';
				
			var $modal = $('#ajax-modal');
			$('#modal_ajax_billing').on('click', function () {
				// create the backdrop and wait for next modal to be triggered
				$('body').modalmanager('loading');
				modal_order_id = $(this).data('id');
				setTimeout(function () {
					$modal.load('api/modal_ajax_order_billing.phtml?order_id=' + '<%=order_id%>', '', function () {
						$modal.modal();
					});
				}, 500);
			});
			
			$modal.on('hidden', function () {
				jQuery.ajax({
					type:"post",
					url: "api/sp_get_order_info.phtml",
					data: {'order_id' :'<%=order_id%>', 'infotype': 'billing_address', 'isAjax':true},
					dataType: 'json',
					success: function(data) {
						
						var EditItems= "";
						for (var i = 0; i < data.OrderInfo.length; i++){
							EditItems = data.OrderInfo[i].detail;
						}
						
						jQuery("#panel_body_billing_address").html(EditItems);
						
					}
				});
			})

			$modal.on('click', '#billing_update_btn', function () {
				
			});
			
			
			var $modal2 = $('#ajax-modal2');
			$('#modal_ajax_shipping').on('click', function () {
				// create the backdrop and wait for next modal to be triggered
				$('body').modalmanager('loading');
				modal_order_id = $(this).data('id');
				setTimeout(function () {
					$modal2.load('api/modal_ajax_order_shipping.phtml?order_id=' + '<%=order_id%>', '', function () {
						$modal2.modal();
					});
				}, 500);
			});
			
			$modal2.on('hidden', function () {
				jQuery.ajax({
					type:"post",
					url: "api/sp_get_order_info.phtml",
					data: {'order_id' :'<%=order_id%>', 'infotype': 'shipping_address', 'isAjax':true},
					dataType: 'json',
					success: function(data) {
						
						var EditItems= "";
						for (var i = 0; i < data.OrderInfo.length; i++){
							EditItems = data.OrderInfo[i].detail;
						}
						
						jQuery("#panel_body_shipping_address").html(EditItems);
						
					}
				});
			})

			$modal2.on('click', '#shipping_update_btn', function () {
				
			});
			
			var $modal4 = $('#ajax-modal4');
			$('.modal-view-email').on('click', function () {
				// create the backdrop and wait for next modal to be triggered
				$('body').modalmanager('loading');
				modal_log_id = $(this).data('id');
				setTimeout(function () {
					$modal4.load('api/modal_ajax_email_log_detail.phtml?log_id=' + modal_log_id, '', function () {
						$modal4.modal();
					});
				}, 500);
			});
			
			
		};
		return {
			init: function () {
				initModals();
			}
		};
	}();
</script>
<script language="javascript">
var FormValidator = function () {
	
	
	
	var runValidator1 = function() {
		// for more info visit the official plugin documentation: 
		// http://docs.jquery.com/Plugins/Validation

		var form1 = $('#message_form');
		var error1 = $('.alert-danger', form1);
		var success1 = $('.alert-success', form1);

		form1.validate({
			errorElement: 'span', //default input error message container
			errorClass: 'help-block help-block-error', // default input error message class
			focusInvalid: false, // do not focus the last invalid input
			ignore: "",  // validate all fields including form hidden input
			//RULES
			rules: {
				pf_email_to: {
					minlength: 2,
					required: true
				},
				pf_email_subject: {
					minlength: 2,
					required: true
				},
				pf_email_to_name: {
					minlength: 2,
					required: true
				},
				pf_email_content: {
					minlength: 2,
					required: true
				}
			},

			invalidHandler: function (event, validator) { //display error alert on form submit              
				success1.hide();
				error1.show();
				App.scrollTo(error1, -200);
			},

			errorPlacement: function (error, element) { // render error placement for each input type
				var cont = $(element).parent('.input-group');
				if (cont) {
					cont.after(error);
				} else {
					element.after(error);
				}
			},

			highlight: function (element) { // hightlight error inputs

				$(element)
					.closest('.form-group').addClass('has-error'); // set error class to the control group
			},

			unhighlight: function (element) { // revert the change done by hightlight
				$(element)
					.closest('.form-group').removeClass('has-error'); // set error class to the control group
			},

			success: function (label) {
				label
					.closest('.form-group').removeClass('has-error'); // set success class to the control group
			},

			submitHandler: function (form) {
				success1.hide();
				error1.hide();
				$.ajax({
					type: "POST",
					url: "api/sp_sales_orders_send_email.phtml",
					data: $("#message_form").serialize(),
					success: function() {
						success1.show();
						jQuery("#pf_email_content").val('');
						jQuery.ajax({
							type:"post",
							url: "api/sp_get_email_log_list.phtml",
							data: {'order_id' :'<%=order_id%>', 'isAjax':true},
							dataType: 'json',
							success: function(data) {
								
								var LogItems= "";
								for (var i = 0; i < data.EMAILLOGS.length; i++){
									LogItems = data.EMAILLOGS[i].detail;
								}
								
								jQuery("#email_log_list").html(LogItems);
								
								//Enable Modal
								UIModals.init();
							}
						});
					},
					error: function() {
						error1.show();
					}
				});
			}
		});

	};
	
	var runValidator2 = function() {
		// for more info visit the official plugin documentation: 
		// http://docs.jquery.com/Plugins/Validation

		var form1 = $('#tn_form');
		var error1 = $('.alert-danger', form1);
		var success1 = $('.alert-success', form1);

		form1.validate({
			errorElement: 'span', //default input error message container
			errorClass: 'help-block help-block-error', // default input error message class
			focusInvalid: false, // do not focus the last invalid input
			ignore: "",  // validate all fields including form hidden input
			//RULES
			rules: {
				tn_tracking_number: {
					minlength: 2,
					required: true
				},
				tn_shipped_date: {
					minlength: 2,
					required: true
				},
				tn_carrier: {
					required: true
				}
			},
			messages: {
				dept_name: "Please specify category name"
			},

			invalidHandler: function (event, validator) { //display error alert on form submit              
				success1.hide();
				error1.show();
				App.scrollTo(error1, -200);
			},

			errorPlacement: function (error, element) { // render error placement for each input type
				var cont = $(element).parent('.input-group');
				if (cont) {
					cont.after(error);
				} else {
					element.after(error);
				}
			},

			highlight: function (element) { // hightlight error inputs

				$(element)
					.closest('.form-group').addClass('has-error'); // set error class to the control group
			},

			unhighlight: function (element) { // revert the change done by hightlight
				$(element)
					.closest('.form-group').removeClass('has-error'); // set error class to the control group
			},

			success: function (label) {
				label
					.closest('.form-group').removeClass('has-error'); // set success class to the control group
			},

			submitHandler: function (form) {
				success1.hide();
				error1.hide();
				$.ajax({
					type: "POST",
					url: "api/sp_sales_orders_tn_update.phtml",
					data: $("#tn_form").serialize(),
					success: function() {
						success1.show();
						jQuery("#pf_email_content").val('');
						jQuery.ajax({
							type:"post",
							url: "api/sp_sales_order_get_tn_list.phtml",
							data: {'order_id' :'<%=order_id%>', 'isAjax':true},
							dataType: 'json',
							success: function(data) {
								
								var LogItems= "";
								for (var i = 0; i < data.EMAILLOGS.length; i++){
									LogItems = data.EMAILLOGS[i].detail;
								}
								
								jQuery("#tn_list").html(LogItems);
							}
						});
					},
					error: function() {
						error1.show();
					}
				});
			}
		});

	};
	
	/*
	
	var runValidator1 = function () {
		var form1 = $('#message_form');
		var errorHandler1 = $('#errorHandler1', form1);
		var errorHandler2 = $('#errorHandler2', form1);
		var successHandler1 = $('.successHandler', form1);
		$.validator.addMethod("FullDate", function () {
			//if all values are selected
			if ($("#dd").val() != "" && $("#mm").val() != "" && $("#yyyy").val() != "") {
				return true;
			} else {
				return false;
			}
		}, 'Please select a day, month, and year');
		$('#message_form').validate({
			errorElement: "span", // contain the error msg in a span tag
			errorClass: 'help-block',
			errorPlacement: function (error, element) { // render error placement for each input type
				if (element.attr("type") == "radio" || element.attr("type") == "checkbox") { // for chosen elements, need to insert the error after the chosen container
					error.insertAfter($(element).closest('.form-group').children('div').children().last());
				} else if (element.attr("name") == "dd" || element.attr("name") == "mm" || element.attr("name") == "yyyy") {
					error.insertAfter($(element).closest('.form-group').children('div'));
				} else {
					error.insertAfter(element);
					// for other inputs, just perform default behavior
				}
			},
			ignore: "",
			
			//RULES
			rules: {
				pf_email_to: {
					minlength: 2,
					required: true
				},
				pf_email_subject: {
					minlength: 2,
					required: true
				},
				pf_email_to_name: {
					minlength: 2,
					required: true
				},
				pf_email_content: {
					minlength: 2,
					required: true
				}
			},
			//END OF RULES
			
			invalidHandler: function (event, validator) { //display error alert on form submit
				successHandler1.hide();
				errorHandler1.show();
			},
			highlight: function (element) {
				$(element).closest('.help-block').removeClass('valid');
				$(element).closest('.form-group').removeClass('has-success').addClass('has-error').find('.symbol').removeClass('ok').addClass('required');
			},
			unhighlight: function (element) { 
				$(element).closest('.form-group').removeClass('has-error');
			},
			success: function (label, element) {
				label.addClass('help-block valid');
				$(element).closest('.form-group').removeClass('has-error').addClass('has-success').find('.symbol').removeClass('required').addClass('ok');
			},
			submitHandler: function (form) {
				successHandler1.hide();
				errorHandler1.hide();
				errorHandler2.hide();
				$.ajax({
					type: "POST",
					url: "api/sp_sales_orders_send_email.phtml",
					data: $("#message_form").serialize(),
					success: function() {
						successHandler1.show();
						jQuery("#pf_email_content").val('');
						jQuery.ajax({
							type:"post",
							url: "api/sp_get_email_log_list.phtml",
							data: {'order_id' :'<%=order_id%>', 'isAjax':true},
							dataType: 'json',
							success: function(data) {
								
								var LogItems= "";
								for (var i = 0; i < data.EMAILLOGS.length; i++){
									LogItems = data.EMAILLOGS[i].detail;
								}
								
								jQuery("#email_log_list").html(LogItems);
								
								//Enable Modal
								UIModals.init();
							}
						});
					},
					error: function() {
						errorHandler2.show();
					}
				});
			}
		});
	};
	
	var runValidator2xxx = function () {
		var form2 = $('#tn_form');
		var errorHandler1 = $('#errorHandler1', form2);
		var errorHandler2 = $('#errorHandler2', form2);
		var successHandler1 = $('.successHandler', form2);
		$.validator.addMethod("FullDate", function () {
			//if all values are selected
			if ($("#dd").val() != "" && $("#mm").val() != "" && $("#yyyy").val() != "") {
				return true;
			} else {
				return false;
			}
		}, 'Please select a day, month, and year');
		$('#tn_form').validate({
			errorElement: "span", // contain the error msg in a span tag
			errorClass: 'help-block',
			errorPlacement: function (error, element) { // render error placement for each input type
				if (element.attr("type") == "radio" || element.attr("type") == "checkbox") { // for chosen elements, need to insert the error after the chosen container
					error.insertAfter($(element).closest('.form-group').children('div').children().last());
				} else if (element.attr("name") == "dd" || element.attr("name") == "mm" || element.attr("name") == "yyyy") {
					error.insertAfter($(element).closest('.form-group').children('div'));
				} else {
					error.insertAfter(element);
					// for other inputs, just perform default behavior
				}
			},
			ignore: "",
			
			//RULES
			rules: {
				tn_tracking_number: {
					minlength: 2,
					required: true
				},
				tn_shipped_date: {
					minlength: 2,
					required: true
				},
				tn_carrier: {
					required: true
				}
			},
			//END OF RULES
			
			invalidHandler: function (event, validator) { //display error alert on form submit
				successHandler1.hide();
				errorHandler1.show();
			},
			highlight: function (element) {
				$(element).closest('.help-block').removeClass('valid');
				$(element).closest('.form-group').removeClass('has-success').addClass('has-error').find('.symbol').removeClass('ok').addClass('required');
			},
			unhighlight: function (element) { 
				$(element).closest('.form-group').removeClass('has-error');
			},
			success: function (label, element) {
				label.addClass('help-block valid');
				$(element).closest('.form-group').removeClass('has-error').addClass('has-success').find('.symbol').removeClass('required').addClass('ok');
			},
			submitHandler: function (form) {
				successHandler1.hide();
				errorHandler1.hide();
				errorHandler2.hide();
				$.ajax({
					type: "POST",
					url: "api/sp_sales_orders_tn_update.phtml",
					data: $("#tn_form").serialize(),
					success: function() {
						successHandler1.show();
						jQuery("#pf_email_content").val('');
						jQuery.ajax({
							type:"post",
							url: "api/sp_sales_order_get_tn_list.phtml",
							data: {'order_id' :'<%=order_id%>', 'isAjax':true},
							dataType: 'json',
							success: function(data) {
								
								var LogItems= "";
								for (var i = 0; i < data.EMAILLOGS.length; i++){
									LogItems = data.EMAILLOGS[i].detail;
								}
								
								jQuery("#tn_list").html(LogItems);
								
								//Enable Modal
								//UIModals.init();
							}
						});
					},
					error: function() {
						errorHandler2.show();
					}
				});
			}
		});
	};
	
	*/
	return {
		//main function to initiate template pages
		init: function () {
			runValidator1();
			runValidator2();
		}
	};
}();
</script>
<script>
	jQuery(document).ready(function() {
		TableData.init();
		UIModals.init();
		FormValidator.init();
		
	});
</script>
<script>
	jQuery(document).ready(function() {
	   //defaults
	   $.fn.editable.defaults.url = 'api/sp_sales_orders_detail_update.phtml'; 
		var c = window.location.href.match(/c=inline/i) ? 'inline' : 'popup';
				$.fn.editable.defaults.mode = c === 'inline' ? 'inline' : 'popup';

		$('#order_status').editable({
			source: [
				{value: 'pending', text: 'Pending'},
				{value: 'processing', text: 'Processing'},
				{value: 'holded', text: 'On Hold'},
				{value: 'complete', text: 'Complete'},
				{value: 'closed', text: 'Closed'},
				{value: 'canceled', text: 'Canceled'}
			] 
		});
		
		$('#order_taxable').editable({
			source: [
				{value: '1', text: 'Yes'},
				{value: '0', text: 'No'}
			] 
		});
		
		$('#ship_via').editable({
			source: [
				<% if bShowUPS then %>
				{value: 'U03', text: 'UPS GROUND'},
				{value: 'U12', text: 'UPS 3-Day Select'},
				{value: 'U02', text: 'UPS 2nd Day Air'},
				{value: 'U59', text: 'UPS 2nd Day Air AM'},
				{value: 'U13', text: 'UPS Next Day Air Saver'},
				{value: 'U01', text: 'UPS Next Day Air'},
				{value: 'U14', text: 'UPS Next Day Air Early AM'},
				{value: 'U07', text: 'UPS Worldwide Express'},
				{value: 'U08', text: 'UPS Worldwide Expedited'},
				{value: 'U11', text: 'UPS Standard'},
				{value: 'U54', text: 'UPS Worldwide Express Plus'},
				{value: 'U59', text: 'UPS 2nd Day Air AM'},
				{value: 'U65', text: 'UPS Express Saver'},
				<% end if %>
				<% if bShowFedEx then %>
				{value: 'F90', text: 'FedEx Home Delivery'},
				{value: 'F92', text: 'FedEx Ground'},
				{value: 'F03', text: 'FedEx 2Day'},
				{value: 'F05', text: 'FedEx Standard Overnight'},
				{value: 'F06', text: 'FedEx First Overnight'},
				{value: 'F20', text: 'FedEx Express Saver'},
				{value: 'F01', text: 'FedEx Priority Overnight'},
				{value: 'F03', text: 'FedEx International Economy'},
				{value: 'F06', text: 'FedEx International First'},
				{value: 'F20', text: 'FedEx International Priority'},
				<% end if %>
				<% if bShowUSPS then %>
				{value: 'S01', text: 'USPS Parcel'},
				{value: 'S02', text: 'USPS Priority'},
				{value: 'S03', text: 'USPS Express'},
				{value: 'S04', text: 'USPS Global Express Mail(EMS)'},
				{value: 'S05', text: 'USPS Airmail Parcel Post'},
				{value: 'S06', text: 'USPS Economy Parcel Post'},
				<% end if %>
				{value: 'None', text: 'None'}
			],

			success: function(response, newValue) {
				jQuery.ajax({
					type:"post",
					url: "api/sp_get_shipping_rate.phtml",
					data: {'order_id' :'<%=order_id%>', 'v1' :newValue, 'isAjax':true},
					dataType: 'json',
					success: function(data) {
						var RateValue= "0.00";
						for (var i = 0; i < data.SHIPPINGRATE.length; i++){
							RateValue = data.SHIPPINGRATE[i].rate;
						}
						RateValue1 = Number(RateValue).toFixed(2);
						$("#sh_panel_shipping_total").html(RateValue1);
						jQuery.ajax({
							type:"post",
							url: "api/sp_sales_orders_detail_update.phtml",
							data: {'name': 'order_shipping_sh', 'pk' :'<%=order_id%>', 'value' :RateValue1, 'isAjax':false},
							dataType: 'html',
							success: function(data) {
								UpdateOrderTotals();
							}
						});
						
					}
				});
			}
		});
		
		$('#order_comments').editable({
			showbuttons: 'bottom'
		}); 
		
		$('#order_notes').editable({
			showbuttons: 'bottom'
		});

		$('#shopper_email').editable({
			validate: function(value) {
			   if($.trim(value) == '') return 'This field is required';
			   if(!isValidEmailAddress(value)) return 'Valid email address is required';
			}
		});
		
		$('#order_shipping_sh').editable({
			validate: function(value) {
			   if($.trim(value) == '') return 'This field is required';
			   if($.isNumeric(value) == false) return 'Valid numeric value is required';
			},
			display: function(value, response) {
			  return false;   //disable this method
			},
			success: function(response, newValue) {
			  newValue = Number(newValue).toFixed(2);
			  $(this).html(newValue);
			  var order_subtotal = $("#order_subtotal").html();
			  var order_tax = $("#order_tax").html();
			  var discount_amount = $("#discount_amount").html();
			  
			  var order_grand_total = Number(order_subtotal) + Number(newValue) + Number(order_tax) - Number(discount_amount);
			  $("#order_grand_total").html(order_grand_total.toFixed(2));
			  
			  ProcessPostItemUpdate();
			}
		});
		
		$('#discount_amount').editable({
			validate: function(value) {
			   if($.trim(value) == '') return 'This field is required';
			   if($.isNumeric(value) == false) return 'Valid numeric value is required';
			},
			display: function(value, response) {
			  return false;   //disable this method
			},
			success: function(response, newValue) {
			  newValue = Number(newValue).toFixed(2);
			  $(this).html(newValue);
			  var order_subtotal = $("#order_subtotal").html();
			  var order_tax = $("#order_tax").html();
			  var order_shipping_sh = $("#order_shipping_sh").html();
			  
			  var order_grand_total = Number(order_subtotal) + Number(order_shipping_sh) + Number(order_tax) - Number(newValue);
			  $("#order_grand_total").html(order_grand_total.toFixed(2));
			  
			  ProcessPostItemUpdate();
			  
			}
		});
		
		$('#billing_city').editable({
			validate: function(value) {
			   if($.trim(value) == '') return 'This field is required';
			}
		});
		
		jQuery.ajax({
			type:"post",
			url: "api/sp_get_order_items.phtml",
			data: {'order_id' :'<%=order_id%>', 'isAjax':true},
			dataType: 'json',
			success: function(data) {
				
				var EditItems= "";
				for (var i = 0; i < data.ORDERITEMS.length; i++){
					EditItems = data.ORDERITEMS[i].detail;
				}
				
				jQuery("#order_detail").html(EditItems);
				ProcessPostItemUpdate();
			}
		});
		
		var $modal3 = $('#ajax-modal3');
		$modal3.on('hidden', function () {
			jQuery.ajax({
				type:"post",
				url: "api/sp_get_order_items.phtml",
				data: {'order_id' :'<%=order_id%>', 'isAjax':true},
				dataType: 'json',
				success: function(data) {
					var EditItems= "";
					for (var i = 0; i < data.ORDERITEMS.length; i++){
						EditItems = data.ORDERITEMS[i].detail;
					}
					
					jQuery("#order_detail").html(EditItems);
					
					ProcessPostItemUpdate();
				}
			});
			
		})
		
		/* PRIVATE CATALOG */
		jQuery.ajax({
			type:"post",
			url: "api/sp_catalog_get_subcategories.phtml",
			data: {parent_id: '0', 'isAjax':true},
			dataType: 'json',
			success: function(data) {
				var listItems= "<option value=''>All Categories</option>";
				for (var i = 0; i < data.Subcategories.length; i++){
					listItems+= "<option value='" + data.Subcategories[i].id + "'>" + data.Subcategories[i].name + "</option>";
				}
				var select = jQuery("#catalog_category1"), options = '';
				select.empty(); 
				select.append(listItems);
			}
		});
		
		
		jQuery( "#catalog_category1" ).change(function() {
		  jQuery.ajax({
				type:"post",
				url: "api/sp_catalog_get_subcategories.phtml",
				data: {parent_id: jQuery('#catalog_category1').val(), 'isAjax':true},
				dataType: 'json',
				success: function(data) {
					var listItems= "<option value=''>All Categories</option>";
					for (var i = 0; i < data.Subcategories.length; i++){
						listItems+= "<option value='" + data.Subcategories[i].id + "'>" + data.Subcategories[i].name + "</option>";
					}
					var select = jQuery("#catalog_category2"), options = '';
					select.empty(); 
					select.append(listItems);
					
					select = jQuery("#catalog_category3"), options = '';
					select.empty(); 
					
					select = jQuery("#catalog_category4"), options = '';
					select.empty();
					oTable1.fnReloadAjax("api/sp_sales_order_product_list.phtml?v1=" + jQuery('#catalog_category1').val());
				}
			});
		});
		
		jQuery( "#catalog_category2" ).change(function() {
		  jQuery.ajax({
				type:"post",
				url: "api/sp_catalog_get_subcategories.phtml",
				data: {parent_id: jQuery('#catalog_category2').val(), 'isAjax':true},
				dataType: 'json',
				success: function(data) {
					var listItems= "<option value=''>All Categories</option>";
					for (var i = 0; i < data.Subcategories.length; i++){
						listItems+= "<option value='" + data.Subcategories[i].id + "'>" + data.Subcategories[i].name + "</option>";
					}
					var select = jQuery("#catalog_category3"), options = '';
					select.empty(); 
					select.append(listItems);
					
					select = jQuery("#catalog_category4"), options = '';
					select.empty();
					oTable1.fnReloadAjax("api/sp_sales_order_product_list.phtml?v1=" + jQuery('#catalog_category1').val() + "&v2=" + jQuery('#catalog_category2').val());
				}
			});
		});
		
		jQuery( "#catalog_category3" ).change(function() {
		  jQuery.ajax({
				type:"post",
				url: "api/sp_catalog_get_subcategories.phtml",
				data: {parent_id: jQuery('#catalog_category3').val(), 'isAjax':true},
				dataType: 'json',
				success: function(data) {
					var listItems= "<option value=''>All Categories</option>";
					for (var i = 0; i < data.Subcategories.length; i++){
						listItems+= "<option value='" + data.Subcategories[i].id + "'>" + data.Subcategories[i].name + "</option>";
					}
					var select = jQuery("#catalog_category4"), options = '';
					select.empty(); 
					select.append(listItems);
					
					oTable1.fnReloadAjax("api/sp_sales_order_product_list.phtml?v1=" + jQuery('#catalog_category1').val() + "&v2=" + jQuery('#catalog_category2').val() + "&v3=" + jQuery('#catalog_category3').val());
				}
			});
		});
		
		/* ICECAT CATALOG */
		jQuery.ajax({
			type:"post",
			url: "api/sp_catalog_get_icecat_subcategories.phtml",
			data: {parent_id: '2833', 'isAjax':true},
			dataType: 'json',
			success: function(data) {
				var listItems= "<option value=''>All Categories</option>";
				for (var i = 0; i < data.Subcategories.length; i++){
					listItems+= "<option value='" + data.Subcategories[i].id + "'>" + data.Subcategories[i].name + "</option>";
				}
				var select = jQuery("#icecat_category1"), options = '';
				select.empty(); 
				select.append(listItems);
			}
		});
		
		jQuery( "#icecat_category1" ).change(function() {
		  jQuery.ajax({
				type:"post",
				url: "api/sp_catalog_get_icecat_subcategories.phtml",
				data: {parent_id: jQuery('#icecat_category1').val(), 'isAjax':true},
				dataType: 'json',
				success: function(data) {
					var listItems= "<option value=''>All Categories</option>";
					for (var i = 0; i < data.Subcategories.length; i++){
						listItems+= "<option value='" + data.Subcategories[i].id + "'>" + data.Subcategories[i].name + "</option>";
					}
					var select = jQuery("#icecat_category2"), options = '';
					select.empty(); 
					select.append(listItems);
					
					select = jQuery("#icecat_category3"), options = '';
					select.empty(); 
					
					select = jQuery("#icecat_category4"), options = '';
					select.empty();
					oTable2.fnReloadAjax("api/sp_sales_order_icecat_list.phtml?v1=" + jQuery('#icecat_category1').val());
				}
			});
		});
		
		jQuery( "#icecat_category2" ).change(function() {
		  jQuery.ajax({
				type:"post",
				url: "api/sp_catalog_get_icecat_subcategories.phtml",
				data: {parent_id: jQuery('#icecat_category2').val(), 'isAjax':true},
				dataType: 'json',
				success: function(data) {
					var listItems= "<option value=''>All Categories</option>";
					for (var i = 0; i < data.Subcategories.length; i++){
						listItems+= "<option value='" + data.Subcategories[i].id + "'>" + data.Subcategories[i].name + "</option>";
					}
					var select = jQuery("#icecat_category3"), options = '';
					select.empty(); 
					select.append(listItems);
					
					select = jQuery("#icecat_category4"), options = '';
					select.empty();
					oTable2.fnReloadAjax("api/sp_sales_order_icecat_list.phtml?v1=" + jQuery('#icecat_category1').val() + "&v2=" + jQuery('#icecat_category2').val());
				}
			});
		});
		
		jQuery( "#icecat_category3" ).change(function() {
		  jQuery.ajax({
				type:"post",
				url: "api/sp_catalog_get_icecat_subcategories.phtml",
				data: {parent_id: jQuery('#icecat_category3').val(), 'isAjax':true},
				dataType: 'json',
				success: function(data) {
					var listItems= "<option value=''>All Categories</option>";
					for (var i = 0; i < data.Subcategories.length; i++){
						listItems+= "<option value='" + data.Subcategories[i].id + "'>" + data.Subcategories[i].name + "</option>";
					}
					var select = jQuery("#icecat_category4"), options = '';
					select.empty(); 
					select.append(listItems);
					
					oTable2.fnReloadAjax("api/sp_sales_order_icecat_list.phtml?v1=" + jQuery('#icecat_category1').val() + "&v2=" + jQuery('#icecat_category2').val() + "&v3=" + jQuery('#icecat_category3').val());
				}
			});
		});
		
		
	   
	});
</script>
<script>
function ProcessPostItemUpdate()
{
	$('.modal-delete-line').on('click', function () {
				
		modal_row_id = $(this).data('id');
		$( "#dialog-confirm" ).dialog({
		  resizable: false,
		  width:360,
		  height:180,
		  modal: true,
		  buttons: {
			"Delete item": function() {
				$( this ).dialog( "close" );
				jQuery.ajax({
					type:"post",
					url: "api/sp_sales_orders_detail_update.phtml?name=item_delete",
					data: {'order_id' :'<%=order_id%>', 'row_id' : modal_row_id, 'isAjax':true},
					dataType: 'json',
					success: function(data) {
						
						jQuery.ajax({
							type:"post",
							url: "api/sp_get_order_items.phtml",
							data: {'order_id' :'<%=order_id%>', 'isAjax':true},
							dataType: 'json',
							success: function(data) {
								
								var EditItems= "";
								for (var i = 0; i < data.ORDERITEMS.length; i++){
									EditItems = data.ORDERITEMS[i].detail;
								}
								
								jQuery("#order_detail").html(EditItems);
								ProcessPostItemUpdate();
								
							}
						});
					}
				});
			},
			Cancel: function() {
				$( this ).dialog( "close" );
			}
		  }
		});
		
	});
	
	var $modal3 = $('#ajax-modal3');
	$('.modal-edit-line').on('click', function () {
		$('body').modalmanager('loading');
		var modal_order_id = $(this).data('id');
		setTimeout(function () {
			$modal3.load('api/modal_ajax_order_line_item.phtml?order_id=<%=order_id%>&row_id=' + modal_order_id, '', function () {
				$modal3.modal();
			});
		}, 500);
	});
	
	UpdateOrderTotals();
	UpdateShippingMethod();
	
}
function randomstring(length, special) {  var iteration = 0;  var password = "";  var randomNumber;  if(special == undefined){      var special = false;  }  while(iteration < length){    randomNumber = (Math.floor((Math.random() * 100)) % 94) + 33;    if(!special){      if ((randomNumber >=33) && (randomNumber <=47)) { continue; }      if ((randomNumber >=58) && (randomNumber <=64)) { continue; }      if ((randomNumber >=91) && (randomNumber <=96)) { continue; }      if ((randomNumber >=123) && (randomNumber <=126)) { continue; }    }    iteration++;    password += String.fromCharCode(randomNumber);  }  return password;}

function UpdateOrderTotals()
{
	jQuery.ajax({
		type:"post",
		url: "api/sp_get_order_totals.phtml",
		data: {'order_id' :'<%=order_id%>', 'isAjax':true},
		dataType: 'json',
		success: function(data) {
			
			var subtotal= "0.00";
			var grandtotal = "0.00";
			
			for (var i = 0; i < data.ORDERTOTALS.length; i++){
				subtotal = data.ORDERTOTALS[i].subtotal;
				grandtotal = data.ORDERTOTALS[i].grandtotal;
				shtotal = data.ORDERTOTALS[i].shtotal;
				taxtotal = data.ORDERTOTALS[i].taxtotal;
			}
			
			$("#order_subtotal").html(subtotal);
			$("#order_grand_total").html(grandtotal);
			$("#order_tax").text(taxtotal);
			$("#order_shipping_sh").text(shtotal);
			$("#order_shipping_sh").editable('setValue',shtotal);
			
			$("#order_email_pdf").html("<i class='fa fa-file-pdf-o'></i> <a href='docs/order<%=order_id%>.pdf?guid=" + randomstring(12) + "' target='_blank'>Sales Order #<%=order_id%> PDF</a>");
			//save grand total ...
		}
	});
	
}

function UpdateShippingMethod()
{
	
}

</script>

<script type="text/javascript">
function getSearchResult(sku, descr, cost) {
	//alert("adding private catalog item");
	$("#stack2").modal("hide");
	var $modal3 = $('#ajax-modal3');
	$('body').modalmanager('loading');
	var modal_order_id = $(this).data('id');
	setTimeout(function () {
		$modal3.load('api/modal_ajax_order_line_item.phtml?item_mode=0&order_id=<%=order_id%>&row_id=0&sku=' + sku, '', function () {
			$modal3.modal();
		});
	}, 500);
}
function getIcecatSearchResult(sku, descr, cost) {
	$("#stack2").modal("hide");
	var $modal3 = $('#ajax-modal3');
	$('body').modalmanager('loading');
	var modal_order_id = $(this).data('id');
	setTimeout(function () {
		$modal3.load('api/modal_ajax_order_line_item.phtml?item_mode=7&order_id=<%=order_id%>&row_id=0&sku=' + sku, '', function () {
			$modal3.modal();
		});
	}, 500);
}
</script>
<!-- end: JavaScript Event Handlers for this page -->
<!-- END PAGE LEVEL SCRIPTS -->
</body>
</html>