<!--#INCLUDE FILE="../../local/local.phtml"-->
<!--#INCLUDE FILE="../i_adoopen.phtml"-->
<!--#INCLUDE FILE="../../util/xt_func_session.phtml"-->
<!--#INCLUDE File="../../util/xt_func_string.phtml" -->
<!--#INCLUDE File="../../util/xt_func_misc_option.phtml" -->
<!--#INCLUDE File="../../util/xt_func_util.phtml" -->
<!--#INCLUDE File="../../util/xt_func_client.phtml" -->
<!--#INCLUDE File="../../util/xt_func_shopper.phtml" -->
<!--#INCLUDE File="../../util/xt_func_payment.phtml" -->
<!--#INCLUDE File="../../util/xt_func_rc4.phtml" -->
<!--#INCLUDE FILE="../../util/xt_func_shoppingcart.phtml"-->
<%
	dim status_msg,bcont
	op = Request("op")
	returnPage = Trim(Request("returnPage"))
	returnPage = FilterXSS(returnPage)
	
	sql = "SELECT setting_values FROM " & g_storeid & "_setting WHERE setting_type = 'M_NEW_CUSTOMER_REG_REQ_TO_FILL'"
	set rsSetting = dbconn.Execute(sql)
	if not rsSetting.EOF then
	req_setting1 = rsSetting(0)
	else
	req_setting1 = "0"
	end if
	rsSetting.Close
  
	if Len(req_setting1) = 1 then
	else
	  req_setting1 = "0"
	end if
		
	Select case op
	
	case "NEW"
		
		bcont = true
		new_email = Trim(Request.Form("new_email"))
		new_email = FilterEmailString(new_email)

		new_password1 = Trim(Request.Form("new_password1"))
		new_password1 = FilterPassword(new_password1)
		new_password2 = Trim(Request.Form("new_password2"))
		new_password2 = FilterPassword(new_password2)
		
		firstname = Request("firstname")
		lastname = Request("lastname")

		agreeterms = Request.Form("agreeterms")

		if agreeterms = "1" then
			bcont = true
		else
			bcont = false
		end if
		
		if bcont then
			'Generate unique shopper id
			g_shopper_id = GetUniqueLongIntegerID()
			
			'ADD customer
			Set rsUpdate = Server.CreateObject("ADODB.Recordset")
			with rsUpdate
				.ActiveConnection = dbconn
				.CursorLocation = 3
				.CursorType = 1
				.LockType = 3
				.Source = g_storeid & "_shopper WHERE shopper_id='0'"
				.Open
				.AddNew
			end with
			
			rsUpdate("shopper_id") = g_shopper_id
			rsUpdate("Email") = new_email
			rsUpdate("Password") = ""
			rsUpdate("FirstName") = firstname
			rsUpdate("LastName") = lastname
			
			If dbconn.Errors.Count > 0 Then
				dbconn.Errors.Clear
				rsUpdate.CancelUpdate
			else
				rsUpdate.Update
				Session("shopper_id") = g_shopper_id
			End If
			
			rsUpdate.Close
			set rsUpdate = nothing
			
			salt = getRandomString(5)
			sql = "UPDATE " & g_storeid & "_shopper SET password = CONVERT(VARCHAR(32), HashBytes('MD5', '" & salt & new_password1 & "'), 2) + ':' + '" & salt & "' WHERE shopper_id='" & g_shopper_id & "'"
			dbconn.Execute(sql)

			Session("LOGINGROUP") = "D"
			Session("Shopper_Name") = firstname & " " & lastname
			Response.Redirect g_secure_url & "register_confirm.phtml?returnPage=" & returnPage
		else

		end if 'agree terms
		
		'==================================================================
		' Clean up strings for xss
		new_password1 = FilterXSS(new_password1)
		new_password2 = FilterXSS(new_password2)
		bill_firstname = FilterXSS(bill_firstname)
		bill_lastname = FilterXSS(bill_lastname)
				
	case else
	
	End Select
	
%>