<!--#INCLUDE FILE="../../local/local.phtml"-->
<!--#INCLUDE FILE="../i_adoopen.phtml"-->
<!--#INCLUDE FILE="../../util/xt_func_session.phtml"-->
<!--#INCLUDE FILE="../../util/xt_func_string.phtml"-->
<!--#INCLUDE FILE="../../util/xt_func_util.phtml"-->
<!--#INCLUDE File="../../util/xt_func_shopper.phtml" -->
<!-- #INCLUDE File="../../util/xt_func_payment.phtml" -->
<!-- #INCLUDE File="../../util/xt_func_client.phtml" -->
<!--#INCLUDE FILE="../../util/xt_func_shoppingcart.phtml"-->
<%
	sessionID = Request("sessionID")
	sessionID = FilterSessionString(sessionID)
	if Len(sessionID) > 0 then
		Session("SESSIONKEY") = sessionID
	else
		if Len(Session("SESSIONKEY")) > 0 then
			'session key exist
		else
			'no key information...
			Response.Redirect g_secure_url
		end if
	end if
%>
<!--#INCLUDE FILE="../i_login.phtml"-->
<%
	
	if Len(Session("shopper_id")) > 0 then
	else
		Session("REFERER_URL2") = g_secure_url & "checkout.phtml"
		Response.Redirect g_secure_url & "login.phtml"
	end if
	iCount = GetTotalItemsInCart()
	if( iCount < 1 )then
		Response.Redirect g_secure_url & "cart.phtml"
	end if

	store_payment_gateway_enabled = GetSettingValue("store_payment_gateway_enabled", "0")
	store_payment_cc_type = GetSettingValue("store_payment_cc_type", "")
	store_payment_cc_use_card_id = GetSettingValue("store_payment_cc_use_card_id", "0")
	
	store_payment_check_enabled = GetSettingValue("store_payment_check_enabled", "0")
	store_payment_check_title = GetSettingValue("store_payment_check_title", "Check/Money Order")
	
	store_payment_purchase_order_enabled = GetSettingValue("store_payment_purchase_order_enabled", "0")
	store_payment_purchase_order_title = GetSettingValue("store_payment_purchase_order_title", "Purchase Order")
	
	'Response.Write(store_payment_cc_type)

%>