<!--#INCLUDE FILE="../../local/local.phtml"-->
<!--#INCLUDE FILE="../i_adoopen.phtml"-->
<!--#INCLUDE FILE="../../util/xt_func_session.phtml"-->
<!--#INCLUDE FILE="../../util/xt_func_string.phtml"-->
<!--#INCLUDE FILE="../../util/xt_func_util.phtml"-->
<!--#INCLUDE File="../../util/xt_func_shopper.phtml" -->
<!-- #INCLUDE File="../../util/xt_func_payment.phtml" -->
<!--#INCLUDE FILE="../../util/xt_func_shoppingcart.phtml"-->
<%
	sessionID = Request("sessionID")
	sessionID = FilterSessionString(sessionID)
	if Len(sessionID) > 0 then
		Session("SESSIONKEY") = sessionID
	else
		if Len(Session("SESSIONKEY")) > 0 then
			'session key exist
		else
			'no key information...
			Response.Redirect g_secure_url
		end if
	end if
%>
<!--#INCLUDE FILE="../i_login.phtml"-->
<%
	iCount = GetTotalItemsInCart()
	if( iCount < 1 )then
		Response.Redirect g_secure_url & "basket.phtml"
	end if
%>

<%
	

%>