<!--#INCLUDE FILE="../../local/local.phtml"-->
<!--#INCLUDE FILE="../i_adoopen.phtml"-->
<!--#INCLUDE FILE="../../util/xt_func_session.phtml"-->
<!--#INCLUDE FILE="../../util/xt_func_string.phtml"-->
<!--#INCLUDE FILE="../../util/xt_func_util.phtml"-->
<!--#INCLUDE File="../../util/xt_func_shopper.phtml" -->
<!-- #INCLUDE File="../../util/xt_func_payment.phtml" -->
<!--#INCLUDE FILE="../../util/xt_func_shoppingcart.phtml"-->
<%
	sessionID = Request("sessionID")
	sessionID = FilterSessionString(sessionID)
	if Len(sessionID) > 0 then
		Session("SESSIONKEY") = sessionID
	else
		if Len(Session("SESSIONKEY")) > 0 then
			'session key exist
		else
			'no key information...
			Response.Redirect g_secure_url
		end if
	end if
	
	'check dept_id dept_ID if blank...
	sql = "SELECT * FROM " &  g_storeid & "_sales_order WHERE order_id='"& Session("OrderID") & "'"
	Set rsOrder = dbconn.Execute(sql)
	if not rsOrder.EOF then
		g_increment_id = rsOrder("increment_id")
	else
		
	end if
	rsOrder.Close
%>
<!--#INCLUDE FILE="../i_login.phtml"-->