<%response.Expires=-1%>
<%
	Response.CodePage = 65001
	Response.CharSet = "UTF-8"
%>
<!-- #INCLUDE File="../local/local.phtml" -->
<!-- #INCLUDE File="../util/xt_func_util.phtml" -->
<!-- #INCLUDE File="../util/xt_func_string.phtml" -->
<%
	mfg_id=Trim(Request("mfg_id"))
	sql = "SELECT * FROM " & g_storeid & "_map_manuf WHERE dept_id = '0' AND manuf_filter='" & mfg_id & "'"
	set rsMfg = dbconn.Execute(sql)
	if not rsMfg.EOF then
		mfg_map_enabled = 1
	else
		mfg_map_enabled = 0
	end if
	rsMfg.Close
	set rsMfg = nothing
	
%>
<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
	<h4>Manufacturer</h4>
</div>
<form role="form" id='billingform'>
<input type="hidden" name="mfg_id" value="<%=mfg_id%>" />
<div class="modal-body" style="padding-left: 30px;">
	<div class="col-md-12">
		<div class="alert alert-danger display-hide">
		<button class="close" data-close="alert"></button> You have some form errors. Please check below. 
		</div>
		<div class="alert alert-success display-hide">
		<button class="close" data-close="alert"></button> Your form validation is successful! 
		</div>
	</div>
	<div class="row">
		<div class="form-group">
			<label class="col-sm-3 control-label" for="mfg_name">
				Map Enabled <span class="symbol required"></span> 
			</label>
			<div class="col-sm-9">
				<select id="mfg_map_enabled" name="mfg_map_enabled" class="form-control select input-sm">
					<option value="0" <% if mfg_map_enabled = 0 then%>selected<% end if %>>No</option>
					<option value="1" <% if mfg_map_enabled = 1 then%>selected<% end if %>>Yes</option>
				</select>
			</div>
		</div>
	</div>
</div>
<div class="modal-footer">
	<button class="btn btn-primary btn-sm" id="billing_update_btn">Update</button>
	<button type="button" data-dismiss="modal" class="btn btn-white btn-sm">Cancel</button>
</div>
</form>
<script language="javascript">
var FormValidation = function () {

	// basic validation
	var handleValidation1 = function() {
		// for more info visit the official plugin documentation: 
			// http://docs.jquery.com/Plugins/Validation

			var form1 = $('#billingform');
			var error1 = $('.alert-danger', form1);
			var success1 = $('.alert-success', form1);

			form1.validate({
				errorElement: 'span', //default input error message container
				errorClass: 'help-block help-block-error', // default input error message class
				focusInvalid: false, // do not focus the last invalid input
				ignore: "",  // validate all fields including form hidden input
				//RULES
				rules: {
					mfg_name: {
						required: true
					}
				},

				invalidHandler: function (event, validator) { //display error alert on form submit              
					success1.hide();
					error1.show();
					App.scrollTo(error1, -200);
				},

				errorPlacement: function (error, element) { // render error placement for each input type
					var cont = $(element).parent('.input-group');
					if (cont) {
						cont.after(error);
					} else {
						element.after(error);
					}
				},

				highlight: function (element) { // hightlight error inputs

					$(element)
						.closest('.form-group').addClass('has-error'); // set error class to the control group
				},

				unhighlight: function (element) { // revert the change done by hightlight
					$(element)
						.closest('.form-group').removeClass('has-error'); // set error class to the control group
				},

				success: function (label) {
					label
						.closest('.form-group').removeClass('has-error'); // set success class to the control group
				},

				submitHandler: function (form) {
					success1.hide();
					error1.hide();
					
					$.ajax({
					type: "POST",
					url: "api/sp_catalog_icecat_manufacturer_detail_update.phtml",
					data: $("#billingform").serialize(),
					success: function() {
						success1.show();
						setTimeout(function () {
							 $('#ajax-modal4').modal('hide');
						}, 700);
					},
					error: function() {
						error1.show();
					}
				});
				}
			});


	}
	return {
		//main function to initiate the module
		init: function () {
			handleValidation1();
		}
	};

}();
</script>
<script type="text/javascript">

	$("#billingform").submit(function (e) {
		e.preventDefault(); //prevent default form submit
	});
	FormValidation.init();
	
</script>