<%response.Expires=-1%>
<%
	Response.CodePage = 65001
	Response.CharSet = "UTF-8"
%>
<!-- #INCLUDE File="../local/local.phtml" -->
<!-- #INCLUDE File="../util/xt_func_util.phtml" -->
<!-- #INCLUDE File="../util/xt_func_string.phtml" -->
<%
	mfg_id=Trim(Request("mfg_id"))
	bNewMfg = true
	sql = "SELECT * FROM " & g_storeid & "_mfg WHERE mfg_id='" & mfg_id & "'"
	set rsMfg = dbconn.Execute(sql)
	if not rsMfg.EOF then
		mfg_name = rsMfg("mfg_name")
		mfg_map_enabled = rsMfg("mfg_map_enabled")
		mfg_url_key = rsMfg("url_key")
		bNewMfg = false
	end if
	rsMfg.Close
	set rsMfg = nothing
	
%>
<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
	<h4>Manufacturer</h4>
</div>
<form role="form" id='billingform' class="form-horizontal">
<div class="form-body">
<input type="hidden" name="mfg_id" value="<%=mfg_id%>" />
<div class="modal-body" style="padding-left: 30px;">
	<div class="col-md-12">
		<div class="alert alert-danger display-hide">
		<button class="close" data-close="alert"></button> You have some form errors. Please check below. 
		</div>
		<div class="alert alert-success display-hide">
		<button class="close" data-close="alert"></button> Your form validation is successful! 
		</div>
	</div>
	<div class="row">
		<div class="form-group">
			<label class="col-md-3 control-label" for="mfg_name">
				Name <span class="required"> * </span>
			</label>
			<div class="col-md-6">
				<input type="text" placeholder="" id="mfg_name" name="mfg_name" class="form-control input-sm" value="<%=mfg_name%>">
			</div>
		</div>
		<div class="form-group">
			<label class="col-md-3 control-label" for="url_key">
				URL Key <span class="symbol required"></span> 
			</label>
			<div class="col-md-6">
				<input type="text" placeholder="" id="url_key" name="url_key" class="form-control input-sm" value="<%=mfg_url_key%>">
			</div>
		</div>
		<div class="form-group">
			<label class="col-md-3 control-label" for="mfg_name">
				Map Enabled <span class="required"> * </span>
			</label>
			<div class="col-md-6">
				<select id="mfg_map_enabled" name="mfg_map_enabled" class="form-control select input-sm">
					<option value="0" <% if mfg_map_enabled = 0 then%>selected<% end if %>>No</option>
					<option value="1" <% if mfg_map_enabled = 1 then%>selected<% end if %>>Yes</option>
				</select>
			</div>
		</div>
	</div>
</div>
<div class="modal-footer">
	<button class="btn btn-primary btn-sm" id="billing_update_btn"><%if bNewMfg then%>Add<%else%>Update<%end if%></button>
	<button type="button" data-dismiss="modal" class="btn btn-white btn-sm">Cancel</button>
</div>
</div>
</form>
<script language="javascript">
var FormValidation = function () {

	// basic validation
	var handleValidation1 = function() {
		// for more info visit the official plugin documentation: 
			// http://docs.jquery.com/Plugins/Validation

			var form1 = $('#billingform');
			var error1 = $('.alert-danger', form1);
			var success1 = $('.alert-success', form1);

			form1.validate({
				errorElement: 'span', //default input error message container
				errorClass: 'help-block help-block-error', // default input error message class
				focusInvalid: false, // do not focus the last invalid input
				ignore: "",  // validate all fields including form hidden input
				//RULES
				rules: {
					mfg_name: {
						required: true
					},
					url_key: {
						minlength: 3,
						"remote":
						{
						  url: 'api/sp_product_check_url_key.phtml?pf_id=<%=mfg_id%>&url_key_type=0',
						  type: "post"
						}
					}
				},
				messages: {
					mfg_name: "Please specify name",
					url_key:
					{
						minlength: "The URL Key must be greater than 3 chracter length.",
						remote: "The specified URL Key is not unique."
					}
				},
				
				invalidHandler: function (event, validator) { //display error alert on form submit              
					success1.hide();
					error1.show();
					App.scrollTo(error1, -200);
				},


				highlight: function (element) { // hightlight error inputs

					$(element)
						.closest('.form-group').addClass('has-error'); // set error class to the control group
				},

				unhighlight: function (element) { // revert the change done by hightlight
					$(element)
						.closest('.form-group').removeClass('has-error'); // set error class to the control group
				},

				success: function (label) {
					label
						.closest('.form-group').removeClass('has-error'); // set success class to the control group
				},

				submitHandler: function (form) {
					success1.hide();
					error1.hide();
					
					$.ajax({
						type: "POST",
						url: "api/sp_catalog_manufacturer_detail_update.phtml",
						data: $("#billingform").serialize(),
						success: function() {
							success1.show();
							setTimeout(function () {
								 $('#ajax-modal3').modal('hide');
							}, 700);
						},
						error: function() {
							error1.show();
						}
					});
				}
			});


	}
	return {
		//main function to initiate the module
		init: function () {
			handleValidation1();
		}
	};

}();
</script>

<script type="text/javascript">

	$("#billingform").submit(function (e) {
		e.preventDefault(); //prevent default form submit
	});
	FormValidation.init();
	
</script>