<%@ Language=VBScript %>
<%
	Response.CodePage = 65001
	Response.CharSet = "UTF-8"
%>
<%
  Response.Expires = -1
%>
<!-- #INCLUDE File="../local/local.phtml" -->
<!-- #INCLUDE File="../util/xt_func_util.phtml" -->
<!-- #INCLUDE File="../util/xt_func_string.phtml" -->
<%
	sEcho = Trim(Request("draw"))
	iDisplayLength = Trim(Request("length"))
	iDisplayStart = Trim(Request("start"))
  
	sEcho = FilterStringEx(sEcho, "[^0-9]")
	iDisplayLength = FilterStringEx(iDisplayLength, "[^0-9]")
	iDisplayStart = FilterStringEx(iDisplayStart, "[^0-9]")

	sEcho = Cint(sEcho)
	iDisplayLength = Cint(iDisplayLength)
	iDisplayStart = Cint(iDisplayStart)
	
	'=======================================================================================
	strWhere = ""
	'---------------------------------------------------------------------------------------
	page_id = Trim(Request("page_id"))
	if Len(page_id) > 0 then
		if IsNumeric(page_id) then
			strWhere = strWhere &  " (page_id like '%" & page_id & "%') AND"
		end if
	end if
	'----------------------------------------------------------------------------------------
	page_title = Trim(Request("page_title"))
	if Len(page_title) > 1 then
		strWhere = strWhere &  " (page_title like '%" & page_title & "%') AND"
	end if
	'----------------------------------------------------------------------------------------
	page_url_key = Trim(Request("page_url_key"))
	if Len(page_url_key) > 1 then
		strWhere = strWhere &  " (page_url_key like '%" & page_url_key & "%') AND"
	end if
	'----------------------------------------------------------------------------------------
	sMin = Trim(Request("page_date_created_from"))
	sMax = Trim(Request("page_date_created_to"))
	sDateRange = ""
	if IsDate(sMin) then
		if IsDate(sMax) then
			dMax = CDate(sMax)
			dMax = DateAdd("d", 1, dMax)
			sMax = FormatDateTime(dMax,0)
			sDateRange = "(page_date_created between '" & sMin & "' AND '" & sMax & "')"
		else
			'dMin = CDate(sMin)
			dMax = Date()
			dMax = DateAdd("d", 1, dMax)
			sMax = FormatDateTime(dMax,0)
			sDateRange = "(page_date_created between '" & sMin & "' AND '" & sMax & "')"
		end if
	else
		if IsDate(sMax) then
			dMax = CDate(sMax)
			dMax = DateAdd("d", 1, dMax)
			sMax = FormatDateTime(dMax,0)
			sDateRange = "(page_date_created between '1/1/1970' AND '" & sMax & "')"
		end if
	end if
	
	if Len(sDateRange) > 0 then
		strWhere = strWhere &  " " & sDateRange & " AND"
	end if
	'----------------------------------------------------------------------------------------
	sMin = Trim(Request("page_date_updated_from"))
	sMax = Trim(Request("page_date_updated_to"))
	sDateRange = ""
	if IsDate(sMin) then
		if IsDate(sMax) then
			dMax = CDate(sMax)
			dMax = DateAdd("d", 1, dMax)
			sMax = FormatDateTime(dMax,0)
			sDateRange = "(page_date_modified between '" & sMin & "' AND '" & sMax & "')"
		else
			'dMin = CDate(sMin)
			dMax = Date()
			dMax = DateAdd("d", 1, dMax)
			sMax = FormatDateTime(dMax,0)
			sDateRange = "(page_date_modified between '" & sMin & "' AND '" & sMax & "')"
		end if
	else
		if IsDate(sMax) then
			dMax = CDate(sMax)
			dMax = DateAdd("d", 1, dMax)
			sMax = FormatDateTime(dMax,0)
			sDateRange = "(page_date_modified between '1/1/1970' AND '" & sMax & "')"
		end if
	end if
	
	if Len(sDateRange) > 0 then
		strWhere = strWhere &  " " & sDateRange & " AND"
	end if
	
	'----------------------------------------------------------------------------------------
	page_status = Trim(Request("page_status"))
	if Len(page_status) > 0 then
		strWhere = strWhere &  " (page_status = '" & page_status & "') AND"
	end if
	'----------------------------------------------------------------------------------------
	
	if Len(strWhere) > 0 then
		strWhere = Left(strWhere, Len(strWhere) - 4)
	else
		strWhere = "page_title LIKE '%%'"
	end if
	
	'=======================================================================================
	'ORDERING
	SELECT CASE Trim(Request("order[0][column]"))
	CASE "0"
		sOrder = "page_id DESC"
	CASE "1"
		sOrder = "page_id " & Trim(Request("order[0][dir]"))
	CASE "2"
		sOrder = "page_title " & Trim(Request("order[0][dir]"))
	CASE "3"
		sOrder = "page_url_key " & Trim(Request("order[0][dir]"))
	CASE "4"
		sOrder = "page_date_created " & Trim(Request("order[0][dir]"))
	CASE "5"
		sOrder = "page_date_modified " & Trim(Request("order[0][dir]"))
	CASE "6"
		sOrder = "page_status " & Trim(Request("order[0][dir]"))
	CASE "7"
		sOrder = "page_id " & Trim(Request("order[0][dir]"))
	CASE ELSE
		sOrder = "page_id DESC"
	END SELECT 
	'here we create the variable "strOrderBy" that will be used in the SQL querry
	strOrderBy = "ORDER BY " & sOrder

	'======================================================================================

	sql = "SELECT * FROM " & g_storeid & "_pages WHERE " & strWhere & " " & strOrderBy
	sqlx = "SELECT COUNT(page_id) FROM " & g_storeid & "_pages WHERE " & strWhere 

	set rs = dbconn.Execute(sql)

	iTotalDisplayRecords = 0
	iTotalRecords = 50
	set rs1 = dbconn.Execute(sqlx)
	if not rs1.EOF then
		iTotalDisplayRecords = rs1(0)
		iTotalRecords = rs1(0)
	else
	end if
	rs1.Close

	'iTotalDisplayRecords = 50

	'iTotalRecords = 50

	%>
	{"draw": <%=sEcho%>, "recordsTotal": <%=iTotalRecords%>, "recordsFiltered": <%=iTotalDisplayRecords%>, "data": [ 
	<%
	i = 0

	if rs.eof = false then
		rs.move(iDisplayStart)
		do while i < iDisplayLength and not rs.eof
			
			s_page_id = Trim(rs("page_id"))
			s_page_title = rs("page_title")
			s_date_created = rs("page_date_created")
			s_date_modified = rs("page_date_modified")
			s_page_url_key = rs("page_url_key")
			
			s_date_created = ConvertToTimeZone(s_date_created)
			s_date_modified = ConvertToTimeZone(s_date_modified)
			
			s_page_size = rs("page_size")
			i_page_status = rs("page_status")
			SELECT CASE i_page_status
			CASE 1
				s_status = "Enabled"
			CASE 2
				s_status = "Disabled"
			CASE ELSE
				s_status = "Disabled"
			END SELECT

			If Len(s_page_title) > 0 Then
				s_page_title = Replace(s_page_title, "'", "&#39")
				s_page_title = Replace(s_page_title, """", "&#34;")
			End If
						
			
			
			aaData = aaData & "['"
			aaData = aaData & "<label class=\'mt-checkbox mt-checkbox-single mt-checkbox-outline\'><input name=\'id[]\' type=\'checkbox\' class=\'checkboxes\' value=\'" &  s_block_id & "\'/><span></span></label> " & "','" 
			'aaData = aaData & "<a href=\'design_cms_page_edit.phtml?pid=" & s_page_id & "\'>" & s_page_id & "</a>','" 
			aaData = aaData & s_page_id & "','" 
			aaData = aaData & s_page_title & "','" 
			aaData = aaData & s_page_url_key & "','" 
			aaData = aaData & s_date_created & "','" 
			aaData = aaData & s_date_modified & "','"
			aaData = aaData & s_status & "','"
			'aaData = aaData & "<input type=checkbox name=\'delete_page\' value=\'" & s_page_id & "\'>" & "','"
			'if Len(s_page_url_key) > 0 then
				'aaData = aaData & "<a href=\'"& g_store_url & "" & s_page_url_key & ".html\' target=\'_FRN\'>Preview</a>" &  "'],"
			'else
				'aaData = aaData & "<a href=\'" & g_store_url & "page.phtml?pid=" & s_page_id & "\' target=\'_FRN\'>Preview</a>" &  "'],"
			'end if
			aaData = aaData & "<a href=\'design_cms_page_edit.phtml?pid=" & s_page_id & "\' class=\'btn btn-sm btn-default btn-circle btn-editable\'><i class=\'fa fa-pencil\'></i> Edit</a>&nbsp;"
			
			if Len(s_page_url_key) > 0 then
				aaData = aaData & "<a href=\'" & g_store_url & "" & s_page_url_key & ".html\' class=\'btn btn-sm btn-default btn-circle btn-editable\' target=\'_FRN\'><i class=\'fa fa-search\'></i> Preview</a>'],"
			else
				aaData = aaData & "<a href=\'" & g_store_url & "page.phtml?pid=" & s_page_id & "\' class=\'btn btn-sm btn-default btn-circle btn-editable\' target=\'_FRN\'><i class=\'fa fa-search\'></i> Preview</a>'],"
			end if
			
			
	
			
			aaData = Replace(aaData,"'",chr(34))
			rs.MoveNext
			i=i+1
		loop
		rs.Close
		if Len(aaData) > 0 then
			aaData = Left(aaData, Len(aaData)-1)
		else
			aaData = ""
		end if
	else
		aaData = ""
	end if
	response.write aaData & "] }"

%>