<%response.Expires=-1%>
<!-- #INCLUDE File="../local/local.phtml" -->
<%
	parent_id = Trim(Request("parent_id"))
%>
{
"Subcategories" : [
<%
	s_sub = ""
	if parent_id <> "" then
		sql = "SELECT dept_name, dept_id FROM " & g_storeid & "_dept WHERE parent_dept='" & parent_id & "' ORDER BY dept_name"
		set rs1 = dbconn.Execute(sql)
		do while not rs1.EOF
			s_sub = s_sub & "{""id"" : """ & rs1(1) & """,""name"" : """ & rs1(0) & """},"
			rs1.MoveNext
		loop
		rs1.Close
		set rs1 = nothing
		if Len(s_sub) > 0 then
			s_sub = Left(s_sub, Len(s_sub)-1)
		end if
	end if
	response.Write(s_sub)
%>
]
}
