<%response.Expires=-1%>
<%
	Response.CodePage = 65001
	Response.CharSet = "UTF-8"
%>
<!-- #INCLUDE File="../local/local.phtml" -->
<!-- #INCLUDE File="../util/xt_func_util.phtml" -->
<!-- #INCLUDE File="../util/xt_func_string.phtml" -->
<%
	
	'--POST DATA------------------------------------------
	mode = Trim(Request("mode"))
	system_id = Trim(Request("system_id"))
	system_op = Trim(Request("system_op"))
	dept_id = Trim(Request("dept_id"))
	
	system_sku = Trim(Request("system_sku"))
	system_name = Trim(Request("system_name"))
	system_desc = Trim(Request("system_desc"))
	system_desc2 = Trim(Request("system_desc2"))
	system_detail = Trim(Request("system_detail"))
	system_weight = Trim(Request("system_weight"))
	
	if IsNumeric(system_weight) then
	else
		system_weight = 0
	end if 

	system_is_nontaxable = Trim(Request("system_is_nontaxable"))
	system_is_noship = Trim(Request("system_is_noship"))
	system_enable_upload = Trim(Request("system_enable_upload"))
	
	system_pricing_model = Trim(Request("system_pricing_model"))
	system_update_mode = Trim(Request("system_update_mode"))
	system_option_mode = Trim(Request("system_option_mode"))
	
	system_u_markup_A = Trim(Request("system_u_markup_A"))
	system_u_markup_B = Trim(Request("system_u_markup_B"))
	system_u_markup_C = Trim(Request("system_u_markup_C"))
	system_u_markup_D = Trim(Request("system_u_markup_D"))
	
	pf_productimage = Trim(Request("productimage"))
	if Len(pf_productimage) > 3 then
	else
		pf_productimage = "--"
	end if
	
	
	formop = Trim(Request("formop"))
	group_id = Trim(Request("group_id"))
	group_name = Trim(Request("group_name"))
	
	sysdept_id = Trim(Request("sysdept_id"))
	sysdept_name = Trim(Request("sysdept_name"))
	sysdept_description = Trim(Request("sysdept_description"))
	sysdept_mode = Trim(Request("sysdept_mode"))
	allow_none = Trim(Request("allow_none"))
	none_default = Trim(Request("none_default"))
	
	if formop = "group" then
	
		if group_id = "0" then
			Set rsUpdate = Server.CreateObject("ADODB.Recordset")
			with rsUpdate
				.ActiveConnection = dbconn
				.CursorLocation = 3
				.CursorType = 1
				.LockType = 3
				.Source = g_storeid & "_system_config_group WHERE group_id='0'"
				.Open
				.AddNew
			end with
			rsUpdate("group_id") = GetUniqueLongIntegerID()
			rsUpdate("pf_id") = system_id
		else
			Set rsUpdate = Server.CreateObject("ADODB.Recordset")
			with rsUpdate
				.ActiveConnection = dbconn
				.CursorLocation = 3
				.CursorType = 1
				.LockType = 3
				.Source = g_storeid & "_system_config_group WHERE group_id='" & group_id & "'"
				.Open
			end with
			
		end if
		
		rsUpdate("group_name") = group_name
		
		If dbconn.Errors.Count > 0 Then
			dbconn.Errors.Clear
			rsUpdate.CancelUpdate
		else
			rsUpdate.Update
		End If
		
		rsUpdate.Close
		set rsUpdate = nothing
	
	end if
	
	if formop = "options" then
	
		if sysdept_id = "0" then
			
			new_row = 0
			sql = "SELECT MAX(sysdept_row) FROM " & g_storeid & "_sysdept WHERE config_id='" & system_id & "'"
			set rsMax = dbconn.Execute(sql)
			if not rsMax.EOF then
				new_row = rsMax(0) + 1
			end if
			rsMax.Close
			set rsMax = nothing
			
			if IsNumeric(new_row) then
			else
				new_row = 0
			end if
			
			Set rsUpdate = Server.CreateObject("ADODB.Recordset")
			with rsUpdate
				.ActiveConnection = dbconn
				.CursorLocation = 3
				.CursorType = 1
				.LockType = 3
				.Source = g_storeid & "_sysdept WHERE sysdept_id='0'"
				.Open
				.AddNew
			end with
			rsUpdate("sysdept_id") = GetUniqueLongIntegerID()
			rsUpdate("config_id") = system_id
			rsUpdate("sysdept_group") = ""
			rsUpdate("sysdept_row") = new_row
		else
			
			Set rsUpdate = Server.CreateObject("ADODB.Recordset")
			with rsUpdate
				.ActiveConnection = dbconn
				.CursorLocation = 3
				.CursorType = 1
				.LockType = 3
				.Source = g_storeid & "_sysdept WHERE sysdept_id='" & sysdept_id & "'"
				.Open
			end with
		end if
		
		rsUpdate("sysdept_name") = sysdept_name
		rsUpdate("sysdept_description") = sysdept_description
		rsUpdate("sysdept_mode") = sysdept_mode
		rsUpdate("allow_none") = allow_none
		rsUpdate("none_default") = none_default
		rsUpdate("sysdept_qty") = ""
		
		If dbconn.Errors.Count > 0 Then
			dbconn.Errors.Clear
			rsUpdate.CancelUpdate
		else
			rsUpdate.Update
		End If
		
		rsUpdate.Close
		set rsUpdate = nothing
		
	end if
	
	if formop = "main" then
	
		Response.Write(pf_productimage)
		
		if system_op = "new" then
			Set rsUpdate = Server.CreateObject("ADODB.Recordset")
			with rsUpdate
				.ActiveConnection = dbconn
				.CursorLocation = 3
				.CursorType = 1
				.LockType = 3
				.Source = g_storeid & "_system_product WHERE pf_id='0'"
				.Open
				.AddNew
			end with
			
			rsUpdate("pf_id") = system_id
			
			'-------------------------------------------------------------------------------------
			'GET NEW PRODUCT ID
			'-------------------------------------------------------------------------------------	
		else
			Set rsUpdate = Server.CreateObject("ADODB.Recordset")
			with rsUpdate
				.ActiveConnection = dbconn
				.CursorLocation = 3
				.CursorType = 1
				.LockType = 3
				.Source = g_storeid & "_system_product WHERE pf_id='" & system_id & "'"
				.Open
			end with
			
		end if
		
		
		rsUpdate("sku") = system_sku
		rsUpdate("name") = system_name
		rsUpdate("description") = system_desc
		rsUpdate("description2") = system_desc2
		rsUpdate("details") = system_detail
		rsUpdate("weight") = system_weight
		rsUpdate("is_nontaxable") = system_is_nontaxable
		rsUpdate("is_noship") = system_is_noship
		rsUpdate("sys_enable_upload") = system_enable_upload
		rsUpdate("pricing_model") = system_pricing_model
		rsUpdate("update_mode") = system_update_mode
		rsUpdate("option_mode") = system_option_mode
		rsUpdate("u_markup_A") = system_u_markup_A
		rsUpdate("u_markup_B") = system_u_markup_B
		rsUpdate("u_markup_C") = system_u_markup_C
		rsUpdate("u_markup_D") = system_u_markup_D
		
		rsUpdate("thumb_image") = "--"
		rsUpdate("thumb_image2") = "--"
		rsUpdate("thumb_image3") = "--"
		rsUpdate("thumb_image4") = "--"
		
		rsUpdate("mm_type") = 1
		rsUpdate("image_file") = pf_productimage
		
		If dbconn.Errors.Count > 0 Then
			dbconn.Errors.Clear
			rsUpdate.CancelUpdate
		else
			rsUpdate.Update
		End If
		
		rsUpdate.Close
		set rsUpdate = nothing
		
		
		if system_op = "new" then
		
			sql = "DELETE FROM " & g_storeid & "_system_dept_prod WHERE pf_id = '" & system_id & "'"
			dbconn.Execute sql
		
			Set rsUpdate = Server.CreateObject("ADODB.Recordset")
			with rsUpdate
				.ActiveConnection = dbconn
				.CursorLocation = 3
				.CursorType = 1
				.LockType = 3
				.Source = g_storeid & "_system_dept_prod WHERE pf_id='0'"
				.Open
				.AddNew
			end with
			
			rsUpdate("dept_id") = dept_id
			rsUpdate("pf_id") = system_id
		
			If dbconn.Errors.Count > 0 Then
				dbconn.Errors.Clear
				rsUpdate.CancelUpdate
			else
				rsUpdate.Update
			End If
			
			rsUpdate.Close
			set rsUpdate = nothing
		
		end if
	
	end if
	
	
%>