<!-- #INCLUDE File="../local/local.phtml" -->
<!-- #INCLUDE File="../util/xt_func_util.phtml" -->
<!-- #INCLUDE File="../util/xt_func_string.phtml" -->
<%
	'--POST DATA------------------------------------------
	block_id = Trim(Request("block_id"))
	block_title = Trim(Request("block_title"))
	block_identifier = Trim(Request("block_identifier"))
	block_status = Request("block_status")
	block_content = Trim(Request("block_content"))	
	'--END OF POST DATA-----------------------------------
	
	if block_id = "0" then
		Set rsUpdate = Server.CreateObject("ADODB.Recordset")
		with rsUpdate
			.ActiveConnection = dbconn
			.CursorLocation = 3
			.CursorType = 1
			.LockType = 3
			.Source = g_storeid & "_static_block WHERE block_id=0"
			.Open
			.AddNew
		end with
		rsUpdate("block_date_created") = Now()
	else
		Set rsUpdate = Server.CreateObject("ADODB.Recordset")
		with rsUpdate
			.ActiveConnection = dbconn
			.CursorLocation = 3
			.CursorType = 1
			.LockType = 3
			.Source = g_storeid & "_static_block WHERE block_id=" & block_id
			.Open
		end with
	end if
	rsUpdate("block_title") = block_title
	rsUpdate("block_identifier") = block_identifier
	rsUpdate("block_status") = block_status
	rsUpdate("block_content") = block_content
	rsUpdate("block_date_modified") = Now()
	
	If dbconn.Errors.Count > 0 Then
		dbconn.Errors.Clear
		rsUpdate.CancelUpdate
	else
		rsUpdate.Update
	End If
	
	rsUpdate.Close
	set rsUpdate = nothing
	
	
%>