<%response.Expires=-1%>
<%
	Response.CodePage = 65001
	Response.CharSet = "UTF-8"
%>
<!-- #INCLUDE File="../local/local.phtml" -->
<%
	attribute_id = Trim(Request("attribute_id"))
%>
{
"Suboptions" : [
<%
	s_sub = ""
	if attribute_id <> "" then
		sql = "SELECT option_name, option_id FROM " & g_storeid & "_eav_attribute_option WHERE attribute_id = " &  attribute_id & " ORDER BY sort_order"
		set rs1 = dbconn.Execute(sql)
		do while not rs1.EOF
			s_sub = s_sub & "{""id"" : """ & rs1(1) & """,""name"" : """ & rs1(0) & """},"
			rs1.MoveNext
		loop
		rs1.Close
		set rs1 = nothing
		if Len(s_sub) > 0 then
			s_sub = Left(s_sub, Len(s_sub)-1)
		end if
	end if
	response.Write(s_sub)
%>
]
}
