<%@ Language=VBScript %>
<%
	Response.CodePage = 65001
	Response.CharSet = "UTF-8"
%>
<%
  Response.Expires = -1
%>
<!-- #INCLUDE File="../local/local.phtml" -->
<!-- #INCLUDE File="../util/xt_func_util.phtml" -->
<!-- #INCLUDE File="../util/xt_func_string.phtml" -->
<%
	sEcho = Trim(Request("draw"))
	iDisplayLength = Trim(Request("length"))
	iDisplayStart = Trim(Request("start"))

	sEcho = FilterStringEx(sEcho, "[^0-9]")
	iDisplayLength = FilterStringEx(iDisplayLength, "[^0-9]")
	iDisplayStart = FilterStringEx(iDisplayStart, "[^0-9]")

	sEcho = Cint(sEcho)
	iDisplayLength = Cint(iDisplayLength)
	iDisplayStart = Cint(iDisplayStart)
  
	'sEcho = Cint(Request("sEcho"))
	'iDisplayLength = Cint(Request("iDisplayLength"))
	'iDisplayStart = Cint(Request("iDisplayStart"))
  
	'=======================================================================================
	strWhere = ""
	'---------------------------------------------------------------------------------------
	product_id = Trim(Request("product_id"))
	Session("DT_CATALOG_PRODUCT_1_ID") = product_id
	if Len(product_id) > 0 then
		strWhere = strWhere &  " (pf_id like '%" & product_id & "%') AND"
	end if
	'----------------------------------------------------------------------------------------
	product_name = Trim(Request("product_name"))
	Session("DT_CATALOG_PRODUCT_1_NAME") = product_name
	if Len(product_name) > 1 then
		strWhere = strWhere &  " (name like '%" & product_name & "%') AND"
	end if
	'----------------------------------------------------------------------------------------
	product_sku = Trim(Request("product_sku"))
	Session("DT_CATALOG_PRODUCT_1_SKU") = product_sku
	if Len(product_sku) > 1 then
		strWhere = strWhere &  " (sku like '%" & product_sku & "%') AND"
	end if
	'----------------------------------------------------------------------------------------
	sMin = Trim(Request("product_cost_from"))
	sMax = Trim(Request("product_cost_to"))
	Session("DT_CATALOG_PRODUCT_1_COST_FROM") = sMin
	Session("DT_CATALOG_PRODUCT_1_COST_TO") = sMax
	sTotalRange = ""
	if IsNumeric(sMin) then
		if IsNumeric(sMax) then
			sTotalRange = "(list_price between " & sMin & " AND " & sMax & ")"
		else
			sMax = "1000000"
			sTotalRange = "(list_price between " & sMin & " AND " & sMax & ")"
		end if
	else
		if IsNumeric(sMax) then
			sTotalRange = "(list_price between 0 AND " & sMax & ")"
		end if
	end if
	
	if Len(sTotalRange) > 0 then
		strWhere = strWhere &  " " & sTotalRange & " AND"
	end if
	'----------------------------------------------------------------------------------------
	sMin = Trim(Request("product_price_from"))
	sMax = Trim(Request("product_price_to"))
	Session("DT_CATALOG_PRODUCT_1_PRICE_FROM") = sMin
	Session("DT_CATALOG_PRODUCT_1_PRICE_TO") = sMax
	sTotalRange = ""
	if IsNumeric(sMin) then
		if IsNumeric(sMax) then
			sTotalRange = "(price_D between " & sMin & " AND " & sMax & ")"
		else
			sMax = "1000000"
			sTotalRange = "(price_D between " & sMin & " AND " & sMax & ")"
		end if
	else
		if IsNumeric(sMax) then
			sTotalRange = "(price_D between 0 AND " & sMax & ")"
		end if
	end if
	
	if Len(sTotalRange) > 0 then
		strWhere = strWhere &  " " & sTotalRange & " AND"
	end if
	'----------------------------------------------------------------------------------------
	sMin = Trim(Request("product_quantity_from"))
	sMax = Trim(Request("product_quantity_to"))
	Session("DT_CATALOG_PRODUCT_1_QTY_FROM") = sMin
	Session("DT_CATALOG_PRODUCT_1_QTY_TO") = sMax
	sTotalRange = ""
	if IsNumeric(sMin) then
		if IsNumeric(sMax) then
			sTotalRange = "(stock between " & sMin & " AND " & sMax & ")"
		else
			sMax = "1000000"
			sTotalRange = "(stock between " & sMin & " AND " & sMax & ")"
		end if
	else
		if IsNumeric(sMax) then
			sTotalRange = "(stock between 0 AND " & sMax & ")"
		end if
	end if
	
	if Len(sTotalRange) > 0 then
		strWhere = strWhere &  " " & sTotalRange & " AND"
	end if
	'----------------------------------------------------------------------------------------
	product_status = Trim(Request("product_status"))
	if Len(product_status) > 1 then
		strWhere = strWhere &  " (item_status = '" & product_status & "') AND"
	end if
	'----------------------------------------------------------------------------------------
	
	if Len(strWhere) > 0 then
		strWhere = Left(strWhere, Len(strWhere) - 4)
	else
		strWhere = " pf_id LIKE '%%'"
	end if
	
	
	'=======================================================================================
	'ORDERING
	SELECT CASE Trim(Request("order[0][column]"))
	CASE "0"
		sOrder = "pf_id DESC"
	CASE "1"
		sOrder = "pf_id " & Trim(Request("order[0][dir]"))
	CASE "2"
		sOrder = "pf_id " & Trim(Request("order[0][dir]"))
	CASE "3"
		sOrder = "name " & Trim(Request("order[0][dir]"))
	CASE "4"
		sOrder = "sku " & Trim(Request("order[0][dir]"))
	CASE "5"
		sOrder = "list_price " & Trim(Request("order[0][dir]"))
	CASE "6"
		sOrder = "price_D " & Trim(Request("order[0][dir]"))
	CASE "7"
		sOrder = "stock " & Trim(Request("order[0][dir]"))
	CASE "8"
		sOrder = "item_status " & Trim(Request("order[0][dir]"))
	CASE "9"
		sOrder = "pf_id DESC"
	CASE ELSE
		sOrder = "pf_id DESC"
	END SELECT 
	'here we create the variable "strOrderBy" that will be used in the SQL querry
	strOrderBy = "ORDER BY " & sOrder

	'======================================================================================
	

	Set dbconn=server.CreateObject("ADODB.Connection")
	dbconn.Open g_connection_string
	
	sql = "SELECT * FROM " & g_storeid & "_product WHERE " & strWhere & " " & strOrderBy
	sqlx = "SELECT COUNT(pf_id) FROM " & g_storeid & "_product WHERE " & strWhere 
	
	set rs = dbconn.Execute(sql)
	
	iTotalDisplayRecords = 0
	iTotalRecords = 50
	set rs1 = dbconn.Execute(sqlx)
	if not rs1.EOF then
		iTotalDisplayRecords = rs1(0)
		iTotalRecords = rs1(0)
	else
	end if
	rs1.Close
	
%>
{"draw": <%=sEcho%>, "recordsTotal": <%=iTotalRecords%>, "recordsFiltered": <%=iTotalDisplayRecords%>, "data": [ 
<%
	i = 0
	if rs.eof = false then
		rs.move(iDisplayStart)
		do while i < iDisplayLength and not rs.eof

			s_pf_id = rs("pf_id")
			s_name = Trim(rs("name"))
			
			if Session("CURRENT_ADMIN_VIEW_ID") <> "1" then
				s_name = TranslateX(s_name, 2, s_pf_id, 1)
			end if
			sku = Trim(rs("sku"))
			
			If Len(s_name) > 0 Then
				s_name = Replace(s_name, "'", "&#39")
				s_name = Replace(s_name, """", "&#34;")
			End if
			
			If Len(sku) > 0 Then
				sku = Replace(sku, "'", "&#39")
				sku = Replace(sku, """", "&#34;")
			End if
				
			s_price = FormatNumber(rs("list_price"),2)
			s_price_D = FormatNumber(rs("price_D"),2)
			s_qty = rs("stock")
			s_image_file = rs("image_file")
			s_zoom_image = rs("zoom_image")
			prod_mm_type = rs("mm_type")
			prod_espec_sku = Trim(rs("espec_sku"))
			prod_use_icecat_images = rs("use_icecat_images")
			
			SELECT CASE rs("item_status")
			CASE 0
				s_active = "Active"
			CASE 1
				s_active = "Call for Avaialability"
			CASE 2
				s_active = "Inactive"
			END SELECT
			
			
			'sqlc = "SELECT d.dept_name as dept_name FROM " & g_storeid & "_dept as d INNER JOIN " & g_storeid & "_dept_prod as dp ON d.dept_id = dp.dept_id WHERE dp.pf_id='"&s_pf_id&"'"
			'set rsDN = dbconn.execute(sqlc)
			'if not rsDN.EOF then
				'dept_name = rsDN("dept_name")
			'End If
			
			ssImgSize = "upload/w_" & "70" & ",h_" & "70" & ",c_pad/"
			if s_image_file = "--" then
				cloudImg = g_noimage_url
				ssImg = Replace(cloudImg, "upload/", ssImgSize)
			else
				if prod_mm_type = 1 then
					if Len(prod_espec_sku) > 0 AND prod_use_icecat_images = 1 then
						'USE ICECAT IMAGE
						icecat_id = 0
						if Session("ENABLEINT") = "2" OR Session("ENABLEINT") = "3" then
							sql = "SELECT * FROM A_ssprice_CA WHERE sku='" & prod_espec_sku & "'"
						else
							sql = "SELECT * FROM A_ssprice_main WHERE sku='" & prod_espec_sku & "'"
						end If

						set rsPA = dbconn_icecat.Execute(sql)
						if not rsPA.EOF then
							image_published = rsPA("image_published")
							categoryid = Trim(rsPA("CATEGORY"))
							icecat_id = rsPA("icecat_id")
						end if
						rsPA.Close

						sql = "SELECT cloudinary_url FROM [icecat].dbo.cloudinary_images WHERE product_id = " & icecat_id
						Set rsCloudImage = dbconn_icecat.Execute(sql)
						If Not rsCloudImage.EOF Then
							cloudImg = Trim(rsCloudImage("cloudinary_url"))
						Else
							sql = "SELECT * FROM " & g_storeid & "_product_image WHERE image_name = '" & prod_thumb_image & "'"
							Set rsCloudImage2 = conn.Execute(sql)
							If Not rsCloudImage2.EOF Then
								cloudImg = Trim(rsCloudImage2("cloud_url"))
							Else
								cloudImg = g_noimage_url
							End If
							rsCloudImage2.Close
							Set rsCloudImage2 = Nothing
						End If
						rsCloudImage.Close
						Set rsCloudImage = Nothing
						ssImg = Replace(cloudImg, "upload/", ssImgSize)
					else
						sql = "SELECT * FROM " & g_storeid & "_product_image WHERE image_name = '" & s_image_file & "'"
						Set rsCloudImage2 = dbconn.Execute(sql)
						If Not rsCloudImage2.EOF Then
							cloudImg = Trim(rsCloudImage2("cloud_url"))
						Else
							cloudImg = g_noimage_url
						End If
						rsCloudImage2.Close
						Set rsCloudImage2 = Nothing
						ssImg = Replace(cloudImg, "upload/", ssImgSize)
					end if
				else
					ssImg = "http://a4.res.cloudinary.com/dd3llssvr/image/fetch/" & "w_" & "70" & ",h_" & "70" & ",c_pad/" & g_store_url & "assets/pmedia/prod_img/" & Server.URLEncode(s_image_file)
				end if
			end if
			
			
			g_grid_image_url = ssImg
			
			aaData = aaData & "['"
			aaData = aaData & "<label class=\'mt-checkbox mt-checkbox-single mt-checkbox-outline\'><input name=\'id[]\' type=\'checkbox\' class=\'checkboxes\' value=\'" &  s_pf_id & "\'/><span></span></label> " & "','" 
			aaData = aaData & s_pf_id & "','" 
			'aaData = aaData & "<img src=\'" & g_secure_url & "thumb_img/" & s_thumb_image & "\' width=70>','" 
			aaData = aaData & "<img src=\'" & g_grid_image_url & "\' width=70>','" 
			aaData = aaData & s_name & "','" 
			aaData = aaData & sku & "','" 
			aaData = aaData & s_price & "','"
			aaData = aaData & s_price_D & "','"
			aaData = aaData & s_qty & "','"
			
			'aaData = aaData & dept_name & "','"
			
			SELECT CASE s_active
			CASE "Active"
				s_label = "label label-success"
			CASE "Call for Avaialability"
				s_label = "label label-warning"
			CASE "Inactive"
				s_label = "label label-danger"
			END SELECT
			
			aaData = aaData & "<span class=\'" & s_label & "\'>" & s_active & "</span>','"
			aaData = aaData & "<a href=\'catalog_product_detail.phtml?pf_id=" & s_pf_id & "\' class=\'btn btn-sm btn-default btn-circle btn-editable\'><i class=\'fa fa-pencil\'></i> Edit</a>'],"
		'	aaData = aaData & "<input type=\'checkbox\' class=\'checkbox\' name=\'prAction\' id=\'prAction\' value=\'" & s_pf_id & "\'>'],"
		  
		  aaData = Replace(aaData,"'",chr(34))
		  rs.MoveNext
		  i=i+1
		loop
		rs.Close
		aaData = Left(aaData, Len(aaData)-1)
	else
		aaData = ""
	end if
	response.write aaData & "] }"
%>