<%@ Language=VBScript %>
<%
  Response.Expires = -1
%>
<!-- #INCLUDE File="../local/local.phtml" -->
<!-- #INCLUDE File="../util/xt_func_util.phtml" -->
<!-- #INCLUDE File="../util/xt_func_string.phtml" -->
<%
	
	sEcho = Trim(Request("sEcho"))
	iDisplayLength = Trim(Request("iDisplayLength"))
	iDisplayStart = Trim(Request("iDisplayStart"))

	sEcho = FilterStringEx(sEcho, "[^0-9]")
	iDisplayLength = FilterStringEx(iDisplayLength, "[^0-9]")
	iDisplayStart = FilterStringEx(iDisplayStart, "[^0-9]")

	sEcho = Cint(sEcho)
	iDisplayLength = Cint(iDisplayLength)
	iDisplayStart = Cint(iDisplayStart)

	sSearch = Trim(Request("sSearch"))
	sSearch = FilterStringEx(sSearch, "[^0-9a-zA-Z _/-]")

	if Len(sSearch) > 0 then
		sSearchDate = Replace(sSearch, "*", "%")
	end if
	
	'================================================================================================================================
	

	'SEARCH - here we make the Where clause that will be used in the SQL querry. You only put here the fields you want to search 
	strWhere = " inventory_id NOT IN (SELECT pf_id FROM " & g_storeid & "_product) AND (inventory_id LIKE '%" & sSearch & "%' OR "
	strWhere = strWhere &  " inventory_name LIKE '%" & sSearch & "%' OR "
	strWhere = strWhere &  " inventory_sku LIKE '%" & sSearch & "%')"

	
	'=======================================================================================
	'ORDERING
	'passes through all cols and first check if the column is sortable, if yes then construct
	'the variable "order" that list in order the sequence of ordering
	for k = 0 to 7
		if Request("bSortable_" & k)="true" then
			order = order & Request("iSortCol_" & k) & " " & Request("sSortDir_" & k)
		end if
	next
	'here we replace the number corresponding the column position by the corresponding name of the column in the database
	order =	Replace(order,"0",", inventory_id")
	order =	Replace(order,"1",", inventory_id")
	order =	Replace(order,"2",", inventory_id")
	order =	Replace(order,"3",", inventory_id")
	order =	Replace(order,"4",", inventory_id")
	order =	Replace(order,"5",", inventory_id")
	order =	Replace(order,"6",", inventory_id")
	order =	Replace(order,"7",", inventory_id")
	order =	Replace(order,"8",", inventory_id")
	order =	Replace(order,"9",", inventory_id")
	
	'here we eliminate the first comma of the variable "order"
	if Len(order) > 0 then
	  order = Right(order, Len(order)-1)
	else
	  order = "inventory_id DESC"
	end if

	'here we create the variable "strOrderBy" that will be used in the SQL querry
	strOrderBy = "ORDER BY " & order
	
	'======================================================================================
	

	Set dbconn=server.CreateObject("ADODB.Connection")
	dbconn.Open g_connection_string
	
	sql = "SELECT * FROM " & g_storeid & "_product_inventory WHERE " & strWhere & " " & strOrderBy
	
	
	sqlx = "SELECT COUNT(inventory_id) FROM " & g_storeid & "_product_inventory WHERE " & strWhere 
		
	set rs = dbconn.Execute(sql)
	
	iTotalDisplayRecords = 0
	iTotalRecords = 50
	set rs1 = dbconn.Execute(sqlx)
	if not rs1.EOF then
	  iTotalDisplayRecords = rs1(0)
	  iTotalRecords = rs1(0)
	else
	end if
	rs1.Close
	
	'iTotalDisplayRecords = 50
	
	'iTotalRecords = 50
	
%>
{"sEcho": <%=sEcho%>, "iTotalRecords": <%=iTotalRecords%>, "iTotalDisplayRecords": <%=iTotalDisplayRecords%>, "aaData": [ 
<%
  i = 0
  
  if rs.eof = false then
		rs.move(iDisplayStart)
		do while i < iDisplayLength and not rs.eof
	
			s_inventory_id = rs("inventory_id")
			s_inventory_name = Trim(rs("inventory_name"))
			s_inventory_sku = Trim(rs("inventory_sku"))
			s_inventory_price = Trim(rs("inventory_name"))
			
			If Len(s_inventory_name) > 0 Then
				s_inventory_name = Replace(s_inventory_name, "'", "&#39")
				s_inventory_name = Replace(s_inventory_name, """", "&#34;")
			End if
			
			s_price = FormatNumber(rs("inventory_price_D"),2)
			s_qty = Trim(rs("inventory_qty"))
			
			
			inventory_attribute_id_1 = rs("inventory_attribute_id_1")
			inventory_attribute_option_id_1 = rs("inventory_attribute_option_id_1")
			inventory_attribute_id_2 = rs("inventory_attribute_id_2")
			inventory_attribute_option_id_2 = rs("inventory_attribute_option_id_2")
			inventory_attribute_id_3 = rs("inventory_attribute_id_3")
			inventory_attribute_option_id_3 = rs("inventory_attribute_option_id_3")
			
			'================================================================================================
			aaData = aaData & "['"
			aaData = aaData &  s_inventory_id & "','"
			aaData = aaData &  s_inventory_name & "','"
			aaData = aaData &  s_inventory_sku & "','"
			aaData = aaData &  s_price & "','"
			aaData = aaData &  s_qty & "','"
			
			
			
			sql = "SELECT attribute_id, admin_label FROM " & g_storeid & "_eav_attribute WHERE configurable=1 ORDER BY sort_order"
			set rs1 = dbconn.Execute(sql)
			do while not rs1.EOF
			
				s_option_label = ""
				qsql = ""
				SELECT CASE CInt(rs1("attribute_id"))
				CASE CInt(inventory_attribute_id_1)
					qsql = "SELECT option_name FROM " & g_storeid & "_eav_attribute_option WHERE option_id = " & inventory_attribute_option_id_1
				CASE CInt(inventory_attribute_id_2)
					qsql = "SELECT option_name FROM " & g_storeid & "_eav_attribute_option WHERE option_id = " & inventory_attribute_option_id_2
				CASE CInt(inventory_attribute_id_3)
					qsql = "SELECT option_name FROM " & g_storeid & "_eav_attribute_option WHERE option_id = " & inventory_attribute_option_id_3
				END SELECT
				
				if Len(qsql) > 0 then
					set rsq = dbconn.Execute(qsql)
					if not rsq.EOF then
						s_option_label = rsq(0)
					end if
					rsq.Close
					set rsq = nothing
				end if
				
				If Len(s_option_label) > 0 Then
					s_option_label = Replace(s_option_label, "'", "&#39")
					s_option_label = Replace(s_option_label, """", "&#34;")
				End if
			
				aaData = aaData &  s_option_label & "','"
			
				rs1.MoveNext
			loop
			rs1.Close
			set rs1 = nothing
			
			aaData = aaData & "<button type=\'button\' class=\'btn btn-xs btn-teal\' onclick=\'getSearchResult(**" & s_inventory_id & "**);\'><i class=\'fa fa-download\'></i></button>'],"
			'aaData = aaData & "']," 
		  
			  
			aaData = Replace(aaData,"'",chr(34))
			rs.MoveNext
			i=i+1
		loop
		rs.Close
		aaData = Replace(aaData,"**", "'")
		aaData = Left(aaData, Len(aaData)-1)
	else
		aaData = ""
	end if
	response.write aaData & "] }"
	
%>