<%@ Language=VBScript %>
<%
	Response.CodePage = 65001
	Response.CharSet = "UTF-8"
%>
<%
  Response.Expires = -1
%>
<!-- #INCLUDE File="../local/local.phtml" -->
<!-- #INCLUDE File="../util/xt_func_util.phtml" -->
<!-- #INCLUDE File="../util/xt_func_string.phtml" -->
<%
	sEcho = Trim(Request("draw"))
	iDisplayLength = Trim(Request("length"))
	iDisplayStart = Trim(Request("start"))

	sEcho = FilterStringEx(sEcho, "[^0-9]")
	iDisplayLength = FilterStringEx(iDisplayLength, "[^0-9]")
	iDisplayStart = FilterStringEx(iDisplayStart, "[^0-9]")

	sEcho = Cint(sEcho)
	iDisplayLength = Cint(iDisplayLength)
	iDisplayStart = Cint(iDisplayStart)
	
	'=======================================================================================
	strWhere = ""
	'---------------------------------------------------------------------------------------
	quote_id = Trim(Request("quote_id"))
	if Len(quote_id) > 0 then
		if IsNumeric(quote_id) then
			strWhere = strWhere &  " (quote_id like '%" & quote_id & "%') AND"
		end if
	end if
	'----------------------------------------------------------------------------------------
	sMin = Trim(Request("quote_date_from"))
	sMax = Trim(Request("quote_date_to"))
	sDateRange = ""
	if IsDate(sMin) then
		if IsDate(sMax) then
			dMax = CDate(sMax)
			dMax = DateAdd("d", 1, dMax)
			sMax = FormatDateTime(dMax,0)
			sDateRange = "(date_created between '" & sMin & "' AND '" & sMax & "')"
		else
			'dMin = CDate(sMin)
			dMax = Date()
			dMax = DateAdd("d", 1, dMax)
			sMax = FormatDateTime(dMax,0)
			sDateRange = "(date_created between '" & sMin & "' AND '" & sMax & "')"
		end if
	else
		if IsDate(sMax) then
			dMax = CDate(sMax)
			dMax = DateAdd("d", 1, dMax)
			sMax = FormatDateTime(dMax,0)
			sDateRange = "(date_created between '1/1/1970' AND '" & sMax & "')"
		end if
	end if
	
	if Len(sDateRange) > 0 then
		strWhere = strWhere &  " " & sDateRange & " AND"
	end if
	'----------------------------------------------------------------------------------------
	quote_customer_company = Trim(Request("quote_customer_company"))
	if Len(quote_customer_company) > 1 then
		strWhere = strWhere &  " (company_name like '%" & quote_customer_company & "%') AND"
	end if
	'----------------------------------------------------------------------------------------
	quote_customer_name = Trim(Request("quote_customer_name"))
	if Len(quote_customer_name) > 1 then
		strWhere = strWhere &  " (shopper_firstname + ' ' + shopper_lastname like '%" & quote_customer_name & "%') AND"
	end if
	'----------------------------------------------------------------------------------------
	'order_ship_to = Trim(Request("order_ship_to"))
	'if Len(order_ship_to) > 1 then
		'strWhere = strWhere &  " (ShipFirstName + ' ' + ShipLastName like '%" & order_ship_to & "%') AND"
	'end if
	'----------------------------------------------------------------------------------------
	sMin = Trim(Request("quote_price_from"))
	sMax = Trim(Request("quote_price_to"))
	sTotalRange = ""
	if IsNumeric(sMin) then
		if IsNumeric(sMax) then
			sTotalRange = "(quote_amount between " & sMin & " AND " & sMax & ")"
		else
			sMax = "1000000"
			sTotalRange = "(quote_amount between " & sMin & " AND " & sMax & ")"
		end if
	else
		if IsNumeric(sMax) then
			sTotalRange = "(quote_amount between 0 AND " & sMax & ")"
		end if
	end if
	
	if Len(sTotalRange) > 0 then
		strWhere = strWhere &  " " & sTotalRange & " AND"
	end if
	'----------------------------------------------------------------------------------------
	quote_status = Trim(Request("quote_status"))
	if Len(quote_status) > 0 then
		strWhere = strWhere &  " (quote_status = '" & quote_status & "') AND"
	end if
	'----------------------------------------------------------------------------------------
	quote_owner = Trim(Request("quote_owner"))
	if Len(quote_owner) > 0 then
		strWhere = strWhere &  " (quote_owner = '" & quote_owner & "') AND"
	end if
	'----------------------------------------------------------------------------------------
	quote_name = Trim(Request("quote_name"))
	if Len(quote_name) > 1 then
		strWhere = strWhere &  " (quote_name like '%" & quote_name & "%') AND"
	end if
	'----------------------------------------------------------------------------------------
	quote_so = Trim(Request("quote_so"))
	if Len(quote_so) > 1 then
		strWhere = strWhere &  " (order_id like '%" & quote_so & "%') AND"
	end if
	'----------------------------------------------------------------------------------------
	
	if Len(strWhere) > 0 then
		strWhere = Left(strWhere, Len(strWhere) - 4)
	else
		strWhere = " quote_name LIKE '%%'"
	end if
	
	
	'=======================================================================================
	'ORDERING
	SELECT CASE Trim(Request("order[0][column]"))
	CASE "0"
		sOrder = "quote_id DESC"
	CASE "1"
		sOrder = "quote_id " & Trim(Request("order[0][dir]"))
	CASE "2"
		sOrder = "date_created " & Trim(Request("order[0][dir]"))
	CASE "3"
		sOrder = "company_name " & Trim(Request("order[0][dir]"))
	CASE "4"
		sOrder = "shopper_firstname + ' ' + shopper_lastname " & Trim(Request("order[0][dir]"))
	CASE "5"
		sOrder = "quote_amount " & Trim(Request("order[0][dir]"))
	CASE "6"
		sOrder = "quote_status " & Trim(Request("order[0][dir]"))
	CASE "7"
		sOrder = "quote_owner " & Trim(Request("order[0][dir]"))
	CASE "8"
		sOrder = "quote_name " & Trim(Request("order[0][dir]"))
	CASE "9"
		sOrder = "order_id " & Trim(Request("order[0][dir]"))
	CASE ELSE
		sOrder = "quote_id DESC"
	END SELECT 
	'here we create the variable "strOrderBy" that will be used in the SQL querry
	strOrderBy = "ORDER BY " & sOrder

	'======================================================================================
	strWhere = " dist_name LIKE '%%'"
	strOrderBy = "ORDER BY po_id DESC"
	

	sql = "SELECT * FROM " & g_storeid & "_po WHERE " & strWhere & " " & strOrderBy
	sqlx = "SELECT COUNT(po_id) FROM " & g_storeid & "_po WHERE " & strWhere 

	set rs = dbconn.Execute(sql)

	iTotalDisplayRecords = 0
	iTotalRecords = 50
	set rs1 = dbconn.Execute(sqlx)
	if not rs1.EOF then
		iTotalDisplayRecords = rs1(0)
		iTotalRecords = rs1(0)
	else
	end if
	rs1.Close

	'iTotalDisplayRecords = 50

	'iTotalRecords = 50

	%>
	{"draw": <%=sEcho%>, "recordsTotal": <%=iTotalRecords%>, "recordsFiltered": <%=iTotalDisplayRecords%>, "data": [ 
	<%
	i = 0

	if rs.eof = false then
		rs.move(iDisplayStart)
		do while i < iDisplayLength and not rs.eof
			
			s_po_id = Trim(rs("po_id"))
			s_po_dist_name = rs("dist_name")
			s_po_amount = FormatNumber(rs("po_amount"),2)
			
			po_status = rs("po_status")

			s_date_created = rs("date_created")
			s_date_updated = rs("date_updated")
			
			s_date_created = ConvertToTimeZone(s_date_created)
			s_date_updated = ConvertToTimeZone(s_date_updated)
			
			s_po_dist_flag = rs("po_dist_flag")
			s_shipping_contact_first = rs("shipping_contact_first")
			s_shipping_contact_last = rs("shipping_contact_last")
			s_shipping_contact = rs("shipping_contact")


			select case po_status
			case 0
				s_po_status = "Pending"
			case 1
				s_po_status = "Closed"
			case 2
				s_po_status = "Approved"
			case 3
				
				if po_dist_flag = 2 then ' Tech Data
					sql = "SELECT DISTINCT item_TD_order FROM " & g_storeid & "_po_item WHERE po_id=" & s_po_id
					poOrderList = ""
					set rsItem = Conn.Execute(sql)
					do while not rsItem.EOF
						if Len(rsItem("item_TD_order")) > 0 then
							poOrderList = poOrderList & "<br><a href=""javascript:OpenTDInvoice('" & rsItem("item_TD_order") & "','" & s_po_id & "')"">" & rsItem("item_TD_order") & "</a>"
						end if
						rsItem.MoveNext
					loop
					rsItem.Close
				end if
				
				if po_dist_flag = 1 then ' Ingram Micro
					sql = "SELECT DISTINCT item_IM_order FROM " & g_storeid & "_po_item WHERE po_id=" & s_po_id
					poOrderList = ""
					set rsItem = Conn.Execute(sql)
					do while not rsItem.EOF
						if Len(rsItem("item_IM_order")) > 0 then
							poOrderList = poOrderList & "<br><a href=""javascript:OpenIMInvoice('" & rsItem("item_IM_order") & "','" & s_po_id & "')"">" & rsItem("item_IM_order") & "</a>"
						end if
						rsItem.MoveNext
					loop
					rsItem.Close
				end if
				
				if po_dist_flag = 3 then ' Synnex
					sql = "SELECT DISTINCT item_SN_order FROM " & g_storeid & "_po_item WHERE po_id=" & s_po_id
					poOrderList = ""
					set rsItem = Conn.Execute(sql)
					do while not rsItem.EOF
						if Len(rsItem("item_SN_order")) > 0 then
							poOrderList = poOrderList & "<br><a href=""javascript:OpenSNInvoice('" & rsItem("item_SN_order") & "','" & s_po_id & "')"">" & rsItem("item_SN_order") & "</a>"
						end if
						rsItem.MoveNext
					loop
					rsItem.Close
				end if
				
				if po_dist_flag = 4 then ' D&H
					sql = "SELECT DISTINCT item_DH_order FROM " & g_storeid & "_po_item WHERE po_id=" & s_po_id
					poOrderList = ""
					set rsItem = Conn.Execute(sql)
					do while not rsItem.EOF
						if Len(rsItem("item_DH_order")) > 0 then
							poOrderList = poOrderList & "<br><a href=""javascript:OpenDHInvoice('" & rsItem("item_DH_order") & "','" & s_po_id & "')"">" & rsItem("item_DH_order") & "</a>"
						end if
						rsItem.MoveNext
					loop
					rsItem.Close
				end if
				
				if po_dist_flag = 5 then ' Supplies Network
					sql = "SELECT DISTINCT item_SUN_order FROM " & g_storeid & "_po_item WHERE po_id=" & s_po_id
					poOrderList = ""
					set rsItem = Conn.Execute(sql)
					do while not rsItem.EOF
						if Len(rsItem("item_SUN_order")) > 0 then
							poOrderList = poOrderList & "<br><a href=""javascript:OpenSUNInvoice('" & rsItem("item_SUN_order") & "','" & s_po_id & "')"">" & rsItem("item_SUN_order") & "</a>"
						end if
						rsItem.MoveNext
					loop
					rsItem.Close
				end if
							
				s_po_status = "Partial Fulfilled"
				if Len(poOrderList)>0 Then
					s_po_status =  s_po_status & "<br>-------<br>" & poOrderList
				End If

			case 4
				s_po_status = "Converted"
			case else
				s_po_status = "Pending"
			end select
			

			if Len(s_shipping_contact) > 0 Then
			else
				s_shipping_contact = s_shipping_contact_last & ", " & s_shipping_contact_first
			end if

			If Len(s_shipping_contact) > 0 Then
				s_shipping_contact = Replace(s_shipping_contact, "'", "&#39")
			End If
			
			If Len(s_po_dist_name) > 0 Then
				s_po_dist_name = Replace(s_po_dist_name, "'", "&#39")
				s_po_dist_name = Replace(s_po_dist_name, """", "&#34;")
			End If
						
			
			
			aaData = aaData & "['"
			aaData = aaData & "<a href=\'v2_po.asp?po_id=" & s_po_id & "\'>" & s_po_id & "</a>','" 
			aaData = aaData & s_po_dist_name & "','" 
			aaData = aaData & s_shipping_contact & "','" 
			aaData = aaData & s_po_amount & "','"
			aaData = aaData & s_po_status & "','" 
			aaData = aaData & s_date_updated & "','"
			aaData = aaData & "<a class=\'btn btn-blue btn-xs btn-o\' href=\'javascript:OpenPrintInvoice(" & s_po_id & ")\'><i class=\'fa fa-print\'></i></a>','"
			aaData = aaData & "<input type=checkbox name=\'delete_po\' value=\'" & s_po_id & "\'>" &  "'],"
	
			
			aaData = Replace(aaData,"'",chr(34))
			rs.MoveNext
			i=i+1
		loop
		rs.Close
		if Len(aaData) > 0 then
			aaData = Left(aaData, Len(aaData)-1)
		else
			aaData = ""
		end if
	else
		aaData = ""
	end if
	response.write aaData & "] }"

%>