<%@ Language=VBScript %>
<%
	Response.CodePage = 65001
	Response.CharSet = "UTF-8"
%>
<%
  Response.Expires = -1
%>
<!-- #INCLUDE File="../local/local.phtml" -->
<!-- #INCLUDE File="../util/xt_func_util.phtml" -->
<!-- #INCLUDE File="../util/xt_func_string.phtml" -->
<%
	sEcho = Trim(Request("draw"))
	iDisplayLength = Trim(Request("length"))
	iDisplayStart = Trim(Request("start"))

	sEcho = FilterStringEx(sEcho, "[^0-9]")
	iDisplayLength = FilterStringEx(iDisplayLength, "[^0-9]")
	iDisplayStart = FilterStringEx(iDisplayStart, "[^0-9]")

	sEcho = Cint(sEcho)
	iDisplayLength = Cint(iDisplayLength)
	iDisplayStart = Cint(iDisplayStart)
  
	'sEcho = Cint(Request("sEcho"))
	'iDisplayLength = Cint(Request("iDisplayLength"))
	'iDisplayStart = Cint(Request("iDisplayStart"))
  
	'=======================================================================================
	strWhere = ""
	'---------------------------------------------------------------------------------------
	product_id = Trim(Request("product_id"))
	if Len(product_id) > 0 then
		strWhere = strWhere &  " (inventory_id like '%" & product_id & "%') AND"
	end if
	'----------------------------------------------------------------------------------------
	product_name = Trim(Request("product_name"))
	if Len(product_name) > 1 then
		strWhere = strWhere &  " (inventory_name like '%" & product_name & "%') AND"
	end if
	'----------------------------------------------------------------------------------------
	product_sku = Trim(Request("product_sku"))
	if Len(product_sku) > 1 then
		strWhere = strWhere &  " (inventory_sku like '%" & product_sku & "%') AND"
	end if
	'----------------------------------------------------------------------------------------
	sMin = Trim(Request("product_cost_from"))
	sMax = Trim(Request("product_cost_to"))
	sTotalRange = ""
	if IsNumeric(sMin) then
		if IsNumeric(sMax) then
			sTotalRange = "(inventory_cost between " & sMin & " AND " & sMax & ")"
		else
			sMax = "1000000"
			sTotalRange = "(inventory_cost between " & sMin & " AND " & sMax & ")"
		end if
	else
		if IsNumeric(sMax) then
			sTotalRange = "(inventory_cost between 0 AND " & sMax & ")"
		end if
	end if
	
	if Len(sTotalRange) > 0 then
		strWhere = strWhere &  " " & sTotalRange & " AND"
	end if
	'----------------------------------------------------------------------------------------
	sMin = Trim(Request("product_price_from"))
	sMax = Trim(Request("product_price_to"))
	sTotalRange = ""
	if IsNumeric(sMin) then
		if IsNumeric(sMax) then
			sTotalRange = "(inventory_price_D between " & sMin & " AND " & sMax & ")"
		else
			sMax = "1000000"
			sTotalRange = "(inventory_price_D between " & sMin & " AND " & sMax & ")"
		end if
	else
		if IsNumeric(sMax) then
			sTotalRange = "(inventory_price_D between 0 AND " & sMax & ")"
		end if
	end if
	
	if Len(sTotalRange) > 0 then
		strWhere = strWhere &  " " & sTotalRange & " AND"
	end if
	'----------------------------------------------------------------------------------------
	sMin = Trim(Request("product_quantity_from"))
	sMax = Trim(Request("product_quantity_to"))
	sTotalRange = ""
	if IsNumeric(sMin) then
		if IsNumeric(sMax) then
			sTotalRange = "(inventory_qty between " & sMin & " AND " & sMax & ")"
		else
			sMax = "1000000"
			sTotalRange = "(inventory_qty between " & sMin & " AND " & sMax & ")"
		end if
	else
		if IsNumeric(sMax) then
			sTotalRange = "(inventory_qty between 0 AND " & sMax & ")"
		end if
	end if
	
	if Len(sTotalRange) > 0 then
		strWhere = strWhere &  " " & sTotalRange & " AND"
	end if
	'----------------------------------------------------------------------------------------
	product_status = Trim(Request("product_status"))
	if Len(product_status) > 1 then
		strWhere = strWhere &  " (inventory_avail = " & product_status & ") AND"
	end if
	'----------------------------------------------------------------------------------------
	
	if Len(strWhere) > 0 then
		strWhere = Left(strWhere, Len(strWhere) - 4)
	else
		strWhere = " inventory_id LIKE '%%'"
	end if
	
	
	'=======================================================================================
	'ORDERING
	SELECT CASE Trim(Request("order[0][column]"))
	CASE "0"
		sOrder = "inventory_id DESC"
	CASE "1"
		sOrder = "inventory_id " & Trim(Request("order[0][dir]"))
	CASE "2"
		sOrder = "inventory_id " & Trim(Request("order[0][dir]"))
	CASE "3"
		sOrder = "inventory_name " & Trim(Request("order[0][dir]"))
	CASE "4"
		sOrder = "inventory_sku " & Trim(Request("order[0][dir]"))
	CASE "5"
		sOrder = "inventory_cost " & Trim(Request("order[0][dir]"))
	CASE "6"
		sOrder = "inventory_price_D " & Trim(Request("order[0][dir]"))
	CASE "7"
		sOrder = "inventory_qty " & Trim(Request("order[0][dir]"))
	CASE "8"
		sOrder = "inventory_avail " & Trim(Request("order[0][dir]"))
	CASE ELSE
		sOrder = "inventory_id DESC"
	END SELECT 
	'here we create the variable "strOrderBy" that will be used in the SQL querry
	strOrderBy = "ORDER BY " & sOrder
	'======================================================================================
	

	Set dbconn=server.CreateObject("ADODB.Connection")
	dbconn.Open g_connection_string
	
	sql = "SELECT * FROM " & g_storeid & "_product_inventory WHERE " & strWhere & " " & strOrderBy
	sqlx = "SELECT COUNT(inventory_id) FROM " & g_storeid & "_product_inventory WHERE " & strWhere 
	
	set rs = dbconn.Execute(sql)
	
	iTotalDisplayRecords = 0
	iTotalRecords = 50
	set rs1 = dbconn.Execute(sqlx)
	if not rs1.EOF then
		iTotalDisplayRecords = rs1(0)
		iTotalRecords = rs1(0)
	else
	end if
	rs1.Close
	
%>
{"draw": <%=sEcho%>, "recordsTotal": <%=iTotalRecords%>, "recordsFiltered": <%=iTotalDisplayRecords%>, "data": [ 
<%
	i = 0
	if rs.eof = false then
		rs.move(iDisplayStart)
		do while i < iDisplayLength and not rs.eof

			s_inventory_id = rs("inventory_id")
			inventory_name = Trim(rs("inventory_name"))
			inventory_name= JsonEscape(inventory_name)
			If Len(inventory_name) > 0 Then
				inventory_name = Replace(inventory_name, "'", "&#39")
			End if
			if Len(inventory_name) > 0 then
				inventory_name = Replace(inventory_name, VbCrLf, " ")
			end if
			if Len(inventory_name) > 0 then
				inventory_name = Replace(inventory_name, """", " ")
			end if
			s_sku = Trim(rs("inventory_sku"))
			
			s_cost = FormatNumber(rs("inventory_cost"),2)
			s_price_D = FormatNumber(rs("inventory_price_D"),2)
			s_qty = rs("inventory_qty")
			
			SELECT CASE rs("inventory_avail")
			CASE 0
				s_active = "Out of Stock"
			CASE 1
				s_active = "In Stock"
			CASE ELSE
				s_active = ""
			END SELECT
			
			aaData = aaData & "['"
			aaData = aaData & "<label class=\'mt-checkbox mt-checkbox-single mt-checkbox-outline\'><input name=\'id[]\' type=\'checkbox\' class=\'checkboxes\' value=\'" &  s_inventory_id & "\'/><span></span></label> " & "','" 
			aaData = aaData & s_inventory_id & "','" 
			aaData = aaData & inventory_name & "','" 
			aaData = aaData & s_sku & "','" 
			aaData = aaData & s_cost & "','"
			aaData = aaData & s_price_D & "','"
			
			aaData = aaData & "<input type=\'text\' class=\'form-control input-sm edit-qty text-right\' value=\'" & s_qty & "\' data-id=\'" & Trim(s_inventory_id) & "\'>','"
			
			'aaData = aaData & s_qty & "','"
			
			
			SELECT CASE s_active
			CASE "In Stock"
				s_label = "label label-success"
				s_background = "#5c9bd1"
			CASE "Call for Avaialability"
				s_label = "label label-warning"
				s_background = ""
			CASE "Out of Stock"
				s_label = "label label-danger"
				s_background = "#e08283"
			END SELECT
			
			aaData = aaData & "<select class=\'form-control input-sm edit-avail\' data-id=\'" & Trim(s_inventory_id) & "\' style=\'background-color: " & s_background & "\'>"
			aaData = aaData & "<option value=\'1\' style=\'background-color:#ffffff\'"
			if s_active = "In Stock" then
				aaData = aaData & " selected "
			end if
			aaData = aaData & ">In Stock</option>"
			aaData = aaData & "<option value=\'0\' style=\'background-color:#ffffff\'"
			if s_active = "Out of Stock" then
				aaData = aaData & " selected "
			end if
			aaData = aaData & ">Out of Stock</option>"
			aaData = aaData & "</select>','"
			'aaData = aaData & "<span class=\'" & s_label & "\'>" & s_active & "</span>','"
			'aaData = aaData & "<a href=\'#\' class=\'btn btn-xs btn-teal tooltips modal-edit-line\'  data-toggle=\'modal\' data-id=\'" & Trim(s_inventory_id) & "\' data-placement=\'top\' data-original-title=\'Edit\'><i class=\'fa fa-edit\'></i></a>'],"
			'aaData = aaData & "<a href=\'#\' class=\'btn btn-sm btn-default btn-circle btn-editable modal-edit-line\' data-toggle=\'modal\' data-id=\'" & Trim(s_inventory_id) & "\' data-placement=\'top\' data-original-title=\'Edit\'><i class=\'fa fa-pencil\'></i> Edit</a>'],"
			aaData = aaData & "<a href=\'catalog_inventory_detail.phtml?pf_id=" & s_inventory_id & "\' class=\'btn btn-sm btn-default btn-circle btn-editable\'><i class=\'fa fa-pencil\'></i> Edit</a>'],"
		'	aaData = aaData & "<input type=\'checkbox\' class=\'checkbox\' name=\'prAction\' id=\'prAction\' value=\'" & s_pf_id & "\'>'],"
		  
		  aaData = Replace(aaData,"'",chr(34))
		  rs.MoveNext
		  i=i+1
		loop
		rs.Close
		aaData = Left(aaData, Len(aaData)-1)
	else
		aaData = ""
	end if
	response.write aaData & "] }"
%>