<%@ Language=VBScript %>
<%
	Response.CodePage = 65001
	Response.CharSet = "UTF-8"
%>
<%
  Response.Expires = -1
%>
<!-- #INCLUDE File="../local/local.phtml" -->
<!-- #INCLUDE File="../util/xt_func_util.phtml" -->
<!-- #INCLUDE File="../util/xt_func_string.phtml" -->
<%
	sEcho = Trim(Request("draw"))
	iDisplayLength = Trim(Request("length"))
	iDisplayStart = Trim(Request("start"))

	sEcho = FilterStringEx(sEcho, "[^0-9]")
	iDisplayLength = FilterStringEx(iDisplayLength, "[^0-9]")
	iDisplayStart = FilterStringEx(iDisplayStart, "[^0-9]")

	sEcho = Cint(sEcho)
	iDisplayLength = Cint(iDisplayLength)
	iDisplayStart = Cint(iDisplayStart)
	
	'=======================================================================================
	strWhere = ""
	'---------------------------------------------------------------------------------------
	user_id = Trim(Request("user_id"))
	if Len(user_id) > 0 then
		strWhere = strWhere &  " (user_id like '%" & user_id & "%') AND"
	end if
	'---------------------------------------------------------------------------------------
	FirstName = Trim(Request("FirstName"))
	if Len(FirstName) > 0 then
		strWhere = strWhere &  " (FirstName like '%" & FirstName & "%') AND"
	end if
	'---------------------------------------------------------------------------------------
	LastName = Trim(Request("LastName"))
	if Len(LastName) > 0 then
		strWhere = strWhere &  " (LastName like '%" & LastName & "%') AND"
	end if
	'---------------------------------------------------------------------------------------
	Email = Trim(Request("Email"))
	if Len(Email) > 0 then
		strWhere = strWhere &  " (Email like '%" & Email & "%') AND"
	end if
	'----------------------------------------------------------------------------------------
	user_disable = Trim(Request("user_disable"))
	if Len(user_disable) > 0 then
		strWhere = strWhere &  " (user_disable = " & user_disable & ") AND"
	end if
	'----------------------------------------------------------------------------------------
	
	if Len(strWhere) > 0 then
		strWhere = Left(strWhere, Len(strWhere) - 4)
	else
		strWhere = " FirstName LIKE '%%'"
	end if
	
	
	'=======================================================================================
	'ORDERING
	SELECT CASE Trim(Request("order[0][column]"))
	CASE "0"
		sOrder = "user_id DESC"
	CASE "1"
		sOrder = "user_id " & Trim(Request("order[0][dir]"))
	CASE "2"
		sOrder = "FirstName " & Trim(Request("order[0][dir]"))
	CASE "3"
		sOrder = "LastName " & Trim(Request("order[0][dir]"))
	CASE "4"
		sOrder = "Email " & Trim(Request("order[0][dir]"))
	CASE "5"
		sOrder = "user_disable " & Trim(Request("order[0][dir]"))
	CASE ELSE
		sOrder = "user_id DESC"
	END SELECT 
	'here we create the variable "strOrderBy" that will be used in the SQL querry
	strOrderBy = "ORDER BY " & sOrder

	'======================================================================================
	

	sql = "SELECT * FROM " & g_storeid & "_users WHERE " & strWhere & " " & strOrderBy
	sqlx = "SELECT COUNT(user_id) FROM " & g_storeid & "_users WHERE " & strWhere 

	set rs = dbconn.Execute(sql)

	iTotalDisplayRecords = 0
	iTotalRecords = 50
	set rs1 = dbconn.Execute(sqlx)
	if not rs1.EOF then
		iTotalDisplayRecords = rs1(0)
		iTotalRecords = rs1(0)
	else
	end if
	rs1.Close

	'iTotalDisplayRecords = 50

	'iTotalRecords = 50

	%>
	{"draw": <%=sEcho%>, "recordsTotal": <%=iTotalRecords%>, "recordsFiltered": <%=iTotalDisplayRecords%>, "data": [ 
	<%
	i = 0

	if rs.eof = false then
		rs.move(iDisplayStart)
		do while i < iDisplayLength and not rs.eof
			
			s_user_id = Trim(rs("user_id"))
			s_FirstName = Trim(rs("FirstName"))
			s_LastName = Trim(rs("LastName"))
			s_Email = rs("Email")
			user_disable = rs("user_disable")

			select case user_disable
			case 0
				s_status = "Active"
			case 1
				s_status = "Inactive"
			case else
				s_status = "Open"
			end select
			
			aaData = aaData & "['"
			aaData = aaData & "<label class=\'mt-checkbox mt-checkbox-single mt-checkbox-outline\'><input name=\'id[]\' type=\'checkbox\' class=\'checkboxes\' value=\'" &  s_quote_id & "\'/><span></span></label> " & "','" 
			aaData = aaData & s_user_id & "','" 
			aaData = aaData & s_FirstName & "','"
			aaData = aaData & s_LastName & "','" 
			aaData = aaData & s_Email & "','"
			aaData = aaData & s_status & "','" 
			aaData = aaData & "<a href=\'store_users_edit.phtml?user_id=" & s_user_id & "\' class=\'btn btn-sm btn-outline grey-salsa\'><i class=\'fa fa-search\'><\/i> View<\/a>" & "'],"
			
			aaData = Replace(aaData,"'",chr(34))
			rs.MoveNext
			i=i+1
		loop
		rs.Close
		if Len(aaData) > 0 then
			aaData = Left(aaData, Len(aaData)-1)
		else
			aaData = ""
		end if
	else
		aaData = ""
	end if
	response.write aaData & "] }"

%>