<%response.Expires=-1%>
<!-- #INCLUDE File="../local/local.phtml" -->
<!-- #INCLUDE File="../util/xt_func_util.phtml" -->
<!-- #INCLUDE File="../util/xt_func_string.phtml" -->
<%
	'--POST DATA------------------------------------------
	mode = Trim(Request("mode"))
	dept_id = Trim(Request("dept_id"))
	dept_name = Trim(Request("dept_name"))
	
	skey= Trim(Request("skey"))
    dkey= Trim(Request("dkey"))
	
	if mode = "gsort" then
	
		sql = "SELECT dept_row FROM " & g_storeid & "_system_dept WHERE dept_id='" & skey & "'"
        set rs1 = dbconn.Execute(sql)
        if not rs1.EOF then
            source_sort_order = rs1(0)
        end if
        rs1.Close
        set rs1 = nothing
        
        sql = "SELECT dept_row FROM " & g_storeid & "_system_dept WHERE dept_id='" & dkey & "'"
        set rs1 = dbconn.Execute(sql)
        if not rs1.EOF then
            dest_sort_order = rs1(0)
        end if
        rs1.Close
        set rs1 = nothing
		
		if source_sort_order > dest_sort_order then
		
			sql = "SELECT * FROM " & g_storeid & "_system_dept WHERE "
			sql = sql & " dept_row >= " & dest_sort_order 
			sql = sql & " AND dept_row <= " & source_sort_order 
			sql = sql & " ORDER BY dept_row"
			
			set rs1 = dbconn.Execute(sql)
			do while not rs1.EOF
				sql = "UPDATE " & g_storeid & "_system_dept SET dept_row = dept_row + 1 WHERE dept_id='" & rs1("dept_id") & "'"
				dbconn.Execute(sql)
				rs1.MoveNext
			loop
			rs1.Close
			set rs1 = nothing
			
			sql2 = "UPDATE " & g_storeid & "_system_dept SET dept_row = " & dest_sort_order & " WHERE dept_id='" & skey & "'"
			dbconn.Execute(sql2)
		else
			sql = "SELECT * FROM " & g_storeid & "_system_dept WHERE "
			sql = sql & " dept_row >= " & source_sort_order 
			sql = sql & " AND dept_row <= " & dest_sort_order 
			sql = sql & " ORDER BY dept_row"
			
			set rs1 = dbconn.Execute(sql)
			do while not rs1.EOF
				sql = "UPDATE " & g_storeid & "_system_dept SET dept_row = dept_row - 1 WHERE dept_id='" & rs1("dept_id") & "'"
				dbconn.Execute(sql)
				rs1.MoveNext
			loop
			rs1.Close
			set rs1 = nothing
			sql2 = "UPDATE " & g_storeid & "_system_dept SET dept_row = " & dest_sort_order & " WHERE dept_id='" & skey & "'"
			dbconn.Execute(sql2)
			
		end if
		Response.Write("{""Success"" : []}")
		
	else
		'====================================================================================================================
		'UPDATE _dept table....
		'====================================================================================================================
		
		if dept_id = "0" then
			Set rsUpdate = Server.CreateObject("ADODB.Recordset")
			with rsUpdate
				.ActiveConnection = dbconn
				.CursorLocation = 3
				.CursorType = 1
				.LockType = 3
				.Source = g_storeid & "_system_dept WHERE dept_id='0'"
				.Open
				.AddNew
			end with
			
			'-------------------------------------------------------------------------------------
			'GET NEW DEPT_ID
			sql = "SELECT * FROM " & g_storeid & "_system_dept ORDER BY dept_id"
			set rsx = dbconn.Execute(sql)
			bok = false
			i = 1
			do while not ( bok or rsx.EOF)
				currentID = rsx("dept_id")
				currentID = Right(rsx("dept_id"),3)
				if(i <> CInt(currentID)) then
					bok = true
				end if
				i = i + 1
				rsx.MoveNext
			loop
			rsx.Close
			set rsx = nothing
		
			if(bok) then
				i = i - 1
			end if
		
			if(i > 9) then
				new_deptid = "0" + CStr(i)
			else
				new_deptid = "00" + CStr(i)
			end if
			
			new_deptid = "SD-" & new_deptid
			
			dept_id = new_deptid
			
			sql = "SELECT MAX(dept_row) FROM " & g_storeid & "_system_dept"
			set rsx = dbconn.Execute(sql)
			
			if(not rsx.EOF) then
				if rsx(0) > 0 then
					new_row = rsx(0) + 1
				else
					new_row = 1
				end if
			else
				new_row = 1
			end if
			rsx.Close
			set rsx = nothing
			
			'-------------------------------------------------------------------------------------
			rsUpdate("dept_id") = dept_id
			rsUpdate("dept_row") = new_row
			
		else
			Set rsUpdate = Server.CreateObject("ADODB.Recordset")
			with rsUpdate
				.ActiveConnection = dbconn
				.CursorLocation = 3
				.CursorType = 1
				.LockType = 3
				.Source = g_storeid & "_system_dept WHERE dept_id='" & dept_id & "'"
				.Open
			end with
		end if
		
		dept_is_hidden = Trim(Request("dept_is_hidden"))
		
		rsUpdate("dept_name") = dept_name
		rsUpdate("is_hide") = dept_is_hidden
		
		If dbconn.Errors.Count > 0 Then
			dbconn.Errors.Clear
			rsUpdate.CancelUpdate
		else
			rsUpdate.Update
		End If
		
		rsUpdate.Close
		set rsUpdate = nothing
		
		
		
	end if
	
%>