<%response.Expires=-1%>
<!-- #INCLUDE File="../local/local.phtml" -->
<%
	category_id = Trim(Request("category_id"))
	parent_id = Trim(Request("parent_id"))
	sql = "SELECT * FROM " & g_storeid & "_system_dept WHERE dept_id='" & category_id & "'"
	set rs = dbconn.Execute(sql)
	if not rs.EOF then
		dept_name = Trim(rs("dept_name"))
		is_hidden = Trim(rs("is_hide"))
		if rs("is_hide") then
		  dept_is_hidden = "1"
		else
		  dept_is_hidden = "0"
		end if
	else
		dept_name = ""
		dept_is_hidden = "0"
	end if
	rs.Close
	
	set rs = nothing

%>
<input type="hidden" name="dept_id" id="dept_id" value="<%=category_id%>" >
<input type="hidden" name="parent_id" id="parent_id" value="0" >
<div class="tabbable-bordered">
	<ul id="myTab" class="nav nav-tabs">
		<li <% if Session("SYSTEMLIST_TABTARGET") = "#system_list_tab_example1" OR Session("SYSTEMLIST_TABTARGET") = "" then %>class="active"<% end if %>>
			<a href="#system_list_tab_example1" data-toggle="tab">
				General Information
			</a>
		</li>
		<li <% if Session("SYSTEMLIST_TABTARGET") = "#system_list_tab_example2" then %>class="active"<% end if %>>
			<a href="#system_list_tab_example2" data-toggle="tab">
				Category Systems
			</a>
		</li>
	</ul>
	<div class="tab-content">
		<div class="tab-pane <% if Session("SYSTEMLIST_TABTARGET") = "#system_list_tab_example1" OR Session("SYSTEMLIST_TABTARGET") = "" then %>active<% end if %>" id="system_list_tab_example1">
			<div class="form-group">
				<label class="col-sm-2 control-label" for="dept_name">
				Name <span class="symbol required"></span>
				</label>
				<div class="col-sm-8">
				<input type="text" placeholder="" id="dept_name" name="dept_name" class="form-control" value="<%=dept_name%>">
				</div>
			</div>
			<div class="form-group">
				<label class="col-sm-2 control-label" for="dept_is_hidden">
					Visibility <span class="symbol required"></span>
				</label>
				<div class="col-sm-4"> 
					<select id="dept_is_hidden" name="dept_is_hidden" class="js-example-basic-hide-search js-states form-control">
					<option value=""></option>
					<option value="0" <%if dept_is_hidden = "0" then%>selected<%end if%>>Show</option>
					<option value="1" <%if dept_is_hidden = "1" then%>selected<%end if%>>Hide</option>
					</select>
				</div>
			</div>
		</div>
		<div class="tab-pane <% if Session("SYSTEMLIST_TABTARGET") = "#system_list_tab_example2" then %>active<% end if %>" id="system_list_tab_example2">
			<table class="table table-striped table-hover">
				<thead>
				<tr>
				  <th>
					System ID
				  </th>
				  <th>
					Main Image
				  </th>
				  <th>
					Name
				  </th>
				  <th>
				  </th>
				</tr>
				<%
					sql = "SELECT * FROM " & g_storeid & "_system_product as a, "
					sql = sql &  g_storeid & "_system_dept_prod as b "
					sql = sql & "WHERE a.pf_id = b.pf_id "
					sql = sql & "AND dept_id = '" & category_id & "' "
					
					ssImgSize = "upload/w_" & "70" & ",h_" & "70" & ",c_pad/"
					set rsSystems= dbconn.Execute(sql)
					do while not rsSystems.EOF
						
						mm_type = rsSystems("mm_type")
						image_file = rsSystems("image_file")
						thumb_image = rsSystems("thumb_image")
						if mm_type = 1 then
							sql = "SELECT * FROM " & g_storeid & "_product_image WHERE image_name = '" & image_file & "'"
							Set rsCloudImage2 = dbconn.Execute(sql)
							If Not rsCloudImage2.EOF Then
								cloudImg = Trim(rsCloudImage2("cloud_secure_url"))
							Else
								cloudImg = g_noimage_url
							End If
							rsCloudImage2.Close
							Set rsCloudImage2 = Nothing
							ssImg = Replace(cloudImg, "upload/", ssImgSize)
						else
							if Len(thumb_image) > 3 then
								ssImg = "../media/catalog/system/" & thumb_image
							else
								ssImg = g_noimage_url
							end if
						end if
						
				%>
				<tr>
					<td>
						<%=rsSystems("pf_id")%>
					</td>
					<td>
						<img src="<%=ssImg%>" border="0" width="70">
					</td>
					<td>
						<%=rsSystems("name")%>
					</td>
					<td>
						<a href="catalog_system_detail.phtml?system_id=<%=rsSystems("pf_id")%>" class="btn btn-sm btn-default btn-circle btn-editable"><i class="fa fa-pencil"></i> Edit</a>
					</td>
				</tr>
				<%
						rsSystems.MoveNext
					loop
					rsSystems.Close
					set rsSystems = nothing
				%>
				</thead>
			</table>
		</div>
		
	</div>
</div>
	

