<%response.Expires=-1%>
<%
	Response.CodePage = 65001
	Response.CharSet = "UTF-8"
%>
<!-- #INCLUDE File="../local/local.phtml" -->
<!-- #INCLUDE File="../util/xt_func_util.phtml" -->
<!-- #INCLUDE File="../util/xt_func_string.phtml" -->
<%
	For Each sItem In Request.Form
		'Response.Write(sItem)
		'Response.Write(" - [" & Request.Form(sItem) & "]" & "<br>")
		if SetSettingValue(sItem, Trim(Request.Form(sItem)) ) then
		
		end if
		
	Next

%>