<%
	g_storeid = "hubutu"
	g_source_connection_string = "DRIVER={MySQL ODBC 5.2 UNICODE Driver};Server=104.207.233.67;Database=hubutuco_mage4;Uid=hubutuco_magento;Pwd=uI39bGS0Gvio;Charset=ucs2;"
	g_dest_connection_string = "Provider=SQLOLEDB;Data Source=localhost;Database=GSHOP;uid=dinamall_hanta_user;pwd=hanta_pw0105;"
	g_source_url = "http://www.hubutu.com/"
	
	g_cloudinary_url = "http://a4.res.cloudinary.com/dd3llssvr/image/fetch/"
	g_noimage_url = "http://res.cloudinary.com/dd3llssvr/image/upload/v1423588444/noimage_t0tp8k.png"
	g_cloudinary_upload_url = "http://app.internetreports.com/api/upload"
	g_cloudinary_cloud_name = "dd3llssvr"
	g_cloudinary_api_key = "683217377862163"
	g_cloudinary_api_secret  = "oEpyM8PTGFGJb7DcpGk1SEq9yyY"
	g_cloudinary_max_size = "500"
%>