<%
	Const adTypeBinary = 1
	Const adSaveCreateOverWrite = 2
	Const adSaveCreateNotExist = 1 
				
	g_storeid = "hubutu"
	
	Server.ScriptTimeout=2000
	mysqlsvr = "DRIVER={MySQL ODBC 5.2 ANSI Driver};Server=104.207.233.67;Database=hubutuco_mage4;Uid=hubutuco_magento;Pwd=uI39bGS0Gvio;"
	Set conn = Server.CreateObject("ADODB.connection")
	conn.open mysqlsvr
	
	g_connection_string = "Provider=SQLOLEDB;Data Source=localhost;Database=GSHOP;uid=dinamall_hanta_user;pwd=hanta_pw0105;"
	Set dbconn = Server.CreateObject("ADODB.Connection")
	dbconn.open g_connection_string
	
	Set objFSO = Server.CreateObject("Scripting.FileSystemObject")
	Dim strRootFolder
	strRootFolder = Server.MapPath("../..")
	
	'DELETE ALL
	'sql = "DELETE FROM " & g_storeid & "_product WHERE pf_id like '12%'"
	'dbconn.Execute(sql)
	
	'INITIAL UPLOAD
	sql = "SELECT * FROM catalog_product_flat_1 ORDER BY entity_id LIMIT 10"
	sql = "SELECT * FROM catalog_product_flat_1 WHERE entity_id > 4224 ORDER BY entity_id LIMIT 60"
	
	set rs = conn.Execute(sql)
	do while not rs.EOF
		pf_id = CStr(1200000000 + rs("entity_id"))
		thumbnail = Trim(rs("thumbnail"))
		if thumbnail = "no_selection" then
			thumbnail = ""
		end if
		pf_productimage = ""
		pf_url_key = Trim(rs("url_key"))
		'-----------------------------------------------------------------------
		If objFSO.FolderExists(strRootFolder & "/media/catalog/product/" & pf_id) Then
		Else
			objFSO.CreateFolder(strRootFolder & "/media/catalog/product/" & pf_id)
		End If
		'-----------------------------------------------------------------------
		if Len(thumbnail) > 4 then
			sourcePath = "http://www.hubutu.com/media/catalog/product" & thumbnail
			ar_thumbnail = Split(thumbnail, "/")
			destPath = strRootFolder & "/media/catalog/product/" & pf_id & "/" & ar_thumbnail(UBound(ar_thumbnail))
			pf_productimage = ar_thumbnail(UBound(ar_thumbnail))
			
			If (objFSO.FileExists(destPath)) Then
 
			Else
				'Response.Write(sourcePath & ":" & destPath & "<br>")
				Set xml = CreateObject("Microsoft.XMLHTTP")
				xml.Open "GET", sourcePath, False
				xml.Send

				set oStream = createobject("Adodb.Stream")

				oStream.type = adTypeBinary
				oStream.open
				oStream.write xml.responseBody
				oStream.savetofile destPath, adSaveCreateOverWrite
				oStream.close

				set oStream = nothing
				Set xml = Nothing
				
				'------------------------------------------------------------------------------------
				
				dim xmlRecv2
				set xmlRecv2 = Server.CreateObject("Msxml2.ServerXMLHTTP")
				xmlRecv2.open "POST", "http://app.internetreports.com/api/upload?FileURL=" & sourcePath, False
				xmlRecv2.setRequestHeader "Content-Type", "application/x-www-form-urlencoded; charset=UTF-8"
				xmlRecv2.setTimeouts 5000, 5000, 15000, 15000
				xmlRecv2.send ""
				pResult = xmlRecv2.responseText
				
				if Len(pResult) > 0 then
					pResult = Replace(pResult, "[""", "")
					pResult = Replace(pResult, """]", "")
					ar_pResult = Split(pResult, """,""")
				end if
				
				cloud_public_id = ""
				cloud_url = ""
				cloud_secure_url = ""
				
				if Len(ar_pResult(0)) > 0 then
					cloud_public_id = ar_pResult(0)
				end if
				
				if Len(ar_pResult(1)) > 0 then
					cloud_url = ar_pResult(1)
				end if
				
				if Len(ar_pResult(2)) > 0 then
					cloud_secure_url = ar_pResult(2)
				end if
				
				
				
				sqlu = "INSERT INTO " & g_storeid & "_product_image (pf_id,image_name,cloud_public_id, cloud_url, cloud_secure_url) VALUES ('"& pf_id &"','" & pf_productimage & "','" & cloud_public_id & "','" & cloud_url & "','" & cloud_secure_url  & "')"
				dbconn.execute(sqlu)
				
			End If
			
		end if
		'-----------------------------------------------------------------------
		
		Set rsUpdate = Server.CreateObject("ADODB.Recordset")
		with rsUpdate
			.ActiveConnection = dbconn
			.CursorLocation = 3
			.CursorType = 1
			.LockType = 3
			.Source = g_storeid & "_product WHERE pf_id='0'"
			.Open
			.AddNew
		end with
		
		
		rsUpdate("pf_id") = pf_id
		rsUpdate("sku") =  rs("sku")
		rsUpdate("name") = rs("name")
		rsUpdate("description") = rs("short_description")
		rsUpdate("weight") = rs("weight")
		
		rsUpdate("image_file") = pf_productimage
		rsUpdate("url_key") = pf_url_key
		
		rsUpdate("use_price") = 1
		if IsNumeric(Trim(rs("cost"))) then
			rsUpdate("list_price") = rs("cost")
		end if
		if IsNumeric(Trim(rs("msrp"))) then
			rsUpdate("retail_price") = rs("msrp")
		end if
		
		if IsNumeric(Trim(rs("price"))) then
			rsUpdate("price_D") = rs("price")
		end if
		
		rsUpdate("mm_type") = 1
		
		
		If dbconn.Errors.Count > 0 Then
			dbconn.Errors.Clear
			rsUpdate.CancelUpdate
		else
			rsUpdate.Update
		End If
		
		rsUpdate.Close
		set rsUpdate = nothing
		
		
		'====================================================================================================================
		'UPDATE _rewrite table....
		'====================================================================================================================
		
		sql = "SELECT rewrite_id FROM " & g_storeid & "_rewrite WHERE rewrite_system_id='" & pf_id & "' AND rewrite_system_type = 2"
		set rsRewrite = dbconn.Execute(sql)
		if not rsRewrite.EOF then
			rewrite_id = rsRewrite("rewrite_id")
		else
			rewrite_id = 0
		end if
		
		rsRewrite.Close
		set rsRewrite = nothing
		
		if rewrite_id = 0 then
			Set rsUpdate = Server.CreateObject("ADODB.Recordset")
			with rsUpdate
				.ActiveConnection = dbconn
				.CursorLocation = 3
				.CursorType = 1
				.LockType = 3
				.Source = g_storeid & "_rewrite WHERE rewrite_id=0"
				.Open
				.AddNew
			end with
			
			rsUpdate("rewrite_type") = 1
			rsUpdate("rewrite_system_type") = 2
			rsUpdate("rewrite_system_id") = pf_id
			rsUpdate("rewrite_redirect_type") = ""
		
		else
			Set rsUpdate = Server.CreateObject("ADODB.Recordset")
			with rsUpdate
				.ActiveConnection = dbconn
				.CursorLocation = 3
				.CursorType = 1
				.LockType = 3
				.Source = g_storeid & "_rewrite WHERE rewrite_id=" & rewrite_id
				.Open
			end with
		end if
		
		rsUpdate("rewrite_request_path") = pf_url_key
		
		If dbconn.Errors.Count > 0 Then
			dbconn.Errors.Clear
			rsUpdate.CancelUpdate
		else
			rsUpdate.Update
		End If
		
		rsUpdate.Close
		set rsUpdate = nothing
			
		rs.MoveNext
	loop
	rs.Close
	set rs = nothing
	
	Response.Write("DONE")
%>