<!-- #INCLUDE File="config.phtml" -->
<!-- #INCLUDE File="../util/xt_func_string.phtml" -->
<%
	Response.CodePage = 65001
	Response.CharSet = "UTF-8"
	Server.ScriptTimeout=2000
%>

<%
	Set source_conn = Server.CreateObject("ADODB.connection")
	source_conn.open g_source_connection_string
	
	Set dest_conn = Server.CreateObject("ADODB.Connection")
	dest_conn.open g_dest_connection_string
	
	sql = "SELECT * FROM customer_address_entity WHERE entity_id NOT IN (SELECT VALUE FROM customer_entity_int WHERE attribute_id=13) ORDER BY parent_id"
	
	set rsx = source_conn.Execute(sql)
	do while not rsx.EOF
		
		default_billing = rsx(0)
		address_id = CStr(1200000000 + rsx(0))
		shopper_id = CStr(1200000000 + rsx("parent_id"))
		billing_first_name = ""
		billing_last_name = ""
		billing_street = ""
		billing_city = ""
		billing_state = ""
		billing_zip = ""
		billing_phone = ""
		billing_country = ""
		billing_company = ""
		billing_prefix = ""
		
		sql = "SELECT * FROM customer_address_entity_varchar WHERE entity_id = " & default_billing
		set rs1 = source_conn.Execute(sql)
		do while not rs1.EOF
			
			SELECT CASE rs1("attribute_id")
			CASE 19
				billing_prefix = rs1("value")
			CASE 20
				billing_first_name = rs1("value")
			CASE 22
				billing_last_name = rs1("value")
			CASE 24
				billing_company = rs1("value")
			CASE 26
				billing_city = rs1("value")
			CASE 27
				billing_country = rs1("value")
			CASE 28
				billing_state = rs1("value")
			CASE 30
				billing_zip = rs1("value")
			CASE 31
				billing_phone = rs1("value")
			END SELECT
			rs1.MoveNext
		loop
		rs1.Close
		set rs1 = nothing
		
		sql = "SELECT * FROM customer_address_entity_text WHERE entity_id = " & default_billing
		set rs1 = source_conn.Execute(sql)
		do while not rs1.EOF
			
			SELECT CASE rs1("attribute_id")
			CASE 25
				billing_street = rs1("value")
			END SELECT
			rs1.MoveNext
		loop
		rs1.Close
		set rs1 = nothing
		
		
		Response.Write(address_id & ":" & shopper_id & ":" & billing_prefix & ":" & billing_street & ":" & billing_city  & ":" & billing_state & ":" & billing_zip & ":" & billing_phone & "<br>")
		Response.Flush
		
		sql = "SELECT billing_address_id FROM " & g_storeid & "_shopper_billing_address WHERE billing_address_id = '" & address_id & "'"
		set rs = dest_conn.Execute(sql)
		if rs.EOF then
			
			Set rsUpdate = Server.CreateObject("ADODB.Recordset")
			with rsUpdate
				.ActiveConnection = dest_conn
				.CursorLocation = 3
				.CursorType = 1
				.LockType = 3
				.Source = g_storeid & "_shopper_billing_address WHERE billing_address_id='0'"
				.Open
				.AddNew
			end with
			
			'GET NEW SHOPPER_ID and SAVE EMAIL Address
			rsUpdate("billing_address_id") = address_id
			rsUpdate("billing_shopper_id") = shopper_id
			
		else
			
			Set rsUpdate = Server.CreateObject("ADODB.Recordset")
			with rsUpdate
				.ActiveConnection = dest_conn
				.CursorLocation = 3
				.CursorType = 1
				.LockType = 3
				.Source = g_storeid & "_shopper_billing_address WHERE billing_address_id='" & address_id & "'"
				.Open
			end with
			
		end if
		
		rsUpdate("billing_address_name") = Left(billing_street, 50)
		rsUpdate("billing_firstname") = billing_first_name
		rsUpdate("billing_lastname") = billing_last_name
		rsUpdate("billing_address") = billing_street
		rsUpdate("billing_city") = billing_city
		rsUpdate("billing_state") = billing_state
		rsUpdate("billing_zip") = billing_zip
		rsUpdate("billing_country") = billing_country
		rsUpdate("billing_phone") = billing_phone
		rsUpdate("billing_set_default") = 0
		rsUpdate("CC_Type") = ""
		rsUpdate("CC_Number") = ""
		rsUpdate("CC_ExpMonth") = ""
		rsUpdate("CC_ExpYear") = ""
		rsUpdate("bill_company") = billing_company
		rsUpdate("NameOnCard") = ""
		rsUpdate("billing_prefix") = billing_prefix
		
		
		If dest_conn.Errors.Count > 0 Then
			dest_conn.Errors.Clear
			rsUpdate.CancelUpdate
		else
			rsUpdate.Update
		End If
		
		rsUpdate.Close
		set rsUpdate = nothing
		
		
		sql = "SELECT address_id FROM " & g_storeid & "_shopper_shipping_address WHERE address_id = '" & address_id & "'"
		set rs = dest_conn.Execute(sql)
		if rs.EOF then
			
			Set rsUpdate = Server.CreateObject("ADODB.Recordset")
			with rsUpdate
				.ActiveConnection = dest_conn
				.CursorLocation = 3
				.CursorType = 1
				.LockType = 3
				.Source = g_storeid & "_shopper_shipping_address WHERE address_id='0'"
				.Open
				.AddNew
			end with
			
			'GET NEW SHOPPER_ID and SAVE EMAIL Address
			rsUpdate("address_id") = address_id
			rsUpdate("shopper_id") = shopper_id
			
		else
			
			Set rsUpdate = Server.CreateObject("ADODB.Recordset")
			with rsUpdate
				.ActiveConnection = dest_conn
				.CursorLocation = 3
				.CursorType = 1
				.LockType = 3
				.Source = g_storeid & "_shopper_shipping_address WHERE address_id='" & address_id & "'"
				.Open
			end with
			
		end if
		
		rsUpdate("address_name") = Left(billing_street, 50)
		rsUpdate("firstname") = billing_first_name
		rsUpdate("lastname") = billing_last_name
		rsUpdate("address") = billing_street
		rsUpdate("city") = billing_city
		rsUpdate("state") = billing_state
		rsUpdate("zip") = billing_zip
		rsUpdate("country") = billing_country
		rsUpdate("phone") = billing_phone
		rsUpdate("set_default") = 0
		rsUpdate("address_type") = 0
		rsUpdate("company") = billing_company
		rsUpdate("prefix") = billing_prefix
		
		
		If dest_conn.Errors.Count > 0 Then
			dest_conn.Errors.Clear
			rsUpdate.CancelUpdate
		else
			rsUpdate.Update
		End If
		
		rsUpdate.Close
		set rsUpdate = nothing
		
		rs.Close
		
		
		
		rsx.MoveNext
	loop
	rsx.Close
	
	set rsx = nothing
	
	source_conn.close
	dest_conn.close
	
%>