<!-- #INCLUDE File="config.phtml" -->
<!-- #INCLUDE File="../util/xt_func_string.phtml" -->
<%
	Response.CodePage = 65001
	Response.CharSet = "UTF-8"
	Server.ScriptTimeout=2000
%>

<%
	Set source_conn = Server.CreateObject("ADODB.connection")
	source_conn.open g_source_connection_string
	
	Set dest_conn = Server.CreateObject("ADODB.Connection")
	dest_conn.open g_dest_connection_string
	
	sql = "SELECT * FROM customer_entity WHERE entity_id > 5478 ORDER BY entity_id"
	
	set rsx = source_conn.Execute(sql)
	do while not rsx.EOF

		s_entity_id = rsx("entity_id")
		shopper_id = CStr(1200000000 + rsx("entity_id"))
		new_email = rsx("Email")
		created_at = rsx("created_at")
		updated_at = rsx("updated_at")
		
		k_name = ""
		FirstName = ""
		LastName = ""
		password = ""
		
		sql = "SELECT * FROM customer_entity_varchar WHERE entity_id = " & s_entity_id & " AND attribute_id IN (4,5,6,7,12)"
		set rs1 = source_conn.Execute(sql)
		do while not rs1.EOF
			
			SELECT CASE rs1("attribute_id")
			CASE 4
				k_name = rs1("value")
			CASE 5
				FirstName = rs1("value")
			CASE 7
				LastName = rs1("value")
			CASE 12
				password = rs1("value")
			END SELECT
			rs1.MoveNext
		loop
		rs1.Close
		set rs1 = nothing
		
		
		default_billing = 0
		default_shipping = 0
		
		sql = "SELECT * FROM customer_entity_int WHERE entity_id = " & s_entity_id & " AND attribute_id IN (13,14)"
		set rs1 = source_conn.Execute(sql)
		do while not rs1.EOF
			
			SELECT CASE rs1("attribute_id")
			CASE 13
				default_billing = rs1("value")
			CASE 14
				default_shipping = rs1("value")
			END SELECT
			rs1.MoveNext
		loop
		rs1.Close
		set rs1 = nothing
		
		billing_first_name = ""
		billing_last_name = ""
		billing_street = ""
		billing_city = ""
		billing_state = ""
		billing_zip = ""
		billing_phone = ""
		billing_country = ""
		billing_company = ""
		billing_prefix = ""
		
		sql = "SELECT * FROM customer_address_entity_varchar WHERE entity_id = " & default_billing
		set rs1 = source_conn.Execute(sql)
		do while not rs1.EOF
			
			SELECT CASE rs1("attribute_id")
			CASE 19
				billing_prefix = rs1("value")
			CASE 20
				billing_first_name = rs1("value")
			CASE 22
				billing_last_name = rs1("value")
			CASE 24
				billing_company = rs1("value")
			CASE 26
				billing_city = rs1("value")
			CASE 27
				billing_country = rs1("value")
			CASE 28
				billing_state = rs1("value")
			CASE 30
				billing_zip = rs1("value")
			CASE 31
				billing_phone = rs1("value")
			END SELECT
			rs1.MoveNext
		loop
		rs1.Close
		set rs1 = nothing
		
		sql = "SELECT * FROM customer_address_entity_text WHERE entity_id = " & default_billing
		set rs1 = source_conn.Execute(sql)
		do while not rs1.EOF
			
			SELECT CASE rs1("attribute_id")
			CASE 25
				billing_street = rs1("value")
			END SELECT
			rs1.MoveNext
		loop
		rs1.Close
		set rs1 = nothing
		
		shipping_first_name = ""
		shipping_last_name = ""
		shipping_street = ""
		shipping_city = ""
		shipping_state = ""
		shipping_zip = ""
		shipping_phone = ""
		shipping_country = ""
		shipping_company = ""
		shipping_prefix = ""
		
		sql = "SELECT * FROM customer_address_entity_varchar WHERE entity_id = " & default_shipping
		set rs1 = source_conn.Execute(sql)
		do while not rs1.EOF
			
			SELECT CASE rs1("attribute_id")
			CASE 19
				shipping_prefix = rs1("value")
			CASE 20
				shipping_first_name = rs1("value")
			CASE 22
				shipping_last_name = rs1("value")
			CASE 24
				shipping_company = rs1("value")
			CASE 26
				shipping_city = rs1("value")
			CASE 27
				shipping_country = rs1("value")
			CASE 28
				shipping_state = rs1("value")
			CASE 30
				shipping_zip = rs1("value")
			CASE 31
				shipping_phone = rs1("value")
			END SELECT
			rs1.MoveNext
		loop
		rs1.Close
		set rs1 = nothing
		
		sql = "SELECT * FROM customer_address_entity_text WHERE entity_id = " & default_shipping
		set rs1 = source_conn.Execute(sql)
		do while not rs1.EOF
			
			SELECT CASE rs1("attribute_id")
			CASE 25
				shipping_street = rs1("value")
			END SELECT
			rs1.MoveNext
		loop
		rs1.Close
		set rs1 = nothing
		
		'FirstName = rsx("Email")
		'LastName = rsx("Email")
		
		Response.Write(shopper_id & ":" & email  & ":" & password & ":" & k_name & ":" & billing_street & ":" & billing_city  & ":" & billing_state & ":" & billing_zip & ":" & billing_phone & "<br>")
		Response.Flush
		
		
		
		sql = "SELECT shopper_id FROM " & g_storeid & "_shopper WHERE shopper_id = '" & shopper_id & "'"
		set rs = dest_conn.Execute(sql)
		if rs.EOF then
		
			Set rsUpdate = Server.CreateObject("ADODB.Recordset")
			with rsUpdate
				.ActiveConnection = dest_conn
				.CursorLocation = 3
				.CursorType = 1
				.LockType = 3
				.Source = g_storeid & "_shopper WHERE shopper_id='0'"
				.Open
				.AddNew
			end with
			
			'GET NEW SHOPPER_ID and SAVE EMAIL Address
			rsUpdate("shopper_id") = shopper_id
			rsUpdate("Email") = new_email
		
		else
			
			Set rsUpdate = Server.CreateObject("ADODB.Recordset")
			with rsUpdate
				.ActiveConnection = dest_conn
				.CursorLocation = 3
				.CursorType = 1
				.LockType = 3
				.Source = g_storeid & "_shopper WHERE shopper_id='" & shopper_id & "'"
				.Open
			end with
		
		end if
		
		rsUpdate("Password") = password
		rsUpdate("FirstName") = FirstName
		rsUpdate("LastName") = LastName
		
		rsUpdate("DateEntered") = created_at
		rsUpdate("DateRegistered") = updated_at
		
		rsUpdate("billing_firstname") = billing_first_name
		rsUpdate("billing_lastname") = billing_last_name
		rsUpdate("Address") = billing_street
		rsUpdate("City") = billing_city
		rsUpdate("Country") = billing_country
		rsUpdate("State") = billing_state
		rsUpdate("ZipCode") = billing_zip
		rsUpdate("Phone") = billing_phone
		rsUpdate("Company") = billing_company
		rsUpdate("prefix") = billing_prefix
		
		rsUpdate("shipping_FirstName") = shipping_first_name
		rsUpdate("shipping_LastName") = shipping_last_name
		rsUpdate("shipping_Address") = shipping_street
		rsUpdate("shipping_City") = shipping_city
		rsUpdate("shipping_Country") = shipping_country
		rsUpdate("shipping_State") = shipping_state
		rsUpdate("shipping_ZipCode") = shipping_zip
		rsUpdate("shipping_Phone") = shipping_phone
		rsUpdate("shipping_Company") = shipping_company
		rsUpdate("shipping_prefix") = shipping_prefix
		
		If dest_conn.Errors.Count > 0 Then
			dest_conn.Errors.Clear
			rsUpdate.CancelUpdate
		else
			rsUpdate.Update
		End If
		
		rsUpdate.Close
		set rsUpdate = nothing
	
		rs.Close
		set rs = nothing
		
		rsx.MoveNext
	loop
	rsx.Close
	
	set rsx = nothing

	source_conn.close
	dest_conn.close
%>