<div id="top-modules">
	<%
		g_static_block_code = "TPL_JOURNAL4_INDEX_SLIDER"
	%>
	<!--#INCLUDE FILE="../../../core/cms/include_show_static_block.phtml"-->
	<%
		g_static_block_code = "TPL_JOURNAL4_INDEX_HEADLINE"
	%>
	<!--#INCLUDE FILE="../../../core/cms/include_show_static_block.phtml"-->
	<%
		g_static_block_code = "TPL_JOURNAL4_INDEX_BANNERS"
	%>
	<!--#INCLUDE FILE="../../../core/cms/include_show_static_block.phtml"-->

</div>