<div class="box journal-carousel carousel-product " id="carousel-233340730" style="">
	<div>
		<div class="htabs box-heading single-tab">
			<a href="#carousel-233340730-0" class="atab">Related Products</a>
		</div>
		<div id="carousel-233340730-0" class="owl-carousel tab-content box-content">
			<div class="product-grid-item display-icon block-button ">
				<div class="product-wrapper " style="">
					<div class="image">
						<a href="http://journal.digital-atelier.com/4/index.php?route=product/product&amp;product_id=30" class="has-second-image" style=";background: url('//digital-cdn.net/4/image/cache/data/demo/canon_eos_5d_2-250x250.jpg') no-repeat;">
						<img class="lazyOwl first-image" width="250" height="250" src="//digital-cdn.net/4/image/cache/data/journal2/transparent-250x250.png" data-src="//digital-cdn.net/4/image/cache/data/demo/canon_eos_5d_1-250x250.jpg" title="Canon EOS 5D" alt="Canon EOS 5D"/>
						</a>
						<span class="label-sale"><b>-20%</b></span>
						<div class="wishlist">
							<a onclick="addToWishList('30');" class="hint--top" data-hint="Add to Wish List"><i class="wishlist-icon"></i><span class="button-wishlist-text">Add to Wish List</span></a>
						</div>
						<div class="compare">
							<a onclick="addToCompare('30');" class="hint--top" data-hint="Compare this Product"><i class="compare-icon"></i><span class="button-compare-text">Compare this Product</span></a>
						</div>
					</div>
					<div class="product-details">
						<div class="name">
							<a href="http://journal.digital-atelier.com/4/index.php?route=product/product&amp;product_id=30">Canon EOS 5D</a>
						</div>
						<div class="description">
							 Canon's press material for the EOS 5D states that it 'defines (a) new D-SLR category', while we'r..
						</div>
						<div class="price">
							<span class="price-old">$119.50</span><span class="price-new">$96.00</span>
							<hr>
							<span class="price-tax">Ex Tax: $80.00</span>
						</div>
						<hr>
						<div class="cart ">
							<a onclick="addToCart('30');" class="button hint--top" data-hint="Add to Cart"><i class="button-left-icon"></i><span class="button-cart-text">Add to Cart</span><i class="button-right-icon"></i></a>
						</div>
						<div class="wishlist">
							<a onclick="addToWishList('30');" class="hint--top" data-hint="Add to Wish List"><i class="wishlist-icon"></i><span class="button-wishlist-text">Add to Wish List</span></a>
						</div>
						<div class="compare">
							<a onclick="addToCompare('30');" class="hint--top" data-hint="Compare this Product"><i class="compare-icon"></i><span class="button-compare-text">Compare this Product</span></a>
						</div>
					</div>
				</div>
			</div>
			<div class="product-grid-item display-icon block-button ">
				<div class="product-wrapper " style="">
					<div class="image">
						<a href="http://journal.digital-atelier.com/4/index.php?route=product/product&amp;product_id=40" class="has-second-image" style=";background: url('//digital-cdn.net/4/image/cache/data/demo/iphone_6-250x250.jpg') no-repeat;">
						<img class="lazyOwl first-image" width="250" height="250" src="//digital-cdn.net/4/image/cache/data/journal2/transparent-250x250.png" data-src="//digital-cdn.net/4/image/cache/data/demo/iphone_1-250x250.jpg" title="iPhone" alt="iPhone"/>
						</a>
						<div class="wishlist">
							<a onclick="addToWishList('40');" class="hint--top" data-hint="Add to Wish List"><i class="wishlist-icon"></i><span class="button-wishlist-text">Add to Wish List</span></a>
						</div>
						<div class="compare">
							<a onclick="addToCompare('40');" class="hint--top" data-hint="Compare this Product"><i class="compare-icon"></i><span class="button-compare-text">Compare this Product</span></a>
						</div>
					</div>
					<div class="product-details">
						<div class="name">
							<a href="http://journal.digital-atelier.com/4/index.php?route=product/product&amp;product_id=40">iPhone</a>
						</div>
						<div class="description">
							 iPhone is a revolutionary new mobile phone that allows you to make a call by simply tapping a nam..
						</div>
						<div class="price">
							 $120.68
							<hr>
							<span class="price-tax">Ex Tax: $101.00</span>
						</div>
						<hr>
						<div class="cart ">
							<a onclick="addToCart('40');" class="button hint--top" data-hint="Add to Cart"><i class="button-left-icon"></i><span class="button-cart-text">Add to Cart</span><i class="button-right-icon"></i></a>
						</div>
						<div class="wishlist">
							<a onclick="addToWishList('40');" class="hint--top" data-hint="Add to Wish List"><i class="wishlist-icon"></i><span class="button-wishlist-text">Add to Wish List</span></a>
						</div>
						<div class="compare">
							<a onclick="addToCompare('40');" class="hint--top" data-hint="Compare this Product"><i class="compare-icon"></i><span class="button-compare-text">Compare this Product</span></a>
						</div>
					</div>
				</div>
			</div>
			<div class="product-grid-item display-icon block-button ">
				<div class="product-wrapper " style="">
					<div class="image">
						<a href="http://journal.digital-atelier.com/4/index.php?route=product/product&amp;product_id=43" class="has-second-image" style=";background: url('//digital-cdn.net/4/image/cache/data/demo/macbook_5-250x250.jpg') no-repeat;">
						<img class="lazyOwl first-image" width="250" height="250" src="//digital-cdn.net/4/image/cache/data/journal2/transparent-250x250.png" data-src="//digital-cdn.net/4/image/cache/data/demo/macbook_1-250x250.jpg" title="MacBook" alt="MacBook"/>
						</a>
						<div class="wishlist">
							<a onclick="addToWishList('43');" class="hint--top" data-hint="Add to Wish List"><i class="wishlist-icon"></i><span class="button-wishlist-text">Add to Wish List</span></a>
						</div>
						<div class="compare">
							<a onclick="addToCompare('43');" class="hint--top" data-hint="Compare this Product"><i class="compare-icon"></i><span class="button-compare-text">Compare this Product</span></a>
						</div>
					</div>
					<div class="product-details">
						<div class="name">
							<a href="http://journal.digital-atelier.com/4/index.php?route=product/product&amp;product_id=43">MacBook</a>
						</div>
						<div class="description">
							 Intel Core 2 Duo processor Powered by an Intel Core 2 Duo processor at speeds up to 2.1..
						</div>
						<div class="price">
							 $589.50
							<hr>
							<span class="price-tax">Ex Tax: $500.00</span>
						</div>
						<hr>
						<div class="cart ">
							<a onclick="addToCart('43');" class="button hint--top" data-hint="Add to Cart"><i class="button-left-icon"></i><span class="button-cart-text">Add to Cart</span><i class="button-right-icon"></i></a>
						</div>
						<div class="wishlist">
							<a onclick="addToWishList('43');" class="hint--top" data-hint="Add to Wish List"><i class="wishlist-icon"></i><span class="button-wishlist-text">Add to Wish List</span></a>
						</div>
						<div class="compare">
							<a onclick="addToCompare('43');" class="hint--top" data-hint="Compare this Product"><i class="compare-icon"></i><span class="button-compare-text">Compare this Product</span></a>
						</div>
					</div>
				</div>
			</div>
			<div class="product-grid-item display-icon block-button ">
				<div class="product-wrapper " style="">
					<div class="image">
						<a href="http://journal.digital-atelier.com/4/index.php?route=product/product&amp;product_id=46" class="has-second-image" style=";background: url('//digital-cdn.net/4/image/cache/data/demo/sony_vaio_5-250x250.jpg') no-repeat;">
						<img class="lazyOwl first-image" width="250" height="250" src="//digital-cdn.net/4/image/cache/data/journal2/transparent-250x250.png" data-src="//digital-cdn.net/4/image/cache/data/demo/sony_vaio_1-250x250.jpg" title="Sony VAIO" alt="Sony VAIO"/>
						</a>
						<div class="wishlist">
							<a onclick="addToWishList('46');" class="hint--top" data-hint="Add to Wish List"><i class="wishlist-icon"></i><span class="button-wishlist-text">Add to Wish List</span></a>
						</div>
						<div class="compare">
							<a onclick="addToCompare('46');" class="hint--top" data-hint="Compare this Product"><i class="compare-icon"></i><span class="button-compare-text">Compare this Product</span></a>
						</div>
					</div>
					<div class="product-details">
						<div class="name">
							<a href="http://journal.digital-atelier.com/4/index.php?route=product/product&amp;product_id=46">Sony VAIO</a>
						</div>
						<div class="description">
							 Unprecedented power. The next generation of processing technology has arrived. Built into the new..
						</div>
						<div class="price">
							 $1,177.00
							<hr>
							<span class="price-tax">Ex Tax: $1,000.00</span>
						</div>
						<hr>
						<div class="cart ">
							<a onclick="addToCart('46');" class="button hint--top" data-hint="Add to Cart"><i class="button-left-icon"></i><span class="button-cart-text">Add to Cart</span><i class="button-right-icon"></i></a>
						</div>
						<div class="wishlist">
							<a onclick="addToWishList('46');" class="hint--top" data-hint="Add to Wish List"><i class="wishlist-icon"></i><span class="button-wishlist-text">Add to Wish List</span></a>
						</div>
						<div class="compare">
							<a onclick="addToCompare('46');" class="hint--top" data-hint="Compare this Product"><i class="compare-icon"></i><span class="button-compare-text">Compare this Product</span></a>
						</div>
					</div>
				</div>
			</div>
			<div class="product-grid-item display-icon block-button ">
				<div class="product-wrapper outofstock" style="">
					<div class="image">
						<a href="http://journal.digital-atelier.com/4/index.php?route=product/product&amp;product_id=50" style="">
						<img class="lazyOwl first-image" width="250" height="250" src="//digital-cdn.net/4/image/cache/data/journal2/transparent-250x250.png" data-src="//digital-cdn.net/4/image/cache/data/4-250x250.jpg" title="Blue Dress" alt="Blue Dress"/>
						</a>
						<img class="outofstock" width="120" height="120" style="position: absolute; top: 0; left: 0" src="//digital-cdn.net/4/image/cache/898654c5b0653d089affce9be70853b1--medium--255-255-255--176-158-102.png" alt=""/>
						<div class="wishlist">
							<a onclick="addToWishList('50');" class="hint--top" data-hint="Add to Wish List"><i class="wishlist-icon"></i><span class="button-wishlist-text">Add to Wish List</span></a>
						</div>
						<div class="compare">
							<a onclick="addToCompare('50');" class="hint--top" data-hint="Compare this Product"><i class="compare-icon"></i><span class="button-compare-text">Compare this Product</span></a>
						</div>
					</div>
					<div class="product-details">
						<div class="name">
							<a href="http://journal.digital-atelier.com/4/index.php?route=product/product&amp;product_id=50">Blue Dress</a>
						</div>
						<div class="description">
							Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the ..
						</div>
						<div class="price">
							 $99.00
							<hr>
							<span class="price-tax">Ex Tax: $99.00</span>
						</div>
						<hr>
						<div class="cart outofstock">
							<a onclick="addToCart('50');" class="button hint--top" data-hint="Add to Cart"><i class="button-left-icon"></i><span class="button-cart-text">Add to Cart</span><i class="button-right-icon"></i></a>
						</div>
						<div class="wishlist">
							<a onclick="addToWishList('50');" class="hint--top" data-hint="Add to Wish List"><i class="wishlist-icon"></i><span class="button-wishlist-text">Add to Wish List</span></a>
						</div>
						<div class="compare">
							<a onclick="addToCompare('50');" class="hint--top" data-hint="Compare this Product"><i class="compare-icon"></i><span class="button-compare-text">Compare this Product</span></a>
						</div>
					</div>
				</div>
			</div>
			<div class="product-grid-item display-icon block-button ">
				<div class="product-wrapper " style="">
					<div class="image">
						<a href="http://journal.digital-atelier.com/4/index.php?route=product/product&amp;product_id=51" class="has-second-image" style=";background: url('//digital-cdn.net/4/image/cache/data/3b-250x250.jpg') no-repeat;">
						<img class="lazyOwl first-image" width="250" height="250" src="//digital-cdn.net/4/image/cache/data/journal2/transparent-250x250.png" data-src="//digital-cdn.net/4/image/cache/data/1-250x250.jpg" title="Blue Short Skirt" alt="Blue Short Skirt"/>
						</a>
						<div class="wishlist">
							<a onclick="addToWishList('51');" class="hint--top" data-hint="Add to Wish List"><i class="wishlist-icon"></i><span class="button-wishlist-text">Add to Wish List</span></a>
						</div>
						<div class="compare">
							<a onclick="addToCompare('51');" class="hint--top" data-hint="Compare this Product"><i class="compare-icon"></i><span class="button-compare-text">Compare this Product</span></a>
						</div>
					</div>
					<div class="product-details">
						<div class="name">
							<a href="http://journal.digital-atelier.com/4/index.php?route=product/product&amp;product_id=51">Blue Short Skirt</a>
						</div>
						<div class="description">
							Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the ..
						</div>
						<div class="price">
							 $75.00
							<hr>
							<span class="price-tax">Ex Tax: $75.00</span>
						</div>
						<hr>
						<div class="cart ">
							<a onclick="addToCart('51');" class="button hint--top" data-hint="Add to Cart"><i class="button-left-icon"></i><span class="button-cart-text">Add to Cart</span><i class="button-right-icon"></i></a>
						</div>
						<div class="wishlist">
							<a onclick="addToWishList('51');" class="hint--top" data-hint="Add to Wish List"><i class="wishlist-icon"></i><span class="button-wishlist-text">Add to Wish List</span></a>
						</div>
						<div class="compare">
							<a onclick="addToCompare('51');" class="hint--top" data-hint="Compare this Product"><i class="compare-icon"></i><span class="button-compare-text">Compare this Product</span></a>
						</div>
					</div>
				</div>
			</div>
		</div>
		<script>
			(function(){
			var opts = $.parseJSON('[[0,1],[470,1],[760,1],[980,1],[1100,1]]');
			jQuery("#carousel-233340730 .owl-carousel").owlCarousel({
				lazyLoad: true,
				itemsCustom: opts,
				autoPlay: false,
				touchDrag: true,
				stopOnHover: true,
				items: 15,
				navigation: true,
				scrollPerPage: true,
				navigationText: false,
				paginationSpeed: 400,
				margin: 20
			});
			$('#carousel-233340730 .htabs a.atab').tabs();
						Journal.equalHeight($('#carousel-233340730 .product-grid-item'), '.name');
			Journal.equalHeight($('#carousel-233340730 .product-grid-item'), '.description');
			var default_section = '';
			if (default_section) {
				$('#carousel-233340730 .htabs a.atab[href="#carousel-233340730-' + default_section + '"]').click();
			} else {
				$('#carousel-233340730 .htabs a.atab').first().click();
			}
								})();
		</script>
	</div>
</div>
<%
	g_static_block_code = "TPL_JOURNAL4_PRODUCT_RIGHT_1"
%>
<!--#INCLUDE FILE="../../../core/cms/include_show_static_block.phtml"-->

<%
	g_static_block_code = "TPL_JOURNAL4_PRODUCT_RIGHT_2"
%>
<!--#INCLUDE FILE="../../../core/cms/include_show_static_block.phtml"-->
