<%
	Response.CodePage = 65001
	Response.CharSet = "UTF-8"
%>
<%response.Expires=-1%>
<!-- #INCLUDE File="../local/local.phtml" -->
<!-- #INCLUDE File="../core/i_adoopen.phtml" -->
<%
	address_id = Trim(Request("address_id"))
%>
{
"Address" : [
<%
	s_address = ""
	if address_id = "0" then
		sql = "SELECT * FROM " & g_storeid & "_shopper WHERE shopper_id = '" & Session("shopper_id") & "'"
		set rsShopper = dbconn.Execute(sql)
		if not rsShopper.EOF then
			shopper_shipping_firstname = rsShopper("shipping_FirstName")
			shopper_shipping_lastname = rsShopper("shipping_LastName")
			shopper_shipping_address = rsShopper("shipping_Address")
			shopper_shipping_city = rsShopper("shipping_City")
			shopper_shipping_state = rsShopper("shipping_State")
			shopper_shipping_zip = rsShopper("shipping_ZipCode")
			shopper_shipping_country = rsShopper("shipping_Country")
			shopper_shipping_phone = rsShopper("shipping_Phone")
			shopper_shipping_company = rsShopper("shipping_company")
			z_shipping_country = shopper_shipping_country
			z_shipping_state = shopper_shipping_state
			z_shipping_postcode = shopper_shipping_zip
		end if
		rsShopper.Close
		set rsShopper = nothing
	else
		sql = "SELECT * FROM " & g_storeid & "_shopper_shipping_address WHERE shopper_id = '" & Session("shopper_id") & "' AND address_id = '" & address_id & "'"
		set rs = dbconn.Execute(sql)
		if not rs.EOF then
			alt_address_id = rs("address_id")
			alt_shopper_id = rs("shopper_id")
			alt_address_name = rs("address_name")
			alt_firstname = rs("firstname")
			alt_lastname = rs("lastname")
			alt_address = rs("address")
			alt_city = rs("city")
			alt_state = rs("state")
			alt_zip = rs("zip")
			alt_country= rs("country")
			alt_phone = rs("phone")
			alt_set_default = rs("set_default")
			alt_company = rs("company")
			alt_address_type = rs("address_type")
			
			z_shipping_country = alt_country
			z_shipping_state = alt_state
			z_shipping_postcode = alt_zip 
			
		end if
		rs.Close
		set rs = nothing
	end if
	
	s_address = s_address & "{""id"" : """ & "country_id" & """,""dvalue"" : """ & z_shipping_country & """},"
	s_address = s_address & "{""id"" : """ & "zone_id" & """,""dvalue"" : """ & z_shipping_state & """},"
	s_address = s_address & "{""id"" : """ & "postcode" & """,""dvalue"" : """ & z_shipping_postcode & """},"
	
	if Len(s_address) > 0 then
		s_address = Left(s_address, Len(s_address)-1)
	end if
	response.Write(s_address)
	
%>
]
}
<!-- #INCLUDE File="../core/i_adoclosed.phtml" -->