<%
	Response.CodePage = 1252 
	Response.CharSet = "windows-1252" 
%>
<!--#INCLUDE FILE="../local/local.phtml"-->
<!--#INCLUDE FILE="../core/i_adoopen.phtml"-->
<!--#INCLUDE FILE="../util/xt_func_session.phtml"-->
<!--#INCLUDE File="../util/xt_func_util.phtml" -->
<!--#INCLUDE FILE="../util/xt_func_string.phtml"-->
<!--#INCLUDE FILE="../util/xt_func_shoppingcart.phtml"-->
<%
	pf_id = Trim(Request("pf_id"))
	filter_attribute_id= Trim(Request("filter_option"))
	filter_option_value= Trim(Request("filter_option_value"))
	
	option_attribute_id = "134"
	
	
	s_config_option_id = ""
	
	sql = "SELECT DISTINCT inventory_attribute_option_id_2 FROM hisandher_product_inventory WHERE inventory_id IN ( "
	sql = sql & "SELECT product_id FROM hisandher_product_super_link WHERE parent_id = '" & pf_id & "') "
	sql = sql & "AND inventory_attribute_id_1 = " & filter_attribute_id & " AND inventory_attribute_option_id_1 = " & filter_option_value & " "
	
	set rsAttID = dbconn.Execute(sql)
	do while not rsAttID.EOF
		s_config_option_id = s_config_option_id & CStr(rsAttID(0)) & ","
		rsAttID.MoveNext
	loop
	rsAttID.Close
	
	if Len(s_config_option_id) > 0 then
		s_config_option_id = Left(s_config_option_id, Len(s_config_option_id) - 1)
	end if

%>
<label class="control-label">Hair Color<span class="required2">*</span></label>
<div id="input-option134">
	<%
		sql = "SELECT * FROM " & g_storeid & "_eav_attribute_option WHERE attribute_id=" & option_attribute_id & " AND option_id IN (" & s_config_option_id & ") ORDER BY sort_order"
		set rsAttOptions = dbconn.Execute(sql)
		do while not rsAttOptions.EOF
			option_color_swatch = rsAttOptions("option_color_swatch")
			display_name = rsAttOptions("display_name")
			option_description = rsAttOptions("option_description")
			if Len(option_description) > 0 then
			else
				option_description = display_name
			end if
	%>
	<div class="radio">
		<label>
		<input type="radio" name="option_<%=option_attribute_id%>" value="<%=rsAttOptions("option_id")%>"/>
		<img src="/media/colorswatch/<%=option_color_swatch%>" title="<%=option_description%>" alt="<%=rsAttOptions("display_name")%>" class="img-thumbnail" width="60"/> <%=rsAttOptions("display_name")%> </label>
	</div>
	<%
			rsAttOptions.MoveNext
		loop
		rsAttOptions.Close
		set rsAttOptions = nothing
	%>
</div>
<ul>
	
	<%
		s_block = ""
		sql = "SELECT * FROM " & g_storeid & "_eav_attribute_option WHERE attribute_id=" & option_attribute_id & " AND option_id IN (" & s_config_option_id & ") ORDER BY sort_order"
		set rsAttOptions = dbconn.Execute(sql)
		do while not rsAttOptions.EOF
			option_color_swatch = rsAttOptions("option_color_swatch")
			display_name = rsAttOptions("display_name")
			option_description = rsAttOptions("option_description")
			if Len(option_description) > 0 then
			else
				option_description = display_name
			end if
			
			s_block = s_block & "<li class=""hint--top3"" data-hint=""" & option_description & """ data-value=""" & rsAttOptions("option_id") & """><span><a class=""tooltip2""><img src=""/media/colorswatch/" & option_color_swatch & """ title=""" & option_description & """ alt=""" & display_name & """ class=""img-thumbnail"" width=""60"">"
			s_block = s_block & "<div>"
			s_block = s_block & "<table border=""0"">"
			s_block = s_block & "<tbody>"
			s_block = s_block & "<tr>"
			s_block = s_block & "<td>"
			s_block = s_block & "<img src=""/media/colorswatch/" & option_color_swatch & """ width=""200"">"
			s_block = s_block & "</td>"
			s_block = s_block & "</tr>"
			s_block = s_block & "<tr>"
			s_block = s_block & "<td>"
			s_block = s_block & option_description
			s_block = s_block & "</td>"
			s_block = s_block & "</tr>"
			s_block = s_block & "</tbody>"
			s_block = s_block & "</table>"
			s_block = s_block & "</div>"
			s_block = s_block & "</a></span><br>"
			s_block = s_block & "<span style=""font-size:11px;text-align:center"">" & display_name & "</span></li>"
	
			rsAttOptions.MoveNext
		loop
		rsAttOptions.Close
		set rsAttOptions = nothing
	%>
	<%=s_block%>
</ul>