<%response.Expires=-1%>
<%
	Response.CodePage = 65001
	Response.CharSet = "UTF-8"
%>
<!--#INCLUDE FILE="../../util/xt_func_carrier.phtml"-->
<!--#INCLUDE FILE="../../util/xt_func_string.phtml"-->	
<!--#INCLUDE FILE="../../util/xt_func_util.phtml"-->	
<!-- #INCLUDE File="../local/local.phtml" -->
<%
	'Response.end
		
	mfg_id = Trim(Request("mfg_id"))
	mfg_name = Trim(Request("mfg_name"))
	mfg_map_enabled = Trim(Request("mfg_map_enabled")) 
	
	if mfg_id = "0" then
		
		Set rsUpdate = Server.CreateObject("ADODB.Recordset")
		with rsUpdate
			.ActiveConnection = dbconn
			.CursorLocation = 3
			.CursorType = 1
			.LockType = 3
			.Source = g_storeid & "_mfg"
			.Open
			.AddNew
		end with
		
		rsUpdate("mfg_id") = GetUniqueLongIntegerID()
		
	else
	
		Set rsUpdate = Server.CreateObject("ADODB.Recordset")
		with rsUpdate
			.ActiveConnection = dbconn
			.CursorLocation = 3
			.CursorType = 1
			.LockType = 3
			.Source = g_storeid & "_mfg WHERE mfg_id='" & mfg_id & "'"
			.Open
		end with
	
	end if
	
	
	rsUpdate("mfg_name") = mfg_name
	rsUpdate("mfg_map_enabled") = mfg_map_enabled
	
	
	If dbconn.Errors.Count > 0 Then
		dbconn.Errors.Clear
		rsUpdate.CancelUpdate
	else
		rsUpdate.Update
	End If
	
	rsUpdate.Close
	set rsUpdate = nothing
		
	
%>