<%response.Expires=-1%>
<!-- #INCLUDE File="../local/local.phtml" -->
<%
	
	attribute_id = Trim(Request("attribute_id"))
%>
{
"Subcategories" : [
<%
	s_sub = ""
	if Len(attribute_id) > 0 then
		sql = "SELECT option_id, option_name FROM " & g_storeid & "_eav_attribute_option WHERE attribute_id=" & attribute_id & " ORDER BY option_name"
		set rs1 = dbconn.Execute(sql)
		do while not rs1.EOF
			sname = rs1(1)
			s_sub = s_sub & "{""id"" : """ & rs1(0) & """,""name"" : """ & sname & """},"
			rs1.MoveNext
		loop
		rs1.Close
		set rs1 = nothing
		if Len(s_sub) > 0 then
			s_sub = Left(s_sub, Len(s_sub)-1)
		end if
	end if
	
	response.Write(s_sub)
%>
]
}
