<%@ Language=VBScript %>
<%
  Response.Expires = -1
%>
<!-- #INCLUDE File="../local/local.phtml" -->
<!-- #INCLUDE File="../util/xt_func_util.phtml" -->
<!-- #INCLUDE File="../util/xt_func_string.phtml" -->
<%
	category_id = Trim(Request("category_id"))
	
	sql = "SELECT icecat_category FROM " & g_storeid & "_dept WHERE dept_id = '" & category_id & "'"
	set rs = dbconn.Execute(sql)
	if not rs.EOF then
		icecat_category = Trim(rs(0))
	end if
	rs.Close
	set rs = nothing
	
	sEcho = Trim(Request("sEcho"))
	iDisplayLength = Trim(Request("iDisplayLength"))
	iDisplayStart = Trim(Request("iDisplayStart"))

	sEcho = FilterStringEx(sEcho, "[^0-9]")
	iDisplayLength = FilterStringEx(iDisplayLength, "[^0-9]")
	iDisplayStart = FilterStringEx(iDisplayStart, "[^0-9]")

	sEcho = Cint(sEcho)
	iDisplayLength = Cint(iDisplayLength)
	iDisplayStart = Cint(iDisplayStart)

	sMin = Trim(Request("min"))
	sMax = Trim(Request("max"))

	sDateRange = ""

	if IsDate(sMin) then
		if IsDate(sMax) then
			dMax = CDate(sMax)
			dMax = DateAdd("d", 1, dMax)
			sMax = FormatDateTime(dMax,0)
			sDateRange = "(date_changed between '" & sMin & "' AND '" & sMax & "')"
		else
			dMax = Date()
			dMax = DateAdd("d", 1, dMax)
			sMax = FormatDateTime(dMax,0)
			sDateRange = "(date_changed between '" & sMin & "' AND '" & sMax & "')"
		end if
	else
		if IsDate(sMax) then
			dMax = CDate(sMax)
			dMax = DateAdd("d", 1, dMax)
			sMax = FormatDateTime(dMax,0)
			sDateRange = "(date_changed between '1/1/1970' AND '" & sMax & "')"
		end if
	end if

	sSearch = Trim(Request("sSearch"))
	sSearch = FilterStringEx(sSearch, "[^0-9a-zA-Z _/-]")

	index_date = DateAdd("d", -30, Date())

	if Len(sSearch) > 0 then
		sSearchDate = Replace(sSearch, "*", "%")
	end if

	'SEARCH - here we make the Where clause that will be used in the SQL querry. You only put here the fields you want to search 
	strWhere = " (sku LIKE '%" & sSearch & "%' OR "
	strWhere = strWhere &  " DESCR LIKE '%" & sSearch & "%' OR "
	strWhere = strWhere &  " VEND_NAME LIKE '%" & sSearch & "%' OR "
	strWhere = strWhere &  " VEND_PART LIKE '%" & sSearch & "%')"

	if Len(str_filter) > 0 then
		strWhere  = strWhere & " AND " & str_filter
	end if
	
	strWhere = strWhere & " AND catid IN (" & icecat_category & ")"

	'=======================================================================================
	'ORDERING
	'passes through all cols and first check if the column is sortable, if yes then construct
	'the variable "order" that list in order the sequence of ordering
	for k = 0 to 7
		if Request("bSortable_" & k)="true" then
			order = order & Request("iSortCol_" & k) & " " & Request("sSortDir_" & k)
		end if
	next
	'here we replace the number corresponding the column position by the corresponding name of the column in the database
	order =	Replace(order,"0",", sku")
	order =	Replace(order,"1",", sku")
	order =	Replace(order,"2",", sku")
	order =	Replace(order,"3",", sku")
	order =	Replace(order,"4",", sku")
	order =	Replace(order,"5",", sku")
	order =	Replace(order,"6",", sku")
	order =	Replace(order,"7",", sku")
	order =	Replace(order,"8",", sku")
	order =	Replace(order,"9",", sku")

	'here we eliminate the first comma of the variable "order"
	if Len(order) > 0 then
		order = Right(order, Len(order)-1)
	else
		order = "sku DESC"
	end if

	'here we create the variable "strOrderBy" that will be used in the SQL querry
	strOrderBy = "ORDER BY " & order

	'======================================================================================

	sql = "SELECT * FROM " & g_storeid & "_ssprice WHERE " & strWhere & " " & strOrderBy
	sqlx = "SELECT COUNT(sku) FROM " & g_storeid & "_ssprice WHERE " & strWhere 

	set rs = dbconn_icecat.Execute(sql)

	iTotalDisplayRecords = 0
	iTotalRecords = 50
	set rs1 = dbconn_icecat.Execute(sqlx)
	if not rs1.EOF then
		iTotalDisplayRecords = rs1(0)
		iTotalRecords = rs1(0)
	else
	end if
	rs1.Close


	
%>
{"sEcho": <%=sEcho%>, "iTotalRecords": <%=iTotalRecords%>, "iTotalDisplayRecords": <%=iTotalDisplayRecords%>, "aaData": [ 
<%
	i = 0

	if rs.eof = false then
		rs.move(iDisplayStart)
		do while i < iDisplayLength and not rs.eof
			
			s_sku = rs("sku")
			s_DESCR = Trim(rs("DESCR"))
			s_VEND_NAME = Trim(rs("VEND_NAME"))
			s_VEND_PART = Trim(rs("VEND_PART"))
			image_published = rs("image_published")
			icecat_id = Trim(rs("icecat_id"))
			s_AVAIL = Trim(rs("AVAIL"))
			
			If Len(s_DESCR) > 0 Then
				s_DESCR = Replace(s_DESCR, "'", "&#39")
				s_DESCR = Replace(s_DESCR, """", "&#34;")
			End if
			
			s_price = FormatNumber(rs("cost"),2)
			s_price_A = FormatNumber(rs("price_A"),2)
			s_price_B = FormatNumber(rs("price_B"),2)
			s_price_C = FormatNumber(rs("price_C"),2)
			s_price_D = FormatNumber(rs("price_D"),2)
			
			aaData = aaData & "['"
			aaData = aaData & s_sku & "','" 
			aaData = aaData & s_VEND_PART & "','" 
			aaData = aaData & s_price & "','"
			aaData = aaData & s_price_A & "','" 
			aaData = aaData & s_price_B & "','" 
			aaData = aaData & s_price_C & "','"
			aaData = aaData & s_price_D & "','"
			
			if (use_price) then
				aaData = aaData & "1" & "','" 
				aaData = aaData & "<i class=\'fa fa-check text-red\'></i>','"
			else
				aaData = aaData & "0" & "','" 
				aaData = aaData & "<i class=\'fa fa-close text-grey\'></i>','"
			end if
			
			aaData = aaData & "<a href=\'#\' class=\'edit-row\'><i class=\'fa fa-pencil\'></i></a>'],"
			
			
			aaData = Replace(aaData,"'",chr(34))
			rs.MoveNext
			i=i+1
		loop
		rs.Close
		aaData = Replace(aaData,"**", "'")
		aaData = Left(aaData, Len(aaData)-1)
	else
		aaData = ""
	end if
	response.write aaData & "] }"

%>