<%@ Language=VBScript %>
<%
	Response.CodePage = 65001
	Response.CharSet = "UTF-8"
%>
<%
  Response.Expires = -1
%>
<!-- #INCLUDE File="../local/local.phtml" -->
<!-- #INCLUDE File="../util/xt_func_util.phtml" -->
<!-- #INCLUDE File="../util/xt_func_string.phtml" -->
<%
	sEcho = Trim(Request("sEcho"))
	iDisplayLength = Trim(Request("iDisplayLength"))
	iDisplayStart = Trim(Request("iDisplayStart"))

	sEcho = FilterStringEx(sEcho, "[^0-9]")
	iDisplayLength = FilterStringEx(iDisplayLength, "[^0-9]")
	iDisplayStart = FilterStringEx(iDisplayStart, "[^0-9]")

	sEcho = Cint(sEcho)
	iDisplayLength = Cint(iDisplayLength)
	iDisplayStart = Cint(iDisplayStart)

	sSearch = Trim(Request("sSearch"))
	sSearch = FilterStringEx(sSearch, "[^0-9a-zA-Z _/-]")

	index_date = DateAdd("d", -30, Date())

	if Len(sSearch) > 0 then
		sSearchDate = Replace(sSearch, "*", "%")
	end If

	Dim ar_sSearch

	strWhere = " (mfg_id LIKE '%" & sSearch & "%' OR "
	strWhere = strWhere &  " mfg_name LIKE '%" & sSearch & "%')"

	'=======================================================================================
	'ORDERING
	'passes through all cols and first check if the column is sortable, if yes then construct
	'the variable "order" that list in order the sequence of ordering
	for k = 0 to 7
		if Request("bSortable_" & k)="true" then
			order = order & Request("iSortCol_" & k) & " " & Request("sSortDir_" & k)
		end if
	next
	'here we replace the number corresponding the column position by the corresponding name of the column in the database
	order =	Replace(order,"0",", mfg_id")
	order =	Replace(order,"1",", mfg_name")

	'here we eliminate the first comma of the variable "order"
	if Len(order) > 0 then
	  order = Right(order, Len(order)-1)
	else
	  order = "mfg_name"
	end if

	'here we create the variable "strOrderBy" that will be used in the SQL querry
	strOrderBy = "ORDER BY " & order

	'======================================================================================


	Set dbconn=server.CreateObject("ADODB.Connection")
	dbconn.Open g_connection_string

	sql = "SELECT * FROM " & g_storeid & "_mfg WHERE " & strWhere & " " & strOrderBy

	'response.write(sql)
	sqlx = "SELECT COUNT(mfg_id) FROM " & g_storeid & "_mfg WHERE " & strWhere 
		
	set rs = dbconn.Execute(sql)

	iTotalDisplayRecords = 0
	iTotalRecords = 50
	set rs1 = dbconn.Execute(sqlx)
	if not rs1.EOF then
	  iTotalDisplayRecords = rs1(0)
	  iTotalRecords = rs1(0)
	else
	end if
	rs1.Close

	'iTotalDisplayRecords = 50

	'iTotalRecords = 50
	
%>
{"sEcho": <%=sEcho%>, "iTotalRecords": <%=iTotalRecords%>, "iTotalDisplayRecords": <%=iTotalDisplayRecords%>, "aaData": [ 
<%
	i = 0
	if rs.eof = false then
		rs.move(iDisplayStart)
		do while i < iDisplayLength and not rs.eof

			s_mfg_id = rs("mfg_id")
			s_mfg_name = Trim(rs("mfg_name"))
			
			aaData = aaData & "['"
			aaData = aaData & "<a href=\'catalog_product_detail.phtml?pf_id=" & s_mfg_id & "\'>" & s_mfg_id & "</a>','" 
			aaData = aaData & s_mfg_name & "','"
			
			SELECT CASE rs("mfg_map_enabled")
			CASE 0
				s_active = "Disabled"
				s_label = "label label-success"
			CASE 1
				s_active = "Enabled"
				s_label = "label label-danger"
			END SELECT
			
			aaData = aaData & "<span class=\'" & s_label & "\'>" & s_active & "</span>','"
			
			'aaData = aaData & s_mfg_name & "','" 
			'aaData = aaData & "<a href=\'#\' class=\'edit-row\'><i class=\'fa fa-pencil\'></i></a>'],"
			aaData = aaData & "<a href=\'#\' class=\'btn btn-xs btn-teal tooltips modal-edit-line\'  data-toggle=\'modal\' data-id=\'" & Trim(s_mfg_id) & "\' data-placement=\'top\' data-original-title=\'Edit\'><i class=\'fa fa-edit\'></i></a>'],"
		  
		  aaData = Replace(aaData,"'",chr(34))
		  rs.MoveNext
		  i=i+1
		loop
		rs.Close
		aaData = Left(aaData, Len(aaData)-1)
	else
		aaData = ""
	end if
	response.write aaData & "] }"
%>