<%@ Language=VBScript %>
<%
	Response.CodePage = 65001
	Response.CharSet = "UTF-8"
%>
<%
  Response.Expires = -1
%>
<!-- #INCLUDE File="../local/local.phtml" -->
<!-- #INCLUDE File="../util/xt_func_util.phtml" -->
<!-- #INCLUDE File="../util/xt_func_string.phtml" -->
<%
	sEcho = Trim(Request("sEcho"))
	iDisplayLength = Trim(Request("iDisplayLength"))
	iDisplayStart = Trim(Request("iDisplayStart"))

	sEcho = FilterStringEx(sEcho, "[^0-9]")
	iDisplayLength = FilterStringEx(iDisplayLength, "[^0-9]")
	iDisplayStart = FilterStringEx(iDisplayStart, "[^0-9]")

	sEcho = Cint(sEcho)
	iDisplayLength = Cint(iDisplayLength)
	iDisplayStart = Cint(iDisplayStart)

	'sEcho = Cint(Request("sEcho"))
	'iDisplayLength = Cint(Request("iDisplayLength"))
	'iDisplayStart = Cint(Request("iDisplayStart"))

	sMin = Trim(Request("min"))
	sMax = Trim(Request("max"))

	sDateRange = ""

	if IsDate(sMin) then
		if IsDate(sMax) then
			dMax = CDate(sMax)
			dMax = DateAdd("d", 1, dMax)
			sMax = FormatDateTime(dMax,0)
			sDateRange = "(date_changed between '" & sMin & "' AND '" & sMax & "')"
		else
	'dMin = CDate(sMin)
			dMax = Date()
			dMax = DateAdd("d", 1, dMax)
			sMax = FormatDateTime(dMax,0)
			sDateRange = "(date_changed between '" & sMin & "' AND '" & sMax & "')"
		end if
	else
		if IsDate(sMax) then
			dMax = CDate(sMax)
			dMax = DateAdd("d", 1, dMax)
			sMax = FormatDateTime(dMax,0)
			sDateRange = "(date_changed between '1/1/1970' AND '" & sMax & "')"
		end if
	end if

	sSearch = Trim(Request("sSearch"))
	sSearch = FilterStringEx(sSearch, "[^0-9a-zA-Z _/-]")

	v1 = Trim(Request("v1")) 'Sales Rep
	v2 = Trim(Request("v2")) 'Status


	index_date = DateAdd("d", -30, Date())

	Select case v1
	case "1"
		str_filter = "(salesrep_id='" & Session("AdminID") & "')"
	case else
		str_filter = ""
	end select

	if Len(sSearch) > 0 then
		sSearchDate = Replace(sSearch, "*", "%")
	end if

	'SEARCH - here we make the Where clause that will be used in the SQL querry. You only put here the fields you want to search 
	if IsNumeric(sSearch) then
		strWhere = " (po_id LIKE '%" & sSearch & "%' OR "
	else
		strWhere = " ("
	end if
	strWhere = strWhere &  " dist_name LIKE '%" & sSearch & "%' OR "
	strWhere = strWhere &  " shipping_contact_first LIKE '%" & sSearch & "%' OR "
	strWhere = strWhere &  " shipping_contact_last LIKE '%" & sSearch & "%' OR "
	if Len(sDateRange) > 0 then
	else
		strWhere = strWhere &  " date_updated LIKE '%" & sSearchDate & "%' OR "
	end if
	strWhere = strWhere &  " po_status LIKE '%" & sSearch & "%')"

	if Len(sDateRange) > 0 then
		strWhere = strWhere &  " AND " & sDateRange
	end if

	if Len(str_filter) > 0 then
		strWhere  = strWhere & " AND " & str_filter
	end if

	if v2 = "All" then
	else
		strWhere = strWhere & " AND po_status='" & v2 & "'"
	end if



	for k = 0 to 5
		if Request("bSortable_" & k)="true" then
			order = order & Request("iSortCol_" & k) & " " & Request("sSortDir_" & k)
		end if
	next
	'here we replace the number corresponding the column position by the corresponding name of the column in the database
	order =	Replace(order,"0",", po_id")
	order =	Replace(order,"1",", dist_name")
	order =	Replace(order,"2",", shipping_contact")
	order =	Replace(order,"3",", po_amount")
	order =	Replace(order,"4",", po_status")
	order =	Replace(order,"5",", date_updated")

	'here we eliminate the first comma of the variable "order"
	if Len(order) > 0 then
		order = Right(order, Len(order)-1)
	else
		order = "po_id DESC"
	end if

	'here we create the variable "strOrderBy" that will be used in the SQL querry
	strOrderBy = "ORDER BY " & order

	'======================================================================================


	'Set dbconn=server.CreateObject("ADODB.Connection")
	'dbconn.Open g_connection_string

	sql = "SELECT * FROM " & g_storeid & "_po WHERE " & strWhere & " " & strOrderBy
	sqlx = "SELECT COUNT(po_id) FROM " & g_storeid & "_po WHERE " & strWhere 

	set rs = dbconn.Execute(sql)

	iTotalDisplayRecords = 0
	iTotalRecords = 50
	set rs1 = dbconn.Execute(sqlx)
	if not rs1.EOF then
		iTotalDisplayRecords = rs1(0)
		iTotalRecords = rs1(0)
	else
	end if
	rs1.Close

	'iTotalDisplayRecords = 50

	'iTotalRecords = 50

	%>
	{"sEcho": <%=sEcho%>, "iTotalRecords": <%=iTotalRecords%>, "iTotalDisplayRecords": <%=iTotalDisplayRecords%>, "aaData": [ 
	<%
	i = 0

	if rs.eof = false then
		rs.move(iDisplayStart)
		do while i < iDisplayLength and not rs.eof
			
			s_po_id = Trim(rs("po_id"))
			s_po_dist_name = rs("dist_name")
			s_po_amount = FormatNumber(rs("po_amount"),2)
			
			po_status = rs("po_status")

			s_date_created = rs("date_created")
			s_date_updated = rs("date_updated")
			
			s_date_created = ConvertToTimeZone(s_date_created)
			s_date_updated = ConvertToTimeZone(s_date_updated)
			
			s_po_dist_flag = rs("po_dist_flag")
			s_shipping_contact_first = rs("shipping_contact_first")
			s_shipping_contact_last = rs("shipping_contact_last")
			s_shipping_contact = rs("shipping_contact")


			select case po_status
			case 0
				s_po_status = "Pending"
			case 1
				s_po_status = "Closed"
			case 2
				s_po_status = "Approved"
			case 3
				
				if po_dist_flag = 2 then ' Tech Data
					sql = "SELECT DISTINCT item_TD_order FROM " & g_storeid & "_po_item WHERE po_id=" & s_po_id
					poOrderList = ""
					set rsItem = Conn.Execute(sql)
					do while not rsItem.EOF
						if Len(rsItem("item_TD_order")) > 0 then
							poOrderList = poOrderList & "<br><a href=""javascript:OpenTDInvoice('" & rsItem("item_TD_order") & "','" & s_po_id & "')"">" & rsItem("item_TD_order") & "</a>"
						end if
						rsItem.MoveNext
					loop
					rsItem.Close
				end if
				
				if po_dist_flag = 1 then ' Ingram Micro
					sql = "SELECT DISTINCT item_IM_order FROM " & g_storeid & "_po_item WHERE po_id=" & s_po_id
					poOrderList = ""
					set rsItem = Conn.Execute(sql)
					do while not rsItem.EOF
						if Len(rsItem("item_IM_order")) > 0 then
							poOrderList = poOrderList & "<br><a href=""javascript:OpenIMInvoice('" & rsItem("item_IM_order") & "','" & s_po_id & "')"">" & rsItem("item_IM_order") & "</a>"
						end if
						rsItem.MoveNext
					loop
					rsItem.Close
				end if
				
				if po_dist_flag = 3 then ' Synnex
					sql = "SELECT DISTINCT item_SN_order FROM " & g_storeid & "_po_item WHERE po_id=" & s_po_id
					poOrderList = ""
					set rsItem = Conn.Execute(sql)
					do while not rsItem.EOF
						if Len(rsItem("item_SN_order")) > 0 then
							poOrderList = poOrderList & "<br><a href=""javascript:OpenSNInvoice('" & rsItem("item_SN_order") & "','" & s_po_id & "')"">" & rsItem("item_SN_order") & "</a>"
						end if
						rsItem.MoveNext
					loop
					rsItem.Close
				end if
				
				if po_dist_flag = 4 then ' D&H
					sql = "SELECT DISTINCT item_DH_order FROM " & g_storeid & "_po_item WHERE po_id=" & s_po_id
					poOrderList = ""
					set rsItem = Conn.Execute(sql)
					do while not rsItem.EOF
						if Len(rsItem("item_DH_order")) > 0 then
							poOrderList = poOrderList & "<br><a href=""javascript:OpenDHInvoice('" & rsItem("item_DH_order") & "','" & s_po_id & "')"">" & rsItem("item_DH_order") & "</a>"
						end if
						rsItem.MoveNext
					loop
					rsItem.Close
				end if
				
				if po_dist_flag = 5 then ' Supplies Network
					sql = "SELECT DISTINCT item_SUN_order FROM " & g_storeid & "_po_item WHERE po_id=" & s_po_id
					poOrderList = ""
					set rsItem = Conn.Execute(sql)
					do while not rsItem.EOF
						if Len(rsItem("item_SUN_order")) > 0 then
							poOrderList = poOrderList & "<br><a href=""javascript:OpenSUNInvoice('" & rsItem("item_SUN_order") & "','" & s_po_id & "')"">" & rsItem("item_SUN_order") & "</a>"
						end if
						rsItem.MoveNext
					loop
					rsItem.Close
				end if
							
				s_po_status = "Partial Fulfilled"
				if Len(poOrderList)>0 Then
					s_po_status =  s_po_status & "<br>-------<br>" & poOrderList
				End If

			case 4
				s_po_status = "Converted"
			case else
				s_po_status = "Pending"
			end select
			

			if Len(s_shipping_contact) > 0 Then
			else
				s_shipping_contact = s_shipping_contact_last & ", " & s_shipping_contact_first
			end if

			If Len(s_shipping_contact) > 0 Then
				s_shipping_contact = Replace(s_shipping_contact, "'", "&#39")
			End If
			
			If Len(s_po_dist_name) > 0 Then
				s_po_dist_name = Replace(s_po_dist_name, "'", "&#39")
				s_po_dist_name = Replace(s_po_dist_name, """", "&#34;")
			End If
						
			
			
			aaData = aaData & "['"
			aaData = aaData & "<a href=\'v2_po.asp?po_id=" & s_po_id & "\'>" & s_po_id & "</a>','" 
			aaData = aaData & s_po_dist_name & "','" 
			aaData = aaData & s_shipping_contact & "','" 
			aaData = aaData & s_po_amount & "','"
			aaData = aaData & s_po_status & "','" 
			aaData = aaData & s_date_updated & "','"
			aaData = aaData & "<a class=\'btn btn-blue btn-xs btn-o\' href=\'javascript:OpenPrintInvoice(" & s_po_id & ")\'><i class=\'fa fa-print\'></i></a>','"
			aaData = aaData & "<input type=checkbox name=\'delete_po\' value=\'" & s_po_id & "\'>" &  "'],"
	
			
			aaData = Replace(aaData,"'",chr(34))
			rs.MoveNext
			i=i+1
		loop
		rs.Close
		if Len(aaData) > 0 then
			aaData = Left(aaData, Len(aaData)-1)
		else
			aaData = ""
		end if
	else
		aaData = ""
	end if
	response.write aaData & "] }"

%>