<%@ Language=VBScript %>
<%
  Response.Expires = -1
%>
<!-- #INCLUDE File="../local/local.phtml" -->
<!-- #INCLUDE File="../util/xt_func_util.phtml" -->
<!-- #INCLUDE File="../util/xt_func_string.phtml" -->
<%
  sEcho = Trim(Request("sEcho"))
  iDisplayLength = Trim(Request("iDisplayLength"))
  iDisplayStart = Trim(Request("iDisplayStart"))
  
  sEcho = FilterStringEx(sEcho, "[^0-9]")
  iDisplayLength = FilterStringEx(iDisplayLength, "[^0-9]")
  iDisplayStart = FilterStringEx(iDisplayStart, "[^0-9]")
  
  sEcho = Cint(sEcho)
  iDisplayLength = Cint(iDisplayLength)
  iDisplayStart = Cint(iDisplayStart)
  
  'sEcho = Cint(Request("sEcho"))
  'iDisplayLength = Cint(Request("iDisplayLength"))
  'iDisplayStart = Cint(Request("iDisplayStart"))
  
  sMin = Trim(Request("min"))
  sMax = Trim(Request("max"))
  
  sDateRange = ""
  
  if IsDate(sMin) then
    if IsDate(sMax) then
      dMax = CDate(sMax)
      dMax = DateAdd("d", 1, dMax)
      sMax = FormatDateTime(dMax,0)
      sDateRange = "(date_changed between '" & sMin & "' AND '" & sMax & "')"
    else
      'dMin = CDate(sMin)
      dMax = Date()
      dMax = DateAdd("d", 1, dMax)
      sMax = FormatDateTime(dMax,0)
      sDateRange = "(date_changed between '" & sMin & "' AND '" & sMax & "')"
    end if
  else
    if IsDate(sMax) then
      dMax = CDate(sMax)
      dMax = DateAdd("d", 1, dMax)
      sMax = FormatDateTime(dMax,0)
      sDateRange = "(date_changed between '1/1/1970' AND '" & sMax & "')"
    end if
  end if
  
  sSearch = Trim(Request("sSearch"))
  sSearch = FilterStringEx(sSearch, "[^0-9a-zA-Z _/-]")
  
  'iDisplayLength = 25
 ' iDisplayStart = 1
 
  index_date = DateAdd("d", -30, Date())
 
  if Len(sSearch) > 0 then
    sSearchDate = Replace(sSearch, "*", "%")
  end if
  
  'SEARCH - here we make the Where clause that will be used in the SQL querry. You only put here the fields you want to search 
  'if IsNumeric(sSearch) then
  'strWhere = " (order_id LIKE '%" & sSearch & "%' OR "
  'else
  'strWhere = " ("
  'end if
  strWhere = " (pf_id LIKE '%" & sSearch & "%' OR "
  'strWhere = strWhere &  " company_name LIKE '%" & sSearch & "%' OR "
  strWhere = strWhere &  " name LIKE '%" & sSearch & "%' OR "
  'strWhere = strWhere &  " shopper_lastname LIKE '%" & sSearch & "%' OR "
  'if Len(sDateRange) > 0 then
  'else
  'strWhere = strWhere &  " date_entered LIKE '%" & sSearchDate & "%' OR "
  'end if
  'strWhere = strWhere &  " order_name LIKE '%" & sSearch & "%' OR "
  strWhere = strWhere &  " description LIKE '%" & sSearch & "%')"
  
  if Len(sDateRange) > 0 then
  strWhere = strWhere &  " AND " & sDateRange
  end if
  
  if Len(str_filter) > 0 then
    strWhere  = strWhere & " AND " & str_filter
  end if
  
  cat_filter = ""
  v1 = Trim(Request("v1"))
  v2 = Trim(Request("v2"))
  v3 = Trim(Request("v3"))
  v4 = Trim(Request("v4"))
  
  if Len(v1) > 0 then
	cat_filter = v1
  end if
  if Len(v2) > 0 then
	cat_filter = v2
  end if
  if Len(v3) > 0 then
	cat_filter = v3
  end if
  if Len(v4) > 0 then
	cat_filter = v4
  end if
  
  if cat_filter <> "" then
	strWhere = strWhere & " AND pf_id IN (SELECT pf_id FROM " & g_storeid & "_dept_prod WHERE dept_id like '" & cat_filter & "%')"
  end if
  
  'v1 = Trim(Request("v1")) 'type
  'v2 = Trim(Request("v2")) 'visibility
  'v3 = Trim(Request("v3")) 'status
  
  'if v1 = "All" then 'type
  'else
    'strWhere = strWhere & " AND type_id='" & v1 & "'"
  'end if
  
  'if v2 = "All" then 'visibility
  'else
    'strWhere = strWhere & " AND Visibility='" & v2 & "'"
  'end if
  
  'if v3 = "All" then 'status
  'else
    'strWhere = strWhere & " AND isActive=" & v3
  'end if
  
  '=======================================================================================
  'ORDERING
	'passes through all cols and first check if the column is sortable, if yes then construct
	'the variable "order" that list in order the sequence of ordering
	for k = 0 to 7
		if Request("bSortable_" & k)="true" then
			order = order & Request("iSortCol_" & k) & " " & Request("sSortDir_" & k)
		end if
	next
	'here we replace the number corresponding the column position by the corresponding name of the column in the database
	order =	Replace(order,"0",", pf_id")
	order =	Replace(order,"1",", pf_id")
	order =	Replace(order,"2",", pf_id")
	order =	Replace(order,"3",", pf_id")
	order =	Replace(order,"4",", pf_id")
	order =	Replace(order,"5",", pf_id")
	order =	Replace(order,"6",", pf_id")
	order =	Replace(order,"7",", pf_id")
	order =	Replace(order,"8",", pf_id")
	order =	Replace(order,"9",", pf_id")
	
	'here we eliminate the first comma of the variable "order"
	if Len(order) > 0 then
	  order = Right(order, Len(order)-1)
	else
	  order = "pf_id DESC"
	end if

	'here we create the variable "strOrderBy" that will be used in the SQL querry
	strOrderBy = "ORDER BY " & order
	
	'======================================================================================
	

	Set dbconn=server.CreateObject("ADODB.Connection")
	dbconn.Open g_connection_string
	
	sql = "SELECT * FROM " & g_storeid & "_product WHERE " & strWhere & " " & strOrderBy
	
	
	sqlx = "SELECT COUNT(pf_id) FROM " & g_storeid & "_product WHERE " & strWhere 
		
	set rs = dbconn.Execute(sql)
	
	iTotalDisplayRecords = 0
	iTotalRecords = 50
	set rs1 = dbconn.Execute(sqlx)
	if not rs1.EOF then
	  iTotalDisplayRecords = rs1(0)
	  iTotalRecords = rs1(0)
	else
	end if
	rs1.Close
	
	'iTotalDisplayRecords = 50
	
	'iTotalRecords = 50
	
%>
{"sEcho": <%=sEcho%>, "iTotalRecords": <%=iTotalRecords%>, "iTotalDisplayRecords": <%=iTotalDisplayRecords%>, "aaData": [ 
<%
  i = 0
  
  if rs.eof = false then
    rs.move(iDisplayStart)
    do while i < iDisplayLength and not rs.eof
    
		s_pf_id = rs("pf_id")
		s_name = Trim(rs("name"))
		sku = Trim(rs("sku"))
		
		If Len(s_name) > 0 Then
			s_name = Replace(s_name, "'", "&#39")
			s_name = Replace(s_name, """", "&#34;")
		End if
			
		s_price = FormatNumber(rs("list_price"),2)
		s_qty = rs("stock")
		s_zoom_image = rs("zoom_image")
		
		'if rs("isActive") then
			s_active = "Enabled"
		'else
			's_active = "Disabled"
		'end if
		
		'i_visibility = rs("visibility")
		'SELECT CASE i_visibility
		'CASE 1
			's_visibility = "Not Visible Individually"
		'CASE 2
			's_visibility = "Catalog"
		'CASE 3
			's_visibility = "Search"
		'CASE 4
			's_visibility = "Catalog, Search"
		'CASE ELSE
			's_visibility = "Catalog, Search"
		'END SELECT
		
		sqlc = "SELECT d.dept_name as dept_name FROM " & g_storeid & "_dept as d INNER JOIN " & g_storeid & "_dept_prod as dp ON d.dept_id = dp.dept_id WHERE dp.pf_id='"&s_pf_id&"'"
		set rsDN = dbconn.execute(sqlc)
		if not rsDN.EOF then
			dept_name = rsDN("dept_name")
		End If
		
		's_type_id = Trim(rs("type_id"))
		's_wholesaler_id = Trim(rs("wholesaler_id"))
		's_gsin = Trim(rs("gsin_id"))
		
		s_store_url = g_store_url
		s_img_pf_id = s_pf_id
		
		if Len(s_zoom_image) > 3 then
			g_grid_image_url = g_cloudinary_url & "w_" & "50" & ",h_" & "50" & ",c_pad,c_fill/" & s_store_url & "media/catalog/product/" & s_img_pf_id & "/" & s_zoom_image
		else
			g_grid_image_url = g_noimage_url
		end if
		
		aaData = aaData & "['"
		'aaData = aaData & "<a href=\'catalog_product_detail.phtml?pf_id=" & s_pf_id & "\'>" & sku & "</a>','" 
		'aaData = aaData & "<img src=\'" & g_secure_url & "thumb_img/" & s_thumb_image & "\' width=70>','"
		aaData = aaData &  s_pf_id & "','"
		aaData = aaData & "<img src=\'" & g_grid_image_url & "\' width=50>','" 
		aaData = aaData & s_name & "','" 
		aaData = aaData & sku & "','" 
		aaData = aaData & s_price & "','"
		aaData = aaData & s_qty & "','"

		SELECT CASE s_active
		CASE "Enabled"
			s_label = "label label-success"
		CASE "Disabled"
			s_label = "label label-warning"
		END SELECT
		
		aaData = aaData & "<span class=\'" & s_label & "\'>" & s_active & "</span>','"
		aaData = aaData & "<button type=\'button\' class=\'btn btn-xs btn-teal\' onclick=\'getSearchResult(**" & s_pf_id & "**);\'><i class=\'fa fa-download\'></i></button>'],"
		'aaData = aaData & "']," 
      
          
      aaData = Replace(aaData,"'",chr(34))
      rs.MoveNext
      i=i+1
    loop
    rs.Close
	aaData = Replace(aaData,"**", "'")
    aaData = Left(aaData, Len(aaData)-1)
  else
    aaData = ""
  end if
  response.write aaData & "] }"
%>